Repository ManageIQ/integration_tests, pull requests merged in 2018-09, with the labels that each got.

#7739 [1LP][RFR] Fixed vm provisioning error in quota test
  cfme/tests/cloud/test_quota_tagging.py
Labels: fix-test, lint-ok

#7683 [1LP][RFR] Check that Nuage events are emitted and received
  cfme/tests/networks/nuage/__init__.py
  cfme/tests/networks/nuage/test_events_are_triggered.py
  requirements/frozen.py3.txt
Labels: WIP, lint-ok, new-test-or-feature

#7747 [1LP][RFR] Updated gitignore
  .gitignore
Labels: lint-ok, other

#7749 [1LP][RFR][NOTEST] Remove test_edit_catalog_after_deleting_provider from our test suite
  cfme/tests/services/test_service_catalogs.py
Labels: lint-ok, other

#7752 [1LP][RFR] Fix test_datastores_summary test on 5.8
  cfme/tests/intelligence/reports/test_canned_corresponds.py
Labels: fix-test, lint-ok

#7751 [1LP][RFR][NOTEST] fix for deployment role entity
  cfme/infrastructure/deployment_roles.py
Labels: fix-framework, lint-ok

#7746 [RFR] added instance cleanup
  cfme/tests/cloud_infra_common/test_provisioning.py
Labels: fix-test, lint-ok

#7754 [1LP][RFR] Fixing provider creation and deleteion for 5.8
  cfme/base/credential.py
  cfme/common/provider.py
Labels: LegacyBranch, fix-test, lint-ok

#7634 [RFR] Remove Polarion IDs from CMQE Tests
  cfme/tests/containers/test_ad_hoc_metrics.py
  cfme/tests/containers/test_basic_metrics.py
  cfme/tests/containers/test_breadcrumbs.py
  cfme/tests/containers/test_cockpit.py
  cfme/tests/containers/test_configurable_menus.py
  cfme/tests/containers/test_containers_smartstate_analysis.py
  cfme/tests/containers/test_containers_smartstate_analysis_multiple_images.py
  cfme/tests/containers/test_containers_summary.py
  cfme/tests/containers/test_labels.py
  cfme/tests/containers/test_logging.py
  cfme/tests/containers/test_manageiq_ansible_custom_attributes.py
  cfme/tests/containers/test_node.py
  cfme/tests/containers/test_overview_data_integrity.py
  cfme/tests/containers/test_projects_dashboard.py
  cfme/tests/containers/test_properties.py
  cfme/tests/containers/test_provider_configuration_menu.py
  cfme/tests/containers/test_provider_openscap_policy_attached.py
  cfme/tests/containers/test_relationships.py
  cfme/tests/containers/test_reload_button_provider.py
  cfme/tests/containers/test_reports.py
  cfme/tests/containers/test_search_bar.py
  cfme/tests/containers/test_smart_management.py
  cfme/tests/containers/test_ssa_set_cve_image_inspector_per_provider.py
  cfme/tests/containers/test_ssl_providers.py
  cfme/tests/containers/test_start_page.py
  cfme/tests/containers/test_static_custom_attributes.py
  cfme/tests/containers/test_table_views.py
  cfme/tests/containers/test_tables_fields.py
  cfme/tests/containers/test_tables_sort.py
  cfme/tests/containers/test_tags.py
Labels: infra-related, lint-ok, other

#7588 [1LP][RFR] VM TagWise graph for host
  cfme/common/candu_views.py
  cfme/configure/configuration/region_settings.py
  cfme/fixtures/candu.py
  cfme/tests/candu/__init__.py
  cfme/tests/candu/test_host_graph.py
Labels: lint-ok, new-test-or-feature

#7619 [1LP][RFR] Expand provision test to check more vlan options for RHV provider
  cfme/tests/infrastructure/test_provisioning_rest.py
Labels: lint-ok, new-test-or-feature

#7675 [1LP][RFR]collection of menus
  cfme/intelligence/reports/menus.py
  cfme/tests/intelligence/reports/test_menus.py
  entry_points.txt
Labels: collections-conversion, lint-ok

#7734 [1LP][RFR][NOTEST] Add BZs for test host creds cases
  cfme/tests/infrastructure/test_host.py
  cfme/tests/infrastructure/test_individual_host_creds.py
Labels: LegacyBranch, blockers-only, lint-ok

#7731 [1LP][RFR] Custom Button: support of host and vm infra objects
  cfme/tests/automate/custom_button/test_buttons.py
  cfme/tests/automate/custom_button/test_infra_objects.py
Labels: lint-ok, new-test-or-feature

#7732 [1LP][RFR] custom button: cloud objects initial commit
  cfme/tests/automate/custom_button/test_cloud_objects.py
Labels: lint-ok, new-test-or-feature

#7743 [1LP][RFR] Fixed all() method error in host advanced search
  cfme/tests/infrastructure/test_advanced_search_host.py
Labels: fix-test, lint-ok

#7737 [1LP][RFR] all method for cluster
  cfme/infrastructure/cluster.py
  cfme/tests/infrastructure/test_cluster_analysis.py
  cfme/tests/infrastructure/test_delete_infra_object.py
Labels: collections-conversion, enhancement, lint-ok

#7720 [1LP][RFR] Ading test publish_vm_to_template for RHV.
  cfme/infrastructure/virtual_machines.py
  cfme/tests/infrastructure/test_publish_vm_to_template.py
Labels: lint-ok, new-test-or-feature

#7769 [1LP][RFR] Fix the link to Google Python Style Guide
  docs/guides/documenting.rst
Labels: doc, lint-ok

#7741 [1LP][RFR] Fixing getting VM state for 5.8
  cfme/common/vm_views.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: LegacyBranch, fix-test, lint-ok

#7756 [1LP][RFR] Change sprout client default auth behavior
  cfme/fixtures/cli.py
  cfme/scripting/sprout.py
  cfme/test_framework/sprout/client.py
  cfme/test_framework/sprout/plugin.py
  sprout/appliances/views.py
Labels: WIP, fix-framework, lint-ok, sprout

#7770 [RFR] fix travis which is broken because pyvmonmi changed version notation
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
Labels: fix-framework, lint-ok

#7740 [1LP][RFR] Adding some fixes for UI problems in 5.8
  cfme/infrastructure/virtual_machines.py
  cfme/services/myservice/ssui.py
  cfme/services/service_catalogs/ui.py
Labels: LegacyBranch, fix-test, lint-ok

#7553 [1LP][RFR] V2v migration tests
  cfme/fixtures/provider.py
  cfme/fixtures/v2v.py
  cfme/tests/v2v/test_v2v_migrations.py
  cfme/tests/v2v/test_v2v_migrations_ui.py
  cfme/v2v/migrations.py
  widgetastic_manageiq/__init__.py
Labels: lint-ok, new-test-or-feature

#7758 [1LP][RFR] fix for quadicon
  cfme/common/vm_views.py
Labels: fix-framework, lint-ok

#7666 [1LP][RFR] Add flavor methods and tests
  cfme/cloud/flavor.py
  cfme/cloud/instance/openstack.py
  cfme/tests/openstack/cloud/test_flavors.py
Labels: lint-ok, new-test-or-feature

#7773 [1LP]Update SproutManager.pool setting
  cfme/test_framework/sprout/plugin.py
Labels: issue-bug

#7753 [1LP][RFR] all method for storage managers
  cfme/storage/manager.py
  cfme/tests/storage/test_manager.py
Labels: collections-conversion, enhancement, fix-test, lint-ok

#7775 [RFR] use "sprout" sprout user key on prt as stopgap to get the builds runn…
  cfme/utils/dockerbot/pytestbase/setup.sh
Labels: rc-regression-fix

#7637 [1LP][RFR] Chargeback CRUD operations: Parameterizing tests
  cfme/tests/intelligence/test_chargeback.py
Labels: enhancement, lint-ok

#7765 [1LP][RFR] Fixed exception error while deleting default tenant in 5.8.5.0
  cfme/configure/access_control/__init__.py
  cfme/tests/configure/test_access_control.py
Labels: LegacyBranch, fix-test, lint-ok

#7772 [1LP][RFR] Fixed TypeError in advanced search for 5.8.5.0
  cfme/tests/infrastructure/test_advanced_search_host.py
Labels: LegacyBranch, fix-test, lint-ok

#7777 [RFR] dockerbot: use the correct user-key cli argument for sprout checkout
  cfme/utils/dockerbot/pytestbase/setup.sh
Labels: issue-bug, lint-ok

#7762 [1LP][RFR] Add download_private_key test
  cfme/cloud/keypairs.py
  cfme/tests/openstack/cloud/test_keypairs.py
Labels: lint-ok, new-test-or-feature

#7778 [WIPTEST] restoring parsing quad removed by PR #7758
  cfme/common/vm_views.py
Labels: WIP-testing, issue-bug, lint-ok

#7781 [WIPTEST][NOTEST] Modify ContainerProviderEditViewUpdated view
  cfme/common/provider_views.py
Labels: WIP-testing, fix-framework, issue-bug, lint-ok

#7766 [RFR] Fixed exception error for openstack provider in 5.8.5.0
  cfme/tests/cloud/test_quota_tagging.py
Labels: fix-test, lint-ok

#7788 [1LP][RFR]This test is no longer valid as the feature is removed from CFME
  cfme/tests/v2v/test_v2v.py
Labels: lint-ok, other, rc-regression-fix

#7789 [RFR] Fix fixtures for sprout appliances, pass pytestconfig
  cfme/fixtures/cli.py
Labels: lint-ok, rc-regression-fix

#7791 [1LP][RFR][NOTEST] Blocking test_vm_migrate with BZ1627297
  cfme/tests/infrastructure/test_vm_migrate.py
Labels: blockers-only, lint-ok, rc-regression-fix

#7787 [1LP][RFR] Change sprout client default auth behavior
  cfme/fixtures/cli.py
  cfme/scripting/sprout.py
  cfme/test_framework/sprout/client.py
  cfme/test_framework/sprout/plugin.py
Labels: LegacyBranch, infra-related, lint-ok

#7806 [WIPTEST] Catch KeyError in _get_template()
  cfme/fixtures/provider.py
Labels: WIP-testing, issue-bug, lint-ok, rc-regression-fix

#7807 [1LP][RFR] Fix fixturelookuperror in test_webmks_console
  cfme/tests/infrastructure/test_webmks_console.py
Labels: lint-ok, rc-regression-fix

#7809 [1LP][RFR] Fix navigation destinations
  cfme/tests/configure/test_visual_infra.py
  cfme/tests/infrastructure/test_kubevirt.py
  cfme/tests/webui/test_splitter.py
Labels: lint-ok, rc-regression-fix

#7804 [WIPTEST] Adding BZ1627758 and fixing test_retirement_now
  cfme/tests/automate/test_common_methods.py
  cfme/tests/cloud_infra_common/test_retirement.py
Labels: WIP-testing, blockers-only, lint-ok, rc-regression-fix

#7796 [RFR][NOTEST] Blocking test_publish_vm_to_template with BZ1622952
  cfme/tests/infrastructure/test_publish_vm_to_template.py
Labels: blockers-only, lint-ok

#7794 [RFR][NOTEST] Blocking test_change_cpu_ram with BZ1627673
  cfme/tests/infrastructure/test_provisioning_dialog.py
Labels: blockers-only, lint-ok

#7808 [1LP][RFR] Fix test generation in test_register_appliance
  cfme/tests/configure/test_register_appliance.py
Labels: lint-ok, rc-regression-fix

#7776 [1LP][RFR] Fixing getting retirement state
  cfme/common/vm.py
  cfme/tests/cloud_infra_common/test_retirement.py
Labels: fix-framework, lint-ok, rc-regression-fix

#7816 [RFR] Fix Adding Container Provider for 5.8 Breakpoint
  cfme/containers/provider/__init__.py
Labels: LegacyBranch, issue-bug, lint-ok

#7817 [1LP][RFR] Bump wrapanapi to 3.0.25
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
Labels: enhancement, lint-ok

#7557 [1LP][RFR] Pre commit black isort
  .isort.cfg
  .pre-commit-config.yaml
  artifactor/__init__.py
  artifactor/__main__.py
  artifactor/example_tests/artifactor_simple_example.py
  artifactor/plugins/filedump.py
  artifactor/plugins/logger.py
  artifactor/plugins/merkyl.py
  artifactor/plugins/ostriz.py
  artifactor/plugins/post_result.py
  artifactor/plugins/reporter.py
  artifactor/plugins/test.py
  artifactor/plugins/video.py
  docs/conf.py
  docs/inventory.py
  requirements/freeze.py
  requirements/freeze_all.py
  scripts/gh-find.py
  scripts/latest_template_tester_report.py
  setup.cfg
  setup.py
  widgetastic_manageiq/__init__.py
  widgetastic_manageiq/expression_editor.py
  widgetastic_manageiq/hacks.py
  widgetastic_manageiq/vm_reconfigure.py
Labels: blackify, lint-ok, py3-compat

#7774 [1LP][RFR]Catalog name appended by My_Company in 5.10
  cfme/services/catalogs/catalog_items/__init__.py
Labels: fix-test, lint-ok

#7827 [RFR] fixed NoSuchElementException use_filter_expression
  cfme/configure/access_control/__init__.py
Labels: lint-ok

#7801 [1LP][RFR] Use specific keyserver.
  cfme/utils/dockerbot/pytestbase/get_keys.py
Labels: issue-bug, lint-ok

#7779 [1LP][RFR] Custom Button: Datastore support and all method for it.
  cfme/infrastructure/datastore.py
  cfme/tests/automate/custom_button/test_infra_objects.py
Labels: collections-conversion, lint-ok, new-test-or-feature

#7780 [1LP][RFR] custom button: support for storage managers
  cfme/tests/automate/custom_button/test_cloud_objects.py
Labels: lint-ok, new-test-or-feature

#7792 [RFR] Update provider not working messages in sprout
  sprout/appliances/tasks.py
Labels: lint-ok, sprout

#7814 [1LP][RFR] Custom Button: Automate test for Infra objects
  cfme/tests/automate/custom_button/__init__.py
  cfme/tests/automate/custom_button/test_infra_objects.py
Labels: lint-ok, new-test-or-feature

#7733 [1LP][RFR] New Set of v2v migration tests
  cfme/common/provider.py
  cfme/fixtures/v2v.py
  cfme/markers/env_markers/provider.py
  cfme/tests/v2v/test_v2v_migrations.py
  cfme/tests/v2v/test_v2v_migrations_ui.py
  cfme/v2v/migrations.py
  widgetastic_manageiq/__init__.py
Labels: lint-ok, new-test-or-feature

#5984 [1LP][RFR] Added test_service_rbac.py testcase
  cfme/base/ui.py
  cfme/configure/access_control/__init__.py
  cfme/services/myservice/__init__.py
  cfme/services/myservice/ui.py
  cfme/tests/services/test_service_rbac.py
Labels: lint-ok, new-test-or-feature

#7786 [1LP][RFR] Fixing test test_credentials_quads for the CFME 5.10
  cfme/tests/openstack/infrastructure/test_provider.py
Labels: fix-test, lint-ok

#7768 [1LP][RFR] NonJSPaginationPane removal
  cfme/infrastructure/virtual_machines.py
  cfme/intelligence/reports/reports.py
  cfme/services/dashboard/ssui.py
  widgetastic_manageiq/__init__.py
Labels: lint-ok, other

#7767 [1LP][RFR] 5.8 NonJS based entities are removed
  cfme/common/host_views.py
  cfme/common/physical_server_views.py
  cfme/common/physical_switch_views.py
  cfme/common/provider_views.py
  cfme/common/vm_views.py
  cfme/configure/access_control/__init__.py
  cfme/infrastructure/datastore.py
  widgetastic_manageiq/__init__.py
Labels: lint-ok, other

#7823 [1LP][RFR] Fix test_cluster_relationships test and update wrapanapi requirements for 5.8
  cfme/tests/intelligence/reports/test_canned_corresponds.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
Labels: LegacyBranch, fix-test, lint-ok

#7797 [1LP][RFR] Allow plugins to return value
  cfme/fixtures/artifactor_plugin.py
Labels: fix-framework, lint-ok

#7793 [1LP][RFR] Testing cloud quota for 'user' and 'group' by provisioning instance via lifecycle
  cfme/tests/cloud/test_quota_tagging.py
Labels: lint-ok, new-test-or-feature

#7829 [1LP][RFR] Fix problem with host list comprehention
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
Labels: fix-test, lint-ok

#7748 [1LP][RFR] Adding test that tries provision VM from template with 2 NICs
  cfme/tests/infrastructure/test_provisioning_dialog.py
Labels: lint-ok, new-test-or-feature

#7824 [1LP][RFR]Fix test_cluster_relationships
  cfme/tests/intelligence/reports/test_canned_corresponds.py
Labels: fix-test, lint-ok

#7831 [1LP][RFR] changed error message to match for blank description
  cfme/tests/configure/test_zones.py
Labels: fix-locator-or-text, lint-ok

#7815 [1LP][RFR] Update valid labels for release script
  cfme/utils/release.py
Labels: enhancement, lint-ok

#7805 [1LP][RFR] added check for ansible logs
  cfme/tests/configure/test_log_depot_operation.py
Labels: lint-ok, new-test-or-feature

#7822 [1LP][RFR] Custom Button: Azone support and all method
  cfme/cloud/availability_zone.py
  cfme/tests/automate/custom_button/test_cloud_objects.py
Labels: lint-ok, new-test-or-feature

#7838 [RFR]Marked test with BZ
  cfme/tests/services/test_provision_stack.py
Labels: blockers-only, lint-ok

#7837 [RFR]Marked test with BZ
  cfme/tests/services/test_cloud_service_catalogs.py
Labels: blockers-only, lint-ok

#7707 [RFR][NOTEST] Removed case-sensitivity of webdriver option.
  cfme/utils/browser.py
Labels: fix-locator-or-text, lint-ok

#7840 [RFR] Remove http restart in auth fixture
  cfme/fixtures/authentication.py
Labels: LegacyBranch

#7832 [1LP][RFR] Fixes the double artifactor shutdown
  cfme/fixtures/artifactor_plugin.py
Labels: fix-framework, lint-ok

#7843 [1LP][RFR] Update StatusBox xpath
  widgetastic_manageiq/__init__.py
Labels: fix-framework, lint-ok

#7854 [RFR] consolidate sprout_appliance contextmanager and fixtures
  cfme/fixtures/appliance.py
  cfme/fixtures/cli.py
  cfme/tests/pod/test_appliance_crud.py
Labels: LegacyBranch, lint-ok

#7714 [1LP][RFR] Adding test_provision_cloud_init_payload for RHEVM
  cfme/common/vm_views.py
  cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py
  cfme/utils/net.py
Labels: lint-ok, new-test-or-feature

#7833 [1LP][RFR] Support reset log for merkyl plugin
  artifactor/plugins/merkyl.py
  cfme/fixtures/merkyl.py
Labels: enhancement, lint-ok, plugins

#7574 [1LP][RFR] Test targeted refresh for Nuage entities
  cfme/exceptions.py
  cfme/tests/networks/nuage/test_events_are_triggered.py
Labels: lint-ok, new-test-or-feature

#7841 [1LP][RFR] Add/Resume OCP Provider API Test
  cfme/containers/provider/__init__.py
  cfme/containers/provider/openshift.py
  cfme/tests/containers/test_pause_resume_workers.py
Labels: lint-ok, new-test-or-feature

#7759 [1LP][RFR] Upgrade scripting and test fixes for repo changes
  cfme/fixtures/appliance.py
  cfme/fixtures/cli.py
  cfme/scripting/appliance.py
  cfme/tests/cli/test_appliance_update.py
  cfme/tests/test_db_migrate.py
  cfme/utils/appliance/db.py
  cfme/utils/repo_gen.py
Labels: enhancement, fix-test, lint-ok

#7800 [1LP][RFR][NOTEST] Removing test_custom_vm_report from RHV regression suite
  cfme/tests/intelligence/reports/test_report_corresponds.py
Labels: lint-ok, other

#7821 [1LP][RFR] Custom Button: Cluster support in infa object
  cfme/tests/automate/custom_button/test_infra_objects.py
Labels: lint-ok, new-test-or-feature

#7834 [1LP][RFR] fixed paginator tests for 5.8
  cfme/tests/configure/test_paginator.py
Labels: LegacyBranch, fix-test, lint-ok

#7744 [1LP][RFR] Fixed Exception Error while deleting default tenant
  cfme/configure/access_control/__init__.py
  cfme/tests/configure/test_access_control.py
Labels: fix-test, lint-ok

#7855 [1LP][RFR] Update auth fixture, restart evmserverd
  cfme/fixtures/authentication.py
Labels: fix-test, lint-ok

#7848 [1LP][RFR] fixed test_group_crud_with_tag for vsphere55
  cfme/tests/configure/test_access_control.py
Labels: fix-test, lint-ok

#7842 [1LP][RFR] Adding ability to add VMware Host creds, as this is new requirement for v2v tests
  cfme/fixtures/v2v.py
Labels: fix-test, lint-ok

#7849 [1LP][RFR]Generic service 5.10 fix
  cfme/services/catalogs/catalog_items/catalog_bundles.py
  cfme/tests/services/test_generic_service_catalogs.py
Labels: fix-test, lint-ok

#7851 [1LP][RFR] 5.8 - add flash message for snapshot
  cfme/infrastructure/virtual_machines.py
Labels: LegacyBranch, fix-test, lint-ok

#7853 [1LP][RFR] Convert `cfme/tests/networks` to package
  cfme/tests/networks/__init__.py
Labels: enhancement, lint-ok

#7856 [1LP][RFR] Update RegionView and tries() method
  cfme/base/ui.py
  cfme/utils/__init__.py
Labels: fix-framework, lint-ok

#7813 [RFR] Fix issue with list comprehention and calling host validation for InfraProvider
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
Labels: fix-test, lint-ok

#7819 [RFR] New subject of provision e-mails in CFME 5.10
  cfme/tests/cloud_infra_common/test_provisioning.py
  cfme/tests/infrastructure/test_provisioning_rest.py
Labels: fix-test, lint-ok

#7845 [RFR] Fix template ownership test
  cfme/tests/cloud_infra_common/test_vm_ownership.py
Labels: fix-test, lint-ok

#7847 [RFR] fixed failed test_group_crud_with_tag[tag-virtualcenter] for vsphere55 for 5.8
  cfme/tests/configure/test_access_control.py
Labels: LegacyBranch, fix-test, lint-ok

#7799 [RFR] Fix Provider relationships templates view for 5.10
  cfme/infrastructure/virtual_machines.py
Labels: fix-locator-or-text, lint-ok

#7852 [RFR] fixed check for ansible logs
  cfme/tests/configure/test_log_depot_operation.py
Labels: lint-ok

#7713 [1LP][RFR] Add csv imports tests to v2v
  cfme/fixtures/v2v.py
  cfme/tests/v2v/test_csv_import.py
  cfme/v2v/migrations.py
Labels: enhancement, lint-ok, new-test-or-feature

#7844 [RFR] modified the name of cluster for 5.8
  cfme/tests/candu/test_cluster_graph.py
Labels: fix-test, lint-ok

#7835 [RFR] uncollect anon_ftp for 5.8 and below
  cfme/tests/configure/test_log_depot_operation.py
Labels: fix-test, lint-ok

#7868 [1lLP][RFR] Fix host fixture for test_relationships, Navigation
  cfme/infrastructure/host.py
  cfme/tests/cloud_infra_common/test_relationships.py
Labels: fix-framework, fix-test, lint-ok, rc-regression-fix

#7865 [1LP][RFR] Add summary view selection to cloud details nav resetter
  cfme/cloud/provider/__init__.py
  cfme/infrastructure/provider/__init__.py
  cfme/tests/cloud_infra_common/test_relationships.py
Labels: fix-test, lint-ok, rc-regression-fix
