Repository ManageIQ/integration_tests, pull requests merged in 2018-02, with the labels that each got.

#6606 [1LP][RFR]Fixed test_invalid_template_type
  cfme/tests/services/test_rest_services.py
Labels: fix-test, lint-ok

#6623 [1LP][RFR] Fix for stack teardown registration
  cfme/tests/services/test_provision_stack.py
Labels: fix-test, lint-ok

#6624 [RFR] Fixed ansible repositories
  cfme/ansible/repositories.py
Labels: fix-framework, lint-ok

#6629 [1LP][RFR] Added a bz blocker for test_alert_vm_turned_on_more_than_twice_in_past_15_minutes
  cfme/tests/control/test_alerts.py
Labels: fix-test, lint-ok

#6593 [1LP][RFR] Fix custom attributes tests on 5.8
  cfme/tests/cloud_infra_common/test_custom_attributes_rest.py
Labels: fix-test, lint-ok

#6547 [RFR][1LP] Remove deprecated use of base_url in env appliance configuration
  cfme/scripting/sprout.py
  cfme/test_framework/appliance.py
  cfme/test_framework/sprout/plugin.py
  cfme/tests/services/test_operations.py
  cfme/utils/appliance/__init__.py
  cfme/utils/browser.py
  cfme/utils/net.py
  cfme/utils/ssh.py
  cfme/utils/tests/test_ipappliance.py
  docs/getting_started.rst
  docs/guides/browser_configuration.rst
  docs/guides/container.rst
  docs/guides/tipsntricks.rst
  docs/guides/vnc_selenium.rst
  fixtures/parallelizer/__init__.py
  fixtures/parallelizer/remote.py
  fixtures/pytest_store.py
  notebooks/Browser Session.ipynb
  scripts/dockerbot/pytestbase/setup.sh
  scripts/wait_for_appliance_ui.py
Labels: lint-ok, tech-debt

#6626 [1LP][WIPTEST] Update BZ blockers in aws RBAC/login tests
  cfme/roles.py
  cfme/tests/integration/test_aws_iam_auth_and_roles.py
Labels: WIP-testing, fix-test, lint-ok

#6612 [1LP][RFR] Add auth provider classes
  cfme/utils/auth/__init__.py
  setup.py
Labels: enhancement, lint-ok

#6582 [1LP][RFR] renamed openshift everywhere
  cfme/containers/provider/kubernetes.py
  cfme/containers/provider/openshift.py
  docs/conf.py
  requirements/frozen.txt
Labels: lint-ok, tech-debt

#6630 [1LP][RFR] Change login method for FF52+
  cfme/base/ui.py
Labels: fix-framework, lint-ok

#6634 [1LP][RFR] Add a --force option to link_config.py to overwrite existing symlinks/files
  cfme/scripting/link_config.py
Labels: enhancement, lint-ok

#6625 [1LP][RFR] Ansible tower type is different in 5.9
  cfme/services/catalogs/catalog_item.py
Labels: fix-framework, lint-ok

#6645 [1LP][RFR] Fix scripts imports
  cfme/scripting/appliance.py
  cfme/scripting/miq.py
  cfme/tests/cli/test_appliance_update.py
  cfme/tests/test_db_migrate.py
  cfme/utils/dockerbot/README.md
  cfme/utils/dockerbot/__init__.py
  cfme/utils/dockerbot/build-container.py
  cfme/utils/dockerbot/check_prs.py
  cfme/utils/dockerbot/dockerbot.py
  cfme/utils/dockerbot/pytestbase/Dockerfile
  cfme/utils/dockerbot/pytestbase/__init__.py
  cfme/utils/dockerbot/pytestbase/get_keys.py
  cfme/utils/dockerbot/pytestbase/post_result.py
  cfme/utils/dockerbot/pytestbase/setup.sh
  cfme/utils/dockerbot/pytestbase/verify_commit.py
  cfme/utils/dockerbot/sel_container.py
  cfme/utils/release.py
  cfme/utils/repo_gen.py
  cfme_test.sh
  docs/getting_started.rst
  scripts/appliance.py
  scripts/tests/test_appliance.py
  setup.py
Labels: fix-framework, lint-ok

#6620 [1LP][RFR] Automate buttons collections conversion
  cfme/automate/buttons.py
  cfme/tests/ansible/test_embedded_ansible_automate.py
  cfme/tests/ansible/test_embedded_ansible_services.py
  cfme/tests/automate/test_buttons.py
  cfme/tests/automate/test_common_methods.py
  cfme/tests/automate/test_vmware_methods.py
  setup.py
Labels: collections-conversion, lint-ok

#6647 [1LP][RFR] fix provider api port test
  cfme/tests/openstack/infrastructure/test_provider.py
Labels: fix-test, lint-ok

#6637 [1LP][RFR] Enabled test for 5.9
  cfme/services/service_catalogs/ssui.py
  cfme/tests/ssui/test_ssui_service_catalogs.py
Labels: fix-locator-or-text, fix-test, lint-ok

#6618 [1LP][RFR] New region tests
  cfme/base/ui.py
  cfme/tests/configure/test_region.py
Labels: lint-ok, new-test-or-feature

#6631 [1LP][RFR] New test_copied_user_password_inheritance test
  cfme/tests/configure/test_access_control.py
Labels: lint-ok, new-test-or-feature

#6633 [1LP][RFR] Blocking test_vm_reconfig_add_remove_hw_cold for RHV
  cfme/tests/infrastructure/test_vm_reconfigure.py
Labels: fix-test, lint-ok

#6648 [1LP][RFR] Add services custom attributes tests
  cfme/tests/cloud_infra_common/test_custom_attributes_rest.py
Labels: lint-ok, new-test-or-feature

#6628 [1LP][RFR] Cloud provider discovery test
  cfme/base/credential.py
  cfme/cloud/provider/ec2.py
  cfme/common/provider_views.py
  cfme/tests/cloud/test_providers.py
Labels: lint-ok, new-test-or-feature

#6640 [1LP][RFR]changing GCE boot_disk_size format used in REST
  cfme/tests/cloud/test_provisioning.py
Labels: fix-test, lint-ok

#6650 [1LP][RFR] Ability to isolate browser sessions
  cfme/test_framework/browser_isolation.py
  cfme/test_framework/pytest_plugin.py
Labels: enhancement, lint-ok

#6651 [1LP][RFR] Added BZ in test_network_providers.py
  cfme/tests/networks/test_network_providers.py
Labels: fix-test, lint-ok

#6654 [1LP][RFR] fix get element id to support any region
  widgetastic_manageiq/__init__.py
Labels: fix-framework, lint-ok

#6644 [1LP][RFR] Replace get_details() for VMs
  cfme/cloud/instance/__init__.py
  cfme/cloud/instance/image.py
  cfme/common/vm.py
  cfme/common/vm_views.py
  cfme/infrastructure/virtual_machines.py
  cfme/tests/cloud/test_instance_power_control.py
  cfme/tests/cloud/test_provisioning.py
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
  cfme/tests/control/__init__.py
  cfme/tests/control/test_alerts.py
  cfme/tests/infrastructure/test_provisioning_dialog.py
  cfme/tests/infrastructure/test_vm_migrate.py
  cfme/tests/infrastructure/test_vm_power_control.py
  cfme/tests/openstack/cloud/test_instances.py
Labels: enhancement, lint-ok, tech-debt

#6646 [1LP][RFR] Minor changes to coverage_merger.rb
  fixtures/ui_coverage.py
  scripts/data/coverage/coverage_merger.rb
Labels: fix-framework, lint-ok

#6584 [1LP][RFR] Aligning cloud provision attributes
  cfme/tests/cloud/test_provisioning.py
  cfme/tests/services/test_cloud_service_catalogs.py
  requirements/frozen.txt
Labels: WIP-testing, enhancement, lint-ok

#6672 [1LP][RFR]Check for smart_management attr
  cfme/common/__init__.py
Labels: fix-test, lint-ok

#6664 [1LP][RFR] Fixed test_migrate_vm
  cfme/tests/infrastructure/test_vm_migrate.py
Labels: fix-test, lint-ok

#6095 [1LP][RFR] Timeprofile collection conversion and Timeprofile fix
  cfme/configure/settings.py
  cfme/tests/configure/test_timeprofile.py
  setup.py
Labels: collections-conversion, lint-ok

#6657 [1LP][RFR] Fixed test_action_prevent_host_ssa
  cfme/tests/control/test_actions.py
Labels: fix-test, lint-ok

#6661 [1LP][RFR][NOTEST] Added descriptions for wait_for functions
  cfme/tests/control/__init__.py
  cfme/tests/control/test_actions.py
  cfme/tests/control/test_alerts.py
  cfme/tests/control/test_rest_control.py
Labels: enhancement, lint-ok

#6662 [1LP][RFR] Updating test_edit_catalog_after_deleting_provider
  cfme/tests/services/test_service_catalogs.py
Labels: fix-test, lint-ok

#6669 [1LP][RFR] Add test for querying provider attributes
  cfme/tests/cloud_infra_common/test_rest_providers.py
Labels: lint-ok, new-test-or-feature

#6678 [1LP][RFR] Add test for querying authentications attributes
  cfme/tests/infrastructure/test_config_management_rest.py
Labels: lint-ok, new-test-or-feature

#6680 [1LP][RFR] fixed issue with floating ip entities
  widgetastic_manageiq/__init__.py
Labels: fix-framework, lint-ok

#6682 [1LP][RFR] fix for non interactive entities
  widgetastic_manageiq/__init__.py
Labels: fix-framework, lint-ok

#6568 [WIP][NOTEST][RFR][1LP] Sprout - Able to select a specific provider type
  sprout/appliances/api.py
  sprout/appliances/migrations/0040_auto_20180201_1342.py
  sprout/appliances/models.py
  sprout/appliances/templates/appliances/my_appliances.html
  sprout/appliances/views.py
Labels: WIP, enhancement, infra-related, lint-ok

#6635 [1LP][WIPTEST] Enhancements to dockerbot setup.sh for easier debugging
  cfme/test_framework/appliance.py
  cfme/utils/appliance/__init__.py
  cfme/utils/dockerbot/pytestbase/setup.sh
Labels: WIP-testing, infra-related, lint-ok

#6671 [1LP][RFR] fix network checks for pod appliance which currently has different db and http hosts
  cfme/test_framework/appliance_police.py
Labels: fix-framework, lint-ok

#6652 [1LP][RFR] Check for order view
  cfme/services/service_catalogs/ui.py
Labels: fix-test, lint-ok

#6684 [RFR]Fix navigation for drift analysis
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
Labels: fix-test, lint-ok

#6659 [RFR]Check none value for key pair
  cfme/tests/cloud/test_providers.py
Labels: lint-ok, new-test-or-feature

#6557 [RFR] Fix Failing tests cfme.tests.containers.test_static_custom_attributes.py
  cfme/tests/containers/test_static_custom_attributes.py
Labels: lint-ok

#6687 Sprout - Fix places where provider_type was not passed through
  sprout/appliances/models.py
  sprout/appliances/views.py
Labels: lint-ok

#6688 [1LP][RFR] Log exceptions to stdout
  scripts/azure_cleanup.py
Labels: infra-related, lint-ok

#6693 [1LP][RFR] Fix upstream appliance setup
  cfme/utils/appliance/__init__.py
Labels: fix-framework, lint-ok

#6681 [1LP][RFR] Fixed relationship click
  cfme/tests/services/test_myservice.py
Labels: lint-ok

#6595 [RFR] openshift templates support in sprout
  sprout/appliances/migrations/0042_openshift_appliances_support.py
  sprout/appliances/models.py
  sprout/appliances/tasks.py
  sprout/requirements.txt
Labels: enhancement, lint-ok

#6658 [RFR] fix failed tests on infrastructure test_hosts.py
  cfme/tests/openstack/infrastructure/test_hosts.py
Labels: fix-test, lint-ok

#6695 [1LP][RFR] fix for quadicons in 5.8
  widgetastic_manageiq/__init__.py
Labels: fix-framework, lint-ok

#6365 [1LP][RFR] Fixed test_add_vm_to_service and removed vm hardcoding
  cfme/tests/services/test_add_remove_vm_to_service.py
Labels: fix-test, lint-ok

#6702 [RFR] fixing sprout for openshift and other providers
  requirements/frozen.txt
  sprout/appliances/migrations/0043_provider_provider_type.py
  sprout/appliances/models.py
  sprout/appliances/tasks.py
  sprout/appliances/views.py
Labels: lint-ok

#6700 [1LP][RFR] VM summary fix for some tests
  cfme/common/vm.py
  cfme/tests/automate/test_vmware_methods.py
  cfme/tests/cloud_infra_common/test_retirement.py
  cfme/tests/infrastructure/test_provisioning_dialog.py
Labels: fix-test, lint-ok

#6679 [1LP][RFR] Fixing test_operations_vm_on and test_datastores_summary
  cfme/intelligence/reports/reports.py
  cfme/tests/intelligence/reports/test_canned_corresponds.py
Labels: fix-test, lint-ok

#5355 [1LP][RFR] SDN topology
  cfme/common/topology.py
  cfme/networks/topology.py
  cfme/tests/networks/test_sdn_topology.py
  setup.py
Labels: enhancement, lint-ok, new-test-or-feature

#6676 [1LP][RFR] VMware WebMKS test fix
  cfme/configure/configuration/server_settings.py
Labels: fix-test, lint-ok

#6683 [1LP][RFR] Fix service order
  cfme/services/service_catalogs/ui.py
  cfme/tests/ansible/test_embedded_ansible_services.py
  cfme/tests/services/test_provision_stack.py
  widgetastic_manageiq/__init__.py
Labels: fix-locator-or-text, fix-test, lint-ok

#6613 [1LP][RFR] Update appliance openldap config method
  cfme/utils/appliance/__init__.py
  cfme/utils/testgen.py
Labels: enhancement, fix-test, lint-ok

#6107 [1LP][RFR] Automate Metering report
  cfme/tests/intelligence/reports/test_metering_report.py
Labels: lint-ok, new-test-or-feature

#6703 [1LP][RFR] Add test checking expected control attributes
  cfme/tests/control/test_rest_control.py
Labels: enhancement, lint-ok, new-test-or-feature

#6701 [1LP][RFR] Add test checking expected VM attributes
  cfme/tests/infrastructure/test_vm_rest.py
Labels: lint-ok, new-test-or-feature

#6696 [1LP][RFR] Add query attributes tests for services collections
  cfme/tests/services/test_rest_services.py
  cfme/utils/rest.py
Labels: lint-ok, new-test-or-feature

#6691 [1LP][RFR] Wrap test_rhev_iso_service_catalog and test_iso_provision_from template
  cfme/tests/infrastructure/test_iso_provisioning.py
  cfme/tests/services/test_iso_service_catalogs.py
Labels: fix-test, lint-ok

#6699 [1LP][RFR] Workaround for snapshot VM suspend
  cfme/tests/infrastructure/test_snapshot.py
Labels: fix-test, lint-ok

#6685 [1LP][RFR] Added Ubuntu to quickstart script
  cfme/scripting/quickstart.py
Labels: enhancement, lint-ok

#6656 [1LP][RFR] Fixed catalog item for cloud providers
  cfme/fixtures/service_fixtures.py
  cfme/services/myservice/ssui.py
  cfme/tests/ssui/test_ssui_myservice.py
  widgetastic_manageiq/__init__.py
Labels: fix-test, lint-ok

#6716 [RFR] Bump wrapanapi
  requirements/frozen.txt
Labels: fix-locator-or-text, lint-ok

#6706 [1LP][RFR] Add new tests for querying access control attributes
  cfme/rest/gen_data.py
  cfme/tests/configure/test_rest_access_control.py
Labels: lint-ok, new-test-or-feature

#6663 [DOC][1LP][RFR] Introducing pudb
  docs/guides/debugging.rst
Labels: doc, lint-ok

#6713 [1LP][RFR] Replacement get_detail() for providers
  cfme/cloud/provider/__init__.py
  cfme/cloud/provider/vcloud.py
  cfme/common/provider.py
  cfme/common/provider_views.py
  cfme/containers/provider/__init__.py
  cfme/containers/provider/openshift.py
  cfme/infrastructure/provider/__init__.py
  cfme/networks/provider/nuage.py
  cfme/physical/physical_server.py
  cfme/physical/provider/__init__.py
  cfme/tests/cloud_infra_common/test_relationships.py
  cfme/tests/openstack/infrastructure/test_relationships.py
Labels: enhancement, lint-ok, tech-debt

#6670 [1LP][RFR] New Openstack Ansible Embedded credential
  cfme/ansible/credentials.py
  cfme/tests/ansible/test_embedded_ansible_basic.py
Labels: lint-ok, new-test-or-feature

#6615 [1LP][RFR] Using default vNIC profile in REST VM provision
  cfme/tests/infrastructure/test_provisioning_rest.py
Labels: fix-test, lint-ok

#6725 [RFR] Updating PF to 0.20.4
  requirements/frozen.txt
  requirements/frozen_docs.txt
Labels: lint-ok, other

#6733 [1LP][RFR] reload button title has been changed in 5.8.3.4
  cfme/common/provider_views.py
Labels: fix-locator-or-text, lint-ok

#6732 [RFR] Convert InfraNetwork to Collections
  cfme/infrastructure/networking.py
  cfme/tests/webui/test_splitter.py
Labels: collections-conversion, lint-ok

#6723 [1LP][RFR] Provider configuration menu test , cancel removing selected container provider
  cfme/tests/containers/test_provider_configuration_menu.py
Labels: fix-test, lint-ok

#6728 [1LP][RFR] New tests and enhancements to service dialogs API testing
  cfme/rest/gen_data.py
  cfme/tests/services/test_rest_services.py
Labels: lint-ok, new-test-or-feature

#6665 [1LP][RFR] New HA test and clean up/fixed old tests for ap+cli
  cfme/fixtures/cli.py
  cfme/tests/cli/test_appliance_cli.py
  cfme/tests/cli/test_appliance_console.py
  cfme/tests/cli/test_appliance_update.py
  cfme/utils/appliance/__init__.py
Labels: lint-ok, new-test-or-feature

#6721 [1LP][RFR] Move test_vm_scan to file with other VMs-related tests
  cfme/tests/infrastructure/test_vm_rest.py
  cfme/tests/test_rest.py
Labels: enhancement, lint-ok

#6719 [1LP][RFR] Fixed test_widgets_operation
  cfme/dashboard.py
Labels: fix-locator-or-text, lint-ok

#6711 [1LP][RFR] Fixing table of tasks in Tasks view
  cfme/configure/tasks.py
  cfme/tests/infrastructure/test_host_analysis.py
Labels: fix-test, lint-ok

#6710 [1LP][RFR] Replacement get_detail() for hosts
  cfme/common/host_views.py
  cfme/infrastructure/host.py
  cfme/tests/cloud_infra_common/test_relationships.py
  cfme/tests/control/test_actions.py
  cfme/tests/infrastructure/test_host_analysis.py
  cfme/tests/infrastructure/test_host_drift_analysis.py
  cfme/tests/infrastructure/test_host_provisioning.py
  cfme/tests/openstack/cloud/test_instances.py
  cfme/tests/openstack/infrastructure/test_host_lifecycle.py
  cfme/tests/openstack/infrastructure/test_hosts.py
Labels: enhancement, lint-ok, tech-debt

#6698 [1LP][RFR] Added ansible playbook custom button
  cfme/automate/buttons.py
  cfme/tests/ansible/test_embedded_ansible_automate.py
  cfme/tests/ansible/test_embedded_ansible_services.py
  cfme/tests/automate/test_buttons.py
  cfme/tests/automate/test_common_methods.py
  cfme/tests/automate/test_vmware_methods.py
  widgetastic_manageiq/__init__.py
Labels: enhancement, lint-ok, new-test-or-feature

#6641 [1LP][RFR] Test vddk version(ssa)
  cfme/tests/infrastructure/test_ssa_vddk.py
Labels: lint-ok, new-test-or-feature

#6675 [1LP][RFR] Test Floating ips names
  cfme/networks/floating_ips.py
  cfme/networks/views.py
  cfme/tests/cloud/test_providers.py
  setup.py
Labels: lint-ok, new-test-or-feature

#6737 [1LP][RFR] Override is_refreshed method in openshift provider
  cfme/containers/provider/openshift.py
Labels: lint-ok

#6743 [1LP][RFR] fix_provider_summary
  cfme/infrastructure/provider/__init__.py
Labels: fix-framework, lint-ok

#6667 [1LP][RFR] Changes for jenkins
  cfme/scripting/quickstart.py
  cfme/utils/browser.py
  cfme/utils/trackerbot.py
  scripts/template_tester.py
  scripts/template_upload_all.py
Labels: infra-related, lint-ok

#6745 [1LP][RFR] Wrapping test_verify_revert_snapshot for RHV-CFME integration
  cfme/tests/infrastructure/test_snapshot.py
Labels: fix-test, lint-ok

#6742 [1LP][RFR] Wrapping test_vm_reconfig_add_remove_hw_cold with BZ for 5.8
  cfme/tests/infrastructure/test_vm_reconfigure.py
Labels: fix-test, lint-ok

#6741 [1LP][RFR] Add new test to cancel vm reconfiguration changes
  cfme/tests/infrastructure/test_vm_reconfigure.py
Labels: lint-ok, new-test-or-feature

#6666 [1LP][RFR] Fix PXE-related testgen and test collection
  cfme/utils/testgen.py
Labels: fix-framework, lint-ok

#6755 [RFR] ContainersProvider update num_container to support changes on CFME 5.9 DB
  cfme/containers/provider/__init__.py
Labels: fix-framework, lint-ok

#6731 [1LP][RFR] Fixed SSH buffering
  cfme/utils/ssh.py
Labels: fix-framework, lint-ok

#6753 [1LP][RFR] Some Lenovo fixes
  cfme/physical/provider/lenovo.py
  cfme/tests/physical_infrastructure/test_providers.py
Labels: fix-framework, lint-ok

#6762 [1LP][RFR][NOTEST] Sprout - Add template_type into the database
  sprout/appliances/migrations/0044_template_template_type.py
  sprout/appliances/models.py
  sprout/appliances/tasks.py
Labels: WIP, enhancement, lint-ok

#6768 [1LP][RFR] Removing BZ wrapper for test_vm_reconfig_add_remove_hw_cold
  cfme/tests/infrastructure/test_vm_reconfigure.py
Labels: tech-debt

#6763 [1LP][RFR] fixed non 0 region issue for list views in 5.8
  widgetastic_manageiq/__init__.py
Labels: fix-framework, lint-ok

#6772 [RFR] move wrapanapi to 2.8.2
  requirements/frozen.txt
Labels: other
