Repository ManageIQ/integration_tests, pull requests merged in 2018-12, with the labels that each got.

#8228 [1LP][RFR]Fix ScopeMismatch Error
  cfme/tests/infrastructure/test_vm_ownership.py
Labels: rc-regression-fix

#8231 [1LP][RFR] Update vddk_url() fixtures in test_compliance, test_actions, & test_alerts
  cfme/tests/control/test_actions.py
  cfme/tests/control/test_alerts.py
  cfme/tests/control/test_compliance.py
Labels: rc-regression-fix

#8233 [RFR][NOTEST]Unzip rework
  cfme/utils/template/base.py
Labels: infra-related, rc-regression-fix

#8226 [RFR] fix all method
  cfme/infrastructure/cluster.py
  cfme/infrastructure/datastore.py
Labels: rc-regression-fix

#8229 [RFR] Add blocker to test_upgrade_single_inplace
  cfme/tests/test_db_migrate.py
Labels: blockers-only

#8214 [1LP][RFR]New Test to validate emails in schedules and add a new attribute to `Schedule`
  cfme/intelligence/reports/reports.py
  cfme/intelligence/reports/schedules.py
  cfme/tests/intelligence/reports/test_crud.py
  data/schedules_crud/basic01.yaml
  data/schedules_report/daily.yaml
  data/schedules_report/hourly.yaml
  data/schedules_report/monthly.yaml
  data/schedules_report/once.yaml
  data/schedules_report/weekly.yaml
Labels: new-test-or-feature

#7929 [RFR] Integration tests for Redfish Physical Chassis and Racks
  cfme/exceptions.py
  cfme/physical/physical_chassis.py
  cfme/physical/physical_rack.py
  cfme/physical/provider/redfish.py
  cfme/tests/physical_infrastructure/test_redfish_physical_chassis.py
  cfme/tests/physical_infrastructure/test_redfish_physical_racks.py
  entry_points.txt
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
Labels: Redfish, fix-framework, lint-ok, new-test-or-feature

#8239 [1LP][RFR] Fixed KeyError and AssertionError in inline automate method
  cfme/automate/explorer/method.py
  cfme/tests/automate/test_vmware_methods.py
Labels: fix-test

#8240 [1LP][RFR] fixed is_displayed for BaseEditDashboardWidgetView and added BZ
  cfme/intelligence/reports/widgets/__init__.py
  cfme/tests/intelligence/reports/test_crud.py
Labels: fix-framework

#8223 [1LP][RFR] CB: refactor infra objects
  cfme/automate/buttons.py
  cfme/tests/automate/custom_button/__init__.py
  cfme/tests/automate/custom_button/test_buttons.py
  cfme/tests/automate/custom_button/test_cloud_objects.py
  cfme/tests/automate/custom_button/test_container_objects.py
  cfme/tests/automate/custom_button/test_infra_objects.py
Labels: fix-test

#8242 [1LP][RFR]v2v Edit mapping test case
  cfme/tests/v2v/test_v2v_migrations_ui.py
  cfme/v2v/migrations.py
  widgetastic_manageiq/__init__.py
Labels: new-test-or-feature

#8247 [1LP][RFR] added properties table for vmdb summary
  cfme/base/ui.py
  cfme/tests/configure/test_database_ui.py
Labels: enhancement

#8067 [1LP][RFR] Pre and post migration tests
  cfme/fixtures/ansible_fixtures.py
  cfme/fixtures/cli.py
  cfme/tests/ansible/test_embedded_ansible_actions.py
  cfme/tests/ansible/test_embedded_ansible_automate.py
  cfme/tests/ansible/test_embedded_ansible_basic.py
  cfme/tests/ansible/test_embedded_ansible_services.py
  cfme/tests/ansible/test_embedded_ansible_tags.py
  cfme/tests/cli/test_appliance_console_db_restore.py
  cfme/tests/cli/test_appliance_update.py
  cfme/tests/configure/test_log_depot_operation.py
  cfme/tests/v2v/test_v2v_ansible.py
  cfme/v2v/migrations.py
  conf/cfme_data.yaml.template
  widgetastic_manageiq/__init__.py
Labels: enhancement, new-test-or-feature

#8248 [1LP][RFR] added is_displayed for UtilizationView, fixed is_displayed for ServiceCatalogsDefaultView and added TimedOutError to exception for test_pull_splitter_persistence
  cfme/optimize/utilization.py
  cfme/services/service_catalogs/ui.py
  cfme/tests/webui/test_splitter.py
  cfme/utils/appliance/__init__.py
Labels: fix-framework

#8234 [1LP][RFR] unifying flash message xpaths and fixing issue in hammer
  cfme/automate/explorer/method.py
  cfme/base/login.py
  cfme/base/ssui.py
  cfme/base/ui.py
  cfme/configure/configuration/server_settings.py
  cfme/intelligence/reports/schedules.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: enhancement, fix-locator-or-text

#8251 [1LP][RFR] added check for the meta tag for IE11
  cfme/tests/test_ui.py
Labels: enhancement

#8244 [1LP][RFR] Fix ssui dashboard test
  cfme/services/dashboard/ssui.py
Labels: fix-test

#8269 Update pytest-collect-polarion
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: infra-related, other

#8255 [1LP][RFR] Fix fill for orchestration catalog item view
  cfme/services/catalogs/catalog_items/__init__.py
  cfme/services/myservice/ui.py
  cfme/services/service_catalogs/ui.py
Labels: fix-framework, tech-debt

#8230 [WIPTEST]Mark test cases with blockers and optimize the test cases
  cfme/tests/configure/test_visual_cloud.py
  cfme/tests/configure/test_visual_infra.py
Labels: enhancement

#8237 [RFR] added check for models and dialogs in log collection
  cfme/tests/configure/test_log_depot_operation.py
Labels: fix-test

#7936 [1LP][RFR] backup restore test
  cfme/tests/pod/test_appliance_crud.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
Labels: new-test-or-feature

#8261 [RFR] jhenner's tests cleanup
  cfme/tests/cli/test_appliance_cli.py
  cfme/tests/cli/test_appliance_console.py
  cfme/tests/cli/test_appliance_console_db_restore.py
  cfme/tests/cli/test_appliance_update.py
  cfme/tests/cloud/test_providers.py
  cfme/tests/cloud_infra_common/test_provisioning.py
  cfme/tests/cloud_infra_common/test_provisioning_manual.py
  cfme/tests/configure/test_db_backup_schedule.py
  cfme/tests/configure/test_register_appliance.py
  cfme/tests/configure/test_schedule_operations.py
  cfme/tests/configure/test_version.py
  cfme/tests/infrastructure/test_iso_provisioning.py
  cfme/tests/infrastructure/test_provisioning_dialog.py
  cfme/tests/intelligence/test_dashboard.py
  cfme/tests/intelligence/test_rss.py
  cfme/tests/test_appliance.py
  cfme/tests/test_db_migrate.py
  cfme/tests/test_db_migrate_manual.py
  cfme/tests/test_manual.py
  cfme/tests/test_replication.py
Labels: manual

#8224 [1LP][RFR] Fixed configuration DropdownDisabled issue
  cfme/configure/access_control/__init__.py
Labels: fix-test

#8222 [1LP][RFR] Fixed power option button is_displayed on archived vms details page
  cfme/tests/infrastructure/test_vm_power_control.py
Labels: fix-test

#8260 [1LP][RFR] new test_tag_mapping_azure_instances
  cfme/cloud/instance/__init__.py
  cfme/configure/configuration/region_settings.py
  cfme/tests/cloud/test_tag_mapping.py
  cfme/tests/test_manual.py
Labels: new-test-or-feature

#8263 [1LP][RFR]stack collection delete fix
  cfme/cloud/stack.py
Labels: fix-test

#8257 [1LP][RFR]Add new collections to rest test cases and fix few typos
  cfme/cloud/instance/image.py
  cfme/tests/test_rest.py
Labels: fix-test, new-test-or-feature

#8225 [1LP][RFR] Fixed assertion error while creating new group
  cfme/configure/access_control/__init__.py
Labels: fix-test

#8115 [1LP][WIPTEST] Add test for validation of Nuage Cloud Tenant inventory
  cfme/cloud/tenant.py
  cfme/fixtures/nuage.py
  cfme/networks/__init__.py
  cfme/networks/provider/__init__.py
  cfme/networks/provider/nuage.py
  cfme/tests/networks/nuage/test_inventory.py
Labels: Nuage, new-test-or-feature

#8238 [1LP][RFR] Update appliance name
  cfme/base/__init__.py
  cfme/base/ui.py
  cfme/utils/appliance/__init__.py
Labels: fix-framework

#8275 [1LP][RFR][NOTEST] update doc bock polarion
  cfme/tests/automate/custom_button/test_buttons.py
  cfme/tests/automate/custom_button/test_cloud_objects.py
  cfme/tests/automate/custom_button/test_container_objects.py
  cfme/tests/automate/custom_button/test_generic_objects.py
  cfme/tests/automate/custom_button/test_import_export.py
  cfme/tests/automate/custom_button/test_infra_objects.py
Labels: manual

#8273 [1LP][RFR] This PR blocks the test cases because of BZs
  cfme/tests/infrastructure/test_vm_power_control.py
Labels: blockers-only

#8221 [1LP][RFR] CB: service automate
  cfme/services/myservice/ssui.py
  cfme/tests/automate/custom_button/test_service_objects.py
  widgetastic_manageiq/__init__.py
Labels: fix-framework, new-test-or-feature

#8259 [1LP][RFR] Add test from flavors management RFE
  cfme/cloud/flavor.py
  cfme/tests/openstack/cloud/test_flavors.py
Labels: new-test-or-feature

#8264 [1LP][RFR] Read first row only from chargeback report
  cfme/tests/intelligence/chargeback/test_resource_allocation.py
Labels: fix-test

#8270 [RFR]Test migration with edited mapping
  cfme/tests/v2v/test_v2v_migrations.py
Labels: new-test-or-feature

#8280 [RFR]Fixed flash assertion error for catalog items
  cfme/services/catalogs/catalog_items/__init__.py
Labels: rc-regression-fix

#8279 [RFR]Fixed services orchestration template
  cfme/services/catalogs/orchestration_template.py
  cfme/tests/services/test_orchestration_template.py
Labels: blockers-only, rc-regression-fix

#8284 [1LP][RFR] Update validate_chargeback_report cost comparisons
  cfme/tests/intelligence/reports/test_validate_chargeback_report.py
Labels: enhancement, fix-test

#8285 [RFR] Re-enable server roles for chargeback report validation tests
  cfme/tests/intelligence/reports/test_validate_chargeback_report.py
Labels: rc-regression-fix

#8288 [RFR] Fixed DropDown is_displayed/is_enabled issue
  cfme/automate/explorer/method.py
  cfme/tests/automate/test_domain.py
Labels: rc-regression-fix

#8265 [1LP][RFR] Update "test_network_provider_add_with_bad_credentials" test
  cfme/tests/networks/test_network_providers.py
Labels: fix-locator-or-text

#8287 [RFR] Fix orchestration template flash assertion error
  cfme/services/catalogs/orchestration_template.py
Labels: rc-regression-fix

#8286 [1LP][RFR] Fix instantiation of server in ServerCollection.all()
  cfme/base/__init__.py
  cfme/base/ui.py
  cfme/tests/cloud/test_cloud_timelines.py
Labels: rc-regression-fix

#8290 [1LP][RFR] Update ViewSelector widgets and selected checks against title
  cfme/common/vm.py
  cfme/infrastructure/datastore.py
  cfme/infrastructure/provider/__init__.py
  cfme/physical/provider/__init__.py
  widgetastic_manageiq/__init__.py
Labels: rc-regression-fix

#8291 [1LP][RFR] Add manual label to release script
  cfme/utils/release.py
Labels: other

#8283 [1LP][RFR] Ensure Nuage AE Class contains auth attributes in AE Schema
  cfme/automate/explorer/__init__.py
  cfme/automate/explorer/klass.py
  cfme/tests/networks/nuage/test_automation.py
Labels: fix-framework, new-test-or-feature

#8278 [1LP][RFR]Fixed permissions service catalog item
  cfme/tests/services/test_catalog_item.py
Labels: enhancement, fix-test

#8266 [1LP][RFR] CB: test check quotes
  cfme/tests/automate/custom_button/test_buttons.py
Labels: new-test-or-feature

#8195 [1lP][RFR] Add test_volume_attach_detach_instance
  cfme/storage/volume.py
  cfme/tests/openstack/cloud/test_volumes.py
Labels: enhancement, new-test-or-feature

#8293 [1LP][RFR] removed generated manual test cases and respectively updated existing test cases
  cfme/tests/pod/test_appliance_crud.py
  cfme/tests/pod/test_ext_auth.py
  cfme/tests/test_manual.py
Labels: fix-locator-or-text

#8294 [RFR] Update manageiq-client
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: enhancement

#8150 [RFR] Test cloud subnet details
  cfme/cloud/tenant.py
  cfme/networks/network_router.py
  cfme/networks/subnet.py
  cfme/networks/views.py
  cfme/tests/networks/nuage/test_inventory.py
Labels: Nuage, new-test-or-feature

#8296 [RFR]Adding Blocker BZ to orchestration template test
  cfme/tests/services/test_orchestration_template.py
Labels: blockers-only

#8304 [1LP][RFR] ipv6 handing in sprout
  cfme/utils/appliance/__init__.py
  cfme/utils/net.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  sprout/appliances/tasks.py
Labels: issue-bug

#8292 [1LP][RFR] Fix cockpit server role
  cfme/tests/cloud_infra_common/test_cockpit_server.py
Labels: fix-test

#8306 [RFR] Fixed is_displayed for ActionDetailsView
  cfme/control/explorer/actions.py
Labels: fix-test

#8309 [1LP][RFR] fix sprout issues
  sprout/appliances/tasks.py
Labels: infra-related, issue-bug, sprout

#8307 [RFR] Fixed is_displayed for PolicyProfileDetailsView
  cfme/control/explorer/policy_profiles.py
Labels: fix-test

#8315 [RFR]Fix test catalog item crud
  cfme/services/catalogs/catalog_items/__init__.py
Labels: fix-test

#8289 [1LP][RFR][NOTEST] update cfme.utils for basic Notebooks
  notebooks/BasicApplianceSetup.ipynb
  notebooks/Browser Session.ipynb
  notebooks/Interaction with Timelines Notebook.ipynb
  notebooks/SSUI Login.ipynb
Labels: doc

#8316 [RFR] resetter method not able to access prerequisite view
  cfme/automate/explorer/klass.py
Labels: fix-framework

#8320 [RFR] Blocking test provisioning dialogs
  cfme/tests/automate/test_provisioning_dialogs.py
Labels: fix-locator-or-text

#8298 [RFR] Fix failing rest service test case
  cfme/rest/gen_data.py
Labels: fix-test

#8322 [1LP][RFR] Automating test_superadmin_tenant_admin_crud
  cfme/tests/configure/test_access_control.py
Labels: new-test-or-feature

#8267 [1LP][RFR] CB: Added test for open url
  cfme/tests/automate/custom_button/test_infra_objects.py
Labels: new-test-or-feature

#8303 [1LP][RFR] Moving manual multi-tenancy test
  cfme/tests/configure/test_access_control.py
  cfme/tests/test_manual.py
Labels: manual

#8169 [1LP][RFR] Test network router details
  cfme/networks/network_router.py
  cfme/tests/networks/nuage/test_inventory.py
Labels: new-test-or-feature
