Repository ManageIQ/integration_tests, pull requests merged in 2018-06, with the labels that each got.

#7303 [1LP][RFR]Adding new file which includes test case related to quota
  cfme/tests/infrastructure/test_quota.py
Labels: lint-ok, new-test-or-feature

#7257 [1LP][RFR] Skipping test: hypervisors IPs don't match Hosts IPs
  cfme/tests/openstack/cloud/test_instances.py
Labels: fix-test, lint-ok

#7322 [RFR] fix one test broken by collection conversion
  cfme/tests/cloud/test_providers.py
Labels: fix-test, lint-ok

#7315 [1LP][RFR] Fix instance create in test_tenant_quota
  cfme/cloud/instance/__init__.py
  cfme/tests/cloud/test_tenant_quota.py
Labels: enhancement, fix-test, lint-ok

#7313 [1LP][RFR]fixing azure event tests
  cfme/tests/cloud/test_cloud_events.py
  cfme/tests/cloud_infra_common/test_events.py
Labels: enhancement, lint-ok

#7317 [1LP][RFR] Remove mgmt method from CMQE object classes
  cfme/containers/image.py
  cfme/containers/image_registry.py
  cfme/containers/node.py
  cfme/containers/pod.py
  cfme/containers/project.py
  cfme/containers/replicator.py
  cfme/containers/route.py
  cfme/containers/service.py
  cfme/containers/template.py
  cfme/containers/volume.py
Labels: enhancement, lint-ok

#7319 [RFR][1LP] Map Tags to Collections
  cfme/configure/configuration/region_settings.py
  cfme/tests/configure/test_paginator.py
  setup.py
Labels: collections-conversion, lint-ok

#7311 [1LP][RFR]adding azure provider tests
  cfme/tests/cloud/test_providers.py
Labels: lint-ok, new-test-or-feature

#7309 [1LP][RFR] Added test_automate_instance_missing
  cfme/tests/automate/test_instance.py
Labels: lint-ok, new-test-or-feature

#7307 [1LP][RFR] Added test_automate_git_domain_removed_from_disk
  cfme/automate/import_export.py
  cfme/tests/automate/test_git_import.py
Labels: lint-ok, new-test-or-feature

#7298 [1LP][RFR] Skipping tests blocked by issue #7297
  cfme/tests/infrastructure/test_tenant_quota.py
  cfme/tests/ssui/test_ssui_ansible_service.py
  cfme/tests/ssui/test_ssui_dashboard.py
  cfme/tests/ssui/test_ssui_myservice.py
  cfme/tests/ssui/test_ssui_service_catalogs.py
Labels: fix-test, lint-ok

#7332 [RFR] new wrapanapi version + one fixed test
  cfme/tests/services/test_pxe_service_catalogs.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
Labels: fix-test, lint-ok

#7330 [1LP][RFR] fix for SSUI tests failing on page_has_changes js
  cfme/utils/appliance/implementations/ui.py
Labels: fix-framework, lint-ok

#7336 [1LP][RFR] Remove arg in template_upload_rhevm
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/template.txt
  scripts/template_upload_rhevm.py
Labels: infra-related, issue-bug, lint-ok

#7261 [1LP][RFR] Adding host credential tests
  cfme/common/host_views.py
  cfme/infrastructure/host.py
  cfme/tests/infrastructure/test_individual_host_creds.py
Labels: lint-ok, new-test-or-feature

#7279 [1LP][RFR] Some more tags test
  cfme/cloud/instance/image.py
  cfme/common/__init__.py
  cfme/storage/volume.py
  cfme/tests/cloud/test_providers.py
  cfme/tests/infrastructure/test_host.py
  cfme/tests/services/test_catalog_item.py
  cfme/tests/storage/test_volume.py
Labels: enhancement, fix-test, lint-ok, new-test-or-feature

#7345 [RFR] added provider to catalog items
  cfme/fixtures/service_fixtures.py
  cfme/services/catalogs/catalog_items/__init__.py
  cfme/services/myservice/ssui.py
  cfme/tests/ssui/test_ssui_myservice.py
Labels: issue-bug, lint-ok

#7341 [1LP][RFR] domain id validation for osp
  cfme/tests/cloud/test_providers.py
Labels: lint-ok, new-test-or-feature

#7342 [1LP][RFR] Scvmm test fixes
  cfme/common/provider_views.py
  cfme/tests/infrastructure/test_host.py
  cfme/tests/infrastructure/test_providers.py
Labels: fix-test, lint-ok

#7295 [1LP][RFR] Adding new widget to capture migrations not started/completed list in v2v
  cfme/v2v/migrations.py
  widgetastic_manageiq/__init__.py
Labels: enhancement, lint-ok

#7120 [1LP][RFR] Multiple vms ssa test
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
Labels: lint-ok, new-test-or-feature

#7340 [1LP][WIPTEST] Test: azure_provider_discovery_error
  cfme/cloud/provider/__init__.py
  cfme/tests/cloud/test_providers.py
Labels: WIP-testing, lint-ok, new-test-or-feature

#7271 [1LP][RFR]New tag expression tests
  cfme/configure/access_control/__init__.py
  cfme/tests/cloud_infra_common/test_tag_visibility.py
  cfme/tests/configure/test_access_control.py
  widgetastic_manageiq/expression_editor.py
Labels: lint-ok, new-test-or-feature

#7354 [1LP][RFR][NOTEST] Allow surf_pages for Network pages
  cfme/networks/balancer.py
  cfme/networks/cloud_network.py
  cfme/networks/network_port.py
  cfme/networks/network_router.py
  cfme/networks/provider/__init__.py
  cfme/networks/security_group.py
  cfme/networks/subnet.py
Labels: fix-test, lint-ok

#7351 [1LP][RFR] fix sdn balancer tagvis test
  cfme/tests/networks/test_sdn_balancers.py
Labels: fix-test, lint-ok

#7326 [1LP][RFR] fix summery download test for N/W
  cfme/tests/networks/test_sdn_downloads.py
Labels: fix-test, lint-ok

#7343 [1LP][RFR] Added new widget Infra Mappings List
  cfme/v2v/migrations.py
  widgetastic_manageiq/__init__.py
Labels: enhancement, lint-ok

#7310 [RFR] CMQE Automation Fixes and Fix to ManageIQ Table Sort
  cfme/containers/container.py
  cfme/containers/image.py
  cfme/containers/pod.py
  cfme/containers/project.py
  cfme/containers/provider/__init__.py
  cfme/containers/replicator.py
  cfme/containers/route.py
  cfme/containers/service.py
  cfme/containers/template.py
  cfme/containers/volume.py
  cfme/tests/containers/test_ad_hoc_metrics.py
  cfme/tests/containers/test_alerts.py
  cfme/tests/containers/test_basic_metrics.py
  cfme/tests/containers/test_logging.py
  cfme/tests/containers/test_tables_sort.py
  widgetastic_manageiq/__init__.py
Labels: fix-framework, lint-ok

#7363 Bump miq-version
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: lint-ok

#7368 Add 510z stream parser to trackerbot client util
  cfme/utils/trackerbot.py
Labels: infra-related, lint-ok, other

#7337 [1LP][RFR] Fixing Container Images perform_smartstate_analysis with correct task name
  cfme/configure/tasks.py
  cfme/containers/image.py
Labels: WIP-testing, fix-test, lint-ok

#7367 [RFR] introduce requirements/freeze_all.py --upgrade-only apackage and
  requirements/freeze.py
  requirements/freeze_all.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
  requirements/test_frozen_requirements.py
Labels: lint-ok

#7359 [RFR] Split quickstart
  cfme/scripting/quickstart.py
  cfme/scripting/quickstart/__init__.py
  cfme/scripting/quickstart/__main__.py
  cfme/scripting/quickstart/proc.py
  cfme/scripting/quickstart/system.py
  cfme/scripting/tests/test_quickstart.py
Labels: lint-ok

#7370 Add 510z stream parser to trackerbot client util
  cfme/utils/trackerbot.py
Labels: infra-related

#7335 [1LP][RFR] moving vm provision to common
  cfme/cloud/instance/__init__.py
  cfme/cloud/instance/azure.py
  cfme/cloud/instance/gce.py
  cfme/common/vm.py
  cfme/infrastructure/virtual_machines.py
  cfme/tests/cloud/test_provisioning.py
  cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py
  cfme/tests/cloud_infra_common/test_provisioning.py
  cfme/tests/infrastructure/test_cloud_init_provisioning.py
  cfme/tests/infrastructure/test_provisioning.py
  data/rootpass.cfg
Labels: enhancement, lint-ok

#7116 [1LP][RFR] Implementing Infra service quota tagging related test case.
  cfme/tests/infrastructure/test_quota_tagging.py
Labels: lint-ok, new-test-or-feature

#7375 [RFR] Fixed filtering for supported providers
  cfme/markers/env_markers/provider.py
Labels: lint-ok

#7344 [1LP][RFR] V2v migration details page
  cfme/v2v/migrations.py
  widgetastic_manageiq/__init__.py
Labels: enhancement, lint-ok

#7371 [RFR] Wrapping test_provision_attributes with BZ1592326
  cfme/tests/infrastructure/test_provisioning_rest.py
Labels: lint-ok

#7376 [1LP][RFR] Caching for provider types
  cfme/common/provider.py
Labels: enhancement, lint-ok

#7355 [1LP][RFR] workaround for some bug in ansible pod
  cfme/utils/appliance/__init__.py
Labels: fix-framework, lint-ok

#7361 [RFR] Fixing catalog item form filling
  cfme/services/catalogs/catalog_items/__init__.py
Labels: fix-framework, lint-ok

#7374 [RFR] Force sprout use miq version instead of its own regexps
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
  requirements/template_docs.txt
  sprout/appliances/tasks.py
  sprout/requirements.txt
Labels: lint-ok, sprout, tech-debt

#7380 [1LP][RFR] Update attr.ib convert -> converter
  cfme/utils/appliance/__init__.py
  cfme/utils/appliance/plugin.py
Labels: enhancement, lint-ok

#7352 [1LP][RFR] Fix CMQE Persistent Volume Fixture
  cfme/fixtures/has_persistent_volume.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/template.txt
Labels: lint-ok

#7356 [WIPTEST] Fixed hosts credentials
  cfme/infrastructure/host.py
  cfme/infrastructure/provider/__init__.py
  cfme/tests/infrastructure/test_datastore_analysis.py
  cfme/tests/infrastructure/test_esx_direct_host.py
  cfme/tests/infrastructure/test_individual_host_creds.py
  cfme/utils/hosts.py
  conf/cfme_data.yaml.template
Labels: WIP-testing, fix-framework, fix-test, lint-ok

#7382 [1LP][RFR] Wrapping test_provision_attributes with BZ1592326
  cfme/tests/infrastructure/test_provisioning_rest.py
Labels: fix-test, lint-ok

#7381 [1LP][RFR] Update ext-auth tests to handle multiple groups
  cfme/fixtures/authentication.py
  cfme/tests/integration/test_cfme_auth.py
Labels: enhancement, lint-ok

#7377 [1LP][RFR] Adding wrappers for BZ1591606 and BZ1592430
  cfme/tests/infrastructure/test_vm_power_control.py
  cfme/tests/infrastructure/test_vm_reconfigure.py
Labels: fix-test, lint-ok

#7138 [1LP][RFR]Adding test case related cloud quota tagging.
  cfme/tests/cloud/test_quota_tagging.py
Labels: lint-ok, new-test-or-feature

#7379 [1LP][RFR] replace steam regexps in favor of miq-version
  cfme/utils/template/template_upload.py
  cfme/utils/trackerbot.py
  scripts/sync_template_tracker.py
  scripts/template_upload_all.py
Labels: infra-related, issue-bug, lint-ok

#7389 [1LP][RFR] added supportability template
  conf/supportability.yaml.template
Labels: enhancement, lint-ok

#7390 [1LP][RFR] server name isn't available for pod 5.10 now
  cfme/base/__init__.py
Labels: fix-framework, lint-ok

#7393 [1LP][RFR] Fix get_valid_providers to account for multiple providers of the same…
  cfme/markers/env_markers/provider.py
Labels: WIP-testing, issue-bug, lint-ok

#7395 [1LP][RFR] Change required to support dual browser setup in container
  cfme/tests/test_login.py
  cfme/utils/browser.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
  requirements/template_docs.txt
Labels: lint-ok, tech-debt

#7353 [1LP][RFR] all method filtering support NetworkProvider
  cfme/networks/provider/__init__.py
  cfme/tests/networks/test_sdn_crud.py
  cfme/tests/networks/test_sdn_navigation.py
Labels: enhancement, lint-ok

#7392 [RFR] Adjust new instance fixture to use collections
  cfme/tests/openstack/cloud/test_instances.py
Labels: lint-ok

#7397 [RFR] Fix for Wharf
  cfme/utils/browser.py
Labels: issue-bug, lint-ok

#7348 [RFR][NOTEST]flagging tests to avoid collection for azure_msdn
  cfme/tests/cloud/test_cloud_timelines.py
  cfme/tests/networks/test_sdn_balancers.py
  cfme/tests/networks/test_sdn_inventory_collection.py
  cfme/tests/networks/test_sdn_navigation.py
  cfme/tests/ssui/test_ssui_myservice.py
  cfme/tests/ssui/test_ssui_service_catalogs.py
Labels: fix-test, lint-ok

#7357 [1LP][RFR] Daily and Hourly graph tests
  cfme/fixtures/candu.py
  cfme/tests/candu/test_vm_graph.py
Labels: lint-ok, new-test-or-feature

#7398 [RFR] Only delete marionette on chrome if its there
  cfme/utils/browser.py
Labels: issue-bug, lint-ok

#7362 [1LP][RFR] v2v migration plan collections and widgets
  cfme/v2v/migrations.py
  widgetastic_manageiq/__init__.py
Labels: enhancement, lint-ok

#7384 [1LP][RFR] Ext-auth group switching test
  cfme/tests/integration/test_cfme_auth.py
Labels: lint-ok, new-test-or-feature

#7406 [1LP][RFR] Removing infrastructure_mapping collection as we have v2v_mappings collection
  setup.py
Labels: fix-framework, lint-ok, rc-regression-fix

#7412 [RFR] Allow quickstart to support Fedora 28
  cfme/scripting/quickstart/system.py
  cfme/utils/browser.py
Labels: rc-regression-fix

#7413 [RFR] Fixed an error
  cfme/utils/browser.py
Labels: rc-regression-fix

#7403 [1LP][RFR] Update sync_template_tracker, fixes and new arg
  scripts/sync_template_tracker.py
Labels: lint-ok, rc-regression-fix

#7258 [1LP][RFR] Move breadcrumb widget to patternfly
  cfme/ansible/playbooks.py
  cfme/cloud/availability_zone.py
  cfme/cloud/flavor.py
  cfme/cloud/keypairs.py
  cfme/cloud/provider/__init__.py
  cfme/cloud/stack.py
  cfme/cloud/tenant.py
  cfme/common/__init__.py
  cfme/common/host_views.py
  cfme/common/physical_server_views.py
  cfme/common/provider_views.py
  cfme/common/vm_views.py
  cfme/configure/settings.py
  cfme/containers/node.py
  cfme/containers/provider/__init__.py
  cfme/infrastructure/cluster.py
  cfme/infrastructure/deployment_roles.py
  cfme/infrastructure/provider/__init__.py
  cfme/infrastructure/resource_pool.py
  cfme/services/requests.py
  cfme/storage/manager.py
  cfme/storage/object_store_container.py
  cfme/storage/object_store_object.py
  cfme/storage/volume.py
  cfme/storage/volume_backup.py
  cfme/storage/volume_snapshot.py
  cfme/tests/cloud/test_stack.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
  widgetastic_manageiq/__init__.py
Labels: enhancement, lint-ok

#6942 [1LP][RFR] New proxy tests
  cfme/tests/configure/test_proxy.py
  cfme/utils/appliance/__init__.py
Labels: lint-ok, new-test-or-feature

#7324 [1LP][RFR] Categories, Tags collection conversion
  cfme/common/__init__.py
  cfme/configure/configuration/region_settings.py
  cfme/fixtures/tag.py
  cfme/generic_objects/instance/ui.py
  cfme/infrastructure/config_management.py
  cfme/tests/cloud_infra_common/test_retirement.py
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
  cfme/tests/configure/test_paginator.py
  cfme/tests/configure/test_tag.py
  cfme/tests/configure/test_tag_category.py
  cfme/tests/infrastructure/test_config_management.py
  cfme/tests/infrastructure/test_host_drift_analysis.py
  cfme/tests/infrastructure/test_quota_tagging.py
  setup.py
Labels: collections-conversion, lint-ok

#7334 [1LP][RFR] General UI new tests
  cfme/base/__init__.py
  cfme/base/ui.py
  cfme/configure/access_control/__init__.py
  cfme/tests/webui/test_general_ui.py
Labels: lint-ok, new-test-or-feature
