Repository ManageIQ/integration_tests, pull requests merged in 2018-08, with the labels that each got.

#7473 [1LP][RFR] support for azure ec2 and rhv graph
  cfme/tests/candu/__init__.py
  cfme/tests/candu/test_host_graph.py
  cfme/tests/candu/test_vm_graph.py
Labels: fix-test, lint-ok, new-test-or-feature

#6427 [1LP][RFR] Moving ownership function to use objects
  cfme/common/vm.py
  cfme/tests/cloud_infra_common/test_vm_ownership.py
  cfme/tests/intelligence/chargeback/test_chargeback_long_term_rates.py
  cfme/tests/intelligence/chargeback/test_resource_allocation.py
  cfme/tests/intelligence/reports/test_metering_report.py
  cfme/tests/intelligence/reports/test_validate_chargeback_report.py
Labels: enhancement, lint-ok

#7564 [1LP][RFR] Add BZ1608958 blocker
  cfme/tests/services/test_rest_services.py
Labels: fix-test, lint-ok

#7423 [1LP][RFR] Replacing setup_host_creds() by Host.update_credentials_rest()
  cfme/fixtures/v2v.py
  cfme/infrastructure/datastore.py
  cfme/infrastructure/host.py
  cfme/infrastructure/provider/__init__.py
  cfme/tests/configure/test_schedule_operations.py
  cfme/tests/control/test_actions.py
  cfme/tests/control/test_alerts.py
  cfme/tests/control/test_compliance.py
  cfme/tests/infrastructure/test_datastore_analysis.py
  cfme/tests/infrastructure/test_ssa_vddk.py
  cfme/utils/appliance/__init__.py
  cfme/utils/hosts.py
Labels: enhancement, lint-ok

#7576 [1LP][RFR] Adding blocker for smart mgmt tests
  cfme/tests/containers/test_smart_management.py
Labels: blockers-only, lint-ok

#7541 [1LP][RFR] Test OCP operator role out-of-the-box
  cfme/tests/containers/test_provider_configuration_menu.py
Labels: lint-ok, new-test-or-feature

#7528 [1LP][RFR] Remove provider argument from host collection all
  cfme/tests/openstack/infrastructure/test_hosts.py
  cfme/tests/openstack/infrastructure/test_roles.py
Labels: fix-test, lint-ok

#7539 [1LP][RFR] Add negative test (wrong API port for container provider)
  cfme/tests/containers/test_ssl_providers.py
Labels: lint-ok, new-test-or-feature

#7571 [1LP][RFR] Update openstack/cloud/test_instances
  cfme/tests/openstack/cloud/test_instances.py
Labels: fix-test, lint-ok

#7414 [1LP][WIPTEST] New auth providers users
  cfme/fixtures/authentication.py
  cfme/tests/integration/test_cfme_auth.py
  cfme/utils/auth/__init__.py
Labels: WIP-testing, enhancement, fix-test, lint-ok

#7283 [1LP][RFR] Glance Template Upload
  cfme/common/vm.py
  cfme/networks/provider/__init__.py
  cfme/tests/cloud_infra_common/test_events.py
  cfme/tests/cloud_infra_common/test_genealogy.py
  cfme/tests/containers/test_projects_dashboard.py
  cfme/tests/control/test_actions.py
  cfme/tests/infrastructure/test_iso_provisioning.py
  cfme/tests/infrastructure/test_provisioning_dialog.py
  cfme/tests/infrastructure/test_pxe_provisioning.py
  cfme/tests/infrastructure/test_vm_clone.py
  cfme/tests/infrastructure/test_vm_migrate.py
  cfme/tests/infrastructure/test_vm_power_control.py
  cfme/tests/services/test_cloud_service_catalogs.py
  cfme/tests/test_modules_importable.py
  cfme/utils/appliance/__init__.py
  cfme/utils/template/README.md
  cfme/utils/template/base.py
  cfme/utils/template/ec2.py
  cfme/utils/template/gce.py
  cfme/utils/template/openshift.py
  cfme/utils/template/openstack.py
  cfme/utils/template/rhevm.py
  cfme/utils/template/rhopenshift.py
  cfme/utils/template/scvmm.py
  cfme/utils/template/template_upload.py
  cfme/utils/template/virtualcenter.py
  cfme/utils/trackerbot.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
  requirements/template.txt
  scripts/clone_template.py
  scripts/latest_template_tester_report.py
  scripts/sync_template_tracker.py
  scripts/template_upload_rhevm.py
  sprout/appliances/models.py
  sprout/appliances/tasks.py
  sprout/appliances/views.py
  sprout/logserver.py
  sprout/requirements.txt
  sprout/sprout.sh
Labels: infra-related, lint-ok, other, sprout

#7480 [1LP][RFR] AnalysisProfile collection conversion
  cfme/configure/configuration/analysis_profile.py
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
  cfme/tests/configure/test_analysis_profiles.py
  cfme/tests/configure/test_paginator.py
  cfme/tests/control/test_compliance.py
  cfme/tests/infrastructure/test_ssa_vddk.py
  entry_points.txt
Labels: collections-conversion, lint-ok

#7396 [1LP][RFR] Adding new test case and implementing fix for the a failure.
  cfme/common/vm.py
  cfme/tests/cloud/test_quota_tagging.py
  cfme/tests/cloud/test_tenant_quota.py
Labels: lint-ok, new-test-or-feature

#7112 [1LP][RFR] Added the ability for any object to have a list destinations fn
  cfme/utils/appliance/__init__.py
  cfme/utils/appliance/implementations/__init__.py
  cfme/utils/appliance/implementations/rest.py
  cfme/utils/appliance/implementations/ssui.py
  cfme/utils/appliance/implementations/ui.py
Labels: enhancement, lint-ok

#7275 [1LP][RFR] Bottlenecks collection conversion
  cfme/optimize/bottlenecks.py
  cfme/tests/optimize/test_bottlenecks.py
  entry_points.txt
Labels: collections-conversion, lint-ok

#7318 [1LP][RFR] SystemImage and ISO datastore changes
  cfme/infrastructure/pxe.py
  cfme/tests/infrastructure/test_iso_datastore.py
  cfme/tests/infrastructure/test_iso_provisioning.py
  entry_points.txt
Labels: enhancement, fix-test, lint-ok

#7533 [1LP][RFR] Azone Graph Initial commit
  cfme/cloud/availability_zone.py
  cfme/common/candu_views.py
  cfme/tests/candu/test_azone_graph.py
Labels: lint-ok, new-test-or-feature

#7558 [1LP][RFR] Added 2 new volume backup tests
  cfme/tests/openstack/cloud/test_volume_backup.py
Labels: lint-ok

#7569 [1LP][RFR] Fix version string comparison in delete REST tests
  cfme/utils/rest.py
Labels: fix-test, lint-ok

#7578 [1LP][RFR] Fix clicking checkboxes on HostDriftHistory view (2. attempt)
  cfme/tests/infrastructure/test_host_drift_analysis.py
Labels: fix-test, lint-ok

#7582 [1LP][RFR] Used provider.nodes.all()
  cfme/infrastructure/host.py
  cfme/tests/openstack/infrastructure/test_host_power_control.py
Labels: enhancement, lint-ok

#7585 [1LP][RFR] Fixed dashboard widget column locator
  cfme/dashboard.py
Labels: fix-locator-or-text, lint-ok

#7586 [1LP][RFR] Fixed KeyError: 'total_snapshots' in openstack tests
  cfme/common/vm_views.py
Labels: fix-framework, lint-ok

#7589 [1LP][RFR] Update template upload, ovftool error logging
  cfme/utils/template/base.py
  cfme/utils/template/virtualcenter.py
Labels: enhancement, infra-related, lint-ok

#7598 [RFR] wrapanapi 3.0.22
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
Labels: lint-ok, other

#7306 [1LP][RFR] This removes a_provider and replaces with equivalent provider marks
  cfme/rest/gen_data.py
  cfme/tests/configure/test_access_control.py
  cfme/tests/configure/test_tag.py
  cfme/tests/infrastructure/test_advanced_search_vms.py
  cfme/tests/infrastructure/test_infra_tag_filters_combination.py
  cfme/tests/infrastructure/test_rest_automation_request.py
  cfme/tests/infrastructure/test_rest_templates.py
  cfme/tests/infrastructure/test_vm_ownership.py
  cfme/tests/infrastructure/test_vm_rest.py
  cfme/tests/infrastructure/test_vm_retirement_rest.py
  cfme/tests/services/test_operations.py
  cfme/tests/services/test_rest_services.py
  cfme/tests/test_rest.py
Labels: enhancement, lint-ok

#7543 [1LP][RFR] Version picking unified
  cfme/automate/dialog_box.py
  cfme/automate/dialog_collection_pick.py
  cfme/automate/dialog_element.py
  cfme/automate/dialog_tab.py
  cfme/automate/service_dialogs.py
  cfme/base/credential.py
  cfme/cloud/instance/__init__.py
  cfme/cloud/provider/azure.py
  cfme/common/provider.py
  cfme/containers/provider/__init__.py
  cfme/control/explorer/conditions.py
  cfme/control/explorer/policies.py
  cfme/fixtures/ui_coverage.py
  cfme/infrastructure/config_management.py
  cfme/infrastructure/provider/rhevm.py
  cfme/infrastructure/virtual_machines.py
  cfme/physical/provider/__init__.py
  cfme/rest/gen_data.py
  cfme/tests/automate/test_service_dialog.py
  cfme/tests/containers/test_properties.py
  cfme/utils/__init__.py
  cfme/utils/appliance/__init__.py
  cfme/utils/ssh.py
  cfme/utils/version.py
  entry_points.txt
Labels: enhancement, lint-ok

#7595 [1LP][RFR]removal of new templates from test_modules_importable.py
  .travis.yml
  cfme/networks/provider/__init__.py
  cfme/tests/test_modules_importable.py
  conf/cfme_data.yaml.template
Labels: lint-ok, other

#7512 [1LP][RFR] ansible deployment test for pod appliance
  cfme/tests/pod/test_appliance_crud.py
  cfme/utils/ssh.py
Labels: lint-ok, new-test-or-feature

#7597 [1LP][RFR] Fixed test_domain_import_git
  cfme/base/ui.py
Labels: fix-locator-or-text, lint-ok

#7579 [1LP][RFR] Fixed TypeError while collecting hosts
  cfme/tests/infrastructure/test_tenant_quota.py
Labels: fix-test, lint-ok

#7559 [1LP][RFR] Initial cluster graph commit
  cfme/common/candu_views.py
  cfme/infrastructure/cluster.py
  cfme/tests/candu/test_cluster_graph.py
Labels: lint-ok, new-test-or-feature

#7604 [1LP][RFR] Adding clone BZ to test_query_provider_attributes
  cfme/tests/cloud_infra_common/test_rest_providers.py
Labels: blockers-only, lint-ok

#7580 [1LP][RFR] Added test_instance_attach_volume and related methods
  cfme/cloud/instance/openstack.py
  cfme/tests/openstack/cloud/test_instances.py
Labels: lint-ok, new-test-or-feature

#7599 [1LP][RFR] Fixed test_method_inputs
  cfme/automate/explorer/method.py
Labels: fix-locator-or-text, lint-ok

#7601 [1LP][RFR] moved test_list_networks from infra to cloud
  cfme/tests/openstack/cloud/test_networks.py
  cfme/tests/openstack/infrastructure/test_networks.py
Labels: fix-locator-or-text, lint-ok

#7581 [1LP][RFR] get rid of CloudInfraProvider class
  cfme/cloud/provider/__init__.py
  cfme/common/provider.py
  cfme/infrastructure/provider/__init__.py
  cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py
  cfme/tests/cloud_infra_common/test_cockpit_server.py
  cfme/tests/cloud_infra_common/test_custom_attributes_rest.py
  cfme/tests/cloud_infra_common/test_html5_vm_console.py
  cfme/tests/cloud_infra_common/test_provisioning.py
  cfme/tests/cloud_infra_common/test_relationships.py
  cfme/tests/cloud_infra_common/test_rest_providers.py
  cfme/tests/cloud_infra_common/test_retirement.py
  cfme/tests/cloud_infra_common/test_tag_visibility.py
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
  cfme/tests/cloud_infra_common/test_vm_ownership.py
  cfme/tests/intelligence/chargeback/test_resource_allocation.py
  cfme/tests/intelligence/reports/test_metering_report.py
  cfme/tests/intelligence/reports/test_validate_chargeback_report.py
Labels: enhancement, lint-ok

#7621 [1LP][RFR][NOTEST] Related datastore for VM
  cfme/infrastructure/virtual_machines.py
Labels: enhancement, lint-ok

#7605 [RFR] remove bad json deserialization statements in sprout and etc
  scripts/clone_template.py
  sprout/appliances/tasks.py
Labels: infra-related, lint-ok, sprout

#7620 [RFR] generic shepherd fix for openshift
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  sprout/appliances/tasks.py
Labels: infra-related, lint-ok

#7607 [1LP][RFR] Fix test service/ssui tests for cloud provider
  cfme/fixtures/service_fixtures.py
Labels: fix-test, lint-ok

#7625 [RFR] Making sure we've got VM IP in test_provision_cloud_init
  cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py
Labels: fix-test, lint-ok

#7563 [RFR] Added table object to ContainerObjectAllBaseView
  cfme/tests/containers/test_tables_fields.py
Labels: fix-test, lint-ok

#6219 [1LP][RFR][poc] initial support for explicitly passing of the appliance version
  cfme/scripting/sprout.py
  cfme/test_framework/appliance.py
  cfme/test_framework/sprout/plugin.py
  cfme/utils/appliance/__init__.py
Labels: enhancement, lint-ok

#7609 [1LP][RFR] fixed navigation to AllForProvider view via deleted instance
  cfme/tests/openstack/cloud/test_instances.py
Labels: fix-test, lint-ok

#7617 [1LP][RFR] Fixed test_provisioning_dialog_crud
  cfme/tests/automate/test_provisioning_dialogs.py
Labels: fix-test, lint-ok

#7618 [1LP][RFR][NOTEST] fix for historical data with unicode and str
  cfme/common/vm.py
  cfme/infrastructure/host.py
Labels: enhancement, lint-ok

#7633 [1LP][RFR] Duplicate self.data to preserve internal state
  cfme/networks/provider/nuage.py
Labels: fix-framework, lint-ok

#7590 [1LP][RFR] Fixed test_custom_button_ansible_credential_list
  cfme/services/service_catalogs/ui.py
  cfme/tests/ansible/test_embedded_ansible_services.py
Labels: fix-framework, fix-test, lint-ok

#7632 [1LP][RFR] Check all stats for Nuage provider
  cfme/networks/provider/nuage.py
Labels: lint-ok

#7626 [1LP][RFR] Adding RHV tier as property to XML report
  cfme/markers/rhv.py
Labels: enhancement, lint-ok

#7644 [RFR] fix appliance rename issue in sprout for rhv providers
  sprout/appliances/tasks.py
Labels: issue-bug, lint-ok, sprout

#7524 [1LP][RFR] Modify is_displayed method in every provider's Edit view
  cfme/cloud/provider/__init__.py
  cfme/common/provider_views.py
  cfme/containers/provider/__init__.py
  cfme/infrastructure/provider/__init__.py
  cfme/networks/views.py
  cfme/physical/provider/__init__.py
Labels: fix-framework, lint-ok

#7648 miq-version 0.1.7
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
  sprout/requirements.txt
Labels: rc-regression-fix, sprout

#7635 [1LP][RFR] temporary workaround to cleanup httpd semaphores when httpd was killed
  cfme/utils/appliance/__init__.py
Labels: issue-bug, lint-ok, rc-regression-fix, tech-debt

#7631 [RFR] fixed version check in sprout
  cfme/utils/appliance/__init__.py
  sprout/appliances/tasks.py
Labels: fix-framework, lint-ok, rc-regression-fix

#7646 [1LP][RFR] Fixing analysis profile creation for SSA tests
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
Labels: WIP-testing, fix-test, lint-ok, rc-regression-fix

#7610 [1LP][RFR] This PR will fix the scope of test and updated with Analysis profile create method.
  cfme/tests/infrastructure/test_ssa_vddk.py
Labels: lint-ok, rc-regression-fix

#7387 [1LP][RFR] CMQE Stabilization Effort
  cfme/containers/container.py
  cfme/containers/image.py
  cfme/containers/image_registry.py
  cfme/containers/pod.py
  cfme/containers/project.py
  cfme/containers/provider/__init__.py
  cfme/containers/provider/openshift.py
  cfme/containers/replicator.py
  cfme/containers/route.py
  cfme/containers/service.py
  cfme/containers/template.py
  cfme/containers/volume.py
  cfme/tests/containers/test_ad_hoc_metrics.py
  cfme/tests/containers/test_basic_metrics.py
  cfme/tests/containers/test_breadcrumbs.py
  cfme/tests/containers/test_cockpit.py
  cfme/tests/containers/test_labels.py
  cfme/tests/containers/test_logging.py
  cfme/tests/containers/test_properties.py
  cfme/tests/containers/test_relationships.py
  cfme/tests/containers/test_reports.py
  cfme/tests/containers/test_static_custom_attributes.py
  cfme/tests/containers/test_tags.py
  cfme/utils/appliance/__init__.py
Labels: enhancement, fix-test, lint-ok

#7515 [RFR] Updating provider summary tables fields
  cfme/containers/provider/__init__.py
  cfme/containers/provider/openshift.py
Labels: fix-locator-or-text, lint-ok

#7651 [1LP][RFR] Remove last a_provider uses
  cfme/rest/gen_data.py
  cfme/tests/infrastructure/test_infra_tag_filters_combination.py
  cfme/tests/infrastructure/test_rest_automation_request.py
  cfme/tests/infrastructure/test_rest_templates.py
  cfme/tests/infrastructure/test_vm_retirement_rest.py
  cfme/tests/services/test_rest_services.py
Labels: lint-ok, rc-regression-fix

#7649 [1LP][RFR] DRY the fixtures for V2V
  cfme/fixtures/v2v.py
  cfme/tests/v2v/test_v2v_migrations.py
  cfme/tests/v2v/test_v2v_migrations_ui.py
  cfme/utils/appliance/__init__.py
Labels: lint-ok, rc-regression-fix

#7659 [1LP][RFR] fix for issue when sprout restarts rhev appliances after delivery
  sprout/appliances/tasks.py
Labels: infra-related, issue-bug, lint-ok, rc-regression-fix, sprout

#7660 [RFR] Adding @pytest.mark.rhel_testing to a number of test cases for rhel t…
  cfme/tests/ansible/test_embedded_ansible_basic.py
  cfme/tests/automate/test_provisioning_dialogs.py
  cfme/tests/automate/test_smoke.py
  cfme/tests/cli/test_appliance_cli.py
  cfme/tests/cli/test_appliance_console.py
  cfme/tests/cli/test_appliance_console_db_restore.py
  cfme/tests/cli/test_appliance_update.py
  cfme/tests/cloud/test_instance_power_control.py
  cfme/tests/cloud/test_providers.py
  cfme/tests/cloud_infra_common/test_provisioning.py
  cfme/tests/configure/test_database_ui.py
  cfme/tests/configure/test_register_appliance.py
  cfme/tests/control/test_actions.py
  cfme/tests/distributed/test_appliance_replication.py
  cfme/tests/infrastructure/test_child_tenant.py
  cfme/tests/infrastructure/test_delete_infra_object.py
  cfme/tests/infrastructure/test_provisioning_dialog.py
  cfme/tests/infrastructure/test_vm_reconfigure.py
  cfme/tests/integration/test_cfme_auth.py
  cfme/tests/intelligence/reports/test_crud.py
  cfme/tests/intelligence/reports/test_generate_report.py
  cfme/tests/intelligence/test_chargeback.py
  cfme/tests/intelligence/test_dashboard.py
  cfme/tests/networks/test_network_providers.py
  cfme/tests/networks/test_sdn_crud.py
  cfme/tests/optimize/test_bottlenecks.py
  cfme/tests/services/test_catalog.py
  cfme/tests/ssui/test_ssui_ansible_service.py
  cfme/tests/ssui/test_ssui_dashboard.py
  cfme/tests/ssui/test_ssui_myservice.py
  cfme/tests/test_login.py
  cfme/tests/test_rest.py
Labels: enhancement, lint-ok

#7652 [1LP][RFR] Fix KeyError in test_rest_services for dialog_service_name
  cfme/rest/gen_data.py
  cfme/tests/services/test_rest_services.py
Labels: fix-test, lint-ok, rc-regression-fix

#7638 [1LP][RFR][NOTEST] Custom Button: new object types
  cfme/automate/buttons.py
Labels: enhancement, lint-ok

#7662 [1LP][RFR] additional sprout client/server fixes in order to fix the issue caused by reboot during rename vm
  cfme/test_framework/sprout/plugin.py
  sprout/appliances/tasks.py
Labels: infra-related, lint-ok, rc-regression-fix

#7658 [1LP][RFR] Remove deadlock from ssh client.
  cfme/utils/ssh.py
Labels: fix-framework, lint-ok

#7612 [1LP][RFR] Bump pycurl to version 7.43.0.2
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
Labels: enhancement, lint-ok

#7523 [1LP][NOTEST][RFR] This PR will add wait between validate and save operation.
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
Labels: fix-framework, lint-ok, tech-debt

#7600 [1LP][RFR] Removed unneeded VersionPicks
  cfme/ansible/credentials.py
  cfme/ansible_tower/explorer.py
  cfme/automate/buttons.py
  cfme/automate/explorer/klass.py
  cfme/automate/explorer/method.py
  cfme/cloud/instance/__init__.py
  cfme/cloud/instance/image.py
  cfme/cloud/keypairs.py
  cfme/cloud/tenant.py
  cfme/common/host_views.py
  cfme/common/physical_server_views.py
  cfme/common/physical_switch_views.py
  cfme/common/provider_views.py
  cfme/common/topology.py
  cfme/common/vm.py
  cfme/common/vm_views.py
  cfme/configure/access_control/__init__.py
  cfme/configure/documentation.py
  cfme/configure/settings.py
  cfme/configure/tasks.py
  cfme/containers/container.py
  cfme/containers/image_registry.py
  cfme/containers/node.py
  cfme/containers/pod.py
  cfme/containers/project.py
  cfme/containers/provider/__init__.py
  cfme/containers/replicator.py
  cfme/containers/route.py
  cfme/control/explorer/alert_profiles.py
  cfme/generic_objects/definition/definition_views.py
  cfme/generic_objects/instance/ui.py
  cfme/infrastructure/config_management.py
  cfme/infrastructure/datastore.py
  cfme/infrastructure/deployment_roles.py
  cfme/infrastructure/host.py
  cfme/infrastructure/pxe.py
  cfme/infrastructure/virtual_machines.py
  cfme/intelligence/reports/reports.py
  cfme/intelligence/reports/widgets/__init__.py
  cfme/scripting/setup_env.py
  cfme/services/catalogs/catalog_items/__init__.py
  cfme/services/catalogs/catalog_items/ansible_catalog_items.py
  cfme/services/myservice/ui.py
  cfme/services/requests.py
  cfme/services/service_catalogs/__init__.py
  cfme/storage/manager.py
  cfme/tests/integration/test_aws_iam_auth_and_roles.py
  cfme/utils/appliance/__init__.py
Labels: enhancement, lint-ok

#7640 [NOTEST][RFR][1LP] This PR will change label of smartstate agent.
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
Labels: enhancement, lint-ok

#7643 [1LP][RFR][NOTEST] Adding RHV tier to test_provision_cloud_init
  cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py
Labels: enhancement, lint-ok

#7682 [1LP][RFR] Update httpd workaround for 59z
  cfme/utils/appliance/__init__.py
  cfme/utils/appliance/services.py
Labels: enhancement, lint-ok

#7608 [1LP][RFR] Parameterize default and compare views tests for clouds
  cfme/tests/configure/test_default_views_cloud.py
  cfme/tests/configure/test_default_views_infra.py
Labels: enhancement, lint-ok

#7664 [1LP][RFR] Update test_register_appliance
  cfme/tests/configure/test_register_appliance.py
Labels: enhancement, fix-test, lint-ok

#7624 [1LP][RFR] Datastore Hourly graph
  cfme/common/candu_views.py
  cfme/infrastructure/datastore.py
  cfme/tests/candu/test_datastore_graph.py
Labels: enhancement, lint-ok, new-test-or-feature

#7657 [1LP][RFR] Custom Button: Group crud parametrization for All objects
  cfme/automate/buttons.py
  cfme/tests/automate/test_buttons.py
Labels: enhancement, lint-ok, new-test-or-feature

#7667 [1LP][RFR] Add test for checking for typos in metrics endpoint type
  cfme/tests/containers/test_basic_metrics.py
Labels: lint-ok, new-test-or-feature

#7695 [RFR] Do not start httpd during httpd.service workaround
  cfme/utils/appliance/__init__.py
Labels: fix-framework, infra-related, lint-ok

#7692 [1LP][RFR] fixed test_host_filter_save_cancel
  cfme/tests/infrastructure/test_advanced_search_host.py
Labels: fix-test, lint-ok

#7689 [1LP][RFR] Follow interface change
  cfme/networks/provider/__init__.py
Labels: fix-framework, lint-ok

#7627 [1LP][RFR] Fixed test_service_ansible_playbook_pass_extra_vars
  cfme/services/myservice/ui.py
  cfme/tests/ansible/test_embedded_ansible_services.py
Labels: fix-framework, fix-test, lint-ok

#7688 [1LP][RFR] Cleaning up VMs after some more tests
  cfme/tests/networks/test_provision_to_virtual_network.py
  cfme/tests/services/test_different_dialogs_in_catalogs.py
Labels: enhancement, lint-ok

#7705 [RFR] Put real bugzilla.redhat.com URL in env template
  conf/env.yaml.template
Labels: enhancement, lint-ok

#7676 [1LP][RFR] Fixing CFME5.10 new instance creation
  cfme/tests/openstack/cloud/test_instances.py
Labels: fix-framework, fix-locator-or-text, lint-ok

#7701 [RFR] added some sprout logging during killing appliance
  sprout/appliances/tasks.py
Labels: lint-ok, sprout

#7670 [1LP][RFR] Custom button crud parametrization
  cfme/tests/automate/test_buttons.py
Labels: lint-ok, new-test-or-feature

#7555 [1LP][RFR] Add basic test for pause and resume container provider
  cfme/containers/provider/__init__.py
  cfme/tests/containers/test_provider_configuration_menu.py
Labels: WIP-testing, lint-ok, new-test-or-feature

#7677 [1LP][RFR][NOTEST] Blocking test_service_start with BZ1511099
  cfme/tests/ssui/test_ssui_myservice.py
Labels: blockers-only, lint-ok

#7693 [RFR] CMQE Minor Test Fixes
  cfme/containers/provider/__init__.py
  cfme/tests/containers/test_labels.py
  cfme/tests/containers/test_logging.py
Labels: fix-test, lint-ok

#7630 [1LP][RFR] Add test for appliance console IP configuration
  cfme/tests/cli/test_appliance_console.py
Labels: WIP-testing, lint-ok, new-test-or-feature

#7702 [1LP][RFR] removed blockers mark from test_host_filter_with_user_input and test_…
  cfme/tests/infrastructure/test_advanced_search_host.py
Labels: fix-test, lint-ok

#7697 [1LP][RFR] Use version.lowest instead of 5.9
  cfme/tests/integration/test_aws_iam_auth_and_roles.py
Labels: enhancement, lint-ok

#7698 [1LP][RFR] fixed test_host_filter_without_user_input and host_with_median_vm
  cfme/tests/infrastructure/test_advanced_search_host.py
Labels: fix-test, lint-ok

#7711 [1LP][RFR] Add context manager for DummyAppliance, for script use
  cfme/utils/appliance/__init__.py
  scripts/cleanup_old_vms.py
  scripts/ocp_cleanup.py
Labels: enhancement, infra-related, lint-ok

#7712 [1LP][RFR] fixed error: str object has no attribute pick; added import wait_for
  cfme/control/explorer/conditions.py
  cfme/tests/control/test_basic.py
Labels: fix-test, lint-ok

#7704 [1LP][RFR][NOTEST] Removing test_total_services from RHV suite
  cfme/tests/ssui/test_ssui_dashboard.py
Labels: lint-ok, other

#7710 [1LP][RFR] fixed test_host_bad_creds
  cfme/tests/infrastructure/test_individual_host_creds.py
Labels: fix-test, lint-ok

#7672 [1LP][WIPTEST] Skipping AMQP event with BZ
  cfme/cloud/provider/openstack.py
Labels: WIP-testing, lint-ok

#7679 [RFR][NOTEST] Skipping test_iso_provision_from_template due to BZ1613326
  cfme/tests/infrastructure/test_iso_provisioning.py
Labels: blockers-only, lint-ok

#7717 [1LP][RFR] Add 5.10 stream to Blocking Bug 1620068 for CMQE Smartstate Tests
  cfme/tests/containers/test_containers_smartstate_analysis.py
  cfme/tests/containers/test_containers_smartstate_analysis_multiple_images.py
  cfme/tests/containers/test_provider_openscap_policy_attached.py
  cfme/tests/containers/test_ssa_set_cve_image_inspector_per_provider.py
Labels: blockers-only, lint-ok

#7685 [RFR]Fix unbound local error.
  cfme/fixtures/cli.py
Labels: fix-test, lint-ok

#7639 [1LP][RFR] Add initial Lenovo switches API tests
  cfme/fixtures/physical_switch.py
  cfme/test_framework/pytest_plugin.py
  cfme/tests/physical_infrastructure/api/test_physical_switch_api.py
  cfme/tests/physical_infrastructure/api/test_physical_switch_inventory_api.py
Labels: lint-ok, new-test-or-feature

#7728 [RFR] artifactor logger: fix typo and add a small example file for future d…
  artifactor/example_tests/artifactor_simple_example.py
  artifactor/plugins/logger.py
Labels: fix-framework, lint-ok, rc-regression-fix

#7722 [RFR] fix of issue when new events aren't compared against all expected events
  cfme/utils/events.py
Labels: fix-framework, lint-ok

#7729 Fix list provider vms
  scripts/list_provider_vms.py
Labels: infra-related, lint-ok

#7540 [1LP][RFR] Moving common v2v fixtures to cfme/fixture/v2v.py
  cfme/fixtures/v2v.py
  cfme/tests/v2v/test_v2v_migrations.py
  cfme/tests/v2v/test_v2v_migrations_ui.py
Labels: enhancement, fix-test, lint-ok

#7611 [1LP][RFR] Add new test for provider test resume workers
  cfme/tests/containers/test_pause_resume_workers.py
Labels: lint-ok, new-test-or-feature

#7613 [1LP][RFR] Add Hypervisor hostname tests
  cfme/tests/openstack/infrastructure/test_hosts.py
Labels: lint-ok, new-test-or-feature

#7700 [1LP][RFR][NOTEST] Add BZ wrapper for test host credentials
  cfme/tests/infrastructure/test_host.py
  cfme/tests/infrastructure/test_individual_host_creds.py
Labels: blockers-only, lint-ok

#7642 [1LP][RFR] Fixing clod tests for supporting the CFME 5.10 automation
  cfme/networks/cloud_network.py
  cfme/networks/views.py
  cfme/tests/openstack/cloud/test_networks.py
Labels: fix-locator-or-text, lint-ok

#7602 [1LP][RFR] Cover provision cases with vlan profiles <No Profile> and <Use template nics>
  cfme/tests/infrastructure/test_provisioning_dialog.py
  requirements/frozen.py2.txt
  requirements/frozen_docs.py2.txt
Labels: lint-ok, new-test-or-feature

#7629 [1LP][RFR] Add switching to Summary view for physical infrastructure provider
  cfme/physical/provider/__init__.py
Labels: enhancement, lint-ok

#7684 [RFR] test_provision_cloud_init blocked with BZ 1619744
  cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py
Labels: blockers-only, lint-ok

#7725 [1LP][RFR] fixed AttributeError in test_run_datastore_analysis
  cfme/tests/infrastructure/test_datastore_analysis.py
Labels: fix-test, lint-ok

#7724 [1LP][RFR] fixed AttributeError in test_bind_timeout_rest
  cfme/tests/configure/test_session_timeout.py
Labels: fix-test, lint-ok

#7019 [1LP][RFR] Added new tests for KubeVirt
  cfme/common/vm_views.py
  cfme/infrastructure/provider/kubevirt.py
  cfme/tests/infrastructure/test_kubevirt.py
Labels: lint-ok, new-test-or-feature

#7718 [1LP][RFR] fix cloud_timelines->diagnostic view test
  cfme/tests/cloud/test_cloud_timelines.py
Labels: fix-test, lint-ok

#7721 [1LP][RFR] bump pycryptodome after cve
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: fix-framework, lint-ok

#7742 [1LP][RFR] Update KubeVirt provider class db_types
  cfme/infrastructure/provider/kubevirt.py
Labels: fix-framework, issue-bug, lint-ok
