Repository ManageIQ/integration_tests, pull requests merged in 2018-07, with the labels that each got.

#7419 [1LP][RFR] Fixed remove_creds step
  cfme/utils/hosts.py
Labels: fix-framework, lint-ok

#7425 [1LP][RFR] Fix host update method
  cfme/infrastructure/host.py
Labels: lint-ok

#7421 [1LP][RFR] make sprout's clone template create new delayed task and remove failed appliance
  sprout/appliances/tasks.py
Labels: fix-framework, lint-ok

#7420 [1LP][RFR] Add 'Reset' button test case
  cfme/configure/settings.py
  cfme/tests/configure/test_default_views_cloud.py
  cfme/tests/configure/test_default_views_infra.py
Labels: lint-ok, new-test-or-feature

#7418 [1LP][RFR] Automate test for help menu
  cfme/tests/configure/test_help_menu.py
Labels: lint-ok, new-test-or-feature

#7407 [1LP][RFR] v2v: Renamed new dropdown
  cfme/v2v/migrations.py
Labels: fix-locator-or-text, lint-ok

#7402 [1LP][RFR] Changed test_can_open_vm_view -> test_can_open_vm_advanced_search
  cfme/tests/infrastructure/test_advanced_search_vms.py
Labels: enhancement, lint-ok

#7401 [1LP][RFR] Fixed Ansible Repository edit
  cfme/ansible/repositories.py
Labels: fix-framework, lint-ok

#7428 [RFR] Fixed navigation issue
  cfme/tests/infrastructure/test_provisioning_dialog.py
Labels: lint-ok

#7429 [RFR] Fix tag and category fixture creation
  cfme/tests/cloud_infra_common/test_tag_visibility.py
Labels: fix-test, lint-ok

#7430 [RFR] Moved finalizer definition
  cfme/tests/configure/test_register_appliance.py
Labels: fix-test, lint-ok

#7431 [RFR] Embedded Ansible shouldn't be in the reports
  cfme/tests/intelligence/reports/test_canned_corresponds.py
Labels: fix-test, lint-ok

#7416 [1LP][RFR]Adding appliance method to enable-disable migration UI, and test it
  cfme/tests/v2v/test_v2v.py
  cfme/utils/appliance/__init__.py
Labels: lint-ok, new-test-or-feature

#7432 [1LP][RFR] enable gce for metric on 5.9
  cfme/tests/candu/test_utilization_metrics.py
Labels: fix-test, lint-ok

#7433 [1LP][RFR] circumvent issue when ssh.run_command hangs if appliance suddenly got unavailable
  cfme/utils/ssh.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
Labels: enhancement, lint-ok

#7272 [1LP][RFR] Fixed test Service Start for Azure and EC2
  cfme/fixtures/service_fixtures.py
  cfme/services/myservice/ssui.py
  cfme/tests/ssui/test_ssui_myservice.py
Labels: fix-test, lint-ok

#7302 [1LP][RFR] Gap Collection C&U
  cfme/base/ui.py
  cfme/common/candu_views.py
  cfme/tests/candu/test_gap_collection.py
Labels: lint-ok, new-test-or-feature

#7437 [1LP][RFR]Extra navigation in test_sdn_crud.py
  cfme/tests/networks/test_sdn_crud.py
Labels: fix-test, lint-ok

#7358 [RFR][1LP] Latest build fixes
  cfme/fixtures/cli.py
  cfme/scripting/setup_env.py
  cfme/tests/cli/test_appliance_cli.py
  cfme/tests/cli/test_appliance_console.py
  cfme/tests/cli/test_appliance_console_db_restore.py
  cfme/tests/test_db_restore.py
Labels: WIP-testing, fix-test, lint-ok

#7388 [1LP][RFR] V2V migration tests fixtures
  cfme/infrastructure/provider/__init__.py
  cfme/tests/v2v/test_v2v_migrations.py
  cfme/v2v/migrations.py
Labels: lint-ok, new-test-or-feature

#7449 [1LP][RFR] Fixed creation of Nuage Provider
  cfme/networks/provider/__init__.py
Labels: fix-framework, lint-ok

#7442 [1LP][RFR] Add Bugzilla default URL for Travis
  cfme/utils/bz.py
  conf/cfme_data.yaml.template
  conf/env.yaml.template
Labels: enhancement, lint-ok

#7453 [1LP][RFR] Fix BZ blocker use (remove uncollectif)
  cfme/tests/cli/test_appliance_cli.py
  cfme/tests/cloud_infra_common/test_events.py
  cfme/tests/configure/test_log_depot_operation.py
  cfme/tests/control/test_compliance.py
  cfme/tests/infrastructure/test_vm_power_control.py
  cfme/utils/bz.py
Labels: fix-test, lint-ok, rc-regression-fix

#7439 [1LP][RFR] fix provider.create_rest() for openstack providers
  cfme/cloud/provider/openstack.py
  cfme/common/provider.py
Labels: fix-framework, lint-ok, rc-regression-fix

#7446 [1LP][RFR] adding some logging to sprout
  sprout/appliances/models.py
  sprout/appliances/tasks.py
Labels: lint-ok, sprout

#7400 [1LP][RFR] Update Container test project dashboard according to wrapanapi changes
  cfme/tests/containers/test_projects_dashboard.py
Labels: fix-test, lint-ok

#7454 [1LP][RFR] Check version type before calling functions in utils.bz
  cfme/utils/bz.py
Labels: issue-bug, lint-ok, rc-regression-fix

#7459 [1LP][RFR] fixing quota tagging tests broken by collections conversion
  cfme/tests/cloud/test_quota_tagging.py
Labels: fix-test, lint-ok, rc-regression-fix

#7460 [1LP][RFR] fixed tag tests broken by collections conversion
  cfme/fixtures/tag.py
  cfme/tests/cloud_infra_common/test_tag_visibility.py
Labels: WIP, fix-test, lint-ok, rc-regression-fix

#7465 [WIP] Fixing typo in BZ wrapper for test_provision_attributes
  cfme/tests/infrastructure/test_provisioning_rest.py
Labels: WIP, fix-test, lint-ok, rc-regression-fix

#7463 [1LP][RFR] Remove cfme_data use in utils.bz
  cfme/utils/bz.py
Labels: lint-ok, rc-regression-fix

#7411 [1LP][RFR] Fix provisioning vm to virtual network
  cfme/provisioning.py
  cfme/tests/networks/test_provision_to_virtual_network.py
Labels: fix-test, lint-ok

#7462 [RFR] fix pinnns for wrapanapi pre 3.x and add gevent to the templates
  requirements/template.txt
  requirements/template_docs.txt
Labels: lint-ok

#7468 [RFR] Update Bugzilla.open_states, return set
  cfme/utils/bz.py
Labels: fix-framework, lint-ok, rc-regression-fix

#7444 [1LP][RFR]Fix bottlenecks tests
  cfme/tests/optimize/test_bottlenecks.py
Labels: lint-ok

#7441 [1LP][RFR] Removed network provider class use and added use of collection filtering
  cfme/tests/networks/test_tag_tagvis.py
Labels: lint-ok

#7447 [1LP][RFR]Fix dict key for test_db_backup_schedule
  cfme/tests/configure/test_db_backup_schedule.py
Labels: fix-test, lint-ok

#7476 [1LP][RFR] restoring appliance.ip_address check in pool.fulfilled
  sprout/appliances/models.py
  sprout/appliances/tasks.py
Labels: issue-bug, lint-ok

#7478 [1LP][RFR]Add test for validating flash message tags
  cfme/tests/containers/test_basic_metrics.py
Labels: lint-ok, new-test-or-feature

#7404 [1LP][RFR] Add virt_type Support for Downstream OpenShiftProvider
  cfme/common/provider_views.py
  cfme/containers/provider/openshift.py
Labels: enhancement, lint-ok

#7486 [RFR] make sync_template_trackerbot script ignore templates with empty name
  scripts/sync_template_tracker.py
Labels: infra-related, issue-bug, lint-ok

#7415 [1LP][RFR]Update cloud/infra tagging tests
  cfme/common/__init__.py
  cfme/tests/cloud_infra_common/test_tag_objects.py
Labels: fix-test, lint-ok

#7470 [1LP][RFR] fix get mgmt
  cfme/utils/providers.py
Labels: issue-bug, lint-ok

#7427 [1LP][RFR][W3] refactor lenovo physical server to adequate to lenovo system changes
  cfme/physical/physical_server.py
Labels: lint-ok

#7492 [1LP][RFR] Remove wrapanapi from requirements/frozen_docs*
  cfme/utils/dockerbot/check_prs.py
  docs/conf.py
  docs/modules.rst
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: doc, lint-ok, tech-debt

#7500 [RFR] Remove module mocking in docs/conf
  cfme/fixtures/authentication.py
  docs/conf.py
Labels: doc

#7471 [1LP][RFR] ocp servers cleanup script
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  scripts/ocp_cleanup.py
Labels: infra-related, lint-ok

#7417 [1LP][RFR] ansible url fix for pod appliances
  cfme/utils/appliance/__init__.py
  scripts/template_upload_openshift.py
  sprout/appliances/tasks.py
Labels: lint-ok

#7436 [1LP][RFR] Update aws_iam auth/RBAC test, new access tree in 510z
  cfme/base/__init__.py
  cfme/fixtures/authentication.py
  cfme/roles.py
  cfme/tests/integration/test_aws_iam_auth_and_roles.py
  cfme/tests/integration/test_cfme_auth.py
Labels: fix-test, lint-ok

#7503 [1LP][RFR] Fixed creation of custom buttons
  cfme/automate/buttons.py
Labels: fix-framework, lint-ok

#7502 [1LP][RFR] Fix for quadicon states
  cfme/common/vm.py
  cfme/common/vm_views.py
  cfme/infrastructure/host.py
  cfme/tests/cloud/test_instance_power_control.py
  cfme/tests/distributed/test_appliance_replication.py
  cfme/tests/infrastructure/test_vm_power_control.py
Labels: fix-framework, lint-ok

#7495 [1LP][RFR] Blocking test_pxe_provision_from_template by #7494
  cfme/tests/infrastructure/test_pxe_provisioning.py
Labels: fix-test, lint-ok

#7493 [1LP][RFR] Skipping test_pxe_servicecatalog because of #7491
  cfme/tests/services/test_pxe_service_catalogs.py
Labels: fix-test, lint-ok

#7484 [1LP][RFR] Update Container test overview data integrity according to wrapanapi changes
  cfme/tests/containers/test_overview_data_integrity.py
Labels: fix-test, lint-ok

#7438 [1LP][RFR] Automate test for deleting a report from saved reports list
  cfme/tests/intelligence/reports/test_crud.py
Labels: lint-ok, new-test-or-feature

#7386 [1LP][RFR] Blocking test_child_tenant_quota_enforce_via_lifecycle_infra with GH7385
  cfme/tests/infrastructure/test_child_tenant.py
Labels: fix-test, lint-ok

#7346 [1LP][RFR] Added two parametrized advanced_search tests
  cfme/ansible_tower/__init__.py
  cfme/ansible_tower/explorer.py
  cfme/ansible_tower/jobs.py
  cfme/cloud/availability_zone.py
  cfme/cloud/flavor.py
  cfme/cloud/host_aggregates.py
  cfme/cloud/instance/__init__.py
  cfme/cloud/instance/image.py
  cfme/cloud/keypairs.py
  cfme/cloud/stack.py
  cfme/cloud/tenant.py
  cfme/common/host_views.py
  cfme/common/physical_server_views.py
  cfme/common/provider_views.py
  cfme/containers/build.py
  cfme/infrastructure/cluster.py
  cfme/infrastructure/config_management.py
  cfme/infrastructure/datastore.py
  cfme/infrastructure/resource_pool.py
  cfme/infrastructure/virtual_machines.py
  cfme/networks/views.py
  cfme/services/myservice/ui.py
  cfme/services/workloads.py
  cfme/storage/object_store_container.py
  cfme/storage/object_store_object.py
  cfme/storage/volume.py
  cfme/storage/volume_backup.py
  cfme/storage/volume_snapshot.py
  cfme/tests/webui/test_advanced_search.py
  setup.py
Labels: lint-ok, new-test-or-feature

#7455 [1LP][RFR][NOTEST] support for capturing historical data
  cfme/common/vm.py
  cfme/infrastructure/host.py
Labels: enhancement, lint-ok

#7477 [1LP][RFR] Add test for validating provider column in all projects table
  cfme/tests/containers/test_projects_dashboard.py
Labels: lint-ok, new-test-or-feature

#7511 [RFR] ansible url fix for sprout
  sprout/appliances/tasks.py
Labels: lint-ok

#7458 [1LP][RFR] add mgmt property to Lenovo Provider
  cfme/physical/provider/lenovo.py
Labels: fix-framework, lint-ok

#7350 [1LP][RFR] pod appliance test cases automation
  cfme/fixtures/appliance.py
  cfme/test_framework/sprout/client.py
  cfme/tests/pod/test_appliance_crud.py
Labels: fix-test, lint-ok, new-test-or-feature

#7481 [1LP][RFR] Blocking several service tests because of #7479
  cfme/tests/infrastructure/test_quota_tagging.py
  cfme/tests/infrastructure/test_tenant_quota.py
  cfme/tests/services/test_different_dialogs_in_catalogs.py
  cfme/tests/services/test_pxe_service_catalogs.py
  cfme/tests/services/test_service_catalogs.py
  cfme/tests/services/test_service_manual_approval.py
  cfme/tests/ssui/test_ssui_ansible_service.py
  cfme/tests/ssui/test_ssui_dashboard.py
  cfme/tests/ssui/test_ssui_myservice.py
  cfme/tests/ssui/test_ssui_service_catalogs.py
Labels: fix-test, lint-ok

#7424 [1LP][RFR] Fixed provider and hosts relationships
  cfme/infrastructure/host.py
  cfme/infrastructure/openstack_node.py
  cfme/infrastructure/provider/__init__.py
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
  cfme/tests/configure/test_schedule_operations.py
  cfme/tests/control/test_actions.py
  cfme/tests/control/test_compliance.py
  cfme/tests/infrastructure/test_esx_direct_host.py
  cfme/tests/infrastructure/test_host.py
  cfme/tests/infrastructure/test_host_analysis.py
  cfme/tests/infrastructure/test_host_drift_analysis.py
  cfme/tests/infrastructure/test_vm_migrate.py
  setup.py
Labels: enhancement, fix-framework, lint-ok

#7466 [1LP][RFR] sort out Py3k issue in artifactor
  artifactor/plugins/logger.py
  artifactor/plugins/post_result.py
  widgetastic_manageiq/__init__.py
Labels: fix-framework, lint-ok

#7483 [1LP][RFR] This PR will automate SSA on EC2 instance.
  cfme/cloud/provider/ec2.py
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
Labels: lint-ok, new-test-or-feature

#7508 [1LP][RFR] - Missing flash message - Order Request was Submitted
  cfme/services/service_catalogs/ui.py
Labels: lint-ok

#7490 [RFR] Add prov_class parameter to instantiate network provider
  cfme/tests/networks/test_provision_to_virtual_network.py
Labels: fix-test, lint-ok

#7321 [RFR] Cleaning up after REST provisioning tests
  cfme/tests/infrastructure/test_provisioning_rest.py
Labels: enhancement, fix-test, lint-ok

#7339 [1LP][RFR] Add retries to certificate copy while copy fails network issue occurs
  cfme/containers/provider/openshift.py
  cfme/tests/containers/test_ssl_providers.py
Labels: lint-ok

#7506 [RFR] CMQE Move long_running_env marker
  cfme/tests/containers/test_reports.py
Labels: lint-ok

#7504 [RFR][1LP] Fixed Control policies CRUD operations
  cfme/control/explorer/policies.py
Labels: fix-framework, lint-ok

#7509 [RFR] Fix: Instantiate Method error in N/W
  cfme/networks/provider/__init__.py
Labels: lint-ok

#7505 [1LP][RFR] Test for checking vm migration after assigning tenant quota
  cfme/tests/infrastructure/test_tenant_quota.py
Labels: lint-ok

#7520 [1LP][RFR] Fix in the case a required field is a string
  cfme/tests/infrastructure/test_tenant_quota.py
  cfme/utils/providers.py
Labels: fix-framework, lint-ok, rc-regression-fix

#7451 [1LP][RFR] End to end migration: stage one
  cfme/tests/v2v/test_v2v_migrations.py
  cfme/v2v/migrations.py
  widgetastic_manageiq/__init__.py
Labels: lint-ok, new-test-or-feature

#7521 [RFR] Catch VMInstanceNotFound in IPAppliance
  cfme/utils/appliance/__init__.py
Labels: fix-framework, lint-ok, rc-regression-fix

#7522 [RFR][1LP] Cleanup vms handle error
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
  scripts/cleanup_old_vms.py
Labels: WIP, infra-related, lint-ok, rc-regression-fix

#7518 [1LP][RFR] Fixed AssertionError
  cfme/storage/manager.py
Labels: fix-test, lint-ok

#7530 [RFR] Fix ValueError in host yaml lookup
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
  cfme/tests/infrastructure/test_host_analysis.py
  cfme/tests/infrastructure/test_host_drift_analysis.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
Labels: WIP-testing, fix-test, lint-ok, rc-regression-fix

#7531 [1LP][RFR] Fixed FF60 inside our repo for testing
  cfme/utils/appliance/implementations/ui.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: fix-framework, lint-ok, rc-regression-fix

#7364 [1LP][RFR][NOTEST] Pre commit config
  .gitignore
  .pre-commit-config.yaml
  .travis.yml
Labels: enhancement, lint-ok, tech-debt

#7527 [1LP][RFR] Add legacy options for parametrization
  cfme/fixtures/provider.py
  cfme/markers/env_markers/provider.py
Labels: WIP, lint-ok, rc-regression-fix

#7551 [RFR] Clone template rhos flavor
  cfme/tests/control/test_actions.py
  scripts/clone_template.py
Labels: infra-related, issue-bug, lint-ok

#7525 [1LP][RFR] Jenkins failure fix
  cfme/common/vm_views.py
  cfme/services/catalogs/catalog_items/__init__.py
Labels: fix-test, lint-ok, rc-regression-fix

#7545 [1LP][RFR] browser manager: handle all exceptions and ensure wharf containrs are…
  cfme/utils/browser.py
Labels: fix-framework, lint-ok, rc-regression-fix

#7547 [1LP][RFR] Host collections are now accessible from the provider
  cfme/tests/infrastructure/test_advanced_search_host.py
Labels: lint-ok, rc-regression-fix

#7546 [RFR] Fixed destination error
  cfme/infrastructure/virtual_machines.py
Labels: WIP, lint-ok, rc-regression-fix

#6660 [1LP][RFR] few fixes for Ansible Tower tests
  cfme/tests/infrastructure/test_config_management.py
Labels: fix-locator-or-text, fix-test, lint-ok

#7516 [1LP][RFR] Fixed Expression Editor
  cfme/control/explorer/conditions.py
  cfme/tests/control/test_basic.py
  widgetastic_manageiq/expression_editor.py
Labels: fix-framework, fix-locator-or-text, lint-ok

#7450 [1LP][RFR] Add Nuage to supportability template
  conf/supportability.yaml.template
Labels: enhancement, lint-ok

#7456 [1LP][RFR] Implement test count for tenants and routers
  cfme/networks/provider/nuage.py
Labels: enhancement, lint-ok

#7461 [1LP][RFR] Host hourly and daily Utilization for Vsphere
  cfme/common/candu_views.py
  cfme/tests/candu/test_host_graph.py
Labels: lint-ok

#7467 [1LP][RFR] Add test_instance_operating_system_linux to test_instances
  cfme/tests/openstack/cloud/test_instances.py
Labels: lint-ok, new-test-or-feature

#7482 [1LP][RFR] Fix reading host credentials from yaml to reflect recent changes
  cfme/tests/infrastructure/test_host.py
  cfme/tests/infrastructure/test_individual_host_creds.py
Labels: fix-test, lint-ok

#7498 [1LP][RFR] V2v ui validations
  cfme/tests/v2v/test_v2v_migrations.py
  cfme/tests/v2v/test_v2v_migrations_ui.py
  cfme/utils/testgen.py
  cfme/v2v/migrations.py
  widgetastic_manageiq/__init__.py
Labels: lint-ok

#7514 [1LP][RFR] Specify per containers provider the location of OpenSCAP CVEs and Image-Inspector image
  cfme/tests/containers/test_ssa_set_cve_image_inspector_per_provider.py
Labels: lint-ok, new-test-or-feature

#7246 [1LP][RFR] switch to modern setuptools and create a initial wheel package
  .travis.yml
  entry_points.txt
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
  setup.cfg
  setup.py
Labels: enhancement, lint-ok

#7517 [1LP][RFR] Fix alert profiles update method
  cfme/control/explorer/alert_profiles.py
Labels: fix-framework, lint-ok

#7519 [1LP][RFR] Fix 5.10 PDF issue
  cfme/tests/networks/test_sdn_downloads.py
Labels: fix-test, lint-ok

#7435 [1LP][RFR] Updated test help menu
  cfme/automate/explorer/method.py
  cfme/tests/configure/test_help_menu.py
  cfme/tests/webui/test_general_ui.py
Labels: fix-locator-or-text, fix-test, lint-ok

#7556 [1LP][RFR] enable and apply whitespace fixing pre-commit hooks
  .landscape.yml
  .pre-commit-config.yaml
  cfme/fixtures/ansible_fixtures.py
  cfme/utils/ansible_conf/tags_basic_script.yml
  cfme/utils/ansible_conf/users_basic_script.yml
  cfme/utils/dockerbot/pytestbase/setup.sh
  cfme/utils/template/README.md
  conf/docker.yaml.template
  conf/env.yaml.template
  dockerfiles/cfme_tests_img/Dockerfile
  docs/getting_started.rst
  docs/guides/browser_configuration.rst
  docs/guides/debugging.rst
  docs/guides/editors.rst
  docs/guides/newprovider.rst
  docs/guides/ui_modeling.rst
  docs/guides/vnc_selenium.rst
  docs/index.rst
  eng.user-words
  requirements.txt
  requirements/.gitignore
  requirements/dev.txt
  requirements/docs.txt
  requirements/docs/readme.txt
  requirements/frozen.txt
  requirements/on_rtd.txt
  requirements/perf.txt
  requirements/quickstart/needs.txt
  scripts/data/coverage/coverage_hook.rb
  scripts/data/coverage/coverage_merger.rb
  scripts/data/coverage/manageiq-17302.patch
  scripts/data/enable-internal-db.rbt
  scripts/templates/cfme-run.smem
  scripts/update_template.sh
Labels: lint-ok, tech-debt

#7562 [1LP][RFR] fix end of file of the entry_points.txt
  entry_points.txt
Labels: fix-framework

#7561 [1LP][RFR] added forgotten shebang line in ocp_cleanup script
  scripts/ocp_cleanup.py
Labels: fix-framework, lint-ok

#7566 [1LP][RFR] dockerbot: correct rm statement and remove the force so we notice errors
  cfme/utils/dockerbot/pytestbase/setup.sh
Labels: lint-ok

#7549 [1LP][RFR] HostsCollection.all() uses REST API
  cfme/common/provider.py
  cfme/infrastructure/host.py
Labels: enhancement, lint-ok

#7422 [1LP][RFR] Adding Physical Switches basic UI tests
  cfme/common/physical_switch_views.py
  cfme/physical/physical_switch.py
  cfme/tests/physical_infrastructure/ui/test_physical_switch_details.py
  cfme/tests/physical_infrastructure/ui/test_physical_switch_list.py
  entry_points.txt
Labels: lint-ok, new-test-or-feature

#7327 [1LP][RFR] Initial setup for v2v
  cfme/fixtures/v2v.py
  cfme/test_framework/pytest_plugin.py
  cfme/tests/v2v/test_v2v_migrations.py
  cfme/tests/v2v/test_v2v_migrations_ui.py
  cfme/utils/appliance/__init__.py
Labels: lint-ok, new-test-or-feature

#7526 [1LP][RFR][NOTEST] collection of utilization
  cfme/optimize/utilization.py
  entry_points.txt
Labels: enhancement, lint-ok

#7548 [1LP][RFR] Fixing test_button_on_host
  cfme/tests/automate/test_buttons.py
Labels: fix-test, lint-ok

#7552 [1LP][RFR] fix ui button name to add Physical Infrastructure Provider
  cfme/physical/provider/__init__.py
Labels: fix-locator-or-text, lint-ok

#7534 [1LP][RFR] provision tests/views fixes
  cfme/common/vm.py
  cfme/common/vm_views.py
Labels: WIP, fix-framework, fix-test, lint-ok

#7572 [RFR] run pre-commit to restore a passing lint stage
  cfme/common/vm_views.py
Labels: lint-ok, other

#7570 [1LP][NOTEST][RFR] Adding template related fixtures under cfme.fixtures.provider.py
  cfme/fixtures/provider.py
Labels: lint-ok, new-test-or-feature

#7565 [1LP][RFR] Fixing host fixture in test_relationships
  cfme/tests/cloud_infra_common/test_relationships.py
Labels: fix-test, lint-ok

#7575 [RFR] upgrade the cryptography pin to sort out the cve warning
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: fix-framework, lint-ok

#7568 [1LP][RFR] Fix clicking checkboxes on HostDriftHistory view
  cfme/common/vm.py
  cfme/infrastructure/host.py
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
  cfme/tests/infrastructure/test_host_drift_analysis.py
Labels: fix-test, lint-ok

#7554 [1LP][RFR] Update ContainerProviderEditView is_displayed to use ProviderEditView
  cfme/common/provider_views.py
Labels: fix-framework, lint-ok

#7488 [1LP][RFR]Fix log collection tests
  cfme/configure/configuration/diagnostics_settings.py
  cfme/tests/configure/test_log_depot_operation.py
Labels: fix-test, lint-ok

#7544 [1LP][RFR] Added relationship between Openstack Infra provider and Openstack Node
  cfme/infrastructure/provider/openstack_infra.py
Labels: enhancement, lint-ok
