Repository ManageIQ/integration_tests, pull requests merged in 2018-11, with the labels that each got.

#8060 [RFR] Fixed AttributeError in ScheduleAddView for 5.10z
  cfme/tests/configure/test_schedule_operations.py
Labels: fix-test

#8058 [1LP][RFR] Fixed KeyError in quadicon for 5.10z
  cfme/common/vm_views.py
Labels: fix-test

#8059 [1LP][RFR] Fixed assertion error in region for 5.10z
  cfme/tests/configure/test_region.py
Labels: fix-test

#8056 [1LP][RFR] Add pytest.mark.tier(3) for all tests in test_embedded_ansible_automate
  cfme/tests/ansible/test_embedded_ansible_automate.py
Labels: other

#8054 [1LP][RFR] Address upstream change of message type to success for flash message …
  cfme/services/service_catalogs/ui.py
Labels: fix-test

#8053 [1LP][RFR] Add support for volume type field
  cfme/storage/volume.py
Labels: enhancement

#8015 [1LP][RFR] Download images before uploading to glance
  cfme/utils/template/base.py
Labels: infra-related

#8061 [RFR] Added new way to set conversion host
  cfme/fixtures/v2v.py
Labels: fix-test

#8052 [1LP][RFR] Fix generic object class view and test
  cfme/generic_objects/definition/definition_views.py
  cfme/generic_objects/definition/ui.py
  cfme/tests/generic_objects/test_definitions.py
Labels: fix-framework

#8048 [1LP][RFR] Visibility enhancement and Test
  cfme/automate/buttons.py
  cfme/tests/automate/custom_button/test_generic_objects.py
  widgetastic_manageiq/expression_editor.py
Labels: enhancement, new-test-or-feature

#7963 [1LP][RFR] Create custom role in quota tests instead of super_admin
  cfme/tests/infrastructure/test_project_quota.py
Labels: WIP-testing, fix-test, lint-ok

#8051 [1LP][RFR] Block for 5.10 and test_custom_button_dialog
  cfme/tests/automate/custom_button/test_container_objects.py
Labels: new-test-or-feature

#7975 [1LP][RFR] Add test for scl packages.
  cfme/tests/test_appliance.py
Labels: lint-ok, new-test-or-feature

#8039 [1LP][RFR][NOTEST] Updating ISO provisioning test
  cfme/provisioning.py
  cfme/tests/infrastructure/test_iso_provisioning.py
  data/rhel7.cfg
Labels: fix-test

#8066 [1LP][RFR] Fixed Assertion error in system_image_duplicate_name for 5.10z
  cfme/tests/infrastructure/test_system_image_type.py
Labels: fix-locator-or-text

#8069 [1LP][RFR ]Added new @pytest.mark to separate regression and RFE tests
  cfme/tests/openstack/cloud/test_provider.py
  cfme/tests/openstack/infrastructure/test_hosts.py
Labels: enhancement

#8057 [RFR] Fix sprout orphans
  sprout/appliances/admin.py
  sprout/appliances/tasks.py
Labels: sprout

#8065 [RFR] Added blocker BZ to uncollect tests till BZ fix.
  cfme/tests/ansible/test_embedded_ansible_actions.py
  cfme/tests/ansible/test_embedded_ansible_automate.py
  cfme/tests/ansible/test_embedded_ansible_basic.py
  cfme/tests/ansible/test_embedded_ansible_crud.py
  cfme/tests/ansible/test_embedded_ansible_rest.py
  cfme/tests/ansible/test_embedded_ansible_services.py
  cfme/tests/ansible/test_embedded_ansible_tags.py
Labels: blockers-only

#7628 [RFR] Tests quota for user and group via ui and ssui
  cfme/tests/infrastructure/test_quota_tagging.py
Labels: lint-ok, new-test-or-feature

#8063 [WIPTEST] Add Volume Types Collection including related tests
  cfme/exceptions.py
  cfme/storage/volume_type.py
  cfme/tests/openstack/cloud/test_volumes.py
  entry_points.txt
Labels: new-test-or-feature

#8073 [RFR] Fix VM Utilization view
  cfme/common/candu_views.py
Labels: fix-framework

#8072 [RFR] Fix arg name in requirements/freeze.py
  requirements/freeze.py
Labels: fix-framework

#8087 [1LP][RFR] Surf pages on cloud instance power control
  cfme/cloud/instance/__init__.py
Labels: fix-framework, rc-regression-fix

#8085 [RFR] Fix retire ssui test 510z
  cfme/fixtures/service_fixtures.py
Labels: blockers-only, rc-regression-fix

#8076 [RFR] Fix alert_profile 'Edit' view by adding a check to is_displayed()
  cfme/control/explorer/alert_profiles.py
Labels: fix-framework, rc-regression-fix

#8086 [RFR] Fix ssui service start
  cfme/tests/ssui/test_ssui_myservice.py
Labels: blockers-only

#8090 [1LP][RFR] Fix test failures related to view.is_displayed during Alert creation
  cfme/control/explorer/alerts.py
Labels: fix-framework, rc-regression-fix

#8081 [1LP][RFR] Refarctor Nuage fixture
  cfme/fixtures/nuage.py
Labels: Nuage

#8093 [1lLP][RFR]Add labels to release script
  cfme/utils/release.py
Labels: enhancement

#8068 [1LP][NOTEST][WIPTEST] Cleanup snapshots
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
  scripts/ec2cleanup.py
Labels: infra-related

#8101 [1LP][RFR] fixed azure vms provisioning in 5.10
  cfme/cloud/instance/azure.py
Labels: fix-locator-or-text

#8055 [1LP][RFR]TableRow should use index starting from 0 now
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
  cfme/tests/infrastructure/test_host_drift_analysis.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: issue-bug

#8091 [1LP][RFR]Catalog view is_displayed fix
  cfme/services/catalogs/catalog.py
  cfme/tests/configure/test_access_control.py
  cfme/tests/services/test_catalog.py
Labels: fix-framework

#8097 [1LP][RFR] upgrade pre commit hooks
  .isort.cfg
  .pre-commit-config.yaml
  artifactor/plugins/reporter.py
  requirements/test_frozen_requirements.py
  widgetastic_manageiq/__init__.py
Labels: blackify, enhancement

#8102 [1LP][RFR] Remove smtp_test kwarg from do_vm_provisioning call
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
Labels: fix-test

#8105 [1LP][RFR] Fix provider host all view is_displayed implementation
  cfme/common/host_views.py
Labels: fix-framework

#8127 [RFR] Fixed is_displayed in HostTemplatesOnlyAllView for 5.10z
  cfme/infrastructure/virtual_machines.py
Labels: fix-locator-or-text

#8121 [1LP][RFR] Update test_vm_instance_analysis, unique ssa agent name
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
Labels: enhancement

#8123 [1LP][RFR][NOTEST] Removing test_actions.py out of RHV regression suite
  cfme/tests/control/test_actions.py
Labels: RHV

#8111 [1LP][RFR] Fixed AssertionError in child_quota for 5.10z
  cfme/tests/infrastructure/test_tenant_quota.py
Labels: fix-test

#8106 [1LP][RFR]Bundle view is_displayed fix
  cfme/services/catalogs/catalog_items/catalog_bundles.py
  cfme/tests/services/test_generic_service_catalogs.py
Labels: fix-test

#8104 [1LP][RFR] fixed ProviderTemplatesView and removed BZ blocker
  cfme/common/provider_views.py
  cfme/tests/infrastructure/test_infra_tag_filters_combination.py
Labels: fix-framework

#8110 [1LP][RFR][NOTEST] Fix for all method avoiding Ansible Embedded Manager
  cfme/infrastructure/cluster.py
  cfme/infrastructure/datastore.py
Labels: fix-framework

#8129 [1LP][RFR] skip tests in navigation related to tag
  cfme/tests/storage/test_manager.py
  cfme/tests/storage/test_object_store_container.py
  cfme/tests/storage/test_object_store_object.py
  cfme/tests/storage/test_volume.py
  cfme/tests/storage/test_volume_backup.py
  cfme/tests/storage/test_volume_snapshot.py
Labels: blockers-only

#8095 [RFR] Add tests related to volume type RFE
  cfme/cloud/instance/openstack.py
  cfme/tests/openstack/cloud/test_instances.py
  cfme/tests/openstack/cloud/test_volume_backup.py
Labels: fix-framework, new-test-or-feature

#8113 [1LP][RFR] fixed test_tag_host_after_provider_delete
  cfme/tests/infrastructure/test_host.py
Labels: fix-test

#8134 [1LP][RFR][NOTEST] Blocking test_myservice_crud with BZ1646925
  cfme/tests/ssui/test_ssui_myservice.py
Labels: blockers-only

#8126 [1LP][RFR][NOTEST] Blocking test_provision_vm_to_virtual_network with GH8128
  cfme/tests/networks/test_provision_to_virtual_network.py
Labels: blockers-only

#8132 [1LP][RFR] Update xunit fixture, include group-id from xunit.conf
  cfme/fixtures/xunit_tools.py
Labels: enhancement

#8108 [1LP][RFR] Fixed AssertionError while hard_reboot of azure in 5.10z
  cfme/tests/cloud/test_instance_power_control.py
Labels: fix-locator-or-text

#8092 [1LP][RFR] Fix alert_timeline_cpu by making change for TimelinesChart class
  widgetastic_manageiq/__init__.py
Labels: fix-framework

#8078 [1LP][RFR] Parametrize: enablement and visibility for General objects
  cfme/tests/automate/custom_button/test_generic_objects.py
Labels: new-test-or-feature

#8118 [1LP][RFR] Custom button Icon and Request required test
  cfme/automate/buttons.py
  cfme/tests/automate/custom_button/test_buttons.py
Labels: new-test-or-feature

#8138 [1LP][RFR] Add BZ blocker for VM tag tests in 59
  cfme/tests/candu/test_host_graph.py
Labels: blockers-only

#8116 [1LP][RFR] fixed PlaybookDetailsView
  cfme/ansible/playbooks.py
  cfme/tests/ansible/test_embedded_ansible_tags.py
Labels: fix-framework

#8094 [1LP][RFR] Add view.wait_displayed() when updating an alert
  cfme/control/explorer/alerts.py
Labels: fix-framework

#8141 [1LP][RFR] fixed OneProviderBalancerView
  cfme/networks/views.py
  cfme/tests/networks/test_sdn_balancers.py
Labels: fix-framework

#8084 [1LP][RFR] Update Alert docstring and add ability to create alert with only a 'description'
  cfme/control/explorer/alerts.py
  cfme/tests/control/test_basic.py
Labels: enhancement

#8142 [RFR] Add global uncollect for RHEVM providers for alerts tests
  cfme/tests/control/test_alerts.py
Labels: fix-test

#8041 [1LP][RFR] Add default alerts smoke test
  cfme/control/explorer/alerts.py
  cfme/tests/control/test_default_alerts.py
  data/ui/control/default_alerts.yaml
Labels: enhancement, new-test-or-feature

#8124 [1LP][RFR] Custom Button: Open url non functional test
  cfme/tests/automate/custom_button/test_buttons.py
Labels: new-test-or-feature

#8074 [1LP][RFR]V2v fixes 510z
  cfme/common/vm.py
  cfme/fixtures/v2v.py
  cfme/tests/v2v/test_v2v_cancel_migrations.py
  cfme/tests/v2v/test_v2v_migrations.py
  cfme/tests/v2v/test_v2v_migrations_ui.py
  cfme/tests/v2v/test_v2v_schedule_migrations.py
  cfme/v2v/migrations.py
  widgetastic_manageiq/__init__.py
Labels: fix-framework

#8114 [RFR][NOTEST] Added cleanup for SQS queues
  scripts/ec2cleanup.py
Labels: enhancement, infra-related

#8109 [1LP][RFR] Fix generic object test and views
  cfme/generic_objects/definition/__init__.py
  cfme/generic_objects/definition/definition_views.py
  cfme/generic_objects/definition/ui.py
  cfme/generic_objects/instance/ui.py
  cfme/services/myservice/ui.py
  cfme/tests/generic_objects/test_instances.py
Labels: fix-framework, fix-test

#8148 [1LP][RFR] whitelist test_v2v in xunit_tools
  cfme/fixtures/xunit_tools.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: enhancement

#8133 [1LP][RFR] Fixing Condition CRUD test
  cfme/control/explorer/conditions.py
  widgetastic_manageiq/expression_editor.py
Labels: fix-framework

#7910 [1LP][RFR] Test reset of advanced config to default values.
  cfme/tests/platform/test_advanced_config.py
Labels: lint-ok, new-test-or-feature

#8136 [1LP][RFR][NOTEST] Updating iso_cust_template fixture
  cfme/tests/services/test_iso_service_catalogs.py
Labels: fix-locator-or-text

#8107 [1LP][RFR]Service Link test fix
  cfme/services/myservice/ui.py
Labels: fix-test, rc-regression-fix

#8149 [1LP][RFR] Fix ClassAddView.is_displayed
  cfme/automate/explorer/instance.py
  cfme/automate/explorer/klass.py
Labels: fix-framework

#8156 [1LP][RFR] Making activation of SmartProxy Affinity idempotent
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
Labels: fix-framework

#8153 [1LP][RFR] Fixed AttributeError in DomainEditView for 5.10z
  cfme/automate/explorer/domain.py
Labels: fix-framework

#8146 [1LP][RFR] Blocking test_run_host_analysis with BZ1650179
  cfme/tests/infrastructure/test_host_analysis.py
Labels: blockers-only

#8161 [1LP][RFR] Fix alert creation by adding an extra condition for the default driving event
  cfme/control/explorer/alerts.py
Labels: fix-framework

#8145 [1LP][RFR] Add tests from flavors management RFE
  cfme/cloud/flavor.py
  cfme/tests/openstack/cloud/test_flavors.py
Labels: new-test-or-feature

#8164 [1LP][RFR] Travis pre commit diff
  .travis.yml
Labels: enhancement, infra-related

#8155 [1LP][RFR] Fixed AttributeError in OrchestrationTemplate for 5.10z
  cfme/services/catalogs/orchestration_template.py
Labels: fix-locator-or-text

#8163 [1LP][RFR] fix teardown of test_instance_attach_volume
  cfme/tests/openstack/cloud/test_instances.py
Labels: fix-test

#8168 [1LP][RFR] Fixes dual NICs MAC comparison failure - 1liner
  cfme/tests/v2v/test_v2v_migrations.py
Labels: fix-test

#8154 [1LP][RFR] fixed finalizer cleanup for test_tagvis_infra_object
  cfme/fixtures/tag.py
  cfme/tests/cloud_infra_common/test_tag_objects.py
Labels: fix-test

#8171 [1LP][RFR]Fix CloudIntelReportsView TimedOutError and other test failure
  cfme/intelligence/reports/__init__.py
  cfme/intelligence/reports/menus.py
Labels: fix-test

#8170 [1LP][RFR] Fix StaleElementReferenceException error for test_schedule_crud
  cfme/intelligence/reports/schedules.py
  cfme/tests/intelligence/reports/test_crud.py
  widgetastic_manageiq/__init__.py
Labels: fix-framework

#8182 [1LP][RFR] disable adding merkil to pod containers since it cannot work there
  cfme/fixtures/base.py
Labels: fix-framework

#8151 [RFR] changed the provider to azure for test_tag_tagvis.py
  cfme/networks/floating_ips.py
  cfme/tests/networks/test_tag_tagvis.py
Labels: fix-test

#8178 [1LP][RFR] Remove TODO from schedules
  cfme/intelligence/reports/schedules.py
Labels: other

#8180 [1LP][RFR] Fix TimeProfileAddView's is_displayed
  cfme/configure/settings.py
Labels: fix-test

#8181 [1LP][RFR]Fix ScheduleEditView is_displayed
  cfme/configure/configuration/system_schedules.py
Labels: fix-locator-or-text

#8189 [RFR] removed BZ and fixed fill_tag for test_group_crud_with_tag
  cfme/tests/configure/test_access_control.py
Labels: fix-test

#8184 [1LP][RFR] upgrade notebook requirement after cve warning
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: enhancement, fix-framework

#8194 [1LP][RFR] WaitTab should wait until it is displayed before accessing child widget
  widgetastic_manageiq/__init__.py
Labels: fix-framework

#7946 [1LP][RFR] Add 2 volume backup restore tests
  cfme/tests/openstack/cloud/test_volume_backup.py
Labels: lint-ok, new-test-or-feature

#8188 [1LP][RFR] Updating blockers for test_ssa_schedule
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
Labels: blockers-only

#8192 [RFR] fix 5.10.0.25 changes in enablement
  cfme/tests/automate/custom_button/test_generic_objects.py
Labels: fix-test

#8196 [RFR]Remove typo
  cfme/intelligence/reports/schedules.py
Labels: fix-framework

#8197 [RFR] Fixing test_host_drift_analysis
  cfme/infrastructure/host.py
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
  cfme/tests/infrastructure/test_host_drift_analysis.py
Labels: fix-test

#8198 [RFR]Fix ScopeMismatch error
  cfme/tests/test_rest.py
Labels: fix-test

#8139 [1LP][RFR] fixed test_collect_multiple_servers tests
  cfme/configure/configuration/diagnostics_settings.py
Labels: fix-test

#7690 [1LP][RFR] pytest collecting testcase info for Polarion
  cfme/markers/manual.py
  cfme/tests/.polarion_tests
  conf/polarion_tools.yaml.template
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
  requirements/template_docs.txt
Labels: enhancement, lint-ok, plugins

#7860 [1LP][RFR] Add long name vm migration test
  cfme/tests/v2v/test_v2v_migrations.py
Labels: lint-ok, new-test-or-feature

#8204 [1LP][RFR] visibility and enablement test for container
  cfme/automate/buttons.py
  cfme/tests/automate/custom_button/test_container_objects.py
Labels: new-test-or-feature

#8193 [1LP][RFR] fixed collect_time for dropbox log collection
  cfme/tests/configure/test_log_depot_operation.py
Labels: fix-test

#8183 [1LP][RFR] Custom Button: Cloud-Visibility and Enablement
  cfme/tests/automate/custom_button/test_cloud_objects.py
Labels: new-test-or-feature

#8179 [1LP][RFR] Infra object: CB visibility and enablement
  cfme/tests/automate/custom_button/test_infra_objects.py
Labels: new-test-or-feature

#8167 [1LP][RFR] Uncollect for KubeVirt Provider so that alerts tests don't run on this provider
  cfme/tests/control/test_alerts.py
Labels: blockers-only

#8080 [1LP][RFR] Test for Quota with Catalog_bundle: Verifying quota limit by ordering catalog bundle over the assigned quota
  cfme/tests/infrastructure/test_quota_tagging.py
Labels: new-test-or-feature

#8172 [1LP][RFR] Custom button: Service and Generic object test
  cfme/base/ssui.py
  cfme/services/myservice/ui.py
  cfme/tests/automate/custom_button/test_service_objects.py
Labels: new-test-or-feature

#8203 [1LP][RFR] Use vddk v6_5 for provider vSphere 6.7 (nested) on test_alert_hardware_reconfigured
  cfme/tests/control/test_alerts.py
Labels: fix-test

#8166 [1LP][RFR] 5.10 Fixes for Containers Tests
  cfme/containers/project.py
  cfme/tests/containers/test_basic_metrics.py
  cfme/tests/containers/test_overview_data_integrity.py
  cfme/tests/containers/test_properties.py
  cfme/tests/containers/test_relationships.py
  cfme/tests/containers/test_smart_management.py
  widgetastic_manageiq/__init__.py
Labels: fix-test

#8202 [1LP][RFR] Ensuring page safe after filling VM provisioning form
  cfme/common/vm_views.py
Labels: enhancement, fix-framework

#8089 [1LP][RFR] Fix myservice ssui crud
  cfme/tests/ssui/test_ssui_myservice.py
Labels: fix-locator-or-text, rc-regression-fix

#8191 [1LP][RFR] added all method for keypairs, tenant and flavor collections
  cfme/cloud/flavor.py
  cfme/cloud/keypairs.py
  cfme/cloud/tenant.py
Labels: enhancement

#8209 [RFR] fixed indent for test_tagvis_cloud_object and removed if for appliance.version < 5.8
  cfme/tests/cloud_infra_common/test_tag_objects.py
Labels: fix-test

#8173 [1LP][RFR] fix test_vmware_alarm_selection_does_not_fail by restructuring test
  cfme/tests/control/test_bugs.py
Labels: fix-test

#7870 [1LP][RFR] Add test policy to check source VM from starting after migration
  cfme/tests/v2v/test_post_migrations.py
Labels: lint-ok, new-test-or-feature

#8177 [1LP][RFR] New tests for Quota: checks quota assigned by automation methods for user and group by provisioning instance over quota limit
  cfme/tests/cloud/test_quota_tagging.py
Labels: new-test-or-feature

#7977 [1LP][RFR] Test for new feature of VM: Rename the VM
  cfme/common/vm.py
  cfme/common/vm_views.py
  cfme/infrastructure/virtual_machines.py
  cfme/tests/infrastructure/test_vm_ownership.py
Labels: WIP-testing, enhancement, lint-ok, new-test-or-feature

#8218 [1LP][RFR] Add fixture to enable v2v migration UI in downstream 510z
  cfme/fixtures/v2v.py
Labels: fix-test, tech-debt

#8213 [1LP][RFR] Fix power operation
  cfme/dashboard.py
  cfme/services/myservice/ssui.py
Labels: issue-bug, tech-debt

#8216 [1LP][RFR] Refactor tests to just read first row from the report
  cfme/tests/intelligence/chargeback/test_chargeback_long_term_rates.py
Labels: fix-test

#8005 [RFR] [NOTEST] Added unzipping of manageiq templates for ec2 and gce
  cfme/utils/template/base.py
  cfme/utils/template/gce.py
Labels: enhancement, infra-related
