Repository ManageIQ/integration_tests, pull requests merged in 2018-10, with the labels that each got.

#7887 [1LP][RFR][NOTEST] Blocking test_actions.py with BZ1633606
  cfme/tests/control/test_actions.py
Labels: blockers-only, lint-ok

#7888 [1LP][RFR][NOTEST] Blocking test_tenant_quota_vm_reconfigure with BZ1626232
  cfme/tests/infrastructure/test_tenant_quota.py
Labels: blockers-only, lint-ok

#7873 [1LP][RFR] Fix test_bad_password
  cfme/tests/test_login.py
Labels: fix-test, lint-ok

#7885 [1LP][RFR][NOTEST] Blocking several service tests with BZ1633540
  cfme/tests/infrastructure/test_quota_tagging.py
  cfme/tests/infrastructure/test_tenant_quota.py
  cfme/tests/services/test_different_dialogs_in_catalogs.py
  cfme/tests/services/test_service_catalogs.py
  cfme/tests/services/test_service_manual_approval.py
  cfme/tests/ssui/test_ssui_myservice.py
  cfme/tests/ssui/test_ssui_service_catalogs.py
Labels: blockers-only, lint-ok

#7874 [1LP][RFR] delete vm after the test
  cfme/tests/cloud_infra_common/test_tag_visibility.py
Labels: fix-test, lint-ok

#7876 [1LP][RFR] Fixed type error in advance search for 5.10
  cfme/tests/infrastructure/test_advanced_search_host.py
Labels: fix-test, lint-ok

#7884 [1LP][RFR][NOTEST] Adding two PXE blockers and removing unused ones
  cfme/tests/infrastructure/test_pxe_provisioning.py
  cfme/tests/services/test_pxe_service_catalogs.py
Labels: blockers-only, lint-ok

#7879 [1LP][RFR] uncollect tests for keypair visibility in 5.8
  cfme/tests/cloud_infra_common/test_tag_objects.py
Labels: fix-locator-or-text, lint-ok

#7902 [1LP][RFR] custom sprout request time
  cfme/test_framework/sprout/client.py
  cfme/test_framework/sprout/plugin.py
Labels: lint-ok, sprout

#7864 [1LP][RFR][NOTEST] Need to separate out Managers from provider
  cfme/infrastructure/cluster.py
  cfme/infrastructure/datastore.py
Labels: fix-framework, lint-ok

#7919 [1LP][RFR] Move widgetastic exception import
  cfme/configure/configuration/diagnostics_settings.py
Labels: fix-framework, lint-ok

#7878 [1LP][RFR] Upgrade the change password test
  cfme/tests/test_login.py
Labels: lint-ok, new-test-or-feature

#7825 [1LP][RFR] Custom Button: Support for Cloud networks and All method
  cfme/networks/cloud_network.py
  cfme/tests/automate/custom_button/test_cloud_objects.py
Labels: lint-ok, new-test-or-feature

#7892 [1LP][RFR][NOTEST] Wrapping test_no_power_controls_on_archived_vm with BZ1633727
  cfme/tests/infrastructure/test_vm_power_control.py
Labels: blockers-only, lint-ok

#7877 [1LP][RFR][NOTEST] Blocking test_vm_reconfig_add_remove_hw_* with BZ1632782
  cfme/tests/infrastructure/test_vm_reconfigure.py
Labels: blockers-only, lint-ok

#7871 [1LP][RFR] Fix test_rolename_required_error_validation
  cfme/tests/configure/test_access_control.py
Labels: lint-ok

#7862 [1LP][RFR] Custom Button: template images object support
  cfme/automate/buttons.py
  cfme/tests/automate/custom_button/test_buttons.py
  cfme/tests/automate/custom_button/test_cloud_objects.py
  cfme/tests/automate/custom_button/test_infra_objects.py
Labels: lint-ok, new-test-or-feature

#7861 [1LP][RFR] Add test for migration with rbac
  cfme/tests/v2v/test_v2v_migrations_ui.py
Labels: WIP-testing, lint-ok, new-test-or-feature

#7900 [RFR] Fix ovirt template upload failure
  cfme/utils/template/rhevm.py
Labels: infra-related, lint-ok

#7771 [RFR][NOMERGE] switch the hardcoding of marionette to True in order to test
  cfme/ansible/credentials.py
  cfme/ansible/repositories.py
  cfme/automate/explorer/method.py
  cfme/common/provider.py
  cfme/configure/access_control/__init__.py
  cfme/configure/configuration/diagnostics_settings.py
  cfme/configure/configuration/server_settings.py
  cfme/control/explorer/__init__.py
  cfme/infrastructure/virtual_machines.py
  cfme/intelligence/chargeback/rates.py
  cfme/services/myservice/ssui.py
  cfme/services/myservice/ui.py
  cfme/services/service_catalogs/ui.py
  cfme/tests/candu/test_host_graph.py
  cfme/tests/cloud/test_stack.py
  cfme/tests/configure/test_access_control.py
  cfme/tests/control/test_smoke_control.py
  cfme/tests/infrastructure/test_tenant_quota.py
  cfme/tests/integration/test_aws_iam_auth_and_roles.py
  cfme/tests/integration/test_cfme_auth.py
  cfme/tests/v2v/test_v2v.py
  cfme/tests/v2v/test_v2v_migrations_ui.py
  cfme/utils/appliance/implementations/ssui.py
  cfme/utils/appliance/implementations/ui.py
  cfme/utils/browser.py
  cfme/v2v/migrations.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: enhancement, lint-ok, tech-debt

#7850 [1LP][RFR] Add test incr backup of attached volume crud
  cfme/storage/volume_backup.py
  cfme/tests/openstack/cloud/test_volume_backup.py
Labels: lint-ok, new-test-or-feature

#7866 [1LP][RFR]V2v tests mac addr
  cfme/common/vm.py
  cfme/fixtures/v2v.py
  cfme/tests/v2v/test_v2v_migrations.py
  cfme/v2v/migrations.py
Labels: lint-ok, new-test-or-feature

#7587 [1LP][RFR] Add password requirements test.
  cfme/tests/cloud/test_providers.py
Labels: lint-ok, new-test-or-feature

#7928 [RFR] uncollect host tests against 5.10
  cfme/tests/candu/test_gap_collection.py
  cfme/tests/candu/test_host_graph.py
  cfme/tests/infrastructure/test_host_drift_analysis.py
  cfme/tests/infrastructure/test_individual_host_creds.py
  cfme/tests/v2v/test_csv_import.py
  cfme/tests/v2v/test_v2v_migrations_ui.py
Labels: fix-test, lint-ok

#7012 [1LP][RFR] UI Tests for PhysicalRack
  cfme/exceptions.py
  cfme/physical/physical_rack.py
  cfme/tests/physical_infrastructure/test_physical_rack.py
  entry_points.txt
Labels: collections-conversion, lint-ok, widgetastic-conversion

#7763 [1LP][RFR] Implement regex search
  cfme/fixtures/merkyl.py
Labels: enhancement, lint-ok

#7912 [RFR] Provider dashboard view with parametrized cards
  cfme/cloud/provider/__init__.py
  cfme/common/provider_views.py
  cfme/containers/overview.py
  cfme/tests/containers/test_containers_summary.py
  cfme/tests/containers/test_overview_data_integrity.py
  widgetastic_manageiq/__init__.py
Labels: WIP-testing, enhancement, lint-ok

#7905 [1LP][RFR]Automate test: Resetting changes on Default Filters page
  cfme/configure/settings.py
  cfme/tests/configure/test_default_filters.py
Labels: lint-ok, new-test-or-feature

#7922 [1LP][RFR][NOTEST] Dealing with datepicker bug in CFME 5.9
  cfme/tests/automate/test_common_methods.py
  cfme/tests/cloud_infra_common/test_retirement.py
Labels: blockers-only, lint-ok

#7907 [1LP][RFR] Functions to get progress bar percentage in MigrationProgressBar widget
  widgetastic_manageiq/__init__.py
Labels: enhancement, lint-ok

#7932 [RFR]EditManagementRelationship view should have wait_for_view check disabled
  cfme/infrastructure/virtual_machines.py
  cfme/tests/cloud/test_cloud_timelines.py
  cfme/tests/infrastructure/test_timelines.py
Labels: fix-framework, lint-ok

#7933 [RFR]Fixing navigation to SetOwnershipView which doesn't have is_displayed
  cfme/common/vm.py
Labels: fix-framework, lint-ok

#7931 [RFR] fix provisioning view navigation
  cfme/common/vm.py
  cfme/provisioning.py
  cfme/tests/cloud/test_providers.py
Labels: fix-framework, lint-ok

#7930 [1LP][RFR]ProviderClusters.is_displayed had a typo and always returned False
  cfme/infrastructure/provider/__init__.py
Labels: fix-framework, lint-ok

#7926 [1LP][RFR] Fix CMQE Custom Attribute Test Case
  cfme/tests/containers/test_static_custom_attributes.py
Labels: fix-test, lint-ok

#7858 [1LP][RFR] Move Nuage fixtures
  cfme/fixtures/networks.py
  cfme/fixtures/nuage.py
  cfme/test_framework/pytest_plugin.py
  cfme/tests/networks/nuage/test_events_are_triggered.py
Labels: lint-ok, other

#7663 [1LP][RFR] Add logging for writing yum repos in update tests
  cfme/tests/cli/test_appliance_update.py
Labels: enhancement, lint-ok

#7899 [1LP][RFR] Adding New Smart State Analysis Test
  cfme/common/__init__.py
  cfme/configure/tasks.py
  cfme/containers/image.py
  cfme/tests/containers/test_containers_smartstate_analysis.py
Labels: lint-ok, new-test-or-feature

#7889 [1LP][RFR] Custom Button: Import & Export RFE automate
  cfme/automate/buttons.py
  cfme/tests/automate/custom_button/test_import_export.py
Labels: lint-ok, new-test-or-feature

#7937 [1LP][RFR] Fix view obj context
  cfme/automate/explorer/instance.py
  cfme/automate/explorer/klass.py
  cfme/automate/explorer/namespace.py
  cfme/dashboard.py
  cfme/infrastructure/config_management.py
  cfme/intelligence/chargeback/rates.py
  cfme/services/catalogs/orchestration_template.py
Labels: fix-framework, lint-ok

#7901 [1LP][WIPTEST] Custom Button: User Group Tenant
  cfme/automate/buttons.py
  cfme/configure/access_control/__init__.py
  cfme/tests/automate/custom_button/test_generic_objects.py
Labels: WIP-testing, lint-ok, new-test-or-feature

#7942 [RFR] Fix BZ instantiation for server.get_master
  cfme/base/__init__.py
Labels: fix-framework, lint-ok

#7918 [RFR] Flash message after ordering catalog is success now
  cfme/services/service_catalogs/ui.py
  cfme/tests/services/test_service_catalogs.py
Labels: fix-test, lint-ok

#7940 [1LP][WIPTEST] fix is_displayed of VolumeRestoreView and VolumeBackupView to return True
  cfme/storage/volume.py
  cfme/storage/volume_backup.py
Labels: WIP-testing, fix-framework, lint-ok

#7921 [1LP][WIPTEST] Fix- custom button infra object paginator selection problem
  cfme/tests/automate/custom_button/test_infra_objects.py
Labels: WIP-testing, fix-test, lint-ok

#7943 [1LP][RFR] Update Taggable.add_tag nav error handling
  cfme/common/__init__.py
Labels: WIP-testing, fix-framework, lint-ok

#7696 [1LP][WIPTEST] Appliance SSH use and SystemD service updates
  cfme/base/ui.py
  cfme/containers/provider/openshift.py
  cfme/fixtures/customer_db_migrate.py
  cfme/fixtures/ui_coverage.py
  cfme/scripting/appliance.py
  cfme/test_framework/appliance_police.py
  cfme/tests/cli/test_appliance_console_db_restore.py
  cfme/tests/cli/test_evmserverd.py
  cfme/tests/configure/test_log_depot_operation.py
  cfme/tests/configure/test_ntp_server.py
  cfme/tests/distributed/test_appliance_replication.py
  cfme/tests/optimize/test_bottlenecks.py
  cfme/tests/test_db_migrate.py
  cfme/utils/appliance/__init__.py
  cfme/utils/appliance/db.py
  cfme/utils/appliance/implementations/ui.py
  cfme/utils/appliance/services.py
  scripts/precompile_assets.py
Labels: WIP-testing, enhancement, lint-ok

#7944 [WIPTEST] Fix is_displayed for Rates
  cfme/intelligence/chargeback/rates.py
Labels: WIP-testing, fix-framework, lint-ok

#7945 [RFR] Remove wait_for_evm_service and fix call to evmserverd.running
  cfme/containers/provider/openshift.py
  cfme/scripting/setup_env.py
  cfme/tests/cli/test_appliance_cli.py
  cfme/tests/cli/test_appliance_console.py
  cfme/tests/cli/test_appliance_console_db_restore.py
  cfme/tests/configure/test_log_depot_operation.py
  cfme/tests/test_db_migrate.py
  cfme/utils/appliance/__init__.py
  cfme/utils/appliance/services.py
  notebooks/BasicApplianceSetup.ipynb
Labels: lint-ok, rc-regression-fix

#7949 [RFR] Update call to CatalogItem 'Add' dest, wait_for_view
  cfme/services/catalogs/catalog_items/__init__.py
Labels: fix-framework, rc-regression-fix

#7951 [RFR] Fix SavedReportDetailsView.is_displayed
  cfme/intelligence/reports/reports.py
Labels: fix-framework, lint-ok, rc-regression-fix

#7950 [RFR] Fix bottlenecks view is_displayed
  cfme/optimize/bottlenecks.py
Labels: fix-framework, lint-ok, rc-regression-fix

#7952 [RFR] Fix tasks nav
  cfme/configure/tasks.py
Labels: WIP-testing, fix-framework, lint-ok, rc-regression-fix

#7954 [RFR] Fix: is_displayed for template details
  cfme/infrastructure/virtual_machines.py
Labels: fix-framework, lint-ok, rc-regression-fix

#7958 [1LP][RFR] replace view.is_displayed->False with NotImplementedError
  cfme/common/__init__.py
  cfme/common/host_views.py
  cfme/common/vm_views.py
  cfme/containers/provider/__init__.py
  cfme/infrastructure/provider/openstack_infra.py
  cfme/infrastructure/pxe.py
  cfme/intelligence/chargeback/rates.py
  cfme/networks/views.py
  cfme/services/catalogs/catalog_items/ansible_catalog_items.py
  cfme/storage/volume.py
  cfme/utils/appliance/implementations/ssui.py
  cfme/utils/appliance/implementations/ui.py
Labels: WIP-testing, enhancement, lint-ok

#7964 [1LP][RFR] fix group navigation displayed
  cfme/automate/__init__.py
  cfme/automate/buttons.py
  cfme/tests/automate/custom_button/test_buttons.py
Labels: fix-framework, lint-ok, rc-regression-fix

#7956 [1LP][RFR] Fix is_displayed for create and edit dialog
  cfme/automate/dialogs/__init__.py
  cfme/automate/dialogs/dialog_box.py
  cfme/automate/dialogs/dialog_element.py
  cfme/automate/dialogs/dialog_tab.py
Labels: fix-framework, lint-ok, rc-regression-fix

#7973 [1LP][RFR] fixed more is_displayed methods which I missed before
  cfme/cloud/instance/openstack.py
  cfme/common/vm_views.py
  cfme/infrastructure/config_management.py
  cfme/infrastructure/datastore.py
  cfme/infrastructure/virtual_machines.py
Labels: fix-framework, lint-ok, rc-regression-fix

#7968 [1LP][RFR] CMQE Fix is_displayed for Container Builds
  cfme/containers/build.py
Labels: lint-ok, rc-regression-fix

#7985 [1LP][RFR][NOTEST] removed BZ blockers
  cfme/tests/configure/test_log_depot_operation.py
Labels: fix-locator-or-text, lint-ok

#7984 Update paramiko and wt.core
  cfme/tests/candu/test_gap_collection.py
  cfme/tests/candu/test_host_graph.py
  cfme/tests/infrastructure/test_host_drift_analysis.py
  cfme/tests/infrastructure/test_individual_host_creds.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: lint-ok, other

#7987 [RFR] Fix is_displayed() for DiagnosticServerWorkersView
  cfme/configure/configuration/diagnostics_settings.py
Labels: fix-framework, lint-ok, rc-regression-fix

#7986 [RFR] Fix is_displayed and step() for CMQE project Class
  cfme/containers/project.py
Labels: fix-framework, lint-ok, rc-regression-fix

#7981 [1LP][RFR] Fixing retirement state for 5.10
  cfme/tests/cloud_infra_common/test_retirement.py
Labels: fix-test, lint-ok

#7989 [1LP][RFR] Add assignable displayed exception
  cfme/cloud/instance/openstack.py
  cfme/common/__init__.py
  cfme/common/host_views.py
  cfme/common/vm_views.py
  cfme/containers/provider/__init__.py
  cfme/exceptions.py
  cfme/infrastructure/config_management.py
  cfme/infrastructure/datastore.py
  cfme/infrastructure/provider/openstack_infra.py
  cfme/infrastructure/pxe.py
  cfme/infrastructure/virtual_machines.py
  cfme/intelligence/chargeback/rates.py
  cfme/networks/views.py
  cfme/services/catalogs/catalog_items/ansible_catalog_items.py
  cfme/storage/volume.py
Labels: enhancement, lint-ok

#7976 [RFR] Fix message in unique name tests
  cfme/tests/configure/test_access_control.py
Labels: fix-locator-or-text, lint-ok

#7967 [RFR]Fix view is_displayed for services
  cfme/services/catalogs/__init__.py
  cfme/services/service_catalogs/ui.py
Labels: fix-framework, lint-ok, rc-regression-fix

#7980 [WIPTEST] Network view fix
  cfme/networks/provider/__init__.py
  cfme/networks/views.py
Labels: WIP-testing, fix-framework, lint-ok, rc-regression-fix

#7947 [1LP][RFR] Fix PolicyCollection.PRETTY and PoliciesAllView.is_displayed
  cfme/control/explorer/conditions.py
  cfme/control/explorer/policies.py
  cfme/control/explorer/policy_profiles.py
  cfme/tests/control/test_actions.py
Labels: fix-framework, lint-ok, rc-regression-fix

#7948 [1LP][WIPTEST] Update ConfigManager/SystemManager views/nav
  cfme/infrastructure/config_management.py
Labels: WIP-testing, fix-framework, lint-ok, rc-regression-fix

#7992 [WIPTEST] Fix is_displayed method for InstanceDetailsView
  cfme/cloud/instance/__init__.py
Labels: WIP-testing, lint-ok, rc-regression-fix

#7988 [RFR]Myservice view fix
  cfme/services/myservice/ui.py
Labels: WIP-testing, fix-framework, lint-ok, rc-regression-fix

#7966 [1LP][RFR][NOTEST] Blocking test_pxe_provision_from_template with GH7965
  cfme/tests/infrastructure/test_pxe_provisioning.py
  cfme/tests/services/test_pxe_service_catalogs.py
Labels: blockers-only, lint-ok

#7916 [1LP][RFR] new test_250_vmware_hosts_loading
  cfme/tests/infrastructure/test_host.py
Labels: lint-ok, new-test-or-feature

#7911 [1LP][RFR] Enabled SmartProxy Affinity for SSA
  cfme/base/ui.py
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
Labels: RHV, lint-ok, new-test-or-feature

#7897 [1LP][RFR]V2v migration with special chars name
  cfme/tests/v2v/test_v2v_migrations.py
  cfme/tests/v2v/test_v2v_migrations_ui.py
Labels: lint-ok, new-test-or-feature

#7880 [1LP][RFR]V2v schedule migration tests
  cfme/tests/v2v/test_v2v_schedule_migrations.py
  widgetastic_manageiq/__init__.py
Labels: WIP-testing, fix-test, lint-ok

#8001 [1LP][RFR][NOTEST] Adding BZ1639364 to appliance name workaround
  cfme/base/__init__.py
Labels: fix-framework

#8000 [RFR] Fix evmserverd restart call
  cfme/tests/test_db_migrate.py
Labels: fix-test

#7998 [NOTEST][RFR] EC2 template fix
  cfme/utils/template/base.py
  cfme/utils/template/ec2.py
Labels: enhancement, infra-related

#7560 [1LP][RFR] Make proxy tests working
  cfme/tests/configure/test_proxy.py
  cfme/utils/appliance/__init__.py
Labels: lint-ok, new-test-or-feature

#8003 [RFR] Fix Test: test_infra_report_page_per_item
  cfme/tests/configure/test_visual_infra.py
Labels: enhancement, fix-test

#8006 [RFR]updating v2v ui tests to correctly work with 5.10 and handle wait_for_view better
  cfme/fixtures/v2v.py
  cfme/tests/v2v/test_v2v_migrations_ui.py
  cfme/v2v/migrations.py
Labels: fix-framework, rc-regression-fix

#7818 [1LP][RFR]Adding new Test: Migration Plans Sorting type/Order
  cfme/tests/v2v/test_v2v_migrations_ui.py
  cfme/v2v/migrations.py
Labels: WIP-testing, lint-ok, new-test-or-feature

#8009 [RFR] Update SystemSchedule views for zone reference
  cfme/configure/configuration/system_schedules.py
  cfme/tests/configure/test_db_backup_schedule.py
Labels: fix-framework

#8008 [RFR] Change nav targets for report prerequisites
  cfme/intelligence/reports/reports.py
Labels: fix-test, rc-regression-fix

#8010 [RFR] Fix alert profile All is_displayed
  cfme/control/explorer/alert_profiles.py
Labels: fix-framework, rc-regression-fix

#7972 [RFR] Fix: Clean automation log before execute button
  cfme/tests/automate/custom_button/__init__.py
  cfme/tests/automate/custom_button/test_infra_objects.py
Labels: WIP-testing, fix-test, lint-ok

#8012 [1LP][RFR] Update groups reference in test_vm_ownership
  cfme/tests/cloud_infra_common/test_vm_ownership.py
Labels: fix-test

#8016 [RFR] CMQE Remove Blocking Bug for Smart Management Test
  cfme/tests/containers/test_smart_management.py
Labels: blockers-only

#8013 [1LP][RFR] Fix services catalog view
  cfme/automate/explorer/domain.py
  cfme/base/ui.py
  cfme/services/catalogs/catalog_items/__init__.py
  cfme/services/catalogs/catalog_items/ansible_catalog_items.py
  cfme/services/catalogs/orchestration_template.py
Labels: fix-framework, rc-regression-fix

#8017 [RFR] Updated CMQE SSL Test to Handle No Metrics
  cfme/tests/containers/test_ssl_providers.py
Labels: fix-test

#8007 [1LP][RFR] WaitTab and wt.core update for Table
  cfme/automate/dialogs/dialog_element.py
  cfme/automate/explorer/klass.py
  cfme/base/ui.py
  cfme/cloud/provider/ec2.py
  cfme/cloud/provider/vcloud.py
  cfme/common/host_views.py
  cfme/common/provider_views.py
  cfme/common/vm.py
  cfme/common/vm_views.py
  cfme/configure/access_control/__init__.py
  cfme/configure/configuration/analysis_profile.py
  cfme/configure/settings.py
  cfme/configure/tasks.py
  cfme/containers/provider/__init__.py
  cfme/dashboard.py
  cfme/infrastructure/config_management.py
  cfme/infrastructure/provider/openstack_infra.py
  cfme/infrastructure/provider/rhevm.py
  cfme/infrastructure/virtual_machines.py
  cfme/intelligence/reports/reports.py
  cfme/networks/provider/nuage.py
  cfme/optimize/bottlenecks.py
  cfme/services/catalogs/catalog_items/__init__.py
  cfme/services/catalogs/catalog_items/ansible_catalog_items.py
  cfme/services/catalogs/catalog_items/catalog_bundles.py
  cfme/services/myservice/ui.py
  cfme/services/requests.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
  widgetastic_manageiq/__init__.py
Labels: fix-framework

#8019 [RFR] Update keys in schedules_report/*.yaml, email types
  cfme/intelligence/reports/__init__.py
  cfme/intelligence/reports/schedules.py
  data/schedules_report/daily.yaml
  data/schedules_report/hourly.yaml
  data/schedules_report/monthly.yaml
  data/schedules_report/once.yaml
  data/schedules_report/weekly.yaml
Labels: fix-test

#8004 [1LP][RFR] Test custom button dialog
  cfme/tests/automate/custom_button/__init__.py
  cfme/tests/automate/custom_button/test_cloud_objects.py
  cfme/tests/automate/custom_button/test_infra_objects.py
Labels: fix-framework, new-test-or-feature

#7962 [1LP][RFR][NOTEST] removed blocker for test_paginator
  cfme/tests/configure/test_paginator.py
Labels: blockers-only, lint-ok

#7953 [1LP][RFR] Add cloud provider dashboard tests
  cfme/tests/openstack/cloud/test_provider.py
Labels: lint-ok, new-test-or-feature

#7894 [1LP][RFR] Add Physical Storage entity
  cfme/physical/physical_storage.py
  entry_points.txt
Labels: enhancement, lint-ok, new-test-or-feature

#7760 [1LP][RFR] Added new update tests and fixtures for them
  cfme/fixtures/cli.py
  cfme/tests/cli/test_appliance_update.py
  cfme/utils/appliance/__init__.py
Labels: lint-ok, new-test-or-feature

#7691 [1LP][RFR] Fixed timing issues for Openstack test_networks tests
  cfme/tests/openstack/cloud/test_networks.py
Labels: fix-test, lint-ok

#7959 [WIPTEST] Updates to Chargeback Assignments Class and Tests
  cfme/intelligence/chargeback/assignments.py
  cfme/intelligence/chargeback/rates.py
  cfme/tests/containers/test_chargeback.py
  cfme/tests/intelligence/chargeback/test_chargeback_long_term_rates.py
  cfme/tests/intelligence/chargeback/test_resource_allocation.py
  cfme/tests/intelligence/reports/test_validate_chargeback_report.py
  cfme/tests/intelligence/test_chargeback_assignments.py
  cfme/tests/ssui/test_ssui_dashboard.py
Labels: enhancement, fix-framework, lint-ok, rc-regression-fix

#8027 [RFR][NOTEST] fix Image time out
  cfme/cloud/instance/image.py
Labels: rc-regression-fix

#8028 [1LP][RFR] Update ImageDetailsView.is_displayed
  cfme/cloud/instance/image.py
Labels: fix-framework

#7726 [1LP][WIP] Add a test for redfish physical server details
  cfme/common/provider_views.py
  cfme/physical/physical_server.py
  cfme/physical/provider/redfish.py
  cfme/tests/physical_infrastructure/test_redfish_physical_server_details.py
  entry_points.txt
Labels: Redfish, WIP, enhancement, lint-ok, new-test-or-feature

#7917 [1LP][RFR] Modify report download method for 5.10
  cfme/intelligence/reports/reports.py
  cfme/tests/intelligence/test_download_report.py
Labels: fix-test, lint-ok

#7890 [1LP][WIPTEST] new test_provider_log_level
  cfme/tests/configure/test_logs.py
Labels: lint-ok, new-test-or-feature

#7994 [1LP][RFR]Fix YAML data for scheduling a report
  data/schedules_crud/basic01.yaml
Labels: fix-locator-or-text

#7991 [1LP][RFR] new test_openstack_provider_has_dashboard
  cfme/tests/cloud/test_providers.py
Labels: WIP-testing, lint-ok, new-test-or-feature

#7983 [1LP][RFR] new test for advanced setting for remote servers
  cfme/base/ui.py
  cfme/tests/configure/test_remote_server_tabs.py
Labels: lint-ok, new-test-or-feature

#7904 [1LP][RFR] Automate test: Create schedule for base report
  cfme/intelligence/reports/reports.py
  cfme/tests/intelligence/reports/test_crud.py
Labels: WIP-testing, enhancement, lint-ok, new-test-or-feature

#8034 wrapanapi 3.0.30 for scvmm cleanup behavior
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
Labels: infra-related

#7914 [1LP][RFR] Custom Button: Container object initial display test
  cfme/automate/buttons.py
  cfme/tests/automate/custom_button/test_buttons.py
  cfme/tests/automate/custom_button/test_container_objects.py
Labels: lint-ok, new-test-or-feature

#8031 [RFR] Fixed TypeError of host in 5.10z
  cfme/tests/infrastructure/test_host.py
Labels: fix-framework

#8030 [RFR] Fixed KeyError of customization_template in 5.10z
  cfme/infrastructure/pxe.py
Labels: fix-framework

#8029 [RFR]Orchestration view is_displayed fix
  cfme/services/catalogs/catalog.py
  cfme/services/catalogs/catalog_items/__init__.py
  cfme/services/catalogs/orchestration_template.py
Labels: fix-framework

#7896 [1LP][WIPTEST]V2v ui tests providers refactoring
  cfme/tests/v2v/test_v2v_migrations_ui.py
  cfme/v2v/migrations.py
Labels: enhancement, fix-test, lint-ok

#8025 [1LP][RFR] Add service dropdownlist dialog required element
  cfme/tests/services/test_dialog_element_in_catalog.py
Labels: enhancement

#8037 [1LP][RFR] Custom Button: automate with dialog test and BZ blockers
  cfme/tests/automate/custom_button/test_generic_objects.py
Labels: fix-test, new-test-or-feature

#7996 [1LP][RFR] Add host networks and subnets tests
  cfme/infrastructure/host.py
  cfme/networks/views.py
  cfme/tests/openstack/infrastructure/test_hosts.py
Labels: new-test-or-feature

#7995 [1LP][RFR] Limit tests to one provider per type
  cfme/tests/candu/test_vm_graph.py
Labels: other

#8043 [1LP][RFR]miq-version 0.1.8, fix py3 compat and TypeError
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: infra-related

#7906 [1LP][RFR] Automate Test: Add schedule for custom report
  cfme/tests/intelligence/reports/test_crud.py
Labels: lint-ok, new-test-or-feature

#7925 [1LP][RFR] QUOTA TEST: To show quota used on tenant quota screen even when no quotas are set
  cfme/configure/access_control/__init__.py
  cfme/tests/cloud_infra_common/test_quota_with_multiple_providers.py
Labels: WIP-testing, lint-ok, new-test-or-feature

#7990 [1LP][RFR]Automate test: Queue Tenant Quota Reports
  cfme/tests/intelligence/reports/test_tenant_quota_reports.py
Labels: lint-ok, new-test-or-feature

#8046 [1LP][RFR] Update markers plugin list, remove dups
  cfme/markers/__init__.py
Labels: enhancement

#7859 [1LP][RFR] added check for logs on dropbox
  cfme/ansible/repositories.py
  cfme/configure/configuration/diagnostics_settings.py
  cfme/services/catalogs/catalog_items/__init__.py
  cfme/services/catalogs/catalog_items/ansible_catalog_items.py
  cfme/tests/configure/test_log_depot_operation.py
Labels: WIP-testing, enhancement, fix-test, lint-ok

#8044 [WIPTEST] fix is_displayed of AttachVolumeView
  cfme/cloud/instance/openstack.py
Labels: fix-framework

#8045 [RFR] re-freeze and remove flake8
  artifactor/plugins/reporter.py
  cfme/scripting/quickstart/__init__.py
  cfme/scripting/quickstart/system.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
  requirements/template_docs.txt
Labels: enhancement

#7596 [1LP][RFR] Add test for vmware default placement
  cfme/tests/infrastructure/test_provisioning_dialog.py
Labels: lint-ok, new-test-or-feature

#8032 [1LP][RFR] Add cloud provider dashboard tests
  cfme/tests/openstack/cloud/test_provider.py
Labels: new-test-or-feature

#8042 [1LP][RFR] added check for advanced tab for region and zones and fixed navigation
  cfme/base/ui.py
  cfme/tests/configure/test_paginator.py
Labels: fix-framework, fix-test

#8023 [1LP][RFR] Added @pytest.mark to separate Regression and RFE tests
  cfme/tests/openstack/cloud/test_flavors.py
  cfme/tests/openstack/cloud/test_instances.py
  cfme/tests/openstack/cloud/test_keypairs.py
  cfme/tests/openstack/cloud/test_networks.py
  cfme/tests/openstack/cloud/test_volume_backup.py
  cfme/tests/openstack/cloud/test_volumes.py
  cfme/tests/openstack/infrastructure/test_host_lifecycle.py
  cfme/tests/openstack/infrastructure/test_host_power_control.py
  cfme/tests/openstack/infrastructure/test_hosts.py
  cfme/tests/openstack/infrastructure/test_provider.py
  cfme/tests/openstack/infrastructure/test_relationships.py
  cfme/tests/openstack/infrastructure/test_resources.py
  cfme/tests/openstack/infrastructure/test_roles.py
Labels: enhancement
