Repository ManageIQ/integration_tests, pull requests merged in 2018-04, with the labels that each got.

#7008 [RFR] Fix test_cloud_networks_query
  cfme/tests/cloud/test_providers.py
Labels: fix-test, lint-ok

#6988 [1LP][RFR] Change user testing via REST following BZ fixes
  cfme/tests/configure/test_rest_access_control.py
Labels: fix-test, lint-ok

#7010 [RFR] name change for kubevirt
  cfme/tests/infrastructure/test_kubevirt.py
Labels: fix-locator-or-text, lint-ok

#7007 [1LP][RFR] Use delete helper functions in all REST tests
  cfme/tests/ansible/test_embedded_ansible_rest.py
  cfme/tests/cloud/test_providers.py
  cfme/tests/cloud_infra_common/test_custom_attributes_rest.py
  cfme/tests/cloud_infra_common/test_rest_providers.py
  cfme/tests/cloud_infra_common/test_snapshots_rest.py
  cfme/tests/configure/test_tag.py
  cfme/tests/configure/test_tag_category.py
  cfme/tests/control/test_rest_control.py
  cfme/tests/infrastructure/test_rest_templates.py
  cfme/tests/infrastructure/test_vm_rest.py
  cfme/tests/intelligence/test_chargeback.py
  cfme/tests/services/test_generic_service_catalogs.py
  cfme/tests/services/test_rest_services.py
  cfme/tests/test_rest.py
  cfme/utils/rest.py
Labels: enhancement, lint-ok

#6987 [1LP][RFR] Check holder in appliance_log_collector
  cfme/test_framework/appliance_log_collector.py
Labels: enhancement, lint-ok

#6992 [1LP][RFR] Disable view.is_display check at the end of Role.update. Fix for BZ156198
  cfme/configure/access_control/__init__.py
Labels: fix-framework, lint-ok

#7014 [RFR] added gitignore for env.local.backup
  .gitignore
Labels: fix-locator-or-text, lint-ok

#7016 [RFR] Added override flag for provider marker
  cfme/markers/env_markers/provider.py
Labels: enhancement, lint-ok

#7018 [1LP][RFR] Delete action for physical server was removed
  cfme/tests/physical_infrastructure/ui/test_physical_server_details.py
  cfme/tests/physical_infrastructure/ui/test_physical_server_list.py
Labels: fix-test, lint-ok

#6968 [1LP][RFR] fixture name change
  cfme/fixtures/service_fixtures.py
  cfme/tests/ssui/test_ssui_dashboard.py
  cfme/tests/ssui/test_ssui_myservice.py
  cfme/tests/ssui/test_ssui_service_catalogs.py
Labels: fix-framework, lint-ok

#7020 [1LP][RFR] Fixed prov_data failures
  cfme/services/myservice/ssui.py
  cfme/tests/services/test_add_remove_vm_to_service.py
  cfme/tests/services/test_different_dialogs_in_catalogs.py
  cfme/tests/services/test_iso_service_catalogs.py
  cfme/tests/services/test_myservice.py
  cfme/tests/services/test_pxe_service_catalogs.py
  cfme/tests/services/test_request.py
  cfme/tests/services/test_service_catalogs.py
  cfme/tests/services/test_service_manual_approval.py
Labels: WIP-testing, lint-ok, rc-regression-fix

#7024 [1LP][RFR]Fix test_quota_tagging
  cfme/tests/infrastructure/test_quota_tagging.py
Labels: fix-test, lint-ok, rc-regression-fix

#7025 [1LP][RFR] Fixture name change for ensure_vm_[running|suspended]
  cfme/tests/cloud_infra_common/test_power_control_rest.py
  cfme/tests/infrastructure/test_vm_power_control.py
Labels: WIP-testing, lint-ok, rc-regression-fix

#6722 [1LP][RFR] Optimized uncollectif
  cfme/markers/uncollect.py
  cfme/tests/control/test_compliance.py
  cfme/tests/test_appliance.py
Labels: fix-framework, lint-ok

#6806 [1LP][RFR] Fix sdn_add_topology
  cfme/common/topology.py
  cfme/tests/networks/test_sdn_topology.py
Labels: fix-test, lint-ok

#6865 [1LP][RFR] Fix publish_to_template; add ownership test
  cfme/common/vm_views.py
  cfme/infrastructure/virtual_machines.py
  cfme/tests/cloud_infra_common/test_vm_ownership.py
Labels: fix-test, lint-ok, new-test-or-feature

#6903 [1LP][RFR] Add UI tests for Identify buttons in the physical server page
  cfme/physical/physical_server.py
  cfme/tests/physical_infrastructure/ui/test_physical_server_details_buttons.py
Labels: lint-ok, new-test-or-feature

#6943 [1LP][RFR] storage Manager provider cleanup
  cfme/storage/manager.py
  cfme/tests/storage/test_manager.py
Labels: fix-test, lint-ok

#7003 [1LP][RFR] New history button test with snapshot
  cfme/infrastructure/virtual_machines.py
  cfme/tests/infrastructure/test_snapshot.py
Labels: lint-ok, new-test-or-feature

#7039 [RFR][1LP] Fix SSHResult use
  cfme/utils/ssh.py
  scripts/template_upload_vsphere.py
Labels: issue-bug

#7017 [1LP][RFR] Coverage data acquisition refinements.
  scripts/data/coverage/coverage_hook.rb
  scripts/data/coverage/coverage_merger.rb
Labels: enhancement, infra-related, lint-ok

#7002 [1LP][RFR] Improved deferred version pick
  cfme/utils/__init__.py
Labels: enhancement, lint-ok

#7038 [1LP][RFR] Fix failure in test_edit_sequence_usergroups for 5.9.2
  cfme/configure/access_control/__init__.py
Labels: fix-locator-or-text, lint-ok

#6989 [1LP][RFR] Fixed strings in Control
  cfme/control/explorer/conditions.py
  cfme/control/explorer/policies.py
  cfme/tests/control/test_basic.py
Labels: fix-locator-or-text, lint-ok

#7042 [RFR] Update utils.trackerbot.parse_template, handle exception
  cfme/utils/trackerbot.py
Labels: WIP-testing, infra-related, issue-bug, lint-ok

#7031 [1LP][RFR] Add rest bind_timeout test for BZ
  cfme/tests/configure/test_session_timeout.py
Labels: lint-ok, new-test-or-feature

#7032 [1LP][RFR] Remove thing_toucher.rb and its use.
  fixtures/ui_coverage.py
  scripts/data/coverage/thing_toucher.rb
Labels: enhancement, lint-ok

#7035 [1LP][RFR] Reports dashboard collections
  cfme/intelligence/reports/dashboards.py
  cfme/tests/intelligence/reports/test_crud.py
  cfme/tests/intelligence/test_dashboard.py
  setup.py
Labels: collections-conversion, lint-ok

#7027 [1LP][RFR] Remove 'with pytest.raises' statement in test_permission_edit
  cfme/tests/configure/test_access_control.py
Labels: fix-test, lint-ok

#7045 [1LP][RFR] Add test for adding duplicate custom attribute using REST
  cfme/tests/cloud_infra_common/test_custom_attributes_rest.py
Labels: lint-ok, new-test-or-feature

#7046 [1LP][RFR] Catch empty object store collection
  cfme/tests/storage/test_object_store_object.py
Labels: fix-test, lint-ok

#6717 [1LP][RFR] Refactor auth framework and tests
  cfme/base/__init__.py
  cfme/base/ui.py
  cfme/configure/access_control/__init__.py
  cfme/configure/configuration/server_settings.py
  cfme/fixtures/authentication.py
  cfme/fixtures/base.py
  cfme/fixtures/cli.py
  cfme/fixtures/configure_auth_mode.py
  cfme/test_framework/pytest_plugin.py
  cfme/tests/cli/test_appliance_cli.py
  cfme/tests/cli/test_appliance_console.py
  cfme/tests/integration/test_aws_iam_auth_and_roles.py
  cfme/tests/integration/test_cfme_auth.py
  cfme/utils/appliance/__init__.py
  cfme/utils/auth/__init__.py
  cfme/utils/ext_auth.py
  conf/cfme_data.yaml.template
  setup.py
Labels: fix-framework, fix-test, lint-ok

#7022 [1LP][RFR] Update dev_guide doc with RC tag/release
  docs/guides/dev_guide.rst
Labels: lint-ok

#7040 [1LP][RFR] Fix template tester upload/template cloning issues across providers
  cfme/utils/appliance/__init__.py
  scripts/clone_template.py
  scripts/template_upload_scvmm.py
  scripts/template_upload_vsphere.py
Labels: enhancement, lint-ok

#7048 [1LP][RFR] cleanup_edomain_templates, handle API exception
  scripts/cleanup_edomain_templates.py
Labels: enhancement, infra-related, lint-ok

#7044 [1LP][RFR] Fixing test_edit_catalog_after_deleting_provider
  cfme/tests/services/test_service_catalogs.py
Labels: fix-test, lint-ok

#6980 [1LP][RFR] Renamed some tests to avoid duplicates
  cfme/tests/cloud/test_instance_power_control.py
  cfme/tests/cloud/test_providers.py
  cfme/tests/cloud/test_provisioning.py
  cfme/tests/cloud/test_stack.py
  cfme/tests/configure/test_tag.py
  cfme/tests/configure/test_version.py
  cfme/tests/infrastructure/test_advanced_search_host.py
  cfme/tests/infrastructure/test_advanced_search_providers.py
  cfme/tests/infrastructure/test_advanced_search_vms.py
  cfme/tests/infrastructure/test_customization_template.py
  cfme/tests/infrastructure/test_providers.py
  cfme/tests/infrastructure/test_provisioning.py
  cfme/tests/infrastructure/test_system_image_type.py
  cfme/tests/infrastructure/test_vm_power_control.py
  cfme/tests/intelligence/test_dashboard.py
  cfme/tests/networks/test_network_providers.py
  cfme/tests/physical_infrastructure/test_providers.py
  cfme/tests/services/test_catalog_item.py
  cfme/tests/services/test_myservice.py
  cfme/tests/services/test_orchestration_template.py
  cfme/tests/services/test_request.py
  cfme/tests/ssui/test_ssui_ansible_service.py
  cfme/tests/ssui/test_ssui_myservice.py
  cfme/tests/ssui/test_ssui_service_catalogs.py
Labels: fix-locator-or-text, lint-ok

#7034 [1LP][RFR] Marking test_relationships with RHV tiers
  cfme/tests/cloud_infra_common/test_relationships.py
Labels: fix-locator-or-text, lint-ok

#7049 [1LP][RFR] Ensure mostly same files show up in coverage data between test runs
  scripts/coverage_report_jenkins.py
  scripts/data/coverage/coverage_merger.rb
Labels: enhancement, lint-ok

#7036 [1LP][RFR] Marking service test cases with RHV tier
  cfme/tests/ssui/test_ssui_myservice.py
  cfme/tests/ssui/test_ssui_service_catalogs.py
Labels: lint-ok

#7033 [1LP][RFR] Marikng test_cockpit_server_role with RHV tier
  cfme/tests/cloud_infra_common/test_cockpit_server.py
Labels: lint-ok

#7030 [1LP][RFR] Marking TestRESTSnapshots with RHV tiers
  cfme/tests/cloud_infra_common/test_snapshots_rest.py
Labels: lint-ok

#7060 [1LP][RFR] Update manageiq-client to 0.4.1
  requirements/frozen.txt
  requirements/frozen_docs.txt
Labels: lint-ok

#7029 [1LP][RFR] RHV tier analyzer
  scripts/tier_analyzer.py
Labels: enhancement, lint-ok, other

#7054 [1LP][RFR] Fix test_host_drift_analysis
  cfme/tests/infrastructure/test_host_drift_analysis.py
Labels: fix-test, lint-ok

#7043 [1LP][RFR] delete_resources_from_collection - collection parameter optional
  cfme/tests/cloud/test_providers.py
  cfme/tests/cloud_infra_common/test_custom_attributes_rest.py
  cfme/tests/cloud_infra_common/test_rest_providers.py
  cfme/tests/configure/test_rest_access_control.py
  cfme/tests/configure/test_tag.py
  cfme/tests/configure/test_tag_category.py
  cfme/tests/control/test_rest_control.py
  cfme/tests/infrastructure/test_rest_templates.py
  cfme/tests/infrastructure/test_vm_rest.py
  cfme/tests/intelligence/test_chargeback.py
  cfme/tests/services/test_generic_service_catalogs.py
  cfme/tests/services/test_rest_services.py
  cfme/tests/test_rest.py
  cfme/utils/rest.py
Labels: enhancement, lint-ok

#7059 [1LP][RFR] Fix provider create for RHV and CFME < 5.8.0.8
  cfme/infrastructure/provider/rhevm.py
Labels: enhancement, lint-ok

#7068 [RFR] Use wait_for func properly
  scripts/template_upload_scvmm.py
Labels: infra-related

#7067 [1LP][RFR] Skip chargeback tests for gce for 58
  cfme/tests/intelligence/reports/test_validate_chargeback_report.py
Labels: fix-test, lint-ok

#7072 [1LP][RFR] Fixed Paralleizer Composite Uncollect
  cfme/markers/composite.py
Labels: lint-ok

#7069 [RFR] Add finalizers to login_admin to auth teardown
  cfme/tests/integration/test_cfme_auth.py
Labels: WIP-testing, fix-test, lint-ok

#7078 [RFR] wrapanapi 2.8.8 has been released
  requirements/frozen.txt
Labels: fix-locator-or-text

#7074 [1LP][RFR] Remove version check from RHEVMProvider constructor
  cfme/infrastructure/provider/rhevm.py
Labels: fix-framework, infra-related, lint-ok

#7070 [1LP][RFR] Fix certs test
  cfme/tests/test_appliance.py
Labels: fix-test, lint-ok

#7050 [1LP][RFR] Added new ansible credentials types
  cfme/ansible/credentials.py
  cfme/tests/ansible/test_embedded_ansible_basic.py
Labels: lint-ok, new-test-or-feature, tech-debt

#7064 [RFR] Fixing test_drift_analysis
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
Labels: fix-test, lint-ok

#7080 [RFR] Bump cryptography, get rid of boto
  requirements/frozen.txt
Labels: lint-ok

#7081 [RFR] tiny fix to openshift template upload test scripts
  scripts/clone_template.py
Labels: fix-framework

#7041 [1LP][RFR] C&U: Line Graph
  cfme/common/candu_views.py
  cfme/fixtures/candu.py
  cfme/infrastructure/virtual_machines.py
  cfme/test_framework/pytest_plugin.py
  cfme/tests/candu/test_vm_graph.py
  widgetastic_manageiq/__init__.py
Labels: lint-ok, new-test-or-feature

#7075 [1LP][RFR] Saved reports converted to collections
  cfme/intelligence/reports/saved.py
  setup.py
Labels: collections-conversion, lint-ok

#7011 [1LP][RFR] Adding new tests of reports scheduling
  cfme/intelligence/reports/schedules.py
  cfme/tests/intelligence/reports/test_reports_schedules.py
  data/schedules_report/daily.yaml
  data/schedules_report/hourly.yaml
  data/schedules_report/monthly.yaml
  data/schedules_report/once.yaml
  data/schedules_report/weekly.yaml
Labels: lint-ok, new-test-or-feature

#6966 [1LP][RFR] Update appliance get/set_yaml_config to property
  cfme/base/__init__.py
  cfme/tests/configure/test_ntp_server.py
  cfme/tests/control/test_alerts.py
  cfme/utils/appliance/__init__.py
  cfme/utils/perf.py
Labels: enhancement, fix-test, lint-ok

#7071 [1LP][RFR] Provisioning dialogs collections conversion
  cfme/automate/provisioning_dialogs.py
  cfme/tests/automate/test_provisioning_dialogs.py
  setup.py
Labels: collections-conversion, lint-ok

#6845 [1LP][RFR] Chargeback tests for long term rates
  cfme/intelligence/reports/reports.py
  cfme/tests/intelligence/chargeback/test_chargeback_long_term_rates.py
Labels: lint-ok, new-test-or-feature

#6999 [1LP][RFR] Wrapping test_vm_reconfig_add_remove_disk_cold with GH6996
  cfme/tests/infrastructure/test_vm_reconfigure.py
Labels: fix-test, lint-ok

#6798 [1LP][RFR] Update sdn collections
  cfme/networks/balancer.py
  cfme/networks/cloud_network.py
  cfme/networks/floating_ips.py
  cfme/networks/network_port.py
  cfme/networks/network_router.py
  cfme/networks/security_group.py
  cfme/networks/subnet.py
  cfme/tests/networks/test_sdn_inventory_collection.py
Labels: lint-ok, new-test-or-feature

#7085 [RFR] excluded smoke tests which aren't applicable for pod appliance
  cfme/tests/cli/test_appliance_console.py
  cfme/tests/test_appliance.py
Labels: fix-test, lint-ok

#7088 [RFR] gce doesn't support vms with underscore in name
  cfme/tests/cloud_infra_common/test_events.py
Labels: fix-test, lint-ok

#7083 [RFR] Wrapping test_tagdialog_catalog_item with BZ1567108
  cfme/tests/services/test_different_dialogs_in_catalogs.py
Labels: lint-ok

#7062 [RFR][1LP] Added new version picking to scripts
  cfme/scripting/appliance.py
Labels: lint-ok

#7063 [1LP][RFR] New fixes for current testing
  cfme/tests/configure/test_register_appliance.py
Labels: WIP-testing, lint-ok

#7087 [RFR] Fix dockerbot provisioning check
  .gitignore
  cfme/utils/dockerbot/pytestbase/Dockerfile
  cfme/utils/dockerbot/pytestbase/check_provisioned.py
  cfme/utils/dockerbot/pytestbase/setup.sh
Labels: lint-ok

#6364 [1LP][RFR] Cloud timeline adding events
  cfme/tests/cloud/test_cloud_timelines.py
Labels: lint-ok, new-test-or-feature

#6986 [1LP][RFR] added collections to DummyAppliance
  cfme/modeling/tests/test_collections.py
  cfme/utils/appliance/__init__.py
Labels: fix-framework, lint-ok

#7097 [1LP][RFR] Update tests using custom users
  cfme/configure/access_control/__init__.py
  cfme/roles.py
  cfme/tests/configure/test_access_control.py
  cfme/tests/integration/test_aws_iam_auth_and_roles.py
  cfme/tests/integration/test_cfme_auth.py
  cfme/tests/integration/test_ldap_auth_and_roles.py
Labels: fix-test, lint-ok, rc-regression-fix

#7103 [RFR] Update vm name for perf workloads
  cfme/tests/perf/workloads/test_provisioning.py
Labels: fix-test, infra-related, lint-ok

#5372 [1LP][RFR] Check for badness rework
  cfme/utils/appliance/implementations/ui.py
Labels: enhancement, lint-ok

#7111 [1LP][RFR] also back out of pytest logging integration :(
  cfme/test_framework/pytest_plugin.py
Labels: fix-framework, lint-ok

#7117 [1LP][RFR] Hack to allow upstream testing to work again
  cfme/base/__init__.py
Labels: fix-framework, lint-ok

#7095 [1LP][RFR] Fix package dependency conflicts
  requirements/frozen.txt
Labels: lint-ok, rc-regression-fix

#7099 [1LP][RFR] introduce find appliance helper
  cfme/test_framework/appliance.py
  cfme/test_framework/appliance_log_collector.py
  cfme/test_framework/browser_isolation.py
  cfme/utils/appliance/__init__.py
Labels: fix-framework, lint-ok

#6997 [1LP][RFR] remove multimethods from utils.version and remove magical globals usage
  cfme/markers/stream_excluder.py
  cfme/markers/uncollect.py
  cfme/rest/gen_data.py
  cfme/tests/cli/test_appliance_cli.py
  cfme/tests/configure/test_docs.py
  cfme/tests/configure/test_register_appliance.py
  cfme/tests/infrastructure/test_host_analysis.py
  cfme/tests/infrastructure/test_host_provisioning.py
  cfme/tests/storage/test_volume_backup.py
  cfme/tests/test_db_migrate.py
  cfme/tests/test_login.py
  cfme/utils/providers.py
  cfme/utils/version.py
  docs/guides/tipsntricks.rst
Labels: fix-framework, fix-test, lint-ok

#7113 [1LP][RFR] Fixed flash message in test_embedded_ansible_repository_crud
  cfme/ansible/repositories.py
Labels: fix-locator-or-text, lint-ok

#7115 [1LP][RFR] Fixed test_service_ansible_playbook_order_credentials
  cfme/tests/ansible/test_embedded_ansible_services.py
Labels: fix-test, lint-ok

#7118 [1LP][RFR] Fixed test_button_avp_displayed
  cfme/tests/automate/test_buttons.py
Labels: fix-test, lint-ok

#7102 [1LP][RFR][NOTEST] Fix sprout read the docs link in README.rst
  sprout/README.rst
Labels: lint-ok

#7100 [1LP][RFR] uncollect ansible tests for 5.8 pod appliance
  cfme/tests/ansible/test_embedded_ansible_actions.py
  cfme/tests/ansible/test_embedded_ansible_automate.py
  cfme/tests/ansible/test_embedded_ansible_basic.py
  cfme/tests/ansible/test_embedded_ansible_crud.py
  cfme/tests/ansible/test_embedded_ansible_rest.py
  cfme/tests/ansible/test_embedded_ansible_services.py
  cfme/utils/appliance/__init__.py
Labels: fix-locator-or-text, lint-ok

#7128 [1LP][RFR] massive iteritems cleanout
  artifactor/plugins/ostriz.py
  artifactor/plugins/reporter.py
  cfme/fixtures/xunit_tools.py
  cfme/markers/meta.py
  cfme/markers/stream_excluder.py
  cfme/tests/configure/test_db_backup_schedule.py
  cfme/tests/configure/test_log_depot_operation.py
  cfme/tests/configure/test_server_roles.py
  cfme/tests/containers/test_logging.py
  cfme/tests/control/test_alerts.py
  cfme/tests/test_db_migrate.py
  cfme/tests/test_db_restore.py
  cfme/tests/test_ui.py
  data/bundles/merkyl/__init__.py
  fixtures/artifactor_plugin.py
  fixtures/provider.py
  fixtures/rbac.py
  scripts/apishow.py
  scripts/coverage_result.py
  scripts/ipappliance.py
  scripts/template_upload_all.py
  scripts/template_upload_ec2.py
  scripts/template_upload_gce.py
  scripts/template_upload_openshift.py
  scripts/template_upload_rhevm.py
  scripts/template_upload_rhevm_qcow2.py
  scripts/template_upload_rhos.py
  scripts/template_upload_scvmm.py
  scripts/template_upload_vsphere.py
  sprout/appliances/api.py
  sprout/appliances/models.py
  sprout/appliances/tasks.py
  sprout/logserver.py
  widgetastic_manageiq/__init__.py
  widgetastic_manageiq/expression_editor.py
Labels: WIP-testing, lint-ok

#7109 [1LP][RFR] enhance requirement freezing
  cfme/scripting/quickstart.py
  requirements/freeze.py
  requirements/freeze_all.py
Labels: fix-framework, lint-ok

#7129 [RFR][1LP] enable the venv to be build on py3k using the template files
  cfme/configure/tasks.py
  cfme/scripting/conf.py
  cfme/scripting/disable_bytecode.py
  cfme/scripting/link_config.py
  cfme/scripting/quickstart.py
  cfme/utils/browser.py
  cfme/utils/db.py
  cfme/utils/dockerbot/sel_container.py
  cfme/utils/repo_gen.py
  fixtures/browser.py
  requirements/template_docs.txt
  widgetastic_manageiq/__init__.py
Labels: WIP, lint-ok

#7121 [1LP][RFR] access to properties of provider summary table has changed
  cfme/tests/openstack/infrastructure/test_resources.py
Labels: fix-test, lint-ok

#7105 [1LP][RFR] Rename Infrastructure.virtual_machines.Vm to InfraVm
  cfme/common/vm.py
  cfme/infrastructure/virtual_machines.py
  cfme/provisioning.py
  cfme/tests/cloud_infra_common/test_cockpit_server.py
  cfme/tests/cloud_infra_common/test_relationships.py
  cfme/tests/cloud_infra_common/test_tag_objects.py
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
  cfme/tests/configure/test_access_control.py
  cfme/tests/configure/test_default_filters.py
  cfme/tests/configure/test_default_views_infra.py
  cfme/tests/configure/test_visual_infra.py
  cfme/tests/control/test_bugs.py
  cfme/tests/infrastructure/test_advanced_search_vms.py
  cfme/tests/infrastructure/test_infra_tag_filters_combination.py
  cfme/tests/infrastructure/test_provisioning_dialog.py
  cfme/tests/infrastructure/test_snapshot.py
  cfme/tests/services/test_operations.py
  cfme/tests/webui/test_splitter.py
  cfme/utils/appliance/__init__.py
  setup.py
  widgetastic_manageiq/__init__.py
Labels: enhancement, lint-ok

#7098 [1LP][RFR] always use appliance parameter in automate simulation calls
  cfme/automate/simulation.py
  cfme/tests/automate/test_domain_priority.py
  cfme/tests/infrastructure/test_snapshot.py
  cfme/tests/services/test_add_remove_vm_to_service.py
Labels: fix-framework, lint-ok

#7023 [1LP][RFR]Use tag object only updates
  cfme/common/__init__.py
  cfme/tests/ansible/test_embedded_ansible_actions.py
  cfme/tests/ansible/test_embedded_ansible_automate.py
  cfme/tests/ansible/test_embedded_ansible_services.py
  cfme/tests/cloud/test_keypairs.py
  cfme/tests/cloud/test_stack.py
  cfme/tests/cloud_infra_common/test_retirement.py
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
  cfme/tests/configure/test_access_control.py
  cfme/tests/containers/test_smart_management.py
  cfme/tests/control/test_actions.py
  cfme/tests/infrastructure/test_host_drift_analysis.py
  cfme/tests/services/test_catalog_item.py
  cfme/tests/services/test_myservice.py
  cfme/tests/storage/test_manager.py
  cfme/tests/storage/test_object_store_container.py
  cfme/tests/storage/test_object_store_object.py
  cfme/tests/storage/test_volume.py
  cfme/tests/storage/test_volume_backup.py
  cfme/tests/storage/test_volume_snapshot.py
Labels: enhancement, fix-framework, lint-ok

#6870 [1LP][RFR] Extending test cases for SSUI
  cfme/tests/cloud/test_tenant_quota.py
  cfme/tests/infrastructure/test_tenant_quota.py
Labels: lint-ok, new-test-or-feature

#7037 [1LP][RFR] Add new tests for the physical server list page
  cfme/common/physical_server_views.py
  cfme/physical/physical_server.py
  cfme/tests/physical_infrastructure/ui/test_physical_server_list.py
  cfme/tests/physical_infrastructure/ui/test_physical_server_list_buttons.py
Labels: lint-ok, new-test-or-feature

#7119 [1LP][RFR] fixing service order() method
  cfme/fixtures/service_fixtures.py
  cfme/services/service_catalogs/ui.py
Labels: fix-framework, lint-ok

#7140 [RFR] Fixed PDF download skipping on upstream
  cfme/tests/networks/test_sdn_downloads.py
Labels: fix-test, lint-ok

#7131 [1LP][RFR] corrected inline literal in getting_started.rst
  docs/getting_started.rst
Labels: lint-ok

#7058 [1LP][RFR] Reports collections conversion
  cfme/intelligence/reports/reports.py
  cfme/intelligence/reports/saved.py
  cfme/tests/configure/test_visual_infra.py
  cfme/tests/containers/test_chargeback.py
  cfme/tests/containers/test_reports.py
  cfme/tests/intelligence/chargeback/test_chargeback_long_term_rates.py
  cfme/tests/intelligence/reports/test_canned_corresponds.py
  cfme/tests/intelligence/reports/test_crud.py
  cfme/tests/intelligence/reports/test_generate_report.py
  cfme/tests/intelligence/reports/test_menus.py
  cfme/tests/intelligence/reports/test_metering_report.py
  cfme/tests/intelligence/reports/test_report_chargeback.py
  cfme/tests/intelligence/reports/test_report_corresponds.py
  cfme/tests/intelligence/reports/test_validate_chargeback_report.py
  cfme/tests/intelligence/reports/test_views.py
  cfme/tests/intelligence/test_download_report.py
  setup.py
Labels: collections-conversion, lint-ok

#7158 [RFR][1LP] Fixed server name again, previous attempt led to recursion
  cfme/base/__init__.py
Labels: fix-framework

#7151 [1LP][RFR] Activating test_vm_power_options_from_on for RHV
  cfme/tests/infrastructure/test_vm_power_control.py
Labels: fix-test, lint-ok

#7065 [1LP][RFR] RHV tiers for several tests
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
  cfme/tests/infrastructure/test_snapshot.py
  cfme/tests/infrastructure/test_vm_clone.py
  cfme/tests/services/test_service_catalogs.py
  cfme/tests/ssui/test_ssui_dashboard.py
Labels: lint-ok, other

#7056 [1LP][RFR] debuginfo-install in quickstart
  cfme/scripting/quickstart.py
Labels: enhancement, lint-ok, tech-debt

#7163 [RFR] New dump2polarion version with support for v2.0.12 of Importers
  requirements/frozen.txt
  requirements/frozen_docs.txt
Labels: enhancement, infra-related, lint-ok

#7160 [RFR] py3 compat hack - ignore unimportable ovirtsdk
  cfme/utils/mgmt_system/__init__.py
  cfme/utils/virtual_machines.py
Labels: lint-ok

#7092 [1LP][RFR]Temporary patch to track coverage in forked CFME processes
  cfme/exceptions.py
  fixtures/ui_coverage.py
  scripts/data/coverage/manageiq-17302.patch
Labels: fix-framework, lint-ok

#7159 [1LP][RFR] remove the need for functools32
  cfme/utils/tracer.py
  requirements/template_docs.txt
  scripts/jenkins_failure_analysis.py
Labels: fix-framework, lint-ok

#7152 [1LP][RFR] Activating test_guest_os_shutdown for RHV
  cfme/tests/infrastructure/test_vm_power_control.py
Labels: lint-ok

#7147 [1LP][RFR] New performance requirements
  cfme/fixtures/version_info.py
  requirements/frozen.txt
  requirements/perf.txt
  requirements/template_docs.txt
Labels: enhancement, lint-ok

#6859 [1LP][RFR] All Provider collections
  cfme/cloud/provider/__init__.py
  cfme/cloud/provider/azure.py
  cfme/cloud/provider/ec2.py
  cfme/cloud/provider/gce.py
  cfme/cloud/provider/openstack.py
  cfme/cloud/provider/vcloud.py
  cfme/common/provider.py
  cfme/containers/provider/__init__.py
  cfme/containers/provider/kubernetes.py
  cfme/containers/provider/openshift.py
  cfme/infrastructure/provider/__init__.py
  cfme/infrastructure/provider/kubevirt.py
  cfme/infrastructure/provider/openstack_infra.py
  cfme/infrastructure/provider/rhevm.py
  cfme/infrastructure/provider/scvmm.py
  cfme/infrastructure/provider/virtualcenter.py
  cfme/networks/provider/__init__.py
  cfme/networks/provider/nuage.py
  cfme/physical/provider/__init__.py
  cfme/physical/provider/lenovo.py
  cfme/tests/cloud/test_providers.py
  cfme/tests/distributed/test_appliance_replication.py
  cfme/tests/infrastructure/test_esx_direct_host.py
  cfme/tests/infrastructure/test_provider_discovery.py
  cfme/tests/infrastructure/test_providers.py
  cfme/tests/networks/test_network_providers.py
  cfme/utils/appliance/__init__.py
  cfme/utils/providers.py
  docs/guides/newprovider.rst
  setup.py
Labels: collections-conversion, lint-ok

#7110 [1LP][RFR] Fix cockpit server role tests for cloud providers
  cfme/cloud/instance/__init__.py
  cfme/tests/cloud_infra_common/test_cockpit_server.py
Labels: fix-framework, lint-ok

#6861 [1LP][RFR]tests for system schedules
  cfme/configure/configuration/system_schedules.py
  cfme/tests/configure/test_schedule_operations.py
Labels: lint-ok, new-test-or-feature

#7161 [1LP][RFR] Adding some more RHV markers
  cfme/services/myservice/ssui.py
  cfme/tests/infrastructure/test_snapshot.py
  cfme/tests/infrastructure/test_vm_reconfigure.py
  cfme/tests/ssui/test_ssui_myservice.py
Labels: fix-test, lint-ok

#7164 [1LP][RFR] Update EntityCollections to report its available collections, sort appliance collections
  cfme/modeling/base.py
  setup.py
Labels: enhancement, lint-ok

#7172 [1LP][RFR] Fix 2 bugs with dropping database
  cfme/utils/appliance/db.py
Labels: fix-framework, lint-ok, rc-regression-fix

#7170 [1LP][RFR] fixed some quota tagging tags broken by one of recent updates
  cfme/tests/infrastructure/test_quota_tagging.py
Labels: fix-test, lint-ok, rc-regression-fix

#7174 [1LP][RFR] Fixed a bug with some network provider collections
  cfme/tests/cloud_infra_common/test_relationships.py
  cfme/tests/networks/test_sdn_crud.py
  cfme/tests/networks/test_sdn_navigation.py
  cfme/tests/networks/test_tag_tagvis.py
Labels: fix-test, lint-ok, rc-regression-fix

#7175 [1LP][RFR] Remove verified BZ from auth integration tests
  cfme/tests/integration/test_aws_iam_auth_and_roles.py
Labels: lint-ok, other
