Repository ManageIQ/integration_tests, pull requests merged in 2018-03, with the labels that each got.

#6689 [1LP][RFR] Adding Physical Servers Inventory API Tests
  cfme/common/provider.py
  cfme/physical/provider/lenovo.py
  cfme/tests/physical_infrastructure/api/test_physical_server_inventory_api.py
Labels: lint-ok, new-test-or-feature

#6754 [1LP][RFR] Fixed is_refreshed() for providers
  cfme/common/provider.py
Labels: fix-framework, lint-ok

#6736 [1LP][RFR] Add TemplateName class to cfme/utils/trackerbot
  cfme/utils/trackerbot.py
Labels: enhancement, infra-related, lint-ok

#6750 [1LP][RFR] Automate test hard reboot for azure
  cfme/cloud/instance/azure.py
  cfme/tests/cloud/test_instance_power_control.py
Labels: lint-ok, new-test-or-feature

#6746 [1LP][RFR] Fixing get_service fixture
  cfme/tests/cloud_infra_common/test_custom_attributes_rest.py
Labels: lint-ok

#6748 [1LP][RFR] New access control tests for user's groups editing
  cfme/tests/configure/test_rest_access_control.py
Labels: lint-ok, new-test-or-feature

#6740 [1LP][RFR] provider_type intergration to stabilize tests and scripts
  cfme/scripting/setup_env.py
  cfme/test_framework/sprout/client.py
  cfme/tests/test_db_migrate.py
  fixtures/appliance.py
Labels: enhancement, lint-ok

#6765 [1LP][RFR] Enhancements to test_provisioning_rest
  cfme/tests/infrastructure/test_provisioning_rest.py
Labels: WIP-testing, enhancement, lint-ok

#6757 [1LP][RFR] Add test for querying template attributes
  cfme/tests/infrastructure/test_rest_templates.py
Labels: lint-ok, new-test-or-feature

#6734 [1LP][RFR] Adds test_provider_options API test
  cfme/tests/cloud_infra_common/test_rest_providers.py
Labels: lint-ok, new-test-or-feature

#6715 [1LP][RFR] Metering Reports: Add support for storage metrics
  cfme/tests/intelligence/reports/test_metering_report.py
Labels: enhancement, lint-ok, new-test-or-feature

#6720 [1LP][RFR] New tests, enhancements and fixes in test_rest.py
  cfme/tests/test_rest.py
Labels: fix-test, lint-ok, new-test-or-feature

#6208 [1LP][RFR] Adding RHV tests for snapshots
  cfme/infrastructure/virtual_machines.py
  cfme/tests/infrastructure/test_snapshot.py
Labels: lint-ok, new-test-or-feature

#6752 [1LP][RFR] Enabled RHV provider for snapshots action test
  cfme/tests/control/test_actions.py
Labels: enhancement, lint-ok

#6779 [1LP][RFR] Extending clean_appliance.py
  scripts/clean_appliance.py
Labels: enhancement

#6770 [1LP][RFR] Added test_tagvis_network_provider_children
  cfme/tests/networks/test_tag_tagvis.py
Labels: new-test-or-feature

#6714 [1LP][RFR]Updating Console tests for SSUI to work with OSP
  cfme/tests/ssui/test_ssui_myservice.py
Labels: WIP-testing, lint-ok

#6787 [1LP][NOTEST][RFR] Adding Saved reports All Navigation View
  cfme/intelligence/reports/saved.py
Labels: fix-framework

#6781 [RFR][1LP] Added --no-quickstart flag for miq shell
  cfme/scripting/ipyshell.py
Labels: other

#6789 [1LP][WIPTEST]skip unsupported hardware warning during PXE provision
  data/rhel6.cfg
Labels: enhancement, tech-debt

#6607 [1LP][RFR] fixes for test_vm_reconfigure
  cfme/infrastructure/virtual_machines.py
  cfme/tests/infrastructure/test_vm_reconfigure.py
  widgetastic_manageiq/vm_reconfigure.py
Labels: WIP-testing, fix-test, lint-ok

#6774 [RFR][1LP] Use paramiko recv_ready as function
  cfme/utils/ssh.py
Labels: fix-framework

#6705 [1LP][RFR] Report coverage statistics to sonarqube
  scripts/coverage_report_jenkins.py
  scripts/coverage_report_sprout.py
Labels: enhancement, lint-ok

#6790 [RFR] Fixing test_providers_summary
  cfme/tests/intelligence/reports/test_canned_corresponds.py
Labels: fix-test

#6726 [RFR] GCE credentials for Ansible embedded
  cfme/ansible/credentials.py
  cfme/tests/ansible/test_embedded_ansible_basic.py
Labels: enhancement, lint-ok, new-test-or-feature

#6760 [RFR] Add support for RHEVM snapshots REST testing
  cfme/tests/cloud_infra_common/test_snapshots_rest.py
  cfme/utils/rest.py
Labels: lint-ok, new-test-or-feature

#6564 [RFR] Updates to cfme.tests.containers.test_manageiq_ansible_*
  cfme/tests/containers/test_manageiq_ansible_providers.py
  cfme/tests/containers/test_manageiq_ansible_tags.py
  cfme/tests/containers/test_manageiq_ansible_users.py
  cfme/tests/containers/test_tags.py
Labels: fix-test, lint-ok

#6777 [1LP][RFR]Updated test_sdn_crud and test_sdn_navigation
  cfme/tests/networks/test_sdn_crud.py
  cfme/tests/networks/test_sdn_navigation.py
Labels: fix-test

#6794 [WIPTEST] Turn the other two recv_ready()'s into functions
  cfme/utils/ssh.py
Labels: fix-framework

#6793 [RFR] Add BZ blocker for SCVMM chargeback tests
  cfme/tests/ssui/test_ssui_dashboard.py
Labels: fix-test

#6795 Revert "[RFR][1LP] Use paramiko recv_ready as function"
  cfme/utils/ssh.py
Labels: issue-bug, tech-debt

#6797 Revert changing paramiko recv_ready to function calls
  cfme/utils/ssh.py
Labels: issue-bug, tech-debt

#6776 [1LP][RFR] update network name locator to network_id on SubnetAddView
  cfme/networks/subnet.py
  cfme/networks/views.py
Labels: fix-locator-or-text

#6782 [RFR] update flash message of edit subnet
  cfme/networks/subnet.py
Labels: fix-framework

#6769 [RFR] sprout appliancepool->template_type migration
  sprout/appliances/api.py
  sprout/appliances/migrations/0045_appliancepool_template_type.py
  sprout/appliances/models.py
  sprout/appliances/views.py
Labels: enhancement

#6819 [1LP][RFR]Fix a typo
  cfme/tests/cloud/test_providers.py
Labels: fix-test

#6800 [1LP][RFR] exists() method converted to a property
  cfme/services/myservice/__init__.py
  cfme/services/myservice/ui.py
Labels: fix-framework

#6775 [1LP][RFR] Fixed Multiple requests error in ansible services tests
  cfme/ansible/repositories.py
  cfme/tests/ansible/test_embedded_ansible_services.py
Labels: fix-test

#6812 [RFR] items property replaced with fields
  cfme/tests/openstack/cloud/test_networks.py
Labels: fix-test

#6813 [1LP][RFR] removing is_container from Sprout->AppliancePool
  sprout/appliances/api.py
  sprout/appliances/migrations/0046_remove_appliancepool_is_container.py
  sprout/appliances/models.py
  sprout/appliances/tasks.py
  sprout/appliances/templates/appliances/my_appliances.html
  sprout/appliances/views.py
Labels: enhancement

#6708 [1LP][RFR] Fix for typo in sprout's poke_trackerbot
  sprout/appliances/models.py
  sprout/appliances/tasks.py
  sprout/appliances/templates/appliances/my_appliances.html
  sprout/appliances/views.py
  sprout/sprout/settings.py
Labels: lint-ok, new-test-or-feature

#6822 [1LP][RFR] make ip fields bigger in sprout in order to fit openshift hostnames
  sprout/appliances/migrations/0047_ipaddress_made_bigger.py
  sprout/appliances/models.py
Labels: fix-framework, infra-related

#6818 [1LP][RFR]Update summary for datastores
  cfme/infrastructure/datastore.py
Labels: fix-test

#6605 [1LP][RFR] Changed event_streams db calls to rest calls
  cfme/tests/integration/__init__.py
  cfme/utils/appliance/__init__.py
  cfme/utils/events.py
  cfme/utils/events_db.py
  fixtures/events.py
Labels: enhancement, lint-ok

#6783 [1LP][RFR] Stabilization fix to test_db_restore
  cfme/tests/test_db_restore.py
  fixtures/appliance.py
Labels: fix-test

#6825 [RFR] openshift_project field doesn't fit real project name
  sprout/appliances/migrations/0048_openshift_project_made_bigger.py
  sprout/appliances/models.py
Labels: fix-framework, infra-related

#6791 [1LP][RFR]parametrizing test_customization_template_crud
  cfme/tests/infrastructure/test_customization_template.py
Labels: enhancement

#6677 [1LP][RFR]last_message update
  cfme/services/requests.py
  cfme/tests/cloud/test_provisioning.py
  cfme/tests/infrastructure/test_provisioning.py
  cfme/tests/infrastructure/test_provisioning_dialog.py
  cfme/tests/infrastructure/test_provisioning_rest.py
  cfme/tests/infrastructure/test_vm_clone.py
  cfme/tests/infrastructure/test_vm_migrate.py
  cfme/tests/services/test_cloud_service_catalogs.py
  cfme/tests/services/test_config_provider_servicecatalogs.py
  cfme/tests/services/test_different_dialogs_in_catalogs.py
  cfme/tests/services/test_generic_service_catalogs.py
  cfme/tests/services/test_iso_service_catalogs.py
  cfme/tests/services/test_myservice.py
  cfme/tests/services/test_provision_stack.py
  cfme/tests/services/test_pxe_service_catalogs.py
  cfme/tests/services/test_service_catalogs.py
Labels: fix-framework, lint-ok

#6823 [1LP][RFR]fixes for vm_reconfigure
  cfme/infrastructure/virtual_machines.py
  cfme/tests/infrastructure/test_vm_reconfigure.py
Labels: fix-test

#6820 [1LP][RFR] Added full_template_vm fixture
  cfme/fixtures/vm.py
  cfme/test_framework/pytest_plugin.py
  cfme/tests/ansible/test_embedded_ansible_actions.py
  cfme/tests/ansible/test_embedded_ansible_automate.py
  cfme/tests/control/test_alerts.py
Labels: enhancement

#6788 [1LP][RFR] Removed vm/host_rising in test_utilization_metrics.
  cfme/tests/test_utilization_metrics.py
Labels: fix-test

#6799 [1LP][RFR] Add Nuage to the RECOGNIZED_BY_CREDS list
  cfme/networks/provider/__init__.py
  cfme/networks/provider/nuage.py
  cfme/utils/appliance/__init__.py
Labels: enhancement

#6805 [1LP][RFR] New db ui test
  cfme/base/ui.py
  cfme/tests/configure/test_database_ui.py
Labels: new-test-or-feature

#6758 [1LP][RFR] Adding test_provision_emails
  cfme/tests/infrastructure/test_provisioning_rest.py
Labels: lint-ok, new-test-or-feature

#6729 [1LP][RFR] Refactored test_provision_stack.py
  cfme/services/catalogs/orchestration_template.py
  cfme/services/requests.py
  cfme/services/service_catalogs/ui.py
  cfme/tests/services/test_provision_stack.py
Labels: fix-test, lint-ok

#6816 [RFR] Make ssh.py's run_command work for all programs
  cfme/utils/ssh.py
Labels: enhancement

#6836 [1LP][RFR] Add browser refresh to provider 'All' resetters
  cfme/cloud/provider/__init__.py
  cfme/infrastructure/provider/__init__.py
Labels: enhancement

#6638 [1LP][RFR] mark rhv tiers
  cfme/tests/automate/test_buttons.py
  cfme/tests/automate/test_common_methods.py
  cfme/tests/cloud_infra_common/test_custom_attributes_rest.py
  cfme/tests/cloud_infra_common/test_discovery.py
  cfme/tests/cloud_infra_common/test_events.py
  cfme/tests/cloud_infra_common/test_html5_vm_console.py
  cfme/tests/cloud_infra_common/test_power_control_rest.py
  cfme/tests/cloud_infra_common/test_rest_providers.py
  cfme/tests/cloud_infra_common/test_retirement.py
  cfme/tests/cloud_infra_common/test_tag_visibility.py
  cfme/tests/cloud_infra_common/test_vm_ownership.py
  cfme/tests/control/test_actions.py
  cfme/tests/control/test_alerts.py
  cfme/tests/infrastructure/test_host.py
  cfme/tests/infrastructure/test_host_analysis.py
  cfme/tests/infrastructure/test_host_drift_analysis.py
  cfme/tests/infrastructure/test_individual_host_creds.py
  cfme/tests/infrastructure/test_iso_datastore.py
  cfme/tests/infrastructure/test_iso_provisioning.py
  cfme/tests/infrastructure/test_providers.py
  cfme/tests/infrastructure/test_provisioning.py
  cfme/tests/infrastructure/test_provisioning_dialog.py
  cfme/tests/infrastructure/test_provisioning_rest.py
  cfme/tests/infrastructure/test_pxe_provisioning.py
  cfme/tests/infrastructure/test_quota_tagging.py
  cfme/tests/infrastructure/test_snapshot.py
  cfme/tests/infrastructure/test_tenant_quota.py
  cfme/tests/infrastructure/test_timelines.py
  cfme/tests/infrastructure/test_vm_migrate.py
  cfme/tests/infrastructure/test_vm_power_control.py
  cfme/tests/infrastructure/test_vm_reconfigure.py
  cfme/tests/intelligence/reports/test_canned_corresponds.py
  cfme/tests/intelligence/reports/test_validate_chargeback_report.py
  cfme/tests/intelligence/reports/test_views.py
  cfme/tests/services/test_different_dialogs_in_catalogs.py
  cfme/tests/services/test_iso_service_catalogs.py
  cfme/tests/services/test_pxe_service_catalogs.py
  cfme/tests/services/test_service_catalogs.py
  cfme/tests/services/test_service_manual_approval.py
  cfme/tests/ssui/test_ssui_myservice.py
  cfme/tests/test_utilization_metrics.py
Labels: WIP, lint-ok, needs-rebase

#6809 [DOC][RFR][NOTEST] Sprout - Remove misleading files and make a handy deployment documentation
  sprout/.env
  sprout/README.rst
  sprout/setup.sh
  sprout/sprout.sh
Labels: doc, enhancement, infra-related

#5718 [1LP][RFR] Added test test_control_import_existing_policies
  cfme/control/explorer/policy_profiles.py
  cfme/tests/control/test_import_policies.py
Labels: lint-ok, new-test-or-feature

#6832 [1LP][RFR] fixed pv script which in some cases removed wrong pv paths
  scripts/openshift/add_remove_persistent_volumes.sh
Labels: infra-related

#6632 [1LP][RFR] Add providers and rename tests
  cfme/networks/views.py
  cfme/tests/networks/test_sdn_balancers.py
  cfme/tests/networks/test_sdn_crud.py
  cfme/tests/networks/test_sdn_downloads.py
  cfme/tests/networks/test_sdn_navigation.py
  cfme/tests/networks/test_sdn_ports.py
Labels: WIP, enhancement, lint-ok

#6643 [1LP][RFR]Added test_tagvis_provider_children for cloud and infra
  cfme/cloud/tenant.py
  cfme/tests/cloud_infra_common/test_relationships.py
Labels: lint-ok, new-test-or-feature

#6764 [1LP][RFR] apply the python modernize import fixer for six
  cfme/test_framework/appliance.py
  cfme/test_framework/sprout/plugin.py
  cfme/tests/configure/test_db_backup_schedule.py
  cfme/tests/distributed/test_appliance_replication.py
  cfme/utils/appliance/__init__.py
  cfme/utils/blockers.py
  cfme/utils/dockerbot/dockerbot.py
  cfme/utils/tests/test_ipappliance.py
  cfme/utils/trackerbot.py
  fixtures/browser.py
  scripts/coverage_report_jenkins.py
  scripts/install_vddk.py
  scripts/template_upload_all.py
  sprout/appliances/models.py
  sprout/appliances/views.py
  sprout/logserver.py
  sprout/sprout/__init__.py
Labels: enhancement, lint-ok

#6761 [1LP][RFR] New test_embedded_ansible_custom_button
  cfme/automate/buttons.py
  cfme/tests/ansible/test_embedded_ansible_automate.py
Labels: WIP-testing, lint-ok, new-test-or-feature

#6842 [1LP][RFR] New test added for checking repos
  cfme/tests/configure/test_register_appliance.py
Labels: new-test-or-feature

#6855 [RFR] Bump wrapanapi for pyvcloud fix
  requirements/frozen.txt
Labels: fix-framework

#6852 [1LP][RFR] Adding support for is_displayed for ParametrizedSummaryTable
  widgetastic_manageiq/__init__.py
Labels: enhancement

#6841 [1LP][RFR] fixed test templates test
  cfme/tests/openstack/infrastructure/test_relationships.py
Labels: fix-test

#6851 [1LP][RFR] New db maintenance and time/date tests
  cfme/tests/cli/test_appliance_console.py
Labels: new-test-or-feature

#6811 [1LP][RFR] Turn eventing ON for Nuage provider
  cfme/networks/provider/__init__.py
  cfme/networks/provider/nuage.py
  cfme/networks/views.py
  cfme/tests/networks/test_network_providers.py
  conf/cfme_data.yaml.template
  conf/credentials.yaml.template
Labels: enhancement

#6785 [1LP][RFR] Adding Physical Server API tests
  cfme/tests/physical_infrastructure/api/test_physical_server_api.py
Labels: new-test-or-feature

#6856 [1LP][RFR] Added new appliance console cli tests
  cfme/fixtures/cli.py
  cfme/tests/cli/test_appliance_cli.py
  cfme/tests/cli/test_appliance_console.py
Labels: new-test-or-feature

#6792 [1LP][RFR] Make coverage_merger.rb not replicate file data anymore
  scripts/coverage_report_jenkins.py
  scripts/data/coverage/coverage_merger.rb
Labels: enhancement, infra-related

#6773 [1LP][RFR] Added cloud support for service catalogs and some refactoring
  cfme/fixtures/service_fixtures.py
  cfme/fixtures/vm_name.py
  cfme/services/service_catalogs/__init__.py
  cfme/services/service_catalogs/ssui.py
  cfme/services/service_catalogs/ui.py
  cfme/tests/ssui/test_ssui_dashboard.py
  cfme/tests/ssui/test_ssui_myservice.py
  cfme/tests/ssui/test_ssui_service_catalogs.py
Labels: enhancement

#6780 [1LP][RFR]New test_advanced_search_registry_element
  cfme/base/ui.py
  cfme/services/workloads.py
  cfme/tests/services/test_service_catalogs.py
Labels: new-test-or-feature

#6858 [1LP][RFR] Slight improvement of SelectTable
  cfme/common/vm_views.py
Labels: enhancement

#6838 [1LP][RFR] image_upload_glance : Add image location url
  scripts/image_upload_glance.py
Labels: enhancement, infra-related

#5762 [1LP][WIPTEST] Refactor user settings
  cfme/base/ui.py
  cfme/cloud/availability_zone.py
  cfme/cloud/flavor.py
  cfme/cloud/instance/__init__.py
  cfme/common/host_views.py
  cfme/configure/access_control/__init__.py
  cfme/configure/settings.py
  cfme/infrastructure/config_management.py
  cfme/infrastructure/datastore.py
  cfme/services/catalogs/catalog.py
  cfme/services/myservice/ui.py
  cfme/services/workloads.py
  cfme/tests/configure/test_default_filters.py
  cfme/tests/configure/test_default_views_cloud.py
  cfme/tests/configure/test_default_views_infra.py
  cfme/tests/configure/test_display_settings.py
  cfme/tests/configure/test_timeprofile.py
  cfme/tests/configure/test_visual_cloud.py
  cfme/tests/configure/test_visual_infra.py
  cfme/tests/containers/test_start_page.py
  cfme/tests/containers/test_table_views.py
  cfme/tests/services/test_config_provider_servicecatalogs.py
  cfme/tests/services/test_provision_stack.py
Labels: enhancement, lint-ok, widgetastic-conversion

#6804 [1LP][RFR] Adding new test case related to relationship discovery
  cfme/tests/cloud_infra_common/test_relationships.py
Labels: lint-ok, new-test-or-feature

#6817 [1LP][RFR] Metering Reports: Support for cloud providers
  cfme/tests/intelligence/reports/test_metering_report.py
Labels: lint-ok, new-test-or-feature

#6844 [1LP][RFR] Refactor get_yaml_config/set_yaml_config for REST
  cfme/base/__init__.py
  cfme/utils/appliance/__init__.py
Labels: enhancement, lint-ok

#6868 [1LP][RFR] simplify the uses markers
  markers/uses.py
Labels: enhancement, lint-ok

#6867 [1LP][RFR] Check that API response contains data
  cfme/utils/rest.py
Labels: enhancement, lint-ok

#6815 [1LP][RFR] Update CMQE tests to use the new parametized summary table
  cfme/tests/containers/test_containers_summary.py
  cfme/tests/containers/test_static_custom_attributes.py
Labels: enhancement, lint-ok

#6833 [1LP][RFR] Added test_ansible_group_id_in_payload
  cfme/tests/ansible/test_embedded_ansible_services.py
Labels: lint-ok, new-test-or-feature

#6749 [1LP][RFR] Add support for adding a user to multiple RBAC groups
  cfme/base/login.py
  cfme/configure/access_control/__init__.py
  cfme/fixtures/tag.py
  cfme/tests/cloud_infra_common/test_vm_ownership.py
  cfme/tests/configure/test_access_control.py
  cfme/tests/intelligence/reports/test_metering_report.py
  cfme/tests/intelligence/reports/test_validate_chargeback_report.py
Labels: WIP-testing, lint-ok, new-test-or-feature

#6814 [1LP][RFR] Add appliance methods for querying/modifying disabled regions
  cfme/cloud/provider/azure.py
  cfme/cloud/provider/ec2.py
  cfme/cloud/provider/gce.py
  cfme/cloud/provider/openstack.py
  cfme/common/provider.py
  cfme/containers/provider/kubernetes.py
  cfme/containers/provider/openshift.py
  cfme/infrastructure/provider/rhevm.py
  cfme/infrastructure/provider/scvmm.py
  cfme/infrastructure/provider/virtualcenter.py
  cfme/networks/provider/nuage.py
  cfme/physical/provider/lenovo.py
  cfme/tests/cloud/test_providers.py
  cfme/utils/appliance/__init__.py
  fixtures/provider.py
Labels: enhancement, fix-test, lint-ok

#6802 [1LP][RFR] Make `summary("Relationships")` great again for NetworkManagers
  cfme/networks/views.py
Labels: fix-framework, lint-ok, tech-debt

#6694 [WIP][NOTEST][1LP] Sprout - UI for resolving stuck templates
  sprout/appliances/models.py
  sprout/appliances/tasks.py
  sprout/appliances/templates/appliances/template_conf.html
  sprout/appliances/templates/base.html
  sprout/appliances/urls.py
  sprout/appliances/views.py
Labels: WIP, lint-ok

#6860 [WIP][1LP][NOTEST] Sprout - Bulk template delete
  sprout/appliances/templates/appliances/templates.html
  sprout/appliances/urls.py
  sprout/appliances/views.py
Labels: WIP, lint-ok

#6821 [1LP][RFR] Blocking test_snapshot_crud for RHV
  cfme/tests/infrastructure/test_snapshot.py
Labels: fix-test, lint-ok

#6834 [1LP][RFR] Unblocking test_verify_revert_snapshot
  cfme/tests/infrastructure/test_snapshot.py
Labels: fix-test, lint-ok

#6824 [1LP][RFR] Uncollecting test_vm_console for RHV-CFME integration
  cfme/tests/ssui/test_ssui_myservice.py
Labels: fix-test, lint-ok

#6837 [1LP][RFR] Expect 200 or 204 from a REST DELETE, change to using assert_response() in most places
  cfme/tests/cloud/test_providers.py
  cfme/tests/configure/test_tag_category.py
  cfme/tests/infrastructure/test_provisioning_rest.py
  cfme/tests/infrastructure/test_vm_ownership.py
  cfme/tests/infrastructure/test_vm_retirement_rest.py
  cfme/tests/intelligence/reports/test_crud.py
  cfme/tests/intelligence/test_chargeback.py
  cfme/tests/perf/workloads/test_provisioning.py
  cfme/tests/services/test_generic_service_catalogs.py
  cfme/tests/services/test_service_catalogs.py
  cfme/utils/rest.py
Labels: lint-ok

#6704 [1LP][RFR] Update all Method to allow Querying of All, Active, or Archived DB Entries
  cfme/containers/container.py
  cfme/containers/image.py
  cfme/containers/node.py
  cfme/containers/pod.py
  cfme/containers/project.py
Labels: enhancement, lint-ok

#6830 [1LP][RFR] Added test_alert_run_ansible_playbook
  cfme/control/explorer/alerts.py
  cfme/tests/ansible/test_embedded_ansible_automate.py
Labels: lint-ok, new-test-or-feature

#6873 [1LP][RFR] Chargeback cost validation : some code refactoring
  cfme/tests/intelligence/reports/test_validate_chargeback_report.py
Labels: enhancement, lint-ok

#6880 [1LP][RFR] Add appliance_log_collector plugin
  cfme/test_framework/appliance_log_collector.py
  cfme/test_framework/pytest_plugin.py
Labels: enhancement, lint-ok

#6863 [1LP][RFR] Update project_key to match what Central CI wants for their sonarqube
  scripts/coverage_report_jenkins.py
Labels: enhancement, lint-ok

#6888 [1LP][RFR] remove iteritems from the framework
  cfme/ansible/credentials.py
  cfme/common/provider.py
  cfme/control/explorer/policies.py
  cfme/exceptions.py
  cfme/infrastructure/virtual_machines.py
  cfme/metaplugins/blockers.py
  cfme/test_framework/pytest_plugin.py
  cfme/utils/__init__.py
  cfme/utils/appliance/__init__.py
  cfme/utils/browser.py
  cfme/utils/category.py
  cfme/utils/smem_memory_monitor.py
  cfme/utils/units.py
  cfme/utils/update.py
Labels: enhancement, lint-ok

#6455 [1LP][RFR] move markers to cfme.markers
  cfme/markers/__init__.py
  cfme/markers/composite.py
  cfme/markers/crud.py
  cfme/markers/env.py
  cfme/markers/env_markers/__init__.py
  cfme/markers/env_markers/provider.py
  cfme/markers/fixtureconf.py
  cfme/markers/manual.py
  cfme/markers/meta.py
  cfme/markers/polarion.py
  cfme/markers/requires.py
  cfme/markers/rhv.py
  cfme/markers/sauce.py
  cfme/markers/skipper.py
  cfme/markers/smoke.py
  cfme/markers/stream_excluder.py
  cfme/markers/uncollect.py
  cfme/markers/uses.py
  cfme/metaplugins/blockers.py
  cfme/metaplugins/server_roles.py
  cfme/test_framework/pytest_plugin.py
  cfme/tests/ansible/test_embedded_ansible_actions.py
  cfme/tests/ansible/test_embedded_ansible_automate.py
  cfme/tests/automate/test_buttons.py
  cfme/tests/cloud/test_cloud_timelines.py
  cfme/tests/cloud_infra_common/test_genealogy.py
  cfme/tests/cloud_infra_common/test_html5_vm_console.py
  cfme/tests/cloud_infra_common/test_relationships.py
  cfme/tests/cloud_infra_common/test_retirement.py
  cfme/tests/control/test_alerts.py
  cfme/tests/infrastructure/test_ssa_vddk.py
  cfme/tests/infrastructure/test_timelines.py
  cfme/tests/infrastructure/test_webmks_console.py
  cfme/tests/networks/test_tag_tagvis.py
  cfme/tests/perf/workloads/test_memory_leak.py
  cfme/tests/ssui/test_ssui_myservice.py
  cfme/tests/ssui/test_ssui_service_catalogs.py
  cfme/utils/apidoc.py
  fixtures/artifactor_plugin.py
  markers/__init__.py
Labels: enhancement, lint-ok

#6036 [1LP][RFR] Storage Volume Snapshot Model page [WT + Collection]
  cfme/exceptions.py
  cfme/storage/volume.py
  cfme/storage/volume_snapshot.py
  cfme/tests/storage/test_volume_snapshot.py
  setup.py
Labels: lint-ok, new-test-or-feature

#6887 [RFR] Get yaml config doesn't work on 5.8
  cfme/base/__init__.py
  cfme/utils/appliance/__init__.py
Labels: fix-framework, lint-ok

#6759 [1LP][RFR] Services catalog collections
  cfme/fixtures/service_fixtures.py
  cfme/rest/gen_data.py
  cfme/services/catalogs/catalog.py
  cfme/tests/ansible/test_embedded_ansible_services.py
  cfme/tests/services/test_catalog.py
  cfme/tests/services/test_different_dialogs_in_catalogs.py
  cfme/tests/services/test_dynamicdd_dialogelement.py
  cfme/tests/services/test_provision_stack.py
  cfme/tests/services/test_rest_services.py
  setup.py
Labels: WIP-testing, collections-conversion, lint-ok

#6878 [1LP][RFR] make embedded ansible tests work against pod appliance
  cfme/tests/ansible/test_embedded_ansible_crud.py
  cfme/utils/appliance/__init__.py
  cfme/utils/ssh.py
Labels: enhancement, lint-ok

#6882 [1LP][RFR] New API tests for checking collection actions
  cfme/tests/test_rest.py
Labels: lint-ok, new-test-or-feature

#6896 [1LP][RFR] Service start/stop
  cfme/services/myservice/__init__.py
  cfme/services/myservice/ssui.py
  cfme/tests/ssui/test_ssui_myservice.py
Labels: enhancement, lint-ok

#6892 [1LP][RFR] simplify utils.bz and remove itervalues usage
  cfme/utils/bz.py
Labels: enhancement, lint-ok

#6857 [1LP][RFR] Orchestration template collection
  cfme/services/catalogs/orchestration_template.py
  cfme/tests/services/test_orchestration_template.py
  cfme/tests/services/test_provision_stack.py
  setup.py
Labels: collections-conversion, lint-ok

#6884 [1LP][RFR] move various fixtures to cfme/fixtures
  cfme/fixtures/version_info.py
  cfme/fixtures/video.py
  cfme/fixtures/virtual_machine.py
  cfme/fixtures/widgets.py
  cfme/fixtures/xunit_tools.py
  cfme/test_framework/pytest_plugin.py
  cfme/tests/cloud/test_instance_power_control.py
  fixtures/version_file.py
Labels: enhancement, lint-ok

#6885 [1LP][RFR] Storage manager tag and remove tests
  cfme/storage/manager.py
  cfme/tests/storage/test_manager.py
Labels: lint-ok, new-test-or-feature

#6116 [1LP][RFR] Adds events API tests to Lenovo provider
  cfme/tests/physical_infrastructure/api/test_physical_server_events_api.py
Labels: lint-ok, new-test-or-feature

#6872 [1LP][RFR] SSA on VM via System Schedule.
  cfme/configure/configuration/system_schedules.py
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
Labels: lint-ok, new-test-or-feature

#6883 [1LP][RFR] Refactor Volume tests
  cfme/storage/volume.py
  cfme/tests/storage/test_volume.py
Labels: enhancement, lint-ok

#6891 [RFR] Remove is_refreshed method from OpenShiftProvider class
  cfme/containers/provider/openshift.py
Labels: enhancement, lint-ok

#6707 [WIP][RFR] Add pre-setup step for openshift provider with alert endpoint
  cfme/common/provider.py
  cfme/containers/provider/__init__.py
  cfme/containers/provider/openshift.py
  cfme/control/explorer/alert_profiles.py
  cfme/tests/containers/test_alerts.py
Labels: WIP, enhancement, lint-ok, new-test-or-feature

#6875 [1LP][RFR][NOTEST]Widgetastic version 0.20.4 had some issues in def classes in browser.py, fixed in latest version
  requirements/frozen.txt
Labels: lint-ok, other

#6894 [1LP][RFR]Rename WidgetasticTaggable to Taggable
  cfme/cloud/availability_zone.py
  cfme/cloud/flavor.py
  cfme/cloud/keypairs.py
  cfme/cloud/stack.py
  cfme/cloud/tenant.py
  cfme/common/__init__.py
  cfme/common/provider.py
  cfme/common/vm.py
  cfme/containers/container.py
  cfme/containers/image.py
  cfme/containers/image_registry.py
  cfme/containers/node.py
  cfme/containers/pod.py
  cfme/containers/project.py
  cfme/containers/replicator.py
  cfme/containers/route.py
  cfme/containers/service.py
  cfme/containers/template.py
  cfme/containers/volume.py
  cfme/infrastructure/cluster.py
  cfme/infrastructure/config_management.py
  cfme/infrastructure/datastore.py
  cfme/infrastructure/host.py
  cfme/infrastructure/resource_pool.py
  cfme/networks/balancer.py
  cfme/networks/cloud_network.py
  cfme/networks/floating_ips.py
  cfme/networks/network_port.py
  cfme/networks/network_router.py
  cfme/networks/provider/__init__.py
  cfme/networks/security_group.py
  cfme/networks/subnet.py
  cfme/physical/physical_server.py
  cfme/services/catalogs/ansible_catalog_item.py
  cfme/services/catalogs/catalog.py
  cfme/services/catalogs/catalog_item.py
  cfme/services/catalogs/orchestration_template.py
  cfme/services/myservice/__init__.py
  cfme/services/service_catalogs/__init__.py
  cfme/storage/manager.py
  cfme/storage/object_store_container.py
  cfme/storage/object_store_object.py
  cfme/storage/volume_backup.py
  cfme/storage/volume_snapshot.py
Labels: enhancement, lint-ok

#6849 [1LP][RFR] Add new test to check cockpit 'Web Console' button enable and disable working
  cfme/cloud/instance/__init__.py
  cfme/tests/cloud_infra_common/test_cockpit_server.py
Labels: lint-ok, new-test-or-feature

#6902 [RFR] Wrapanapi 2.8.4
  requirements/frozen.txt
Labels: lint-ok, other

#6897 [1LP][RFR] Mitigate the bug in CFME where symbols are converted to strings by REST
  cfme/tests/configure/test_ntp_server.py
  cfme/tests/control/test_alerts.py
  cfme/utils/appliance/__init__.py
  cfme/utils/perf.py
Labels: lint-ok

#6905 [1LP][RFR] essential params for openshift appliance serialization
  sprout/appliances/models.py
Labels: lint-ok

#6895 [1LP][RFR] openshift support in clone template
  cfme/utils/appliance/__init__.py
  scripts/clone_template.py
Labels: infra-related, lint-ok

#6900 [1LP][RFR] Fixed configure_fleecing fixture in test_alerts.py
  cfme/tests/control/test_alerts.py
Labels: fix-test, lint-ok

#6917 [1LP][RFR] Updating test to use asset_detail
  cfme/tests/physical_infrastructure/api/test_physical_server_inventory_api.py
Labels: fix-test, lint-ok

#6906 [1LP][RFR] Remove BZ 1502609 blocker pytest.mark from volume tests
  cfme/tests/openstack/cloud/test_volumes.py
Labels: fix-test, lint-ok

#6908 [1LP][RFR] remove BZ, fix test
  cfme/tests/networks/test_sdn_balancers.py
Labels: fix-test, lint-ok

#6920 [1LP][RFR] Added missing import
  cfme/tests/cloud_infra_common/test_relationships.py
Labels: fix-test, lint-ok

#6927 [1LP][RFR] Wrap appliance log tarring, catch errors
  cfme/test_framework/appliance_log_collector.py
Labels: lint-ok, rc-regression-fix

#6912 [1LP][RFR]Implementing fix landing_page related failures
  cfme/tests/configure/test_landing_page.py
Labels: fix-test, lint-ok, rc-regression-fix

#6915 [1LP][RFR] Moved the setup_provider first in the fixture list
  cfme/tests/services/test_add_remove_vm_to_service.py
  cfme/tests/services/test_different_dialogs_in_catalogs.py
  cfme/tests/services/test_myservice.py
  cfme/tests/services/test_service_catalogs.py
  cfme/tests/services/test_service_manual_approval.py
Labels: enhancement, lint-ok

#6914 [1LP][RFR] Update cleanup_old_vms, use ProviderFilter
  scripts/cleanup_old_vms.py
  scripts/list_provider_vms.py
Labels: WIP-testing, enhancement, infra-related, lint-ok

#6910 [1LP][RFR] Update SSL test to support any metrics type
  cfme/tests/containers/test_ssl_providers.py
Labels: lint-ok, rc-regression-fix

#6907 [1LP][RFR] fixed provider test_api_port test
  cfme/tests/openstack/infrastructure/test_provider.py
Labels: fix-test, lint-ok

#6919 [RFR] PR 5762 corrections
  cfme/services/myservice/ui.py
  cfme/services/service_catalogs/ui.py
  cfme/tests/services/test_myservice.py
Labels: lint-ok

#6938 [1LP][RFR] fix for check whether supervisord is running in pod appliance
  cfme/utils/appliance/__init__.py
Labels: fix-framework, lint-ok

#6939 [1LP][RFR] fix for template clone script
  scripts/clone_template.py
Labels: infra-related, lint-ok

#6937 [1LP][RFR] Bump dump2polarion version to v0.20
  requirements/frozen.txt
Labels: infra-related, lint-ok

#6935 [1LP][RFR] widgetastic.patternfly version update
  requirements/frozen.txt
Labels: fix-framework, lint-ok

#6932 [1LP][RFR] Wrapping test_ssa_vm with BZ
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
Labels: fix-test

#6928 [1LP][RFR] Filter azure out of test_reset_vm, azure doesn't support hard reset
  cfme/tests/cloud_infra_common/test_power_control_rest.py
Labels: fix-framework, lint-ok

#6869 [1LP][RFR] Add OpenstackNodeCollection to fix host lifecycle tests
  cfme/infrastructure/openstack_node.py
  cfme/tests/openstack/infrastructure/test_host_lifecycle.py
  setup.py
Labels: enhancement, lint-ok

#6766 [1LP][RFR] Introducing other providers for test case in test_relationship.py
  cfme/infrastructure/virtual_machines.py
  cfme/tests/cloud_infra_common/test_relationships.py
Labels: enhancement, lint-ok

#6940 [1LP][RFR] Fixed docs
  cfme/automate/dialog_element.py
  cfme/automate/dialogs/dialog_element.py
  cfme/common/__init__.py
  cfme/configure/access_control/__init__.py
  cfme/containers/image.py
  cfme/infrastructure/datastore.py
  cfme/storage/volume_backup.py
  cfme/test_framework/appliance_log_collector.py
  cfme/utils/auth/__init__.py
  cfme/utils/dockerbot/build-container.py
  cfme/utils/dockerbot/build_container.py
  cfme/utils/dockerbot/pytestbase/get_keys.py
  cfme/utils/dockerbot/pytestbase/post_result.py
  cfme/utils/dockerbot/pytestbase/verify_commit.py
  cfme/utils/events_db.py
  cfme/utils/rest.py
  cfme/utils/trackerbot.py
  docs/conf.py
  docs/guides/browser_configuration.rst
  docs/guides/newprovider.rst
  docs/modules.rst
  fixtures/ui_coverage.py
  requirements/frozen.txt
  requirements/frozen_docs.txt
Labels: lint-ok

#6916 [1LP][RFR] Add ability to aggregate coverage from multiple jenkins jobs
  scripts/coverage_report_jenkins.py
  scripts/coverage_report_sprout.py
Labels: enhancement, lint-ok

#6881 [1LP][RFR] Making sure SSUI Tests are not skipped
  cfme/fixtures/service_fixtures.py
  cfme/tests/ssui/test_ssui_myservice.py
Labels: fix-test, lint-ok

#6893 [1LP][RFR]Update access_control.py to use WidgetasticTaggable Class
  cfme/common/__init__.py
  cfme/configure/access_control/__init__.py
  cfme/tests/configure/test_access_control.py
Labels: enhancement, lint-ok

#6901 [1LP][RFR] Add missing API collections
  cfme/tests/test_rest.py
Labels: lint-ok, new-test-or-feature

#6929 [1LP][RFR] Tweak base login and ui for exception handling
  cfme/base/login.py
  cfme/base/ui.py
Labels: fix-framework, lint-ok
