Repository ManageIQ/integration_tests, pull requests merged in 2018-05, with the labels that each got.

#7176 [1LP][RFR] Update dump2polarion version to 0.23
  requirements/frozen.txt
  requirements/frozen_docs.txt
Labels: infra-related, lint-ok

#7149 [1LP][RFR] Adding VM hot reconfigure tests
  cfme/tests/infrastructure/test_vm_reconfigure.py
Labels: lint-ok

#7079 [1LP][RFR] Metrics tests for OpenShift provider
  cfme/containers/provider/__init__.py
  cfme/containers/provider/openshift.py
  cfme/tests/containers/test_basic_metrics.py
  scripts/openshift/change_metrics_collection_threshold.rb
Labels: lint-ok, new-test-or-feature

#7182 [RFR] Fixed a typo in the providers
  cfme/cloud/provider/vcloud.py
  cfme/networks/provider/nuage.py
Labels: fix-framework

#7185 [RFR] Updated wrapanapi to 2.8.10
  requirements/frozen.txt
Labels: other

#7178 [1LP][RFR][notest] quickstart RHEL7 debuginfo-install fix
  cfme/scripting/quickstart.py
Labels: issue-bug, lint-ok, other

#7186 [RFR] add logging and retry for enable/disable provider check in sprout
  sprout/appliances/tasks.py
Labels: enhancement, lint-ok, sprout

#7196 [RFR] new wrapanapi version
  requirements/frozen.txt
Labels: lint-ok, other

#7188 [RFR] use a list comprehension instead of a lambda map for log sessionfinish
  fixtures/log.py
Labels: fix-framework, lint-ok

#7194 [RFR][1LP] fix up types in utils.providers
  cfme/utils/providers.py
Labels: fix-framework, lint-ok

#7190 [RFR] fix relative import in cfme/control/explorer/policies.py
  cfme/control/explorer/policies.py
Labels: fix-framework, lint-ok

#7191 [RFR] artifactor client dummy nonzero - py3k
  fixtures/artifactor_plugin.py
Labels: fix-framework, lint-ok

#7192 [1LP][RFR] fix size changed while iteration in provider.all_types
  cfme/common/provider.py
Labels: fix-framework, lint-ok

#7193 [RFR] fix relative import in parallelizer
  fixtures/parallelizer/__init__.py
Labels: fix-framework, lint-ok

#7195 [RFR][NOTEST] add missing deps to requirement templates
  requirements/template_docs.txt
Labels: fix-framework, lint-ok

#7201 [1LP][RFR] use self.appliance instead of current_appliance in myservice/ui
  cfme/services/myservice/ui.py
Labels: fix-framework, lint-ok

#7202 [1LP][RFR] use find_appliance in blockers metaplugin
  cfme/metaplugins/blockers.py
Labels: lint-ok

#7199 [1LP][RFR] use find_appliance in markers.uncollect
  cfme/markers/uncollect.py
Labels: enhancement, fix-framework, lint-ok

#7204 [1LP][RFR] use find_appliance in test_aws_iam_auth_and_roles.py
  cfme/tests/integration/test_aws_iam_auth_and_roles.py
Labels: fix-framework, lint-ok

#7206 [1LP][RFR] use find_appliance in test_appliance_update
  cfme/tests/cli/test_appliance_update.py
Labels: lint-ok

#7207 [1LP][RFR] fix up appliance fetching in appliance script
  cfme/scripting/appliance.py
Labels: fix-framework, lint-ok

#7177 [1LP][RFR] Containers images collection,add ability to filter active images from redHat registry
  cfme/containers/image.py
  cfme/tests/containers/test_containers_smartstate_analysis_multiple_images.py
Labels: lint-ok

#7171 [1LP][RFR] Host Utilization for recent hr
  cfme/common/candu_views.py
  cfme/infrastructure/host.py
  cfme/tests/candu/test_host_graph.py
Labels: lint-ok, new-test-or-feature

#7197 [1LP][RFR] two more manual pod appliance test cases
  cfme/tests/pod/test_appliance_crud.py
Labels: lint-ok

#7205 [RFR] use find_appliance in server roles metaplugin
  cfme/metaplugins/server_roles.py
Labels: lint-ok

#7203 [1LP][RFR] remove unused import in test_docs
  cfme/tests/configure/test_docs.py
Labels: fix-test, lint-ok

#6972 [HOLD] Clean out many get_or_create_current_appliance usages
  cfme/tests/configure/test_docs.py
Labels: lint-ok

#7211 [1LP][RFR] run travis on py3
  .travis.yml
Labels: lint-ok

#7215 [1LP][RFR] uncollect scvmm for chargeback and metering reports
  cfme/tests/intelligence/reports/test_metering_report.py
  cfme/tests/intelligence/reports/test_validate_chargeback_report.py
Labels: lint-ok

#7213 [1LP][RFR] Check DEBUG_INSTALL_COMMAND before adding sudo
  cfme/scripting/quickstart.py
Labels: issue-bug, lint-ok, other

#7135 [1LP][RFR] support for freezing on python3 and python2
  cfme/scripting/quickstart.py
  requirements/freeze.py
  requirements/freeze_all.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
  requirements/frozen_docs.txt
  requirements/template_docs.txt
Labels: enhancement, lint-ok

#7224 [1LP][RFR] Fixed appliance holder
  cfme/test_framework/appliance.py
Labels: fix-framework, lint-ok

#7226 [1LP][RFR] Move numpy import so it can be done later
  cfme/utils/perf.py
  cfme/utils/perf_message_stats.py
  cfme/utils/smem_memory_monitor.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/template_docs.txt
Labels: enhancement, lint-ok

#7228 [RFR] Update requirements, add cycler
  requirements/frozen.py2.txt
  requirements/frozen_docs.py2.txt
  requirements/template_docs.txt
Labels: WIP-testing, issue-bug, lint-ok

#7220 [1LP][RFR] Add a DB disk to SCVMM appliance templates
  scripts/template_upload_scvmm.py
Labels: infra-related, lint-ok

#7231 [RFR] Fix auth_tests
  cfme/tests/integration/test_cfme_auth.py
Labels: fix-framework

#7234 [RFR] Replace deferred verpick with VersionPick
  cfme/cloud/instance/openstack.py
Labels: WIP-testing, fix-framework, lint-ok

#7150 [1LP][RFR] Activating test_guest_os_reset for RHV
  cfme/tests/infrastructure/test_vm_power_control.py
Labels: fix-test, lint-ok

#7154 [1LP][RFR] chargeback tests to validate resource allocation costs
  cfme/tests/intelligence/chargeback/test_resource_allocation.py
Labels: lint-ok, new-test-or-feature

#7155 [1LP][RFR] Added support for other providers [VM graph]
  cfme/cloud/instance/__init__.py
  cfme/cloud/provider/azure.py
  cfme/cloud/provider/ec2.py
  cfme/common/candu_views.py
  cfme/infrastructure/provider/rhevm.py
  cfme/infrastructure/provider/virtualcenter.py
  cfme/infrastructure/virtual_machines.py
  cfme/tests/candu/test_vm_graph.py
Labels: enhancement, fix-test, lint-ok

#6944 [1LP][RFR]Adding test case related to project.
  cfme/tests/infrastructure/test_project_quota.py
Labels: lint-ok, new-test-or-feature

#7225 [RFR] python-modernize -f libmodernize.fixes.fix_basestring . -j8 -w -n
  artifactor/plugins/filedump.py
  artifactor/plugins/reporter.py
  cfme/infrastructure/virtual_machines.py
  cfme/metaplugins/server_roles.py
  cfme/utils/__init__.py
  cfme/utils/appliance/__init__.py
  cfme/utils/blockers.py
  cfme/utils/bz.py
  cfme/utils/ssh.py
  cfme/utils/units.py
  scripts/list_tests.py
  sprout/appliances/models.py
  sprout/sprout/log.py
  widgetastic_manageiq/expression_editor.py
Labels: lint-ok

#7245 [RFR] Added Taretto
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
  requirements/template_docs.txt
Labels: lint-ok, other

#6879 [1LP][RFR] Refactored and added new restore tests
  cfme/fixtures/appliance.py
  cfme/tests/cli/test_appliance_console_db_restore.py
  cfme/tests/test_db_restore.py
Labels: enhancement, lint-ok, new-test-or-feature

#7235 [1LP][RFR] Use a cache for returning provider mgmt instances
  cfme/utils/providers.py
Labels: enhancement, lint-ok

#7242 [1LP][RFR]added windows domain credential tests
  cfme/tests/configure/test_zones.py
Labels: lint-ok, new-test-or-feature

#7156 [1LP][RFR] This PR will automate SSA via Compliance.
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
Labels: lint-ok, new-test-or-feature

#7179 [1LP][RFR] Move FQDN setting into Appliance.set_resolvable_hostname
  cfme/utils/appliance/__init__.py
  sprout/appliances/tasks.py
Labels: enhancement, lint-ok, sprout

#7222 [RFR][1LP] removing retry from check template task because it produces many failed tasks for invalid providers
  sprout/appliances/tasks.py
Labels: enhancement, lint-ok, sprout

#7262 [RFR] new wrapanapi 2.9.0 has been released
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
Labels: lint-ok, other

#7263 [1LP][RFR] Update freeze for wrapanapi 2.9.0
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
  requirements/template.txt
  requirements/template_docs.txt
Labels: fix-framework, lint-ok

#7264 [1LP][RFR] fix python3 on travis and for --collectonly
  .travis.yml
  cfme/fixtures/browser.py
  cfme/fixtures/nelson.py
  cfme/fixtures/smtp.py
  cfme/markers/env_markers/provider.py
  cfme/modeling/base.py
  cfme/scripting/quickstart.py
  cfme/tests/configure/test_docs.py
  cfme/utils/__init__.py
  cfme/utils/appliance/__init__.py
  cfme/utils/appliance/db.py
  cfme/utils/appliance/implementations/ui.py
  cfme/utils/browser.py
  cfme/utils/log_validator.py
  cfme/utils/mgmt_system/__init__.py
  cfme/utils/providers.py
  cfme/utils/pytest_shortcuts.py
  cfme/utils/ssh.py
  cfme/utils/tests/test_datafile_fixture.py
  cfme/utils/tests/test_soft_assert.py
  cfme/utils/units.py
  cfme/utils/virtual_machines.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py3.txt
  requirements/template.txt
  requirements/template_docs.txt
  requirements/test_frozen_requirements.py
Labels: lint-ok, py3-compat

#6786 [1LP][WIPTEST]Add widget and tests for changing the RBAC group for the currently logged in user via the webui
  cfme/base/login.py
  cfme/tests/configure/test_access_control.py
  widgetastic_manageiq/__init__.py
Labels: WIP-testing, enhancement, lint-ok, new-test-or-feature

#7254 [1LP][RFR] fixed timing issues in test_host_lifecycle tests
  cfme/tests/openstack/infrastructure/test_host_lifecycle.py
Labels: fix-test, lint-ok

#7055 [1LP][RFR] Adding new test case related to child tenant.
  cfme/tests/infrastructure/test_child_tenant.py
Labels: lint-ok, new-test-or-feature

#7244 [1LP][RFR] Fixing Quota tagging automation failure
  cfme/tests/infrastructure/test_quota_tagging.py
Labels: fix-test, lint-ok

#7274 [1LP][RFR] Service chargeback: fix SCVMM failure
  cfme/tests/ssui/test_ssui_dashboard.py
Labels: fix-test, lint-ok

#7265 [1LP][RFR]SSA templates extend fixes
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
Labels: fix-test, lint-ok

#7133 [1LP][RFR] Fixed escape sequences
  cfme/utils/appliance/__init__.py
Labels: enhancement, lint-ok

#7146 [1LP][RFR] Added test case to test provision of VM to OVN network.
  cfme/networks/cloud_network.py
  cfme/tests/networks/test_provision_to_virtual_network.py
Labels: lint-ok, new-test-or-feature

#7217 [1LP][RFR]fixing stack dialog filling
  cfme/services/catalogs/catalog_items/__init__.py
  cfme/services/myservice/ui.py
  cfme/services/service_catalogs/__init__.py
  cfme/tests/services/test_provision_stack.py
Labels: lint-ok

#7284 [RFR] Uprev WT.core
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: lint-ok, other

#7237 [1LP][RFR] Chargeback resource allocation : Add support for other providers
  cfme/tests/intelligence/chargeback/test_resource_allocation.py
Labels: lint-ok, new-test-or-feature

#7240 [1LP][RFR] fixed test_nodes test
  cfme/tests/openstack/infrastructure/test_relationships.py
Labels: fix-test, lint-ok

#7260 [1LP][RFR] Fixing test_ssa_schedule for RHEL VM
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
Labels: lint-ok

#7267 [1LP][RFR] extend travis testing for better verification and py3k strictness
  .travis.yml
  cfme/fixtures/parallelizer/parallelizer_tester.py
  cfme/scripting/setup_env.py
  cfme/tests/integration/test_cfme_auth.py
  cfme/tests/test_modules_importable.py
  cfme/utils/browser.py
  cfme/utils/bz.py
  cfme/utils/ftp.py
  cfme/utils/template/base.py
  cfme/utils/template/ec2.py
  cfme/utils/template/rhevm.py
  cfme/utils/trackerbot.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
  requirements/template_docs.txt
Labels: lint-ok, py3-compat

#7268 [1LP][RFR] Move console handle check and change exception type
  cfme/common/vm_console.py
Labels: enhancement, lint-ok

#7270 [1LP][RFR]test provider logs
  cfme/tests/configure/test_logs.py
Labels: lint-ok, new-test-or-feature

#7285 [1LP][RFR]Bump wrapanapi to 2.9.2
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/template.txt
Labels: lint-ok, other

#7259 [1LP][RFR] Raw metric test wait_for and relocate
  cfme/tests/candu/test_utilization_metrics.py
Labels: WIP, fix-test, lint-ok

#7276 [1LP][RFR] fixed test_register_host test
  cfme/tests/openstack/infrastructure/test_host_lifecycle.py
Labels: lint-ok

#7287 [1LP][RFR] fixing logging in sprout for one of tasks
  sprout/appliances/tasks.py
Labels: enhancement, lint-ok, sprout

#7181 [1LP][RFR] preconfigured openshift sprout providers
  cfme/utils/appliance/__init__.py
  sprout/.gitignore
  sprout/appliances/models.py
  sprout/appliances/tasks.py
  sprout/sprout.sh
Labels: infra-related, lint-ok, sprout

#7266 [1LP][RFR]Added new collection for taging api testing
  cfme/tests/configure/test_tag.py
Labels: lint-ok, new-test-or-feature

#7291 [WIPTEST] Fix crud property and __slots__ for test_actions
  cfme/tests/control/test_actions.py
Labels: WIP-testing, fix-test, lint-ok, py3-compat

#7251 [1LP][RFR]Network tag visibility tests
  cfme/networks/floating_ips.py
  cfme/tests/networks/test_sdn_balancers.py
  cfme/tests/networks/test_tag_tagvis.py
Labels: lint-ok, new-test-or-feature

#7108 [1LP][RFR] Tasks collection convertion
  cfme/common/vm.py
  cfme/configure/tasks.py
  cfme/containers/image.py
  cfme/infrastructure/cluster.py
  cfme/infrastructure/datastore.py
  cfme/infrastructure/host.py
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
  cfme/tests/containers/test_containers_smartstate_analysis.py
  cfme/tests/containers/test_containers_smartstate_analysis_multiple_images.py
  cfme/tests/containers/test_provider_openscap_policy_attached.py
  cfme/tests/infrastructure/test_datastore_analysis.py
  cfme/tests/infrastructure/test_host_drift_analysis.py
  cfme/tests/openstack/infrastructure/test_hosts.py
  cfme/tests/openstack/infrastructure/test_roles.py
  setup.py
Labels: collections-conversion, lint-ok

#6985 [1LP][RFR] Replacing raw ovirtsdk api calls by wrapanapi api
  cfme/utils/mgmt_system/__init__.py
  cfme/utils/template/rhevm.py
  cfme/utils/virtual_machines.py
  scripts/delete_vm.py
  scripts/template_upload_rhevm.py
  scripts/template_upload_rhevm_qcow2.py
Labels: enhancement, lint-ok

#7086 [1LP][RFR] Generic objects UI tests
  cfme/generic_objects/definition/__init__.py
  cfme/generic_objects/definition/button_groups.py
  cfme/generic_objects/definition/definition_views.py
  cfme/generic_objects/definition/ui.py
  cfme/generic_objects/instance/__init__.py
  cfme/generic_objects/instance/rest.py
  cfme/generic_objects/instance/ui.py
  cfme/services/myservice/ui.py
  cfme/tests/generic_objects/test_definitions.py
  cfme/tests/generic_objects/test_instances.py
Labels: lint-ok, new-test-or-feature

#7253 [1LP][RFR][BLOCKED] Tests for the network and storage devices links
  cfme/common/physical_server_views.py
  cfme/physical/physical_server.py
  cfme/tests/physical_infrastructure/ui/test_physical_server_details.py
Labels: lint-ok, new-test-or-feature

#7277 [1LP][RFR][NOTEST] Adding cloud-init test for RHV
  cfme/tests/infrastructure/test_cloud_init_provisioning.py
  data/rootpass.cfg
Labels: lint-ok, new-test-or-feature

#7236 [1LP][RFR] V2v infra mapping wizard
  cfme/tests/v2v/test_v2v.py
  cfme/v2v/__init__.py
  cfme/v2v/migrations.py
  setup.py
  widgetastic_manageiq/__init__.py
Labels: lint-ok, new-test-or-feature

#7282 [RFR] Fix locator in SettingsGroupSubmenu
  widgetastic_manageiq/__init__.py
Labels: collections-conversion, fix-framework, lint-ok

#7301 [RFR] Added flags to some tests
  cfme/tests/automate/test_buttons.py
  cfme/tests/cloud_infra_common/test_cockpit_server.py
  cfme/tests/cloud_infra_common/test_relationships.py
  cfme/tests/cloud_infra_common/test_vm_ownership.py
  cfme/tests/configure/test_logs.py
  cfme/tests/control/test_actions.py
  cfme/tests/infrastructure/test_child_tenant.py
  cfme/tests/infrastructure/test_individual_host_creds.py
  cfme/tests/infrastructure/test_kubevirt.py
  cfme/tests/infrastructure/test_project_quota.py
  cfme/tests/infrastructure/test_quota_tagging.py
  cfme/tests/infrastructure/test_snapshot.py
  cfme/tests/infrastructure/test_tenant_quota.py
  cfme/tests/infrastructure/test_vm_power_control.py
  cfme/tests/intelligence/reports/test_canned_corresponds.py
  cfme/tests/intelligence/reports/test_views.py
Labels: lint-ok, rc-regression-fix

#7305 [1LP][RFR] added keystone version support to openstack infra provider
  cfme/cloud/provider/openstack.py
  cfme/common/provider_views.py
  cfme/infrastructure/provider/openstack_infra.py
Labels: enhancement, lint-ok

#7308 [1LP][RFR] Fixed a bad import
  cfme/utils/appliance/__init__.py
Labels: lint-ok, rc-regression-fix

#6949 [1LP][WIP] Test updating password from the login screen
  cfme/base/ui.py
  cfme/tests/test_login.py
Labels: WIP, lint-ok, new-test-or-feature

#7288 [1LP][RFR] Moved log_names to providers
  cfme/cloud/provider/azure.py
  cfme/cloud/provider/ec2.py
  cfme/cloud/provider/openstack.py
  cfme/infrastructure/provider/rhevm.py
  cfme/infrastructure/provider/scvmm.py
  cfme/infrastructure/provider/virtualcenter.py
  cfme/networks/provider/nuage.py
  cfme/physical/provider/lenovo.py
  cfme/tests/configure/test_logs.py
Labels: enhancement, lint-ok

#7299 [1LP][RFR] Activating test_custom_vm_report for RHV-CFME
  cfme/tests/intelligence/reports/test_report_corresponds.py
Labels: fix-test, lint-ok

#7296 [1LP][RFR] Fix credentials template indent
  conf/credentials.yaml.template
Labels: fix-framework, lint-ok

#7294 [1LP][RFR][NOTEST]tagging sdn tests
  cfme/tests/networks/test_sdn_balancers.py
  cfme/tests/networks/test_sdn_crud.py
  cfme/tests/networks/test_sdn_downloads.py
  cfme/tests/networks/test_sdn_inventory_collection.py
  cfme/tests/networks/test_sdn_navigation.py
  cfme/tests/networks/test_sdn_ports.py
  cfme/tests/networks/test_sdn_topology.py
Labels: fix-test, lint-ok

#7293 [1LP][RFR] switch utils/ftp to bytesio
  cfme/utils/ftp.py
Labels: lint-ok, py3-compat

#7312 [RFR] Updated navmazing
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: lint-ok, other
