Repository ManageIQ/integration_tests, pull requests merged in 2019-04, with the labels that each got.

#8453 [1LP][WIPTEST] smartstate smoketest in pod appliance
  cfme/cloud/provider/__init__.py
  cfme/cloud/provider/ec2.py
  cfme/common/provider.py
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
  cfme/tests/pod/test_appliance_crud.py
Labels: WIP-testing, lint-ok, new-test-or-feature

#8639 [WIP] Update polarion_tools.yaml, comments around caseautomation
  conf/polarion_tools.yaml
Labels: WIP, lint-ok, other

#8642 [1LP][RFR][NOTEST] CB: test unique names
  cfme/tests/automate/custom_button/test_cloud_objects.py
  cfme/tests/automate/custom_button/test_container_objects.py
  cfme/tests/automate/custom_button/test_generic_objects.py
  cfme/tests/automate/custom_button/test_infra_objects.py
  cfme/tests/automate/custom_button/test_service_objects.py
Labels: lint-ok, manual

#8646 [1LP][RFR] Remove duplicate test names
  cfme/tests/candu/test_azone_graph.py
  cfme/tests/candu/test_cluster_graph.py
  cfme/tests/candu/test_datastore_graph.py
  cfme/tests/candu/test_host_graph.py
  cfme/tests/candu/test_vm_graph.py
Labels: lint-ok, other

#8651 [1LP][RFR][NOTEST] This will remove duplicate/automated tests from respective manual file.
  cfme/tests/ansible/test_embedded_ansible_manual.py
  cfme/tests/cloud_infra_common/test_vm_instance_analysis_manual.py
Labels: lint-ok, manual

#8649 [1LP][RFR][NOTEST] Add manual tests for RFE
  cfme/tests/intelligence/reports/test_reports_manual.py
Labels: lint-ok, manual

#8596 [1LP][RFR] Updated is_diplayed of AutomateImportExportView
  cfme/base/ui.py
Labels: lint-ok, new-test-or-feature

#8657 [RFR][NOTEST] This PR will remove Manual tests (Duplicate)
  cfme/tests/cli/test_appliance_console.py
Labels: lint-ok, manual

#8652 [1LP][RFR] Adding manual test of services RFE
  cfme/tests/services/test_catalog_item.py
  cfme/tests/services/test_generic_service_catalogs.py
  cfme/tests/services/test_myservice.py
Labels: lint-ok, manual

#8650 [1LP][RFR] Added a test for breadcrumbs RFE
  cfme/tests/webui/test_general_ui.py
Labels: lint-ok, manual

#8600 [1LP][RFR] New Test: Checking git import for multiple domains
  cfme/tests/automate/test_automate_manual.py
  cfme/tests/automate/test_git_import.py
Labels: lint-ok, new-test-or-feature

#8486 [1LP][RFR] This will fix control-action tests for Ansible.
  cfme/control/explorer/actions.py
  cfme/tests/ansible/test_embedded_ansible_basic.py
Labels: fix-test, lint-ok

#8661 [1LP][RFR] Update travis config to include manual tests for collection
  .travis.yml
Labels: enhancement, lint-ok

#8570 [1LP][RFR][NOMERGE] Updates for rhv42 upload
  cfme/utils/template/rhevm.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
  requirements/template.txt
  scripts/template_upload_rhevm.py
  scripts/template_upload_rhevm_qcow2.py
  sprout/appliances/tasks.py
  sprout/requirements.txt
  sprout/sprout.sh
Labels: enhancement, infra-related, lint-ok

#8632 [NOTEST][RFR] Added caseautomation for mmojzis' manual tests
  cfme/tests/test_manual.py
Labels: lint-ok, manual

#8648 [1LP][RFR] new test_tag_change_tag_name
  cfme/configure/configuration/region_settings.py
  cfme/tests/configure/test_tag.py
Labels: lint-ok, new-test-or-feature

#8597 [1LP][RFR]Automate test for vm reconfig add remove disk hot
  cfme/tests/infrastructure/test_vm_reconfigure.py
Labels: lint-ok, new-test-or-feature

#8664 [1LP][RFR][NOTEST]move to manual only
  cfme/tests/automate/custom_button/test_buttons.py
Labels: lint-ok, manual

#8654 [1LP][RFR] items per page in 5.11
  cfme/tests/configure/test_paginator.py
Labels: enhancement, lint-ok

#8667 [RFR][NOTEST] update manageiq-client requirnment to 0.5.1 py3 support
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: lint-ok, py3-compat

#8522 [1LP][RFR] create osp container with wrapanapi
  cfme/storage/object_store_container.py
  cfme/storage/object_store_object.py
  cfme/tests/storage/test_object_store_container.py
  cfme/tests/storage/test_object_store_object.py
Labels: WIP-testing, fix-framework, lint-ok

#8647 [1LP][RFR] fix for tests which fail due to absent web_services credentials
  cfme/tests/infrastructure/test_host.py
Labels: fix-test, lint-ok

#8670 [1LP][RFR]Removing the duplicate test add button group
  cfme/tests/services/test_catalog_item.py
Labels: lint-ok, manual

#8668 [1LP][RFR] Manual test cleanup of vmware reconfig test
  cfme/tests/infrastructure/test_vm_reconfigure.py
Labels: lint-ok, manual

#8622 [1LP][RFR] Tests for grouping candu graphs by tags
  cfme/fixtures/candu.py
  cfme/tests/candu/test_graph_groupbytag.py
Labels: lint-ok, new-test-or-feature

#8404 [1LP][RFR] Migration Plans Refactoring
  cfme/tests/v2v/test_migration_plan.py
  cfme/v2v/infrastructure_mapping.py
  cfme/v2v/migration_plans.py
  cfme/v2v/migrations_new.py
  entry_points.txt
  widgetastic_manageiq/__init__.py
Labels: fix-framework, lint-ok

#8653 [1LP][RFR] New manual testcases
  cfme/tests/cloud/test_snapshot.py
  cfme/tests/cloud_infra_common/test_genealogy.py
  cfme/tests/configure/test_access_control.py
Labels: lint-ok, manual

#8558 [1LP][RFR] New Test: Test object atrribute type in automation schedule
  cfme/configure/configuration/system_schedules.py
  cfme/tests/automate/test_automate_manual.py
  cfme/tests/automate/test_domain.py
  cfme/tests/configure/test_schedule_operations.py
Labels: lint-ok, new-test-or-feature

#8665 [1LP][RFR] Automating Ansible manual test cases.
  cfme/tests/ansible/test_embedded_ansible_basic.py
  cfme/tests/ansible/test_embedded_ansible_manual.py
  cfme/tests/ansible/test_embedded_ansible_services.py
Labels: lint-ok, new-test-or-feature

#8673 [1LP][RFR] This will add workaround for AMI image selection.
  cfme/common/provider.py
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
Labels: fix-test, lint-ok

#8678 [RFR] Modify tenants function
  cfme/rest/gen_data.py
Labels: fix-framework, lint-ok

#8656 [1LP][RFR] moved anikifor manual tests
  cfme/tests/cloud/test_azure_manual.py
  cfme/tests/cloud/test_providers.py
  cfme/tests/cloud_infra_common/test_provisioning_manual.py
  cfme/tests/services/test_provision_stack.py
  cfme/tests/test_manual.py
Labels: lint-ok, manual

#8598 [1LP][RFR] New Test: Checking domain import via git with or without top level domain
  cfme/tests/automate/test_automate_manual.py
  cfme/tests/automate/test_domain.py
  cfme/tests/automate/test_git_import.py
Labels: lint-ok, new-test-or-feature

#8687 [1LP][RFR][NOTEST] Added manual test case for 5.10
  cfme/tests/automate/test_automate_manual.py
Labels: lint-ok, manual

#8645 [1LP][RFR] Update LogValidator usage
  cfme/tests/cli/test_appliance_cli.py
  cfme/tests/cli/test_appliance_console.py
  cfme/tests/containers/test_blacklisted_container_events.py
  cfme/tests/containers/test_pause_resume_workers.py
  cfme/utils/ssh.py
Labels: enhancement, lint-ok

#8688 [1LP][RFR][NOTEST]Add manual test cases for RFE
  cfme/tests/webui/test_general_ui.py
Labels: lint-ok, manual

#8683 [RFR][NOTEST] removing lost named appliances in sprout
  sprout/sprout/settings.py
Labels: infra-related, lint-ok, sprout

#8699 [1LP][RFR] fixing test_basic tests
  cfme/control/explorer/conditions.py
  cfme/tests/control/test_basic.py
Labels: fix-test, lint-ok

#8681 [1LP][RFR] Automating Critical Embedded Ansible manual tests.
  cfme/tests/ansible/test_embedded_ansible_crud.py
  cfme/tests/ansible/test_embedded_ansible_manual.py
Labels: lint-ok, new-test-or-feature

#8679 [1LP][RFR][NOTEST] CB: new manual tests
  cfme/tests/automate/custom_button/test_generic_objects.py
  cfme/tests/automate/custom_button/test_infra_objects.py
  cfme/tests/automate/custom_button/test_service_objects.py
Labels: lint-ok, manual

#8680 [1LP][RFR][NOTEST] Add manual case for BZ 1595259
  cfme/tests/generic_objects/test_instances.py
Labels: lint-ok, manual

#8700 [1LP][RFR] Remove group by tag tests
  cfme/tests/candu/test_host_graph.py
Labels: lint-ok, other

#8535 [NOTEST] [RFR] EC2cleanup boto3 refactor from object to dict
  scripts/ec2cleanup.py
Labels: infra-related, lint-ok

#8705 [1LP][RFR] Removing locator to support modified progress bar widget
  cfme/v2v/migrations.py
Labels: fix-framework, lint-ok

#8608 [1LP][RFR]Adding new tests of vm reconfig add sockets and memory on running Vm
  cfme/tests/infrastructure/test_vm_reconfigure.py
Labels: lint-ok, new-test-or-feature

#8708 [1LP][RFR] additional support of newer debian distributions
  cfme/scripting/quickstart/system.py
Labels: fix-framework, lint-ok

#8702 [1LP][RFR] Move convenience methods to use SystemdService plugin for appliance
  cfme/tests/ansible/test_embedded_ansible_crud.py
  cfme/tests/cli/test_appliance_update.py
  cfme/utils/appliance/__init__.py
  cfme/utils/appliance/services.py
Labels: enhancement, lint-ok

#8671 [1LP][RFR] Added new manual test cases
  cfme/tests/automate/test_automate_manual.py
  cfme/tests/automate/test_git_import.py
  cfme/tests/cloud_infra_common/test_power_control_manual.py
  cfme/tests/cloud_infra_common/test_quota_manual.py
  cfme/tests/services/test_catalog_item.py
Labels: lint-ok, manual

#8669 [1LP][RFR] Global fixture for custom button support.
  cfme/fixtures/provider.py
  cfme/fixtures/service_fixtures.py
  cfme/tests/services/test_add_remove_vm_to_service.py
Labels: enhancement, lint-ok

#8323 [RFR] Test Embedded Ansible integration for Nuage
  cfme/automate/explorer/method.py
  cfme/fixtures/ansible_fixtures.py
  cfme/fixtures/embedded_ansible.py
  cfme/test_framework/pytest_plugin.py
  cfme/tests/networks/nuage/test_automation.py
Labels: lint-ok, new-test-or-feature

#8713 Pass url positionally as its name is changing in manageiq_client
  cfme/base/__init__.py
Labels: fix-framework, lint-ok

#8658 [1LP][RFR][NOTEST]Adding more VMware tests to address qe_test_coverage flags
  cfme/tests/infrastructure/test_vmware_provider.py
Labels: lint-ok, manual

#8561 [1LP][RFR] New Test: Testing imported domain refresh with non-super user
  cfme/automate/explorer/domain.py
  cfme/configure/access_control/__init__.py
  cfme/tests/automate/test_automate_manual.py
  cfme/tests/automate/test_git_import.py
Labels: lint-ok, new-test-or-feature

#8711 [WIPTEST]Fix gen_data function
  cfme/rest/gen_data.py
Labels: WIP-testing, fix-framework, lint-ok

#8666 [1LP][RFR] Automate test: test_deny_service_ordering_via_api
  cfme/tests/services/test_rest_services.py
  cfme/tests/test_rest_manual.py
Labels: lint-ok, new-test-or-feature

#8663 [1LP][RFR] added cloud-init script for vm with powershell
  data/az_pwsh_cloudinit.cfg
Labels: infra-related, lint-ok

#8686 [1LP][RFR] Automate test: test_vm_retirement_requester
  cfme/tests/infrastructure/test_infra_manual.py
  cfme/tests/infrastructure/test_vm_retirement_rest.py
Labels: lint-ok, new-test-or-feature

#8715 [1LP][RFR] make scavenge providers task not to lock provisioning queue
  sprout/appliances/tasks.py
  sprout/sprout/settings.py
Labels: fix-framework, infra-related, lint-ok

#8714 [1LP][RFR] Removed local Ansible fixture and fixed is_displayed.
  cfme/configure/configuration/diagnostics_settings.py
  cfme/tests/configure/test_log_depot_operation.py
Labels: fix-test, lint-ok

#8720 [RFR] Remove finally clause from _get_vm method in control/test_actions.py
  cfme/tests/control/test_actions.py
Labels: fix-test, lint-ok, rc-regression-fix

#8719 [RFR] fix two smoke tests
  cfme/tests/test_appliance.py
Labels: fix-test, lint-ok, rc-regression-fix

#8716 [RFR] Add BZ and workaround for this test
  cfme/tests/control/test_basic.py
Labels: fix-test, lint-ok, rc-regression-fix

#8717 [RFR] Default to vddk 6.5 in vddk_url fixture
  cfme/fixtures/appliance.py
Labels: fix-test, lint-ok, rc-regression-fix

#8682 [1LP][RFR] New Test: Checking 'Q-task_id' for automate methods in automation logs
  cfme/tests/automate/test_automate_manual.py
  cfme/tests/automate/test_method.py
Labels: lint-ok, new-test-or-feature

#8721 [1LP][RFR] CMQE Fix duplicate test function names
  cfme/tests/containers/test_containers_smartstate_analysis_multiple_images.py
Labels: fix-test, lint-ok

#8672 [1LP][RFR] Add Requirement Meta
  cfme/test_requirements.py
  cfme/tests/infrastructure/test_config_management_rest.py
  cfme/tests/test_appliance.py
  cfme/tests/test_manual.py
  cfme/tests/test_replication.py
  cfme/tests/webui/test_general_ui.py
  cfme/utils/testgen.py
Labels: enhancement, lint-ok, other

#8723 [1LP][RFR] Fixed AssertionError while copying method/instance/class to domain
  cfme/automate/explorer/common.py
  cfme/tests/automate/test_automate_manual.py
  cfme/tests/automate/test_domain.py
Labels: lint-ok, new-test-or-feature

#8685 [1LP][RFR] New Test: Testing instance(ansible_tower_job) calls the proper automate method
  cfme/tests/automate/test_automate_manual.py
  cfme/tests/automate/test_instance.py
Labels: lint-ok, new-test-or-feature

#8684 [1LP][RFR] Make BZ references uniform
  cfme/tests/ansible/test_embedded_ansible_basic.py
  cfme/tests/ansible/test_embedded_ansible_manual.py
  cfme/tests/ansible/test_embedded_ansible_services.py
  cfme/tests/automate/custom_button/test_buttons.py
  cfme/tests/automate/custom_button/test_catalog_custom_button.py
  cfme/tests/automate/custom_button/test_cloud_objects.py
  cfme/tests/automate/custom_button/test_infra_objects.py
  cfme/tests/automate/custom_button/test_service_objects.py
  cfme/tests/automate/test_domain.py
  cfme/tests/automate/test_service_dialog.py
  cfme/tests/automate/test_vmware_methods.py
  cfme/tests/candu/__init__.py
  cfme/tests/candu/test_graph_groupbytag.py
  cfme/tests/cli/test_appliance_console.py
  cfme/tests/cloud/test_providers.py
  cfme/tests/cloud/test_tenant.py
  cfme/tests/cloud_infra_common/test_policy_simulation.py
  cfme/tests/cloud_infra_common/test_provisioning_manual.py
  cfme/tests/cloud_infra_common/test_quota_manual.py
  cfme/tests/cloud_infra_common/test_relationships.py
  cfme/tests/cloud_infra_common/test_vm_instance_analysis_manual.py
  cfme/tests/configure/test_access_control.py
  cfme/tests/configure/test_config_manual.py
  cfme/tests/configure/test_log_depot_operation_manual.py
  cfme/tests/configure/test_region.py
  cfme/tests/configure/test_tag.py
  cfme/tests/configure/test_visual_infra.py
  cfme/tests/control/test_actions.py
  cfme/tests/control/test_alerts.py
  cfme/tests/control/test_control_simulation.py
  cfme/tests/infrastructure/test_scvmm_specific.py
  cfme/tests/infrastructure/test_vm_reconfigure.py
  cfme/tests/infrastructure/test_vmware_provider.py
  cfme/tests/intelligence/reports/test_reports_manual.py
  cfme/tests/intelligence/test_timelines_rss_removed.py
  cfme/tests/networks/test_sdn_downloads.py
  cfme/tests/services/test_catalog_item.py
  cfme/tests/services/test_dynamicdd_dialogelement.py
  cfme/tests/services/test_generic_service_catalogs.py
  cfme/tests/services/test_myservice.py
  cfme/tests/services/test_provision_stack.py
  cfme/tests/services/test_rest_services.py
  cfme/tests/test_appliance.py
  cfme/tests/test_db_migrate_manual.py
  cfme/tests/test_manual.py
  cfme/tests/webui/test_general_ui.py
Labels: lint-ok, other

#8726 [RFR] Add in test_requirements where necessary for FAs
  cfme/tests/cloud/test_cloud_timelines.py
  cfme/tests/cloud_infra_common/test_events.py
  cfme/tests/control/test_rest_control.py
  cfme/tests/infrastructure/test_timelines.py
Labels: enhancement, lint-ok

#8697 [1LP][RFR]Automate testcase: test_query_custom_category
  cfme/tests/configure/test_tag_category.py
  cfme/tests/test_rest_manual.py
Labels: lint-ok, new-test-or-feature

#8696 [1LP][RFR]Automate test: test_reports_custom_tags
  cfme/tests/intelligence/reports/test_reports.py
  cfme/tests/intelligence/reports/test_reports_manual.py
Labels: WIP-testing, lint-ok, new-test-or-feature

#8725 [RFR] Update package versions, miq-version in particular
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
  sprout/requirements.txt
Labels: lint-ok, other

#8728 [RFR][NOTEST] reassigned general_ui requirement to pvala and marked tests
  cfme/test_requirements.py
  cfme/tests/cloud/test_providers.py
  cfme/tests/test_csrf.py
  cfme/tests/test_ui.py
  cfme/tests/webui/test_general_ui.py
  cfme/tests/webui/test_splitter.py
Labels: lint-ok, manual

#8724 [1LP][RFR] Fixed failing test cases in 5.10z for rhv provider
  cfme/tests/infrastructure/test_vm_power_control.py
Labels: fix-test, lint-ok, manual

#8733 [1LP][RFR] Fix test operations
  cfme/tests/services/test_operations.py
Labels: fix-test, lint-ok

#8736 [1LP][RFR] restoring scopes of global fixtures
  cfme/fixtures/provider.py
  cfme/fixtures/service_fixtures.py
Labels: fix-framework, lint-ok

#8692 [1LP][RFR] Updating template test to cover vmware provider
  cfme/tests/infrastructure/test_publish_vm_to_template.py
Labels: lint-ok, new-test-or-feature

#8674 [1LP][RFR] SCVMM test cleanup
  cfme/tests/infrastructure/test_scvmm_specific.py
Labels: fix-test, lint-ok, manual

#8722 [1LP][RFR][NOTEST] Updated manual/automated test cases
  cfme/tests/automate/test_automate_manual.py
  cfme/tests/automate/test_common_methods.py
  cfme/tests/cloud_infra_common/test_discovery_and_support.py
  cfme/tests/cloud_infra_common/test_power_control_manual.py
  cfme/tests/cloud_infra_common/test_quota_manual.py
  cfme/tests/cloud_infra_common/test_relationships.py
  cfme/tests/infrastructure/test_vm_ownership.py
  cfme/tests/test_manual.py
Labels: lint-ok, manual

#8731 [1LP][RFR] fix tests screwed up by v2v osp provider
  cfme/tests/openstack/cloud/test_flavors.py
  cfme/tests/openstack/cloud/test_instances.py
  cfme/tests/openstack/cloud/test_volume_backup.py
Labels: fix-test, lint-ok

#8732 [1LP][RFR] cloud init provisioning tests fix
  cfme/tests/cloud_infra_common/test_cloud_init_provisioning.py
Labels: fix-test, lint-ok

#8735 [1LP][RFR] removing unneeded fixture since there is present such global fixture
  cfme/tests/ansible/test_embedded_ansible_services.py
Labels: fix-test, lint-ok

#8740 [RFR] fixing scopes of some global fixtures
  cfme/fixtures/service_fixtures.py
Labels: fix-framework, lint-ok

#8747 [RFR] fixed diagnostics & logs views and relevant tests
  cfme/configure/configuration/diagnostics_settings.py
Labels: fix-framework, lint-ok

#8609 [1LP][RFR] Testing Datastore Cluster Changes with PRT
  cfme/utils/template/virtualcenter.py
Labels: enhancement, lint-ok

#8727 [1LP][RFR] Fix the Pop and Push the appliance to the stack messages
  cfme/utils/appliance/__init__.py
Labels: fix-test, lint-ok

#8744 [1LP][RFR] Use re.search instead of re.match in LogValidator
  cfme/utils/log_validator.py
Labels: enhancement, lint-ok

#8756 [1LP][RFR] Updates for 5.11 configuration, set postgres permissions
  cfme/utils/appliance/__init__.py
  cfme/utils/appliance/db.py
Labels: enhancement, fix-framework, lint-ok

#8739 [1LP][RFR][NOTEST] custom button test requirements
  cfme/test_requirements.py
  cfme/tests/automate/custom_button/test_buttons.py
  cfme/tests/automate/custom_button/test_catalog_custom_button.py
  cfme/tests/automate/custom_button/test_cloud_objects.py
  cfme/tests/automate/custom_button/test_container_objects.py
  cfme/tests/automate/custom_button/test_generic_objects.py
  cfme/tests/automate/custom_button/test_import_export.py
  cfme/tests/automate/custom_button/test_infra_objects.py
  cfme/tests/automate/custom_button/test_rest_custom_button.py
  cfme/tests/automate/custom_button/test_service_objects.py
Labels: enhancement, lint-ok

#8730 [1LP][RFR] Add bugzilla-docstrings to pre-commit
  .pre-commit-config.yaml
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
Labels: enhancement, lint-ok

#8704 [1LP][RFR] Move auth manual testcases
  cfme/tests/integration/test_cfme_auth.py
  cfme/tests/test_manual.py
Labels: lint-ok, manual

#8707 [1LP][RFR] Fixed Embedded Ansible CRUD test file by re-ordering sub-tests
  cfme/tests/ansible/test_embedded_ansible_crud.py
  cfme/utils/appliance/__init__.py
  cfme/utils/appliance/services.py
Labels: fix-test, lint-ok

#8755 [1LP][RFR] fix fixture scope
  cfme/fixtures/service_fixtures.py
Labels: fix-test, lint-ok

#8583 [1LP][RFR] provision cfme from azure
  cfme/tests/cloud/test_providers.py
Labels: lint-ok, new-test-or-feature

#8718 [1LP][RFR] Update snapshot strings
  cfme/infrastructure/virtual_machines.py
Labels: fix-framework, lint-ok

#8690 [1LP][RFR] Post migration new structure and osp support
  cfme/fixtures/v2v_fixtures.py
  cfme/tests/v2v/test_post_migrations.py
Labels: enhancement, lint-ok

#8758 [1LP][RFR] Update cluster property to fetch info through REST
  cfme/infrastructure/virtual_machines.py
Labels: enhancement, lint-ok

#8694 [1LP][RFR]Ansible test refactoring
  cfme/tests/v2v/test_v2v_ansible.py
Labels: enhancement, lint-ok

#8737 [1LP][RFR]Automate test:test_filter_by_flavor_via_api
  cfme/tests/openstack/cloud/test_flavors.py
  cfme/tests/test_rest_manual.py
Labels: lint-ok, new-test-or-feature

#8759 [1LP][RFR] Remove todo and blocker BZ-1668023
  cfme/common/__init__.py
  cfme/tests/automate/custom_button/test_cloud_objects.py
  cfme/tests/automate/custom_button/test_infra_objects.py
Labels: enhancement, lint-ok

#8729 [1LP][RFR] Optimize assign events for policies
  cfme/control/explorer/policies.py
  cfme/tests/ansible/test_embedded_ansible_actions.py
  cfme/tests/cloud_infra_common/test_events.py
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
  cfme/tests/control/test_actions.py
  cfme/tests/control/test_basic.py
  cfme/tests/intelligence/test_reports_with_timelines.py
  widgetastic_manageiq/__init__.py
Labels: enhancement, lint-ok

#8750 [RFR] Remove tests automated in test_relationships for SCVMM
  cfme/tests/infrastructure/test_scvmm_specific.py
Labels: fix-test, lint-ok

#8743 [RFR][NOTEST]reassigned more general ui tests
  cfme/tests/automate/test_customization_paginator.py
  cfme/tests/automate/test_service_dialog.py
  cfme/tests/configure/test_config_manual.py
  cfme/tests/configure/test_paginator.py
  cfme/tests/configure/test_server_name.py
  cfme/tests/networks/test_sdn_downloads.py
  cfme/tests/webui/test_advanced_search.py
  cfme/tests/webui/test_filter_conditions.py
  cfme/tests/webui/test_general_ui.py
Labels: lint-ok, manual

#8760 [1LP][RFR] fixed events table in analysis profiles
  cfme/configure/configuration/analysis_profile.py
Labels: fix-framework, lint-ok

#8765 [WIPTEST] Update creation time check in cleanup_old_vms
  scripts/cleanup_old_vms.py
Labels: WIP-testing, infra-related, lint-ok

#8763 [1LP][RFR] deploying fix for manageiq's table
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: fix-framework, lint-ok

#8757 [1LP][RFR] Check collectonly before registering UiCoveragePlugin
  cfme/fixtures/ui_coverage.py
Labels: enhancement, lint-ok

#8449 [1LP][RFR] added test_ansible_tower_job_templates_tag
  cfme/ansible_tower/explorer.py
  cfme/infrastructure/config_management.py
  cfme/tests/infrastructure/test_config_management.py
Labels: lint-ok, new-test-or-feature

#8742 [1LP][RFR] Automate test: test_rest_metric_rollups
  cfme/tests/test_rest.py
  cfme/tests/test_rest_manual.py
Labels: lint-ok, new-test-or-feature

#8734 [1LP][RFR]Automate test: test_vm_disk_reconfig_via_rest
  cfme/tests/infrastructure/test_vm_reconfigure.py
  cfme/tests/test_rest_manual.py
Labels: lint-ok, new-test-or-feature

#8712 [1LP][RFR] Automate test: test_populate_default_dialog_values
  cfme/tests/services/test_rest_services.py
  cfme/tests/test_rest_manual.py
Labels: lint-ok, new-test-or-feature

#8767 [1LP][RFR]Update wrapanapi to 3.1.3
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: fix-test, lint-ok

#8689 [RFR] Upstream builds templatized and cloned working for VMware, RHEV, and OSP
  cfme/utils/appliance/db.py
  cfme/utils/template/base.py
  cfme/utils/template/openstack.py
  cfme/utils/template/rhevm.py
  cfme/utils/template/virtualcenter.py
  scripts/clone_template.py
Labels: enhancement, fix-framework, lint-ok

#8691 [1LP][RFR] Cleanup and address test failures in test actions
  cfme/tests/control/test_actions.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: fix-test, lint-ok

#8746 [1LP][RFR] Add in a wait_for LogValidator
  cfme/utils/log_validator.py
Labels: enhancement, lint-ok

#8768 [1LP][RFR] fixed is_displayed for ServerCollectLogsView
  cfme/configure/configuration/diagnostics_settings.py
Labels: fix-framework, lint-ok

#8770 [RFR] Use wait_for_log_validation where possible
  cfme/tests/control/test_actions.py
  cfme/tests/networks/nuage/test_automation.py
Labels: enhancement, lint-ok

#8751 [RFR] Automate test case for testing scvmm mac address
  cfme/tests/infrastructure/test_scvmm_specific.py
Labels: lint-ok, new-test-or-feature

#8762 [WIP] Add test case for bz-1700909
  cfme/tests/infrastructure/test_scvmm_specific.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: WIP, lint-ok, new-test-or-feature
