Repository ManageIQ/integration_tests, pull requests merged in 2019-07, with the labels that each got.

#7875 [1LP][RFR] Add evmserver and appliance restart test for migration
  cfme/tests/v2v/test_v2v_migrations_single_vcenter.py
Labels: lint-ok, new-test-or-feature

#9001 [1LP][RFR] V2v manual tests removed
  cfme/tests/test_manual.py
  cfme/tests/v2v/test_v2v_manual.py
Labels: lint-ok, manual

#9014 [1LP][RFR] make test_collect_single_servers work
  cfme/tests/configure/test_log_depot_operation.py
Labels: fix-test, lint-ok

#8980 [1LP][RFR] Automating Ansible Service Verbosity tests
  cfme/tests/ansible/test_embedded_ansible_manual.py
  cfme/tests/ansible/test_embedded_ansible_services.py
Labels: lint-ok, new-test-or-feature

#9006 [1LP][RFR] Adding new customer test case for ems switches bz 1688900 and vcenter rebuilt bz 1719399
  cfme/tests/infrastructure/test_vmware_provider.py
Labels: customer-case, lint-ok, new-test-or-feature

#9026 [1LP][RFR] removed BZ1717902
  cfme/configure/configuration/diagnostics_settings.py
Labels: blockers-only, lint-ok

#9018 [1LP][RFR]New Test: test_reports_disable_enable_schedule_from_summary
  cfme/intelligence/reports/schedules.py
  cfme/tests/intelligence/reports/test_reports_schedules.py
  widgetastic_manageiq/__init__.py
Labels: lint-ok, new-test-or-feature

#9012 [1LP][RFR] Update Taggable.get_tags
  cfme/common/__init__.py
  cfme/configure/configuration/region_settings.py
  cfme/fixtures/candu.py
  cfme/fixtures/tag.py
  cfme/tests/ansible/test_embedded_ansible_services.py
  cfme/tests/ansible/test_embedded_ansible_tags.py
  cfme/tests/automate/custom_button/test_cloud_objects.py
  cfme/tests/automate/custom_button/test_container_objects.py
  cfme/tests/automate/custom_button/test_generic_objects.py
  cfme/tests/automate/custom_button/test_infra_objects.py
  cfme/tests/automate/custom_button/test_service_objects.py
  cfme/tests/cloud/test_keypairs.py
  cfme/tests/cloud_infra_common/test_provisioning.py
  cfme/tests/cloud_infra_common/test_tag_objects.py
  cfme/tests/infrastructure/test_config_management.py
  cfme/tests/infrastructure/test_vmware_provider.py
Labels: fix-framework, fix-test, lint-ok

#9019 [1LP][RFR] Adding service dialog manual test
  cfme/tests/services/test_dialog_element_in_catalog.py
  cfme/tests/ssui/test_ssui_myservice.py
Labels: lint-ok, manual

#9030 [RFR] retrieve ip and rename happen at the same time
  sprout/appliances/tasks.py
Labels: lint-ok, sprout

#8985 [1LP][RFR] Refactor schedules
  cfme/intelligence/reports/reports.py
  cfme/intelligence/reports/schedules.py
  cfme/tests/intelligence/reports/test_crud.py
  cfme/tests/intelligence/reports/test_reports_schedules.py
  data/schedules_crud/basic01.yaml
Labels: enhancement, lint-ok

#9023 [1LP][RFR] execute cb on service vm
  cfme/tests/automate/custom_button/test_service_objects.py
  cfme/tests/automate/custom_button/test_service_vm_custom_button.py
Labels: lint-ok, new-test-or-feature

#8937 [1LP][RFR]Automate more tests Import/Export report
  cfme/tests/intelligence/reports/test_import_export_reports_widgets.py
  cfme/tests/intelligence/reports/test_reports_manual.py
Labels: lint-ok, new-test-or-feature

#9024 [1LP][RFR]Automate Test: test_new_report_fields
  cfme/tests/intelligence/reports/test_reports.py
  cfme/tests/intelligence/reports/test_reports_manual.py
Labels: lint-ok, new-test-or-feature

#9037 [1LP][RFR] Test case updated with log validator
  cfme/tests/automate/test_instance.py
Labels: enhancement, lint-ok

#8996 [1LP][RFR] Improved guest os reset and shutdown test case for rhv
  cfme/tests/infrastructure/test_vm_power_control.py
Labels: fix-test, lint-ok

#9035 [1LP][RFR] 511 refactor for migration tests
  cfme/fixtures/v2v.py
  cfme/fixtures/v2v_fixtures.py
  cfme/test_framework/pytest_plugin.py
  cfme/tests/v2v/test_conversion_host.py
  cfme/tests/v2v/test_migration_plan.py
  cfme/tests/v2v/test_v2v_ansible.py
  cfme/tests/v2v/test_v2v_migrations.py
  cfme/v2v/infrastructure_mapping.py
  cfme/v2v/migration_plans.py
  cfme/v2v/migrations.py
  entry_points.txt
Labels: fix-framework, lint-ok

#9020 [1LP][RFR] CB attribute override test
  cfme/automate/buttons.py
  cfme/tests/automate/custom_button/test_buttons.py
Labels: lint-ok, new-test-or-feature

#9016 [1LP][RFR] Refactored test_csv_imports.py
  cfme/fixtures/v2v_fixtures.py
  cfme/tests/v2v/test_csv_import.py
Labels: enhancement, fix-test, lint-ok

#9044 [1LP][RFR]Smoke tests v2v
  cfme/tests/v2v/test_v2v_migrations.py
  cfme/tests/v2v/test_v2v_smoke.py
Labels: lint-ok, new-test-or-feature

#9043 [1LP][RFR] Add BZ Blocker for 5.11 bug 1727929
  cfme/tests/configure/test_analysis_profiles.py
Labels: blockers-only, lint-ok

#9041 [1LP][RFR] Adding missing tag manual in service test
  cfme/tests/services/test_catalog_item.py
  cfme/tests/services/test_generic_service_catalogs.py
  cfme/tests/services/test_myservice.py
Labels: lint-ok, manual

#9033 [1LP][RFR] Fix test_provision_approval and Request views
  cfme/services/requests.py
  cfme/tests/cloud_infra_common/test_provisioning.py
Labels: fix-framework, fix-test, lint-ok

#9025 [1LP][WIPTEST] automated BZ1718895
  cfme/tests/infrastructure/test_advanced_search_vms.py
  cfme/tests/webui/test_filter_conditions.py
  widgetastic_manageiq/expression_editor.py
Labels: WIP-testing, lint-ok, new-test-or-feature

#9051 [1LP][RFR][NOTEST] Added manual test case for schedules
  cfme/tests/automate/test_automate_manual.py
Labels: lint-ok, manual

#9056 [1LP][WIPTEST]fixing provider refresh with adding wait_for so that hosts_after count is accurate
  cfme/tests/infrastructure/test_vmware_provider.py
Labels: WIP-testing, fix-test, lint-ok

#9054 [1LP][RFR] Close socket connection in utils.net.check_port
  cfme/utils/net.py
Labels: issue-bug, lint-ok

#9055 [1LP][RFR] Update imports in test_framework/sprout/plugin
  cfme/test_framework/sprout/plugin.py
Labels: issue-bug, lint-ok

#8990 [1LP][RFR] Automate manual tests to see VM is attached to Ansible Service.
  cfme/tests/ansible/test_embedded_ansible_manual.py
  cfme/tests/ansible/test_embedded_ansible_services.py
Labels: lint-ok, new-test-or-feature

#9057 [1LP][RFR] Fixed schema field issue in automate
  cfme/tests/automate/test_class.py
  cfme/tests/automate/test_domain.py
  cfme/tests/automate/test_domain_priority.py
  cfme/tests/automate/test_method.py
  cfme/tests/cloud/test_quota.py
  cfme/tests/intelligence/reports/test_widgets.py
Labels: lint-ok

#9050 [1LP][RFR] Collect memory tests for EC2 instances and Availability zones
  cfme/tests/candu/test_azone_graph.py
  cfme/tests/candu/test_utilization_metrics.py
Labels: blockers-only, lint-ok

#9046 [1LP][RFR] UI change for Hosts & Clusters tab
  cfme/configure/access_control/__init__.py
Labels: blockers-only, fix-locator-or-text, lint-ok

#9049 [1LP][RFR] added forced streams for BZ1707328
  cfme/tests/configure/test_tag.py
Labels: blockers-only, lint-ok

#9040 [1LP][RFR] Chargeback rate edit/delete test fixes
  cfme/intelligence/chargeback/rates.py
  cfme/tests/intelligence/test_chargeback.py
Labels: fix-locator-or-text, fix-test, lint-ok

#9031 [1LP][RFR] Refactor LogValidator
  cfme/tests/ansible/test_embedded_ansible_services.py
  cfme/tests/automate/custom_button/test_infra_objects.py
  cfme/tests/automate/custom_button/test_service_vm_custom_button.py
  cfme/tests/automate/test_domain.py
  cfme/tests/automate/test_instance.py
  cfme/tests/automate/test_method.py
  cfme/tests/automate/test_service_automate.py
  cfme/tests/cli/test_appliance_cli.py
  cfme/tests/cli/test_appliance_console.py
  cfme/tests/configure/test_database_ui.py
  cfme/tests/containers/test_blacklisted_container_events.py
  cfme/tests/containers/test_pause_resume_workers.py
  cfme/tests/control/test_actions.py
  cfme/tests/networks/nuage/test_automation.py
  cfme/tests/services/test_catalog_item.py
  cfme/tests/services/test_rest_services.py
  cfme/tests/test_appliance.py
  cfme/utils/log_validator.py
Labels: enhancement, fix-framework, lint-ok

#9045 [1LP][RFR] Automated BZ1720338
  cfme/fixtures/service_fixtures.py
  cfme/tests/services/test_myservice.py
Labels: customer-case, lint-ok, new-test-or-feature

#9004 [1LP][RFR] Fixed vsphere skiping issue
  cfme/tests/infrastructure/test_child_tenant.py
  cfme/tests/infrastructure/test_project_quota.py
  cfme/tests/infrastructure/test_tenant_quota.py
Labels: fix-test, lint-ok

#9071 [1LP][RFR]: Missing log validator changes
  cfme/tests/automate/custom_button/test_buttons.py
Labels: fix-test, lint-ok

#9072 [1LP][RFR] Update paramiko 2.6
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: lint-ok, other

#9074 [RFR] Update to wrapanapi 3.3.1
  cfme/cloud/provider/openstack.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: enhancement, lint-ok

#9011 [1LP][RFR] New Test: Testing manageiq-password decrypt
  cfme/tests/automate/test_common_methods.py
Labels: lint-ok, new-test-or-feature

#9027 [1LP][RFR] Automate test: test_infrastructure_hosts_icons_states
  cfme/infrastructure/host.py
  cfme/tests/infrastructure/test_host.py
  cfme/tests/test_manual.py
Labels: lint-ok, new-test-or-feature

#8620 [1LP][RFR] Fix test_provisioning.
  cfme/automate/explorer/method.py
  cfme/common/__init__.py
  cfme/configure/configuration/server_settings.py
  cfme/tests/cloud_infra_common/test_provisioning.py
Labels: fix-framework, fix-test, lint-ok

#9059 [1LP][RFR] Fix template upload for scvmm
  cfme/utils/template/scvmm.py
Labels: infra-related, lint-ok

#9080 [1LP][RFR] custom menu manual test
  cfme/tests/automate/custom_button/test_custom_menu.py
Labels: lint-ok, manual

#9078 [1LP][RFR]Adding blocker BZ
  cfme/tests/services/test_myservice.py
Labels: blockers-only, lint-ok

#9042 [1LP][RFR] Move manual testcases
  cfme/tests/automate/test_service_dialog.py
  cfme/tests/cloud_infra_common/test_genealogy.py
  cfme/tests/cloud_infra_common/test_html5_vm_console.py
  cfme/tests/cloud_infra_common/test_vm_ownership.py
  cfme/tests/configure/test_access_control.py
  cfme/tests/integration/test_cfme_auth.py
  cfme/tests/test_login.py
  cfme/tests/test_manual.py
Labels: lint-ok, manual, test-cleanup

#9061 [1LP][RFR] Fixed v2v_providers naming issue
  cfme/tests/cloud_infra_common/test_quota_with_multiple_providers.py
Labels: fix-test, lint-ok

#9073 [RFR] Allow for the event VM_MIGRATION_FAILED
  cfme/tests/infrastructure/test_timelines.py
Labels: fix-locator-or-text, lint-ok

#9077 [RFR] fix test #9011
  cfme/tests/automate/test_common_methods.py
Labels: fix-test, lint-ok

#9069 [1LP][RFR]fix schedules and enhance a test for BZ 1729882
  cfme/intelligence/reports/reports.py
  cfme/intelligence/reports/schedules.py
  cfme/tests/intelligence/reports/test_crud.py
  cfme/tests/intelligence/reports/test_reports_schedules.py
Labels: fix-test, lint-ok

#9082 [1LP][RFR] Add BZ marker and update test_server_name patterns for filling
  cfme/tests/configure/test_server_name.py
  cfme/utils/appliance/__init__.py
Labels: enhancement, lint-ok

#9022 [1LP][RFR] Add BZ blocker for Azure memory metric
  cfme/tests/candu/test_azone_graph.py
  cfme/tests/candu/test_utilization_metrics.py
Labels: blockers-only, lint-ok

#9083 [1LP][RFR] New container crud test and remove flash assert in BaseProvider
  cfme/common/provider.py
  cfme/test_requirements.py
  cfme/tests/containers/test_container_provider_crud.py
Labels: fix-framework, fix-test, lint-ok, new-test-or-feature

#9038 [1LP][RFR] Added Ansible 'Vault' credentials Automation tests.
  cfme/services/catalogs/catalog_items/ansible_catalog_items.py
  cfme/tests/ansible/test_embedded_ansible_manual.py
  cfme/tests/ansible/test_embedded_ansible_services.py
Labels: lint-ok, new-test-or-feature

#9090 [1LP][RFR] removing entity_id type convertion to int
  widgetastic_manageiq/__init__.py
Labels: fix-framework

#9087 [1LP][RFR] Fix is displayed archived instances
  cfme/cloud/instance/__init__.py
  cfme/tests/cloud/test_cloud_timelines.py
Labels: blockers-only, fix-locator-or-text, lint-ok

#9058 [1LP][RFR]Automate test: test_custom_logos_via_api AND add widgets for CustomLo…
  cfme/base/__init__.py
  cfme/base/ui.py
  cfme/tests/test_rest.py
  cfme/tests/test_rest_manual.py
Labels: enhancement, lint-ok, new-test-or-feature

#9093 [1LP][RFR] Remove manual nor/rightsize tests for old providers rhv41 and vsphere55
  cfme/tests/candu/test_nor_rightsize.py
Labels: manual

#9032 [1LP][RFR] Automating Ansible tests for Branched Repo and Link to playbook
  cfme/ansible/repositories.py
  cfme/tests/ansible/test_embedded_ansible_basic.py
  cfme/tests/ansible/test_embedded_ansible_manual.py
Labels: WIP-testing, lint-ok, new-test-or-feature

#9086 [1LP][RFR] Added entry for infra_hosts and assigned me "prichard" to it.
  cfme/test_requirements.py
Labels: lint-ok, manual

#9091 [1LP][RFR]Add manual tests for test coverage
  cfme/tests/configure/test_config_manual.py
  cfme/tests/configure/test_server_name.py
  cfme/tests/infrastructure/test_infra_manual.py
  cfme/tests/intelligence/reports/test_reports_manual.py
  cfme/tests/networks/test_sdn_downloads.py
  cfme/tests/test_rest_manual.py
  cfme/tests/webui/test_general_ui_manual.py
Labels: manual

#9068 [1LP][RFR] block test with BZ-1729594
  cfme/tests/automate/custom_button/test_container_objects.py
  cfme/tests/automate/custom_button/test_service_vm_custom_button.py
Labels: WIP-testing, blockers-only, lint-ok

#9039 [1LP][RFR] fixed random tag selection for 5.11
  cfme/common/__init__.py
  widgetastic_manageiq/__init__.py
Labels: fix-framework, lint-ok

#9095 [1LP][NOTEST][RFR] Removing esx direct host provider test
  cfme/tests/infrastructure/test_esx_direct_host.py
Labels: manual

#9081 [1LP][RFR] adding snippets for quick multi-region env setup
  cfme/scripting/setup_env.py
  cfme/utils/appliance/__init__.py
Labels: enhancement, lint-ok

#8894 [1LP][RFR]Automate test: test_report_edit_secondary_display_filter AND update E…
  cfme/intelligence/reports/reports.py
  cfme/tests/intelligence/reports/test_reports.py
  widgetastic_manageiq/expression_editor.py
Labels: enhancement, lint-ok, new-test-or-feature

#9096 [1LP][WIPTEST] Fix Cloud Intel navigation
  cfme/base/__init__.py
  cfme/base/ui.py
  cfme/dashboard.py
  cfme/intelligence/chargeback/__init__.py
  cfme/intelligence/reports/__init__.py
  cfme/intelligence/reports/reports.py
  cfme/intelligence/rss.py
  cfme/intelligence/timelines.py
  cfme/tests/configure/test_landing_page.py
  cfme/tests/intelligence/reports/test_crud.py
Labels: fix-test, rc-regression-fix

#9047 [1LP][RFR] Fixing 5.10 failures
  cfme/fixtures/v2v_fixtures.py
  cfme/tests/v2v/test_infrastructure_mapping.py
  cfme/tests/v2v/test_migration_plan.py
  cfme/tests/v2v/test_v2v_migrations.py
  cfme/v2v/infrastructure_mapping.py
Labels: fix-test, lint-ok, rc-regression-fix

#9098 [1LP][RFR] Add in internet_connectivity server role for CFME 5.11
  cfme/configure/configuration/server_settings.py
Labels: fix-framework, rc-regression-fix

#9099 [1LP][RFR] Remove manual zone tests that are already automated
  cfme/tests/distributed/test_appliance_manual.py
Labels: manual

#9084 [1LP][RFR] Update NavDropdown use, parametrized locators, SSUI locator changes
  cfme/base/login.py
  cfme/base/ssui.py
  cfme/base/ui.py
  cfme/configure/about.py
  cfme/tests/configure/test_server_name.py
  cfme/tests/ssui/test_ssui_dashboard.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
  widgetastic_manageiq/__init__.py
Labels: enhancement, fix-locator-or-text, fix-test, lint-ok

#9094 [1LP][RFR] update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: doc

#9100 [1LP][RFR] Use common view class for timelines view
  cfme/base/ui.py
  cfme/cloud/availability_zone.py
  cfme/cloud/instance/__init__.py
  cfme/cloud/provider/__init__.py
  cfme/common/__init__.py
  cfme/common/host_views.py
  cfme/common/physical_server_views.py
  cfme/common/physical_switch_views.py
  cfme/common/provider_views.py
  cfme/containers/node.py
  cfme/infrastructure/cluster.py
  cfme/infrastructure/virtual_machines.py
  widgetastic_manageiq/__init__.py
Labels: enhancement, fix-framework

#9107 [1LP][RFR][NOTEST] fix Could not find provider Embedded Ansible
  cfme/infrastructure/cluster.py
  cfme/infrastructure/datastore.py
Labels: fix-framework, lint-ok

#9112 [1LP][RFR] removed duplicate manual azure tests
  cfme/tests/cloud/test_azure_manual.py
Labels: lint-ok, manual

#9108 [1LP][RFR] Fixed CandidateNotFound issue
  widgetastic_manageiq/__init__.py
Labels: fix-locator-or-text, lint-ok

#9114 [1LP][RFR] Nav work around for 5.11.0.16
  cfme/services/myservice/ui.py
Labels: fix-locator-or-text, lint-ok

#9118 [RFR] Add "test" to instance names for OSP tests
  cfme/tests/openstack/cloud/test_flavors.py
  cfme/tests/openstack/cloud/test_instances.py
Labels: issue-bug, lint-ok

#9122 [1LP][RFR] Rename duplicate tests
  cfme/tests/intelligence/reports/test_crud.py
Labels: lint-ok, other

#9121 [1LP][RFR] fixed VolumeAddForm for ec2
  cfme/storage/volume.py
Labels: fix-locator-or-text, lint-ok

#9120 [1LP][RFR] exclude pod tests for 5.11 stream
  cfme/tests/pod/test_appliance_crud.py
Labels: fix-locator-or-text, lint-ok

#9103 [1LP][RFR] Avoid flash check with bz
  cfme/tests/automate/custom_button/test_cloud_objects.py
  cfme/tests/automate/custom_button/test_container_objects.py
  cfme/tests/automate/custom_button/test_service_objects.py
  cfme/tests/automate/custom_button/test_service_vm_custom_button.py
Labels: blockers-only, lint-ok

#9063 [1LP][RFR] Import export collection with File Import
  cfme/automate/explorer/domain.py
  cfme/automate/import_export.py
  cfme/base/ui.py
  cfme/tests/automate/test_git_import.py
  entry_points.txt
Labels: collections-conversion, lint-ok

#9102 [1LP][RFR] Fixed is displayed of cloud provider image view
  cfme/cloud/provider/__init__.py
Labels: fix-framework, lint-ok

#9104 [1LP][RFR][NOTEST] Adding new manual test cases
  cfme/tests/automate/test_automate_manual.py
  cfme/tests/automate/test_method.py
  cfme/tests/cloud_infra_common/test_power_control_manual.py
  cfme/tests/cloud_infra_common/test_relationships.py
  cfme/tests/infrastructure/test_vm_power_control.py
Labels: lint-ok, manual

#9128 [RFR] Use ubuntu 14.04 for travis
  .travis.yml
Labels: lint-ok

#9131 Not at all trusty
  .travis.yml
Labels: infra-related, lint-ok

#9134 [1LP][RFR] Updating fauxfactor to 3.0.6
  requirements/frozen.py3.txt
  requirements/frozen_docs.py3.txt
Labels: lint-ok, other

#9092 [RFR] py3prt
  artifactor/plugins/reporter.py
  cfme/modeling/base.py
  cfme/utils/dockerbot/pytestbase/Dockerfile
  cfme/utils/dockerbot/pytestbase/setup.sh
  requirements/frozen.py3.txt
Labels: enhancement, lint-ok, py3-compat

#9125 [RFR] Add severity to alerts test
  cfme/tests/control/test_alerts.py
Labels: lint-ok, other

#8891 [1LP][RFR] Add test_fixauth_dryrun_has_feedback
  cfme/tests/test_appliance.py
Labels: lint-ok, new-test-or-feature

#9079 [1LP][RFR] RBAC tests refactor
  cfme/tests/configure/test_access_control.py
Labels: lint-ok, other

#9124 [RFR] Block retire test in 5.11, remove unused appliance fixtures
  cfme/tests/control/test_actions.py
Labels: blockers-only, lint-ok

#9140 [RFR] Change iterator use in FirefoxProfile.set_preference
  cfme/utils/browser.py
Labels: lint-ok, py3-compat

#9141 [RFR] Py3 compact
  cfme/utils/ssh.py
  scripts/gen_ssl_cert.py
Labels: enhancement, fix-framework

#9139 [RFR] a few fixes for py3 Prt
  cfme/utils/dockerbot/check_prs.py
  cfme/utils/dockerbot/pytestbase/verify_commit.py
Labels: fix-framework, lint-ok, py3-compat

#9142 Updating requirement versions
  requirements/frozen.py3.txt
  requirements/frozen_docs.py3.txt
Labels: fix-framework, lint-ok

#9028 [1LP][RFR] Fixes for UI navigation in test_paginator_config_pages
  cfme/base/ui.py
  cfme/tests/configure/test_paginator.py
Labels: fix-framework, lint-ok

#9137 [1LP][RFR][NOTEST] Add SSA bz metadata
  cfme/tests/control/test_alerts.py
  cfme/tests/control/test_compliance.py
Labels: lint-ok, manual
