Repository ManageIQ/integration_tests, pull requests merged in 2019-02, with the labels that each got.

#8220 [1LP][RFR] Tests to check post migration vm attributes
  cfme/tests/v2v/test_post_migrations.py
Labels: lint-ok, new-test-or-feature

#8423 [RFR] Fix test_generic_objects_tag_rest by fixing fixtures
  cfme/tests/generic_objects/test_instances.py
Labels: lint-ok, manual

#8424 [1LP][RFR] changed the owner of test_generic_objects_tag_rest
  cfme/tests/generic_objects/test_instances.py
Labels: lint-ok, manual

#8395 [1LP][RFR] Automating test_superadmin_child_tenant_delete_parent_catalog
  cfme/tests/configure/test_access_control.py
Labels: lint-ok, new-test-or-feature

#8412 [1LP][RFR]Automating test unique_automation_domain_name
  cfme/tests/configure/test_access_control.py
Labels: lint-ok, new-test-or-feature

#8389 [1LP][RFR] CB: Event cloud objects
  cfme/cloud/availability_zone.py
  cfme/cloud/security_groups.py
  cfme/networks/cloud_network.py
  cfme/networks/network_router.py
  cfme/networks/security_group.py
  cfme/networks/subnet.py
  cfme/storage/manager.py
  cfme/storage/object_store_container.py
  cfme/storage/volume.py
  cfme/tests/automate/custom_button/test_cloud_objects.py
  cfme/tests/automate/custom_button/test_infra_objects.py
Labels: lint-ok, new-test-or-feature

#8413 [RFR] Improved catalog bundle's 'create' method
  cfme/services/catalogs/catalog_items/catalog_bundles.py
Labels: fix-framework, lint-ok

#8391 [RFR][NOTEST] Distributed manual tests with manual tag
  cfme/tests/automate/test_automate_manual.py
  cfme/tests/automate/test_class.py
  cfme/tests/automate/test_domain.py
  cfme/tests/automate/test_domain_priority.py
  cfme/tests/automate/test_git_import.py
  cfme/tests/automate/test_instance.py
  cfme/tests/automate/test_method.py
  cfme/tests/automate/test_namespace.py
  cfme/tests/automate/test_provisioning_dialogs.py
  cfme/tests/automate/test_smoke.py
  cfme/tests/automate/test_vmware_methods.py
  cfme/tests/cloud/test_instance_power_control.py
  cfme/tests/cloud_infra_common/test_power_control_manual.py
  cfme/tests/cloud_infra_common/test_quota_manual.py
  cfme/tests/cloud_infra_common/test_quota_with_multiple_providers.py
  cfme/tests/cloud_infra_common/test_relationships.py
  cfme/tests/infrastructure/test_child_tenant.py
  cfme/tests/infrastructure/test_quota.py
  cfme/tests/infrastructure/test_quota_tagging.py
  cfme/tests/infrastructure/test_tenant_quota.py
  cfme/tests/infrastructure/test_vm_power_control.py
  cfme/tests/services/test_catalog_item.py
  cfme/tests/test_manual.py
Labels: lint-ok, manual

#7785 [RFR]Added crud test for non global filters
  cfme/ansible_tower/explorer.py
  cfme/ansible_tower/jobs.py
  cfme/cloud/availability_zone.py
  cfme/cloud/flavor.py
  cfme/cloud/host_aggregates.py
  cfme/cloud/keypairs.py
  cfme/cloud/stack.py
  cfme/cloud/tenant.py
  cfme/common/host_views.py
  cfme/common/physical_server_views.py
  cfme/common/provider_views.py
  cfme/containers/build.py
  cfme/containers/provider/__init__.py
  cfme/infrastructure/cluster.py
  cfme/infrastructure/config_management.py
  cfme/infrastructure/resource_pool.py
  cfme/infrastructure/virtual_machines.py
  cfme/networks/views.py
  cfme/storage/object_store_container.py
  cfme/storage/object_store_object.py
  cfme/storage/volume.py
  cfme/storage/volume_backup.py
  cfme/storage/volume_snapshot.py
  cfme/tests/webui/test_advanced_search.py
Labels: lint-ok, new-test-or-feature

#8326 [1LP][WIPTEST] This will fix embedded_ansible_services tests
  cfme/fixtures/ansible_fixtures.py
  cfme/services/catalogs/catalog_items/__init__.py
  cfme/services/catalogs/catalog_items/ansible_catalog_items.py
  cfme/tests/ansible/test_embedded_ansible_services.py
Labels: WIP-testing, fix-test, lint-ok

#8417 [1LP][RFR] V2V fixture file
  cfme/fixtures/v2v.py
  cfme/tests/cloud_infra_common/test_quota_with_multiple_providers.py
  cfme/tests/v2v/test_csv_import.py
  cfme/tests/v2v/test_post_migrations.py
  cfme/tests/v2v/test_v2v_ansible.py
  cfme/tests/v2v/test_v2v_cancel_migrations.py
  cfme/tests/v2v/test_v2v_migrations.py
  cfme/tests/v2v/test_v2v_migrations_single_vcenter.py
  cfme/tests/v2v/test_v2v_migrations_ui.py
  cfme/tests/v2v/test_v2v_schedule_migrations.py
Labels: fix-framework, lint-ok

#8430 [1LP][RFR] Deleted obsolete uncollectifs for sdn_downloads tests
  cfme/tests/networks/test_sdn_downloads.py
Labels: fix-test, lint-ok

#8439 [RFR] tiny fixes necessary for pod tests
  cfme/containers/project.py
Labels: fix-framework, lint-ok

#8436 [1LP][RFR] Adding support of ec2
  cfme/tests/storage/test_manager.py
Labels: lint-ok, new-test-or-feature

#8435 [1LP][RFR] Fixes Ansible crud test.
  cfme/tests/ansible/test_embedded_ansible_crud.py
Labels: fix-test, lint-ok

#8433 [1LP][RFR] Moving SCVMM manual cases
  cfme/tests/infrastructure/test_scvmm_specific.py
  cfme/tests/test_manual.py
Labels: lint-ok, manual

#8252 [1LP][RFR] Added rest migrations tests
  cfme/tests/v2v/test_rest_migrations.py
Labels: lint-ok, new-test-or-feature

#8358 [1LP][RFR] Fixed is_displayed of MethodEditView
  cfme/automate/explorer/__init__.py
  cfme/automate/explorer/domain.py
  cfme/automate/explorer/method.py
  cfme/tests/automate/test_domain.py
  cfme/tests/automate/test_method.py
Labels: fix-framework, lint-ok

#8426 [RFR] Fixed AttributeError for AddCatalogItemView
  cfme/services/catalogs/catalog_items/__init__.py
  cfme/tests/automate/test_git_import.py
Labels: fix-framework, lint-ok

#8414 [1LP][RFR] Add in blocker BZs and fix tests that can be fixed for cloud timelines
  cfme/tests/cloud/test_cloud_timelines.py
  widgetastic_manageiq/__init__.py
Labels: fix-framework, lint-ok

#8442 [1LP][RFR] Adding BZ blocker for Azure
  cfme/tests/candu/test_azone_graph.py
  cfme/tests/candu/test_utilization_metrics.py
Labels: blockers-only, lint-ok

#8427 [1LP][RFR] added second provider to test_tagvis_cloud_provider_children
  cfme/tests/cloud_infra_common/test_relationships.py
Labels: lint-ok, new-test-or-feature

#8421 [1LP][RFR] Allow currently_selected to work with trees with multiple roots
  cfme/intelligence/reports/reports.py
  widgetastic_manageiq/__init__.py
Labels: enhancement, lint-ok

#8429 [1LP][RFR] Manual Services/SSUI/Service dialog cleanup
  cfme/tests/generic_objects/test_definitions.py
  cfme/tests/infrastructure/test_vm_migrate.py
  cfme/tests/services/test_catalog_item.py
  cfme/tests/services/test_different_dialogs_in_catalogs.py
  cfme/tests/services/test_dynamicdd_dialogelement.py
  cfme/tests/services/test_myservice.py
  cfme/tests/services/test_service_catalogs.py
  cfme/tests/ssui/test_ssui_service_catalogs.py
  cfme/tests/test_manual.py
Labels: lint-ok, manual

#8444 [1LP][RFR] ignore extdb templates in sprout
  sprout/appliances/tasks.py
Labels: lint-ok, sprout

#8446 [RFR] fix rhevm template scripts
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: fix-framework, lint-ok

#7681 [1LP][RFR] Fix snapshot memory checkbox for 5.10
  cfme/infrastructure/virtual_machines.py
  widgetastic_manageiq/__init__.py
Labels: fix-framework, lint-ok

#8369 [1LP][RFR] New tagging updates
  cfme/common/__init__.py
  cfme/containers/project.py
  cfme/containers/provider/__init__.py
  cfme/tests/containers/test_tags.py
Labels: enhancement, lint-ok, new-test-or-feature

#8432 [1LP][RFR] Adding tests for Ansible Workflow jobs
  cfme/tests/services/test_config_provider_servicecatalogs.py
Labels: lint-ok, new-test-or-feature

#8450 [1LP][RFR] Update wt.patternfly requirements to 0.0.41 and remove root_items
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
  widgetastic_manageiq/__init__.py
Labels: enhancement, lint-ok

#8440 [1LP][RFR] Added test_storage_manager_navigation_from_cloudprovider
  cfme/tests/storage/test_manager.py
Labels: lint-ok, new-test-or-feature

#8447 [1LP][RFR] Reassign test_vm_create to jdupuy
  cfme/tests/cloud_infra_common/test_events.py
Labels: fix-locator-or-text, lint-ok

#8445 [1LP][RFR] Adding BZ blocker for Azure candu graph tests
  cfme/tests/candu/test_vm_graph.py
Labels: blockers-only, lint-ok

#8448 [1LP][RFR] a few small test fixes
  cfme/tests/pod/test_appliance_crud.py
  cfme/tests/pod/test_db_backup_restore.py
  cfme/tests/pod/test_ext_auth.py
  cfme/tests/v2v/test_v2v_migrations_ui.py
Labels: fix-test, lint-ok

#8434 [1LP][RFR] CB: Simulation
  cfme/automate/buttons.py
  cfme/base/ui.py
  cfme/tests/automate/custom_button/test_buttons.py
Labels: enhancement, lint-ok

#8459 [WIPTEST] Fix pytest_generate_tests for test_vm_instance_analysis
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
Labels: WIP-testing, fix-test, lint-ok

#8461 [RFR] fixed FixtureLookupError bug
  cfme/tests/configure/test_register_appliance.py
Labels: fix-test, lint-ok, rc-regression-fix

#8463 [1LP][RFR] Update Appliance.fix_ntp_clock
  cfme/utils/appliance/__init__.py
  scripts/ntp_clock_set.py
  sprout/appliances/tasks.py
Labels: fix-framework, lint-ok

#8467 [1LP][RFR] fix appliance test in 5.10
  cfme/tests/cli/test_appliance_console.py
Labels: fix-test, lint-ok

#8469 [1LP][RFR] fixing quickstart tests
  cfme/scripting/quickstart/system.py
  cfme/scripting/tests/test_quickstart.py
Labels: fix-framework, lint-ok

#8466 [1LP][RFR] a few useful chrome browser options
  cfme/utils/browser.py
Labels: enhancement, lint-ok

#8455 [1LP][RFR][NOTEST] Reassign generic object test and remove manual test case
  cfme/tests/generic_objects/test_definitions.py
Labels: lint-ok, manual

#8452 [1LP][RFR] Fix No providers available skip message.
  cfme/fixtures/cli.py
Labels: fix-locator-or-text, lint-ok

#8451 [1LP][RFR] Ignore providers based on use_for_sprout
  sprout/appliances/tasks.py
  sprout/sprout/settings.py
Labels: lint-ok, sprout

#8437 [1LP][RFR][NOTEST] Remove BZ meta and unassign a test case
  cfme/intelligence/reports/reports.py
  cfme/tests/cloud_infra_common/test_provisioning.py
  cfme/tests/infrastructure/test_provisioning_rest.py
  cfme/tests/perf/workloads/test_provisioning.py
Labels: blockers-only, lint-ok

#6668 [WIPTEST] Remove unneeded BZ blockers from custom attributes tests
  cfme/tests/cloud_infra_common/test_custom_attributes_rest.py
Labels: blockers-only, lint-ok

#7249 [RFR] Fixed prints
  cfme/fixtures/rdb.py
  data/bundles/merkyl/__init__.py
  scripts/gh-find.py
Labels: lint-ok

#8477 [RFR]V2V widgets
  widgetastic_manageiq/__init__.py
Labels: enhancement, fix-framework, lint-ok

#8478 [1LP][RFR] Fix poke_trackerbot sprout task
  sprout/appliances/tasks.py
Labels: issue-bug, lint-ok, sprout

#8208 [1LP][RFR] Fix dashboard tests
  cfme/intelligence/reports/dashboards.py
  cfme/intelligence/reports/reports.py
  cfme/intelligence/reports/widgets/__init__.py
  cfme/tests/intelligence/reports/test_crud.py
  cfme/tests/intelligence/test_dashboard.py
  cfme/utils/bz.py
Labels: fix-locator-or-text, lint-ok

#8483 [1LP][RFR] fixing broken provider object comparison
  cfme/cloud/provider/__init__.py
  cfme/cloud/provider/azure.py
  cfme/cloud/provider/ec2.py
  cfme/cloud/provider/gce.py
  cfme/cloud/provider/openstack.py
  cfme/cloud/provider/vcloud.py
  cfme/common/provider.py
  cfme/containers/provider/__init__.py
  cfme/containers/provider/openshift.py
  cfme/infrastructure/provider/__init__.py
  cfme/infrastructure/provider/kubevirt.py
  cfme/infrastructure/provider/openstack_infra.py
  cfme/infrastructure/provider/rhevm.py
  cfme/infrastructure/provider/scvmm.py
  cfme/infrastructure/provider/virtualcenter.py
  cfme/networks/provider/__init__.py
  cfme/networks/provider/nuage.py
  cfme/physical/provider/__init__.py
  cfme/physical/provider/lenovo.py
  cfme/physical/provider/redfish.py
Labels: fix-framework, lint-ok

#8474 [1LP][RFR] fixed permissions issue and ubuntu version in quickstart scripts and tests
  cfme/scripting/quickstart/system.py
  cfme/scripting/tests/test_quickstart.py
Labels: fix-test, lint-ok

#8484 [1LP][RFR][NOTEST] Removed manual tests from test_manual.py file
  cfme/tests/test_manual.py
Labels: lint-ok, manual

#7802 [1LP][RFR] Add logrotate tests.
  cfme/tests/cli/test_appliance_log_rotate.py
  cfme/tests/test_appliance.py
Labels: lint-ok, new-test-or-feature

#8476 [1LP][RFR] Add in automation test-coverage for BZ 1658670
  cfme/control/explorer/alerts.py
  cfme/tests/control/test_bugs.py
Labels: lint-ok, new-test-or-feature

#8481 [1LP][RFR] handle ntp server set up issues during appliance pre-configuration
  cfme/utils/appliance/__init__.py
  sprout/appliances/tasks.py
Labels: fix-framework, lint-ok

#8482 [1LP][RFR] remove automate_menu_name
  cfme/automate/__init__.py
  cfme/automate/dialogs/__init__.py
  cfme/automate/explorer/__init__.py
  cfme/automate/provisioning_dialogs.py
  cfme/base/ui.py
Labels: fix-locator-or-text, lint-ok

#8468 [1LP][RFR] Add test cases for BZ
  cfme/tests/configure/test_workers.py
Labels: lint-ok, new-test-or-feature

#7183 [1LP][WIPTEST] Changes to allow the report to be stored inside the artifact run dir
  artifactor/__init__.py
  artifactor/plugins/reporter.py
Labels: WIP-testing, enhancement, lint-ok

#8465 [1LP][RFR] Adding ONE_PER_TYPE in ssui/services tests
  cfme/tests/cloud_infra_common/test_cockpit_server.py
  cfme/tests/services/test_add_remove_vm_to_service.py
  cfme/tests/services/test_cloud_service_catalogs.py
  cfme/tests/services/test_different_dialogs_in_catalogs.py
  cfme/tests/services/test_myservice.py
  cfme/tests/services/test_provision_stack.py
  cfme/tests/services/test_request.py
  cfme/tests/services/test_service_catalogs.py
  cfme/tests/services/test_service_manual_approval.py
  cfme/tests/services/test_service_rbac.py
  cfme/tests/ssui/test_ssui_dashboard.py
  cfme/tests/ssui/test_ssui_myservice.py
  cfme/tests/ssui/test_ssui_service_catalogs.py
Labels: fix-locator-or-text, lint-ok

#8464 [1LP][RFR] CB rest crud operation
  cfme/rest/gen_data.py
  cfme/tests/automate/custom_button/__init__.py
  cfme/tests/automate/custom_button/test_rest.py
  cfme/tests/automate/custom_button/test_rest_custom_button.py
  cfme/tests/automate/test_rest.py
Labels: lint-ok, new-test-or-feature

#8491 [1LP][RFR]Fix import formatting in test_rest_custom_button
  cfme/tests/automate/custom_button/test_rest_custom_button.py
Labels: blackify, lint-ok

#8205 [1LP][RFR] Test network port details
  cfme/networks/__init__.py
  cfme/networks/network_port.py
  cfme/networks/subnet.py
  cfme/networks/views.py
  cfme/tests/networks/nuage/test_inventory.py
Labels: lint-ok, new-test-or-feature

#8373 [1LP][RFR] This will separate manual_tests
  cfme/tests/ansible/test_embedded_ansible_manual.py
  cfme/tests/cloud_infra_common/test_vm_instance_analysis_manual.py
  cfme/tests/test_manual.py
Labels: lint-ok, manual

#8460 [1LP][RFR] Fix for test_custom_button_expression by allowing tags to be read
  cfme/services/myservice/ui.py
  cfme/tests/automate/custom_button/test_service_objects.py
Labels: fix-framework, lint-ok

#8479 [1LP][RFR]Fix is_displayed for service retirement date
  cfme/services/myservice/ui.py
  cfme/tests/services/test_myservice.py
Labels: fix-locator-or-text, lint-ok

#8488 [1LP][RFR] Fix invalid cred test for Ansible
  cfme/tests/infrastructure/test_config_management.py
Labels: fix-test, lint-ok

#8492 [1LP][RFR] Add new manual test case for Node Utlization graphs
  cfme/tests/containers/test_overview_data_integrity.py
Labels: lint-ok, manual

#8454 [1LP][RFR] Fix test_cloud_events for changes in 5.10 vs 5.9
  cfme/tests/cloud/test_cloud_events.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
Labels: fix-test, lint-ok

#8494 [1LP][RFR]Tests ssui/services tests cleanup
  cfme/tests/automate/test_service_dialog.py
  cfme/tests/services/test_catalog.py
  cfme/tests/services/test_catalog_item.py
  cfme/tests/services/test_generic_service_catalogs.py
  cfme/tests/services/test_request.py
  cfme/tests/services/test_rest_services.py
  cfme/tests/services/test_service_manual_approval.py
  cfme/tests/ssui/test_ssui_ansible_service.py
  cfme/tests/ssui/test_ssui_dashboard.py
  cfme/tests/ssui/test_ssui_myservice.py
  cfme/tests/ssui/test_ssui_service_catalogs.py
  cfme/tests/ssui/test_ssui_service_dialog.py
Labels: lint-ok, manual

#8471 [1LP][RFR]New Test: test_report_fullscreen_enabled
  cfme/intelligence/reports/reports.py
  cfme/tests/intelligence/reports/test_reports_manual.py
  cfme/tests/intelligence/reports/test_tenant_quota_reports.py
Labels: lint-ok, new-test-or-feature

#8496 [1LP][RFR] fix provisioning tests
  cfme/cloud/instance/azure.py
  cfme/cloud/instance/openstack.py
  cfme/tests/cloud_infra_common/test_provisioning.py
Labels: fix-test, lint-ok

#8475 [1LP][RFR] New Navigate Key to Force Navigation and Remove Browser Refreshes
  cfme/configure/access_control/__init__.py
  cfme/containers/image.py
  cfme/containers/provider/__init__.py
  cfme/tests/containers/test_cockpit.py
  cfme/tests/containers/test_containers_smartstate_analysis.py
  cfme/tests/containers/test_containers_smartstate_analysis_multiple_images.py
  cfme/tests/containers/test_labels.py
  cfme/tests/containers/test_manageiq_ansible_custom_attributes.py
  cfme/tests/containers/test_provider_openscap_policy_attached.py
  cfme/tests/containers/test_ssa_set_cve_image_inspector_per_provider.py
  cfme/tests/containers/test_static_custom_attributes.py
  cfme/utils/appliance/implementations/ssui.py
  cfme/utils/appliance/implementations/ui.py
Labels: enhancement, lint-ok

#8493 [1LP][RFR] This PR updates files for global fixture and removes depricated arguments
  cfme/tests/cloud/test_quota.py
  cfme/tests/cloud/test_quota_tagging.py
  cfme/tests/cloud/test_tenant.py
  cfme/tests/cloud/test_tenant_quota.py
  cfme/tests/cloud_infra_common/test_discovery.py
  cfme/tests/cloud_infra_common/test_quota_with_multiple_providers.py
  cfme/tests/cloud_infra_common/test_relationships.py
  cfme/tests/infrastructure/test_child_tenant.py
  cfme/tests/infrastructure/test_project_quota.py
  cfme/tests/infrastructure/test_quota.py
  cfme/tests/infrastructure/test_quota_tagging.py
  cfme/tests/infrastructure/test_tenant_quota.py
  cfme/tests/infrastructure/test_vm_ownership.py
Labels: fix-locator-or-text, lint-ok

#8499 [1LP][WIPTEST] Do not collect kubevirt or vSphere-IMS providers
  cfme/tests/cloud_infra_common/test_events.py
  cfme/tests/control/test_alerts.py
  cfme/tests/infrastructure/test_timelines.py
Labels: WIP-testing, fix-test, lint-ok

#8501 [RFR] Fix for test generic_buttons
  cfme/services/myservice/ui.py
  cfme/tests/generic_objects/test_instances.py
Labels: fix-test

#8506 [1LP][RFR] bump selenium client version to selenium server version
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
  requirements/template_docs.txt
Labels: issue-bug, lint-ok, rc-regression-fix

#8503 [RFR] Fix service bundles in bundle test
  cfme/tests/services/test_generic_service_catalogs.py
Labels: blockers-only, lint-ok, rc-regression-fix

#8508 [1LP][RFR] Update tests and fixtures to resolve KeyError on yaml keyword
  cfme/fixtures/provider.py
  cfme/tests/cloud_infra_common/test_discovery.py
  cfme/tests/cloud_infra_common/test_vm_ownership.py
  cfme/tests/storage/test_volume.py
  cfme/tests/storage/test_volume_backup.py
  cfme/tests/storage/test_volume_snapshot.py
Labels: fix-test, lint-ok, rc-regression-fix

#8507 [1LP][RFR] fixed storage container tests
  cfme/storage/object_store_container.py
Labels: fix-framework, lint-ok, rc-regression-fix

#8513 [1LP][RFR] Remove the in_version variable, as it is unused
  cfme/cloud/provider/vcloud.py
  cfme/containers/provider/__init__.py
  cfme/networks/balancer.py
  cfme/networks/cloud_network.py
  cfme/networks/floating_ips.py
  cfme/networks/network_port.py
  cfme/networks/network_router.py
  cfme/networks/provider/__init__.py
  cfme/networks/provider/nuage.py
  cfme/networks/security_group.py
  cfme/networks/subnet.py
Labels: fix-framework, lint-ok

#8490 [1LP][RFR] Adding global fixtures and formatting tests according to it
  cfme/automate/explorer/klass.py
  cfme/fixtures/automate.py
  cfme/test_framework/pytest_plugin.py
  cfme/tests/automate/test_class.py
  cfme/tests/automate/test_domain.py
  cfme/tests/automate/test_instance.py
  cfme/tests/automate/test_method.py
  cfme/tests/automate/test_namespace.py
  cfme/tests/automate/test_smoke.py
  cfme/tests/automate/test_vmware_methods.py
Labels: enhancement, lint-ok

#8516 [1LP][RFR] Fix scopes for snapshot tests
  cfme/tests/infrastructure/test_snapshot.py
Labels: fix-locator-or-text, lint-ok

#8515 [RFR] fixed fixture scope mismatch
  cfme/tests/infrastructure/test_vm_reconfigure.py
Labels: WIP-testing, fix-test, lint-ok

#8504 [1LP][RFR] Fix event cloud object test
  cfme/cloud/availability_zone.py
  cfme/networks/cloud_network.py
  cfme/storage/object_store_container.py
  cfme/tests/automate/custom_button/test_cloud_objects.py
Labels: fix-framework, lint-ok

#8524 [RFR] Fix UnboundLocalError in test_resource_allocation
  cfme/tests/intelligence/chargeback/test_resource_allocation.py
Labels: fix-test, lint-ok
