Repository ManageIQ/integration_tests, pull requests merged in 2019-05, with the labels that each got.

#8774 [1LP][RFR] Update openshift template upload, block 5.11
  cfme/utils/template/rhopenshift.py
Labels: infra-related, lint-ok

#8769 [1LP][RFR]Adding new test for customer BZ 1695008
  cfme/tests/infrastructure/test_vmware_provider.py
Labels: lint-ok, manual

#8775 [RFR] Update Providers page in sprout
  sprout/appliances/templates/appliances/providers.html
Labels: lint-ok, sprout

#8776 [1LP][RFR] fix cb group view for 511
  cfme/automate/buttons.py
Labels: fix-framework, lint-ok

#8761 [1LP][RFR] V2V CSV test
  cfme/tests/v2v/test_csv_import.py
  cfme/v2v/migration_plans.py
Labels: fix-test, lint-ok

#8752 [1LP][RFR]Rectify create_rest method for rsa credentials
  cfme/common/provider.py
Labels: enhancement, lint-ok

#8785 [RFR] Random updates related to vsphere55 yaml cleanup
  cfme/tests/configure/test_proxy.py
  cfme/tests/distributed/test_appliance_replication.py
  cfme/tests/v2v/test_csv_import.py
  cfme/utils/appliance/__init__.py
  conf/cfme_data.yaml.template
  scripts/clone_template.py
Labels: enhancement, lint-ok, tech-debt

#8784 [RFR] Update provider check in shepherd task
  sprout/appliances/tasks.py
Labels: WIP-testing, lint-ok, sprout

#8773 [1LP][RFR]Fixed some method names
  cfme/tests/v2v/test_migration_plan.py
  cfme/tests/v2v/test_post_migrations.py
  cfme/tests/v2v/test_v2v_ansible.py
  cfme/v2v/migration_plans.py
Labels: enhancement, lint-ok

#8789 [RFR] Skip plugin config when --help is passed
  cfme/fixtures/artifactor_plugin.py
  cfme/fixtures/node_annotate.py
  cfme/fixtures/parallelizer/__init__.py
  cfme/fixtures/portset.py
  cfme/fixtures/prov_filter.py
  cfme/fixtures/templateloader.py
  cfme/fixtures/ui_coverage.py
  cfme/markers/skipper.py
  cfme/test_framework/appliance.py
Labels: enhancement, lint-ok

#8793 [RFR] added block for BZ1707328
  cfme/tests/configure/test_tag.py
Labels: blockers-only, lint-ok

#8795 [RFR][NOTEST] reassigned test_puma_server
  cfme/tests/test_manual.py
Labels: lint-ok, manual

#8738 [1LP][RFR] CB service vm display test
  cfme/fixtures/service_fixtures.py
  cfme/services/myservice/ssui.py
  cfme/services/myservice/ui.py
  cfme/services/requests.py
  cfme/tests/automate/custom_button/test_service_vm_custom_button.py
Labels: enhancement, lint-ok, new-test-or-feature

#8779 [1LP][RFR] fix setting configuration nav 511
  cfme/base/login.py
  cfme/base/ui.py
Labels: fix-framework, lint-ok

#8781 [1LP][RFR] fix simulation 511 changes
  cfme/automate/buttons.py
  cfme/tests/automate/custom_button/test_buttons.py
Labels: fix-framework, lint-ok

#8796 [1LP][RFR] Adding actions metadata for the tests in test_actions
  cfme/tests/control/test_actions.py
Labels: lint-ok, manual

#7820 [1LP][RFR] Codename tests
  cfme/tests/test_appliance.py
Labels: lint-ok, new-test-or-feature

#8749 [1LP][RFR] Retry ssh connection if failed.
  cfme/utils/appliance/__init__.py
  cfme/utils/ssh.py
Labels: enhancement, fix-framework, lint-ok

#8787 [1LP][RFR][NOTEST] reassigned test_email
  cfme/tests/configure/test_email.py
Labels: lint-ok, manual

#8802 [NOTEST]Chown of TestCases to nachandr
  cfme/tests/configure/test_access_control.py
Labels: fix-locator-or-text, lint-ok

#8741 [1LP][RFR] Schedule migration refactor
  cfme/tests/v2v/test_v2v_schedule_migrations.py
  cfme/v2v/migration_plans.py
Labels: enhancement, lint-ok

#8753 [1LP][RFR] CB catalog crud test and small refactor.
  cfme/automate/buttons.py
  cfme/services/catalogs/catalog_items/__init__.py
  cfme/tests/automate/custom_button/test_catalog_custom_button.py
  widgetastic_manageiq/__init__.py
Labels: enhancement, lint-ok, new-test-or-feature

#8800 [1LP][RFR] 511 open url only for vm/instance and BZ-1706900
  cfme/tests/automate/custom_button/test_buttons.py
Labels: blockers-only, lint-ok

#8799 [1LP][RFR] Blocking test_chargeback_containers for now
  cfme/tests/containers/test_chargeback.py
Labels: lint-ok, tech-debt

#8792 [1LP][RFR][NOTEST] Added new manual test case
  cfme/tests/cloud_infra_common/test_quota_manual.py
Labels: lint-ok, manual

#8806 [1LP][RFR] Update composite-uncollect timeout
  cfme/utils/trackerbot.py
Labels: enhancement, lint-ok

#8808 [RFR] Fix parallelizer decode
  cfme/fixtures/parallelizer/__init__.py
Labels: fix-framework, lint-ok

#8780 [1LP][RFR] New Test: Removal of openshift "Deployment" from automate domain
  cfme/tests/automate/test_automate_manual.py
  cfme/tests/automate/test_namespace.py
Labels: lint-ok, new-test-or-feature

#8814 [1LP][RFR] Change appliance instantiation to use from_provider
  cfme/utils/appliance/__init__.py
Labels: fix-framework, lint-ok

#8457 [1LP][RFR] Storage volume tests also for ec2
  cfme/storage/manager.py
  cfme/storage/volume.py
  cfme/tests/storage/test_volume.py
Labels: enhancement, lint-ok, new-test-or-feature

#8803 [1LP][RFR] Automate test: test_delete_automate_domain_via_api
  cfme/tests/automate/test_rest.py
  cfme/tests/test_rest_manual.py
Labels: lint-ok, new-test-or-feature

#8788 [1LP][RFR] Fix storage navigation
  cfme/ansible/credentials.py
  cfme/ansible/playbooks.py
  cfme/ansible/repositories.py
  cfme/cloud/availability_zone.py
  cfme/cloud/flavor.py
  cfme/cloud/keypairs.py
  cfme/cloud/provider/__init__.py
  cfme/cloud/security_groups.py
  cfme/cloud/stack.py
  cfme/common/host_views.py
  cfme/containers/node.py
  cfme/infrastructure/cluster.py
  cfme/infrastructure/deployment_roles.py
  cfme/infrastructure/resource_pool.py
  cfme/modeling/base.py
  cfme/networks/views.py
  cfme/storage/manager.py
  cfme/storage/object_store_container.py
  cfme/storage/object_store_object.py
  cfme/storage/volume.py
  cfme/storage/volume_backup.py
  cfme/storage/volume_snapshot.py
  cfme/storage/volume_type.py
Labels: fix-framework, lint-ok

#8812 [RFR] [NOTEST] Re-assigning and Adding testSteps to Maunal tests.
  cfme/tests/cli/test_appliance_cli.py
  cfme/tests/cli/test_appliance_console.py
Labels: lint-ok, manual

#8797 [RFR] Move manual update cases
  cfme/tests/cli/test_appliance_update_manual.py
  cfme/tests/cloud_infra_common/test_provisioning_manual.py
  cfme/tests/configure/test_proxy.py
  cfme/tests/distributed/test_appliance_replication.py
  cfme/tests/platform/test_locale.py
  cfme/tests/test_manual.py
Labels: lint-ok, manual

#8815 [1LP][RFR] Add ui_protocol to Appliance.from_provider for provision_appliance
  cfme/utils/appliance/__init__.py
Labels: fix-framework, lint-ok

#8701 [1LP][RFR]V2V migration tests
  cfme/fixtures/v2v_fixtures.py
  cfme/tests/v2v/test_v2v_migrations.py
  cfme/v2v/infrastructure_mapping.py
  cfme/v2v/migration_plans.py
Labels: enhancement, lint-ok

#8636 [1LP][RFR] Move snapshot manual tests
  cfme/tests/cloud/test_snapshot.py
  cfme/tests/infrastructure/test_snapshot.py
  cfme/tests/test_manual.py
Labels: lint-ok, manual

#8821 [RFR] Add a wait_for in getting the server_names
  cfme/tests/cli/test_evmserverd.py
Labels: fix-test, lint-ok, rc-regression-fix

#8822 [1LP][RFR] Add a skip if the template is not available in customization templates
  cfme/tests/services/test_iso_service_catalogs.py
Labels: lint-ok, rc-regression-fix

#8823 [1LP][RFR] Fix TypeError in Latest RC Run
  cfme/automate/buttons.py
  cfme/rest/gen_data.py
  cfme/storage/volume.py
  cfme/tests/ansible/test_embedded_ansible_automate.py
  cfme/tests/storage/test_volume_backup.py
Labels: fix-test, lint-ok, rc-regression-fix

#8830 [1LP][RFR][NOTEST] Re-assigning Test cases to new FA owner
  cfme/tests/cli/test_appliance_cli.py
  cfme/tests/cli/test_appliance_console.py
Labels: fix-locator-or-text, lint-ok

#8817 [1LP][RFR] refactor cleanup_edomain_templates
  cfme/fixtures/ssh_client.py
  cfme/utils/log.py
  cfme/utils/ssh.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
  scripts/cleanup_edomain_templates.py
Labels: enhancement, infra-related, lint-ok

#8834 [1LP][RFR][NOTEST] Adding manual_tests
  cfme/tests/ansible/test_embedded_ansible_manual.py
Labels: lint-ok, manual

#8827 [1LP][RFR][NOTEST] Added manual test case
  cfme/tests/automate/test_automate_manual.py
  cfme/tests/automate/test_method.py
Labels: lint-ok, manual

#8804 [1LP][RFR] Migration rest tests refactor
  cfme/tests/v2v/test_rest_migrations.py
Labels: fix-test, lint-ok

#8805 [1LP][RFR] Automate test: test_welcoming_page
  cfme/common/provider_views.py
  cfme/tests/webui/test_general_ui.py
Labels: lint-ok

#8832 [RFR] Update wt.pf, fix test_provisioning fixtures, add remote_console role
  cfme/configure/configuration/server_settings.py
  cfme/tests/cloud_infra_common/test_provisioning.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: fix-framework, fix-test, lint-ok

#8838 [1LP][RFR] fix Cloud NW Details view
  cfme/networks/views.py
Labels: fix-locator-or-text, lint-ok

#8771 [1LP][RFR] New Test: Testing automate method of sending emails
  cfme/tests/automate/test_method.py
Labels: lint-ok, new-test-or-feature

#8846 fix miq run test exit code
  cfme/scripting/runtest.py
Labels: fix-framework, lint-ok

#8842 [1LP][RFR][NOTEST] Removing Duplicate Test Cases
  cfme/tests/test_appliance.py
Labels: lint-ok, manual

#8849 [1LP][RFR][NOTEST] Re-assigning 'access' requirement owner.
  cfme/test_requirements.py
Labels: lint-ok, manual

#7485 [RFR] Update sync_template_tracker, ignore AMI
  cfme/utils/template/base.py
  cfme/utils/template/rhopenshift.py
  cfme/utils/trackerbot.py
  scripts/sync_template_tracker.py
Labels: enhancement, infra-related, lint-ok

#8837 [1LP][RFR] Fixed test cases related to automate in 5.11
  cfme/automate/explorer/domain.py
  cfme/automate/explorer/instance.py
  cfme/automate/explorer/klass.py
  cfme/automate/explorer/method.py
  cfme/automate/explorer/namespace.py
  cfme/tests/automate/test_domain.py
  cfme/tests/automate/test_method.py
Labels: fix-framework, fix-test, lint-ok

#8791 [1LP][RFR] modified blocker for test_provider_log_level
  cfme/tests/configure/test_logs.py
Labels: blockers-only, lint-ok

#8772 [1LP][RFR]Single Vcenter tests
  cfme/tests/v2v/test_v2v_migrations_single_vcenter.py
  cfme/v2v/migration_plans.py
Labels: fix-test, lint-ok

#8473 [1LP][WIPTEST] This PR will fix SSA tests.
  cfme/common/__init__.py
  cfme/tests/cloud_infra_common/test_vm_instance_analysis.py
Labels: WIP-testing, fix-test, lint-ok

#8706 [1LP][RFR] New Test: Testing quota with service dialog using automate method
  cfme/services/requests.py
  cfme/tests/cloud/test_quota.py
  cfme/tests/cloud_infra_common/test_quota_manual.py
Labels: lint-ok, new-test-or-feature

#8710 [1LP][RFR] Adding service dialog manual test cases
  cfme/tests/services/test_dialog_element_in_catalog.py
  cfme/tests/services/test_dialog_regex_validation_in_catalog.py
  cfme/tests/services/test_different_dialogs_in_catalogs.py
Labels: lint-ok, manual

#8745 [1LP][RFR] New tests for BZs qe_test_coverage
  cfme/tests/cloud/test_snapshot.py
  cfme/tests/configure/test_access_control.py
  cfme/tests/infrastructure/test_vm_reconfigure.py
  cfme/tests/ssui/test_ssui_myservice.py
Labels: lint-ok, manual, new-test-or-feature

#8754 [1LP][RFR] Automate config manager tests for REST
  cfme/infrastructure/config_management.py
  cfme/tests/infrastructure/test_config_management_rest.py
  cfme/tests/test_rest_manual.py
Labels: lint-ok, new-test-or-feature

#8766 [1LP][RFR] Migration UI refactor
  cfme/fixtures/v2v_fixtures.py
  cfme/tests/v2v/test_v2v_migrations_ui.py
  cfme/v2v/infrastructure_mapping.py
  cfme/v2v/migration_plans.py
Labels: enhancement, fix-framework, lint-ok

#8852 [1LP][RFR] Add requirements to all tests
  cfme/test_requirements.py
  cfme/tests/ansible/test_embedded_ansible_rest.py
  cfme/tests/automate/test_customization_paginator.py
  cfme/tests/automate/test_rest.py
  cfme/tests/cloud/test_instance_power_control.py
  cfme/tests/cloud_infra_common/test_power_control_rest.py
  cfme/tests/cloud_infra_common/test_provisioning.py
  cfme/tests/cloud_infra_common/test_snapshots_rest.py
  cfme/tests/configure/test_config_manual.py
  cfme/tests/configure/test_default_filters.py
  cfme/tests/configure/test_default_views_cloud.py
  cfme/tests/configure/test_default_views_infra.py
  cfme/tests/configure/test_landing_page.py
  cfme/tests/configure/test_rest_access_control.py
  cfme/tests/configure/test_session_timeout.py
  cfme/tests/configure/test_tag.py
  cfme/tests/configure/test_tag_category.py
  cfme/tests/configure/test_timeprofile.py
  cfme/tests/configure/test_visual_cloud.py
  cfme/tests/configure/test_visual_infra.py
  cfme/tests/control/test_rest_control.py
  cfme/tests/generic_objects/test_instances.py
  cfme/tests/infrastructure/test_config_management_rest.py
  cfme/tests/infrastructure/test_provider_discovery.py
  cfme/tests/infrastructure/test_provisioning_rest.py
  cfme/tests/infrastructure/test_rest_automation_request.py
  cfme/tests/infrastructure/test_rest_templates.py
  cfme/tests/infrastructure/test_system_image_type.py
  cfme/tests/infrastructure/test_vm_ownership.py
  cfme/tests/infrastructure/test_vm_reconfigure.py
  cfme/tests/infrastructure/test_vm_rest.py
  cfme/tests/infrastructure/test_vm_retirement_rest.py
  cfme/tests/intelligence/reports/test_crud.py
  cfme/tests/intelligence/reports/test_menus.py
  cfme/tests/intelligence/reports/test_report_corresponds.py
  cfme/tests/intelligence/reports/test_reports.py
  cfme/tests/intelligence/reports/test_reports_manual.py
  cfme/tests/intelligence/test_download_report.py
  cfme/tests/openstack/cloud/test_flavors.py
  cfme/tests/services/test_rest_services.py
  cfme/tests/services/test_service_catalogs.py
  cfme/tests/test_rest_manual.py
  cfme/tests/webui/test_rest.py
  conf/polarion_tools.yaml
Labels: fix-test, lint-ok

#8845 [1LP][RFR] Fix test_set_retirement_date failures
  cfme/common/vm_views.py
Labels: fix-framework, lint-ok

#8857 [RFR][NOTEST]Remove unnecessary tests
  cfme/tests/intelligence/reports/test_reports_manual.py
Labels: lint-ok, manual, tech-debt

#8853 [RFR] Update template_upload to block providers on streams
  cfme/utils/template/base.py
  cfme/utils/template/ec2.py
  cfme/utils/template/gce.py
  cfme/utils/template/rhopenshift.py
  cfme/utils/template/template_upload.py
Labels: enhancement, infra-related, lint-ok

#8831 [1LP][RFR] Automate BZ: Add in test_case for buttons on action-edit page
  cfme/tests/control/test_bugs.py
  cfme/utils/bz.py
Labels: fix-framework, lint-ok, new-test-or-feature

#8850 [1LP][RFR] Customer stories requirement
  cfme/test_requirements.py
  cfme/tests/automate/custom_button/test_service_vm_custom_button.py
Labels: lint-ok, manual

#8855 [1LP][WIPTEST]Adding requirement marker for test feature
  cfme/test_requirements.py
Labels: WIP-testing, lint-ok, manual

#8862 [RFR] _custom_configure doesn't work correctly for upstream
  cfme/utils/appliance/__init__.py
Labels: fix-framework, lint-ok, sprout

#8863 [WIPTEST] Add notebook with intro to python multiprocessing
  notebooks/MultiProcessing.ipynb
Labels: WIP-testing, doc, lint-ok

#8840 [1LP][RFR] Move manual vmrc console testcases
  cfme/tests/infrastructure/test_vmrc_console.py
  cfme/tests/test_manual.py
Labels: lint-ok, manual

#8811 [1LP][RFR][NOTEST] Add test steps to the replication tests.
  cfme/tests/test_replication.py
Labels: lint-ok, manual

#8854 [1LP][RFR] handling modals in 5.11
  cfme/services/catalogs/catalog_items/__init__.py
  cfme/utils/appliance/implementations/common.py
  cfme/utils/appliance/implementations/ssui.py
  cfme/utils/appliance/implementations/ui.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: enhancement, fix-framework, fix-test, lint-ok

#8860 [1LP][RFR]Adding requirement-marker to test
  cfme/tests/automate/test_service_dialog.py
  cfme/tests/services/test_dialog_element_in_catalog.py
  cfme/tests/services/test_dialog_regex_validation_in_catalog.py
  cfme/tests/services/test_different_dialogs_in_catalogs.py
  cfme/tests/services/test_dynamicdd_dialogelement.py
Labels: lint-ok, manual

#8861 [1LP][RFR] Undo workaround for BZ 1668849
  cfme/base/ui.py
  cfme/configure/configuration/diagnostics_settings.py
Labels: fix-framework, lint-ok, tech-debt

#8844 [1LP][RFR]Collections refactor for 511, fix failing test and other cleanup
  cfme/tests/test_rest.py
  cfme/tests/test_rest_manual.py
Labels: fix-test, lint-ok

#8829 [1LP][RFR] Catalog level unassigned btn test
  cfme/fixtures/service_fixtures.py
  cfme/tests/automate/custom_button/test_catalog_custom_button.py
Labels: lint-ok, new-test-or-feature

#8858 [RFR] follow-up for #8543
  cfme/common/__init__.py
  cfme/tests/cloud/test_tag_mapping.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: fix-framework, fix-test, lint-ok

#8828 [RFR] Move manual webmks console testcases
  cfme/tests/infrastructure/test_webmks_console.py
  cfme/tests/test_manual.py
Labels: lint-ok, manual

#8819 [RFR] Fix expression test for component ui changes
  cfme/automate/buttons.py
  cfme/tests/automate/custom_button/test_cloud_objects.py
  cfme/tests/automate/custom_button/test_container_objects.py
  cfme/tests/automate/custom_button/test_generic_objects.py
  cfme/tests/automate/custom_button/test_infra_objects.py
Labels: fix-locator-or-text, lint-ok

#8856 [1LP][RFR] Fix toolbar download button for details page
  cfme/ansible/credentials.py
  cfme/ansible/playbooks.py
  cfme/ansible/repositories.py
  cfme/cloud/availability_zone.py
  cfme/cloud/flavor.py
  cfme/cloud/instance/__init__.py
  cfme/cloud/instance/image.py
  cfme/cloud/keypairs.py
  cfme/cloud/security_groups.py
  cfme/cloud/stack.py
  cfme/cloud/tenant.py
  cfme/common/provider_views.py
  cfme/control/log.py
  cfme/infrastructure/cluster.py
  cfme/infrastructure/config_management.py
  cfme/infrastructure/deployment_roles.py
  cfme/infrastructure/resource_pool.py
  cfme/infrastructure/virtual_machines.py
  cfme/intelligence/reports/reports.py
  cfme/networks/views.py
  cfme/storage/manager.py
  cfme/storage/object_store_container.py
  cfme/storage/object_store_object.py
  cfme/storage/volume.py
  cfme/storage/volume_backup.py
  cfme/storage/volume_snapshot.py
  cfme/storage/volume_type.py
Labels: fix-locator-or-text, lint-ok

#8843 [WIPTEST] Bump wait_for to display less trash in the traceback.
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: WIP-testing, enhancement, lint-ok

#8847 [1LP][RFR] Test cases updated with requirements
  cfme/tests/automate/test_provisioning_dialogs.py
  cfme/tests/cloud/test_tenant.py
  cfme/tests/cloud_infra_common/test_quota_with_multiple_providers.py
  cfme/tests/configure/test_access_control.py
  cfme/tests/configure/test_analysis_profiles.py
  cfme/tests/infrastructure/test_quota.py
  cfme/tests/infrastructure/test_quota_tagging.py
  cfme/tests/infrastructure/test_tenant_quota.py
Labels: lint-ok, manual

#8866 [1LP][RFR] Add rails deprecation behavior config method to appliance
  cfme/utils/appliance/__init__.py
Labels: enhancement, lint-ok

#8859 [NOTEST][RFR]Adding test_requirements
  cfme/tests/infrastructure/test_publish_vm_to_template.py
  cfme/tests/infrastructure/test_vmware_provider.py
Labels: lint-ok, tech-debt

#8641 [RFR] Create Ansible service dialog through REST API
  cfme/fixtures/ansible_tower.py
  cfme/test_framework/pytest_plugin.py
  cfme/tests/services/test_config_provider_servicecatalogs.py
Labels: enhancement, lint-ok, new-test-or-feature

#8841 [1LP][RFR]v2v cancel migration tests
  cfme/tests/v2v/test_v2v_cancel_migrations.py
Labels: lint-ok, new-test-or-feature

#8867 [RFR] fixing recursion caused by handling modal
  cfme/utils/appliance/implementations/common.py
  cfme/utils/appliance/implementations/ui.py
Labels: fix-framework, lint-ok

#8748 [RFR] Update tests to use Global fixture.
  cfme/ansible/repositories.py
  cfme/fixtures/ansible_fixtures.py
  cfme/services/myservice/ui.py
  cfme/tests/ansible/test_embedded_ansible_services.py
Labels: enhancement, lint-ok

#8873 [1LP][RFR] Skip maintenance zone in ZoneCollection
  cfme/base/__init__.py
Labels: fix-framework, lint-ok, rc-regression-fix

#8864 [1LP][RFR] Fixed key error in tree path for 5.11
  cfme/automate/explorer/method.py
Labels: fix-locator-or-text, lint-ok, rc-regression-fix

#8877 [1LP][RFR] Fix AttributeError in HandleModalsMixin.handle_alert
  cfme/configure/access_control/__init__.py
  cfme/fixtures/tag.py
  cfme/tests/configure/test_access_control.py
  cfme/utils/appliance/implementations/common.py
Labels: fix-framework, lint-ok, rc-regression-fix

#8886 [RFR][NOTEST] py37 re pattern
  cfme/automate/explorer/__init__.py
  cfme/utils/ftp.py
Labels: lint-ok, py3-compat

#8777 [1LP][RFR] Changes related to CFME 5.11
  cfme/tests/test_appliance.py
  cfme/utils/appliance/__init__.py
  cfme/utils/appliance/db.py
  cfme/utils/appliance/services.py
  cfme/utils/ssh.py
  scripts/data/enable-internal-db.rbt
  scripts/restore.py
Labels: fix-test, lint-ok

#8833 [1LP][RFR] EC2 storage snapshot tests
  cfme/storage/volume.py
  cfme/storage/volume_snapshot.py
  cfme/tests/storage/test_volume_snapshot.py
Labels: fix-framework, lint-ok

#8882 [1LP][RFR] Updated tests with use of ansible global fixture.
  cfme/tests/ansible/test_embedded_ansible_automate.py
  cfme/tests/ansible/test_embedded_ansible_basic.py
Labels: fix-locator-or-text, lint-ok

#8875 [1LP][RFR]Adding global test requirement for test cases
  cfme/tests/cli/test_appliance_cli.py
  cfme/tests/cli/test_appliance_console.py
  cfme/tests/test_replication.py
Labels: lint-ok, manual

#8848 [1LP][RFR] Fixed path of quota related product feature tree
  cfme/tests/automate/test_domain.py
  cfme/tests/automate/test_git_import.py
  cfme/tests/cloud/test_tenant.py
Labels: fix-test, lint-ok

#8790 [1LP][RFR]New Test: test_update_advanced_settings_new_key
  cfme/base/ui.py
  cfme/tests/configure/test_rest_config.py
  cfme/utils/appliance/implementations/ui.py
Labels: fix-test, lint-ok, new-test-or-feature

#8874 [1LP][RFR]Automate test: test_default_view_settings_should_apply_for_service_ca…
  cfme/configure/settings.py
  cfme/services/service_catalogs/ui.py
  cfme/tests/configure/test_default_views_infra.py
  cfme/tests/services/test_service_catalogs.py
  widgetastic_manageiq/__init__.py
Labels: lint-ok, new-test-or-feature
