Repository ManageIQ/integration_tests, pull requests merged in 2019-03, with the labels that each got.

#8518 [1LP][RFR] New test for automate: Checking schema creation without 'Type'
  cfme/tests/automate/test_automate_manual.py
  cfme/tests/automate/test_class.py
Labels: lint-ok, new-test-or-feature

#8502 [1LP][RFR] Automate test case: test_change_truncate_long_text_save_button_enabled
  cfme/tests/configure/test_default_filters.py
  cfme/tests/configure/test_default_views_cloud.py
  cfme/tests/configure/test_default_views_infra.py
  cfme/tests/configure/test_landing_page.py
  cfme/tests/configure/test_timeprofile.py
  cfme/tests/configure/test_visual_cloud.py
  cfme/tests/configure/test_visual_infra.py
Labels: lint-ok, manual, new-test-or-feature

#8443 [1LP][RFR] This test for checking invalid name of namespaces
  cfme/automate/explorer/domain.py
  cfme/tests/automate/test_automate_manual.py
  cfme/tests/automate/test_domain.py
  cfme/tests/automate/test_namespace.py
Labels: lint-ok, new-test-or-feature

#8422 [1LP][RFR] modify fill_rsa_endpoint method and add tenant_mapping options in provider create_rest method
  cfme/cloud/provider/openstack.py
  cfme/common/provider.py
Labels: enhancement, lint-ok

#8510 [RFR] Fix orchestration template test
  cfme/services/catalogs/orchestration_template.py
  cfme/tests/services/test_orchestration_template.py
Labels: fix-test, lint-ok

#8511 [1LP][RFR] fixed active snapshot detection for RHEV
  cfme/infrastructure/virtual_machines.py
Labels: fix-framework, lint-ok

#8533 Updating is_displayed for catalog all page
  cfme/services/catalogs/catalog.py
Labels: fix-locator-or-text, lint-ok

#8509 [1LP][RFR] fix grouping tests by provider in test paralellizer
  cfme/fixtures/parallelizer/__init__.py
  cfme/markers/env_markers/provider.py
Labels: fix-framework, issue-bug, lint-ok

#8411 [1LP][RFR] Group enhancement
  cfme/automate/buttons.py
  cfme/tests/automate/custom_button/test_buttons.py
  widgetastic_manageiq/__init__.py
Labels: enhancement, lint-ok, new-test-or-feature

#8438 [1LP][RFR] Testing generate widget content using auotmate method
  cfme/intelligence/reports/widgets/__init__.py
  cfme/tests/automate/test_automate_manual.py
  cfme/tests/intelligence/reports/test_widgets.py
Labels: lint-ok, new-test-or-feature

#8517 [1LP][RFR] fixed test_create_without_description for 5.10
  cfme/tests/infrastructure/test_snapshot.py
Labels: fix-test, lint-ok

#8528 [1LP][RFR][NOTEST] Added new manual test case
  cfme/tests/automate/test_automate_manual.py
  cfme/tests/test_manual.py
Labels: lint-ok, manual

#8542 [RFR] remove manual case test_diagnostic_timelines
  cfme/tests/test_manual.py
Labels: lint-ok, manual

#8540 [RFR] Update template upload to call trackerbot API if template already exists
  cfme/utils/template/base.py
Labels: enhancement, infra-related, lint-ok

#8480 [1LP][RFR] Infra mapping
  cfme/fixtures/v2v_fixtures.py
  cfme/test_framework/pytest_plugin.py
  cfme/tests/v2v/test_infrastructure_mapping.py
  cfme/v2v/infrastructure_mapping.py
  entry_points.txt
Labels: fix-framework, lint-ok

#8539 [1LP][RFR] added wait_for the Submit button to be enabled
  cfme/services/service_catalogs/ui.py
  cfme/tests/services/test_cloud_service_catalogs.py
Labels: fix-framework, fix-test, lint-ok

#8536 [1LP][RFR] Update tree for aws rbac for 5.9
  cfme/roles.py
  cfme/tests/integration/test_aws_iam_auth_and_roles.py
Labels: fix-framework, lint-ok

#8530 [1LP][RFR] Update tree for aws rbac
  cfme/roles.py
Labels: fix-framework, lint-ok

#8534 [1LP][RFR] fixed no such element in ansible credentials
  cfme/ansible/credentials.py
Labels: fix-test, lint-ok

#8531 [1LP][RFR] clone dialog is broken. uncollecting tests until those are fixed
  cfme/tests/control/test_actions.py
  cfme/tests/infrastructure/test_vm_clone.py
Labels: blockers-only, fix-test, lint-ok

#8527 [1LP][RFR] Fixed exception error while adding entry points
  cfme/services/catalogs/catalog_items/__init__.py
  cfme/tests/cloud/test_tenant_quota.py
Labels: fix-framework, fix-test, lint-ok

#8526 [1LP][RFR][NOTEST] Refactoring polarion metadata and adding tag
  cfme/tests/configure/test_access_control.py
Labels: lint-ok, manual

#8512 [1LP][RFR] Remove fixtured collections from control tests
  cfme/control/explorer/conditions.py
  cfme/control/explorer/policies.py
  cfme/tests/control/test_alerts.py
  cfme/tests/control/test_basic.py
  cfme/tests/control/test_bugs.py
Labels: fix-framework, lint-ok

#8538 [1LP][NOTEST][RFR] deleted duplicate test test_service_provision_azure
  cfme/tests/cloud_infra_common/test_provisioning_manual.py
Labels: lint-ok, manual

#8456 [1LP][RFR] fix teardown dialog
  cfme/automate/__init__.py
  cfme/automate/dialogs/dialog_element.py
  cfme/tests/automate/test_service_dialog.py
Labels: fix-framework, lint-ok

#8547 [1LP][RFR] fixed paginator is_displayed and a bunch of tests failing due to absent paginator
  cfme/tests/configure/test_visual_cloud.py
  cfme/tests/configure/test_visual_infra.py
  widgetastic_manageiq/__init__.py
Labels: fix-test, lint-ok

#8553 [1LP][RFR][NOTEST] Reassign control tests and move manual cases
  cfme/tests/control/test_basic.py
  cfme/tests/control/test_bugs.py
  cfme/tests/control/test_compliance.py
  cfme/tests/control/test_export_policies.py
  cfme/tests/control/test_import_policies.py
  cfme/tests/control/test_smoke_control.py
  cfme/tests/test_manual.py
Labels: lint-ok, manual

#8400 [1LP][RFR] Add 5.9 to the test_db_migrate_replication
  cfme/tests/test_db_migrate.py
  cfme/utils/appliance/__init__.py
  cfme/utils/ssh.py
Labels: fix-locator-or-text, lint-ok

#8495 [1LP][RFR] New test for product features with custom roles
  cfme/tests/cloud_infra_common/test_quota_manual.py
  cfme/tests/configure/test_access_control.py
  cfme/tests/configure/test_analysis_profiles.py
Labels: lint-ok, new-test-or-feature

#8525 [1LP][RFR] New test: Testing automate simulate 'Retry' button using state machines
  cfme/base/ui.py
  cfme/tests/automate/test_automate_manual.py
  cfme/tests/automate/test_method.py
Labels: lint-ok, new-test-or-feature

#8537 [RFR] fixed nodata tests and visual configuration view
  cfme/common/vm_views.py
  cfme/configure/settings.py
  cfme/tests/configure/test_visual_cloud.py
  cfme/tests/configure/test_visual_infra.py
Labels: fix-test, lint-ok

#8541 [RFR]Fix provision stack tests
  cfme/services/catalogs/orchestration_template.py
  cfme/tests/services/test_provision_stack.py
  data/orchestration/rhos13_vm_template.data
Labels: fix-test, lint-ok

#8552 [NOTEST][RFR] Common exists method in BaseEntity
  cfme/ansible/credentials.py
  cfme/ansible/playbooks.py
  cfme/ansible/repositories.py
  cfme/automate/buttons.py
  cfme/automate/dialogs/service_dialogs.py
  cfme/automate/explorer/domain.py
  cfme/automate/explorer/instance.py
  cfme/automate/explorer/klass.py
  cfme/automate/explorer/method.py
  cfme/automate/explorer/namespace.py
  cfme/automate/provisioning_dialogs.py
  cfme/cloud/flavor.py
  cfme/cloud/instance/__init__.py
  cfme/cloud/instance/image.py
  cfme/cloud/keypairs.py
  cfme/cloud/security_groups.py
  cfme/cloud/tenant.py
  cfme/common/vm.py
  cfme/configure/access_control/__init__.py
  cfme/configure/configuration/analysis_profile.py
  cfme/containers/container.py
  cfme/containers/image.py
  cfme/containers/image_registry.py
  cfme/containers/node.py
  cfme/containers/pod.py
  cfme/containers/project.py
  cfme/containers/replicator.py
  cfme/containers/route.py
  cfme/containers/service.py
  cfme/containers/template.py
  cfme/containers/volume.py
  cfme/intelligence/reports/reports.py
  cfme/modeling/base.py
  cfme/networks/cloud_network.py
  cfme/networks/network_router.py
  cfme/networks/subnet.py
  cfme/physical/physical_chassis.py
  cfme/physical/physical_rack.py
  cfme/services/catalogs/catalog.py
  cfme/services/catalogs/catalog_items/__init__.py
  cfme/services/catalogs/orchestration_template.py
  cfme/storage/manager.py
  cfme/storage/volume.py
  cfme/storage/volume_backup.py
  cfme/storage/volume_type.py
Labels: enhancement, lint-ok

#8554 [RFR] removing fixtured collections from test_compliance
  cfme/tests/control/test_compliance.py
Labels: WIP-testing, fix-test, lint-ok

#8523 [1LP][RFR] Add miq polarion, template for polarion_tools.local.yaml
  cfme/scripting/miq.py
  cfme/scripting/polarion.py
  conf/polarion_tools.local.yaml.template
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
Labels: enhancement, lint-ok

#8545 [1LP][RFR] Fix assert view.is_displayed for catalog
  cfme/services/catalogs/catalog.py
Labels: fix-framework, lint-ok

#8498 [1LP][RFR] Fix azone utilization views
  cfme/cloud/availability_zone.py
  cfme/cloud/provider/ec2.py
  cfme/tests/candu/test_azone_graph.py
Labels: fix-framework, lint-ok

#8559 [RFR]Fix updates
  cfme/tests/cli/test_appliance_update.py
Labels: fix-test, lint-ok

#8564 [RFR] Add in a blocker statement for BZ 1687493
  cfme/tests/infrastructure/test_timelines.py
Labels: blockers-only, lint-ok, rc-regression-fix

#8567 [RFR] Update cli fixture get_apps method, lookup sprout user key from config
  cfme/fixtures/cli.py
Labels: fix-test, lint-ok, rc-regression-fix

#8568 [RFR] Update wrapanapi
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
Labels: fix-framework, lint-ok, rc-regression-fix

#8562 [RFR] Remove manual control case
  cfme/tests/control/test_basic.py
  cfme/tests/control/test_import_policies.py
Labels: lint-ok, manual

#8548 [1LP][RFR]Automating test_tenant_unique_catalog
  cfme/tests/configure/test_access_control.py
Labels: lint-ok, new-test-or-feature

#8574 [1LP][RFR] drawer isn't closed in both UI and SSUI
  cfme/utils/appliance/implementations/ssui.py
  cfme/utils/appliance/implementations/ui.py
Labels: fix-framework, lint-ok

#8571 [RFR] fixed parsing process status
  cfme/tests/ansible/test_embedded_ansible_services.py
  cfme/utils/providers.py
  cfme/utils/ssh.py
Labels: fix-framework, lint-ok

#8565 [1LP][RFR] Test coverage for BZ 1683697
  cfme/control/explorer/conditions.py
  cfme/tests/control/test_bugs.py
Labels: lint-ok

#8566 [RFR][NOTEST]Adding/updating VMware manual tests
  cfme/tests/infrastructure/test_vmware_provider.py
  cfme/tests/test_manual.py
Labels: lint-ok, manual

#8546 [1LP][RFR] Networking Switch
  cfme/automate/buttons.py
  cfme/infrastructure/networking.py
  cfme/tests/automate/custom_button/test_infra_objects.py
  cfme/tests/webui/test_splitter.py
  entry_points.txt
Labels: enhancement, fix-framework, lint-ok

#8576 [RFR] Remove condition to fix deleting expressions
  widgetastic_manageiq/expression_editor.py
Labels: fix-framework, lint-ok

#8577 [1LP][RFR] Move create_view to enable error check
  cfme/configure/access_control/__init__.py
Labels: fix-framework, lint-ok

#8557 [RFR] test_custom_button_dialog
  cfme/tests/automate/custom_button/__init__.py
  cfme/tests/automate/custom_button/test_service_objects.py
Labels: lint-ok, new-test-or-feature

#8593 [1LP][RFR] Reassign test cases from mmojzis to jdupuy
  cfme/tests/control/test_actions.py
Labels: fix-locator-or-text, lint-ok

#8587 [1LP][RFR][NOTEST] Removing the test as it is already automated
  cfme/tests/test_manual.py
Labels: lint-ok, manual

#8586 [1LP][RFR][NOTEST] updated BZ for test_provision_vm_to_virtual_network
  cfme/tests/networks/test_provision_to_virtual_network.py
Labels: RHV, blockers-only, lint-ok

#8584 [1LP][RFR] fixed many cli tests
  cfme/fixtures/cli.py
  cfme/tests/cli/test_appliance_cli.py
  cfme/utils/appliance/__init__.py
Labels: fix-test, lint-ok

#8549 [1LP][RFR] Automate test case: test_non_admin_user_reports_access_rest AND modify gen_data access_control functions
  cfme/rest/gen_data.py
  cfme/tests/configure/test_rest_access_control.py
  cfme/tests/intelligence/reports/test_reports.py
Labels: lint-ok, new-test-or-feature

#8569 [1LP][RFR] Bottleneck tests : Add DB migration step after loading DB from an older version of CFME
  cfme/tests/optimize/test_bottlenecks.py
Labels: fix-test, lint-ok

#8556 [1LP][RFR] Use a common exception ItemNotFound
  cfme/base/ui.py
  cfme/cloud/availability_zone.py
  cfme/cloud/flavor.py
  cfme/cloud/instance/__init__.py
  cfme/cloud/instance/image.py
  cfme/cloud/keypairs.py
  cfme/cloud/security_groups.py
  cfme/cloud/tenant.py
  cfme/common/vm.py
  cfme/common/vm_views.py
  cfme/configure/about.py
  cfme/exceptions.py
  cfme/generic_objects/definition/ui.py
  cfme/infrastructure/deployment_roles.py
  cfme/infrastructure/resource_pool.py
  cfme/infrastructure/virtual_machines.py
  cfme/modeling/base.py
  cfme/storage/volume.py
  cfme/storage/volume_backup.py
  cfme/storage/volume_snapshot.py
  cfme/storage/volume_type.py
  cfme/tests/cloud_infra_common/test_tag_visibility.py
  cfme/tests/cloud_infra_common/test_vm_ownership.py
  cfme/tests/openstack/infrastructure/test_host_lifecycle.py
Labels: enhancement, lint-ok

#8591 [1LP][RFR] docblock for create_view
  cfme/utils/appliance/__init__.py
Labels: lint-ok, tech-debt

#8582 [1LP][RFR] Increase IPA timeout
  cfme/utils/appliance/__init__.py
Labels: fix-test, lint-ok

#8519 [1LP][RFR] Separate test_assign_and_unassign_tag for different providers and minimize parametrization
  cfme/tests/configure/test_tag.py
  cfme/tests/intelligence/reports/test_generate_report.py
  cfme/tests/intelligence/reports/test_views.py
Labels: enhancement, lint-ok

#8579 [1LP][RFR] Use role with product features
  cfme/tests/configure/test_access_control.py
Labels: fix-test, lint-ok

#8520 [1LP][RFR] New test: Checking 'Disabled' domain on instance' detail's page
  cfme/automate/explorer/instance.py
  cfme/tests/automate/test_automate_manual.py
  cfme/tests/automate/test_domain_priority.py
Labels: lint-ok, new-test-or-feature

#8590 [RFR] Fix failing test_tenant_quota_reports test
  cfme/intelligence/reports/reports.py
  cfme/tests/intelligence/reports/test_tenant_quota_reports.py
Labels: fix-test, lint-ok

#8578 [1LP][RFR] Move `delete_if_exists` to BaseEntity
  cfme/automate/buttons.py
  cfme/automate/dialogs/service_dialogs.py
  cfme/automate/explorer/domain.py
  cfme/automate/explorer/instance.py
  cfme/automate/explorer/klass.py
  cfme/automate/explorer/method.py
  cfme/automate/explorer/namespace.py
  cfme/common/provider.py
  cfme/control/explorer/actions.py
  cfme/modeling/base.py
  cfme/services/catalogs/catalog_items/__init__.py
Labels: enhancement, lint-ok

#8588 [RFR] TODO consistency
  cfme/automate/buttons.py
  cfme/cloud/tenant.py
  cfme/common/__init__.py
  cfme/services/catalogs/__init__.py
  docs/guides/dev_guide.rst
Labels: doc, lint-ok, other

#8604 [WIPTEST][NOTEST] freezing miq-version support for py2
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
  sprout/requirements.txt
Labels: WIP-testing, lint-ok, py3-compat

#8605 Update deepdiff in template_docs.txt
  requirements/template_docs.txt
Labels: other, py3-compat

#8580 [RFR] Fix collection test compliance
  cfme/tests/control/test_compliance.py
Labels: fix-test, lint-ok

#8592 [1LP][RFR] Don't obscure the tracebacks.
  cfme/common/vm.py
  cfme/tests/cloud_infra_common/test_html5_vm_console.py
  cfme/tests/cloud_infra_common/test_provisioning.py
  cfme/tests/cloud_infra_common/test_vm_ownership.py
  cfme/tests/infrastructure/test_vm_power_control.py
  cfme/tests/infrastructure/test_webmks_console.py
  cfme/tests/ssui/test_ssui_myservice.py
Labels: lint-ok, other

#8112 [1LP][RFR] Quota test for Infra: Testing tenant quota via UI and SSUI
  cfme/services/requests.py
  cfme/tests/infrastructure/test_tenant_quota.py
Labels: lint-ok, new-test-or-feature

#8607 [RFR] Update quickstart, OS_NAME and OS_VERSION, make debuginfo optional
  cfme/scripting/quickstart/__init__.py
  cfme/scripting/quickstart/system.py
Labels: enhancement, lint-ok

#8606 [1LP][RFR] Unicode hack for auth group
  cfme/configure/access_control/__init__.py
  cfme/tests/integration/test_cfme_auth.py
Labels: fix-test, lint-ok

#8514 [1LP][RFR] Implement ComputeRateCollection & StorageRateCollection
  cfme/intelligence/chargeback/rates.py
  cfme/tests/containers/test_chargeback.py
  cfme/tests/intelligence/chargeback/test_chargeback_long_term_rates.py
  cfme/tests/intelligence/reports/test_validate_chargeback_report.py
  cfme/tests/intelligence/test_chargeback.py
  cfme/tests/ssui/test_ssui_dashboard.py
  entry_points.txt
Labels: collections-conversion, lint-ok

#8601 [1LP][RFR] New Test: Checking relationship value with trailing spaces
  cfme/tests/automate/test_automate_manual.py
  cfme/tests/automate/test_instance.py
Labels: lint-ok, new-test-or-feature

#8563 [RFR]Add tree path in reports
  cfme/intelligence/reports/reports.py
  cfme/intelligence/reports/saved.py
Labels: enhancement, lint-ok

#8544 [1LP][RFR] Add TaggableCollection, update containers smart tag tests
  cfme/common/__init__.py
  cfme/containers/container.py
  cfme/containers/image.py
  cfme/containers/image_registry.py
  cfme/containers/node.py
  cfme/containers/pod.py
  cfme/containers/project.py
  cfme/containers/provider/__init__.py
  cfme/containers/provider/openshift.py
  cfme/containers/template.py
Labels: enhancement, lint-ok

#8589 [1LP][RFR] Fix ap tests
  cfme/tests/cli/test_appliance_console.py
Labels: fix-test, lint-ok

#8581 [1LP][RFR] Automate test for Ansible template job with survey
  cfme/tests/services/test_config_provider_servicecatalogs.py
Labels: lint-ok, new-test-or-feature

#8585 [1LP][RFR] ndhandre manual move
  cfme/tests/automate/custom_button/test_service_objects.py
  cfme/tests/test_manual.py
Labels: lint-ok, manual

#8616 [RFR] removed a blocker for test_restart_workers
  cfme/tests/configure/test_workers.py
Labels: blockers-only, lint-ok

#8615 [RFR] updated according to different behaviour in 5.10
  cfme/tests/test_csrf.py
Labels: fix-test, lint-ok

#8614 [RFR] Fix chargeback/test_resource_allocation compute/storage rate creation
  cfme/tests/intelligence/chargeback/test_chargeback_long_term_rates.py
  cfme/tests/intelligence/chargeback/test_resource_allocation.py
Labels: WIP-testing, fix-test, lint-ok, rc-regression-fix

#8211 [RFR] This PR will add deletion of S3 buckets for cleanup script.
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  scripts/ec2cleanup.py
Labels: infra-related, lint-ok

#8613 [1LP][WIPTEST] Add unicode format for string
  cfme/configure/access_control/__init__.py
Labels: WIP-testing, fix-test, lint-ok, rc-regression-fix

#8617 [1LP][RFR][NOTEST] Change assignee of ansible control tests
  cfme/tests/ansible/test_embedded_ansible_basic.py
Labels: lint-ok, other

#8625 [1LP][RFR] move tree selection to entity
  cfme/services/myservice/ui.py
Labels: WIP-testing, issue-bug, lint-ok, rc-regression-fix

#8627 [1LP][RFR] blocker for test_vm_reconfig_add_remove_disk_cold
  cfme/tests/infrastructure/test_vm_reconfigure.py
Labels: blockers-only, lint-ok

#8629 [1LP][RFR] randomly get keys and try to servers
  cfme/utils/dockerbot/pytestbase/get_keys.py
Labels: fix-framework, lint-ok

#8624 [1LP][RFR][NOTEST] Removing the duplicate test
  cfme/tests/services/test_catalog.py
Labels: lint-ok, other

#8612 [1LP][RFR] Uncollect RHV hourly disk graph tests
  cfme/tests/candu/test_host_graph.py
Labels: blockers-only, lint-ok

#8634 [RFR][NOTEST] Change test_schedule_crud name to avoid conflicts on polarion
  cfme/tests/intelligence/reports/test_crud.py
Labels: fix-locator-or-text, lint-ok

#8623 [1LP][RFR] CB: change in flash msg
  cfme/tests/automate/custom_button/test_cloud_objects.py
  cfme/tests/automate/custom_button/test_generic_objects.py
  cfme/tests/automate/custom_button/test_infra_objects.py
  cfme/tests/automate/custom_button/test_service_objects.py
Labels: fix-test, lint-ok

#8628 [1LP][RFR] Enhance gen_data functions
  cfme/rest/gen_data.py
  cfme/tests/configure/test_rest_access_control.py
  cfme/tests/services/test_rest_services.py
Labels: enhancement, lint-ok

#8635 [RFR][NOTEST] resolved duplicate test cases
  cfme/tests/automate/test_customization_paginator.py
  cfme/tests/cloud/test_stack.py
  cfme/tests/configure/test_paginator.py
  cfme/tests/services/test_catalog_item.py
Labels: fix-test, lint-ok

#8626 [1LP][RFR] Update SSHClient.status, evmserverd output processing
  cfme/tests/cli/test_evmserverd.py
  cfme/utils/ssh.py
Labels: fix-framework, lint-ok

#8611 [1LP][WIPTEST] Add in fleecing fixture to cfme.fixtures.appliance
  cfme/fixtures/appliance.py
  cfme/tests/control/test_actions.py
  cfme/tests/control/test_alerts.py
  cfme/tests/control/test_compliance.py
Labels: WIP-testing, enhancement, lint-ok

#8551 [1LP][RFR] Automate test case: test_reports_create_schedule_send_report AND reports schedules refactor
  cfme/intelligence/reports/reports.py
  cfme/intelligence/reports/schedules.py
  cfme/tests/intelligence/reports/test_crud.py
  cfme/tests/intelligence/reports/test_reports_manual.py
  cfme/tests/intelligence/reports/test_reports_schedules.py
  data/schedules_crud/basic01.yaml
  data/schedules_report/daily.yaml
  data/schedules_report/hourly.yaml
  data/schedules_report/monthly.yaml
  data/schedules_report/once.yaml
  data/schedules_report/weekly.yaml
Labels: lint-ok, new-test-or-feature

#8572 [1LP][RFR] Added plan_type in Infra Mapping
  cfme/fixtures/v2v_fixtures.py
  cfme/tests/v2v/test_infrastructure_mapping.py
  cfme/v2v/infrastructure_mapping.py
Labels: enhancement, lint-ok

#8575 [1LP][RFR] Add in policy simulation test case
  cfme/cloud/instance/__init__.py
  cfme/common/vm_views.py
  cfme/infrastructure/virtual_machines.py
  cfme/tests/cloud_infra_common/test_policy_simulation.py
  cfme/tests/control/test_basic.py
  widgetastic_manageiq/__init__.py
Labels: lint-ok, new-test-or-feature

#8543 [1LP][RFR] Tests tagging on provider side
  cfme/common/__init__.py
  cfme/configure/configuration/region_settings.py
  cfme/tests/cloud/test_tag_mapping.py
  cfme/tests/configure/test_tag.py
  conf/polarion_tools.yaml
Labels: enhancement, lint-ok, new-test-or-feature

#8643 [RFR] Add supportability.yaml for MIQ master
  conf/supportability.yaml
Labels: enhancement

#8560 [1LP][RFR] Cb catalog Buttons
  cfme/fixtures/service_fixtures.py
  cfme/services/catalogs/catalog_items/__init__.py
  cfme/tests/automate/custom_button/test_catalog_custom_button.py
  cfme/tests/automate/custom_button/test_service_objects.py
Labels: lint-ok, new-test-or-feature

#8633 [1LP][RFR] Automate test: test_delete_advanced_search filter via REST
  cfme/tests/webui/test_rest.py
Labels: lint-ok, new-test-or-feature

#8631 [1LP][RFR] Storage Container and Object changes.
  cfme/storage/object_store_container.py
  cfme/storage/object_store_object.py
Labels: enhancement, lint-ok

#8638 [1LP][RFR] New test: Include test cases to assert removal of RSS and Timelines pages
  cfme/tests/intelligence/test_timelines_rss_removed.py
Labels: lint-ok, new-test-or-feature

#8599 [1LP][WIPTEST] Automate test control icons simulation
  cfme/control/simulation.py
  cfme/tests/control/test_actions.py
  cfme/tests/control/test_control_simulation.py
  requirements/frozen.py2.txt
  requirements/frozen.py3.txt
  requirements/frozen_docs.py2.txt
  requirements/frozen_docs.py3.txt
  widgetastic_manageiq/__init__.py
Labels: WIP-testing, lint-ok, new-test-or-feature

#8637 [RFR][NOTEST] Move manual tests and add new nonautomated tests
  cfme/tests/infrastructure/test_infra_manual.py
  cfme/tests/intelligence/reports/test_reports_manual.py
  cfme/tests/test_manual.py
  cfme/tests/test_rest_manual.py
  cfme/tests/webui/test_general_ui.py
Labels: lint-ok, manual
