Repository ManageIQ/integration_tests, pull requests merged in 2020-10, with the labels that each got.

#10323 [RFR][NOTEST] Add test importance
  cfme/tests/configure/test_access_control.py
  cfme/tests/integration/test_auth_manual.py
Labels: manual

#10336 [RFR] [NOTEST] Mark tests as manualonly.
  cfme/tests/automate/generic_objects/test_definitions.py
  cfme/tests/distributed/test_appliance_manual.py
  cfme/tests/intelligence/test_chargeback_manual.py
Labels: manual

#10339 Enforce py3.7 as minimum
  cfme/scripting/quickstart/__init__.py
  setup.py
Labels: issue-bug

#10337 [RFR] Fix CodeMirror filling.
  cfme/tests/services/test_provision_stack.py
  widgetastic_manageiq/__init__.py
Labels: issue-bug

#10343 [NOTEST][RFR]add test- prefix to renamed vms test
  cfme/tests/infrastructure/test_vm_ownership.py
Labels: fix-framework
